Repository TauCetiStation/TauCetiClassic, pull requests merged in 2018-08, with the labels that each got.

#2657 Sec console now work for all levels
  code/game/machinery/computer/camera.dm
Labels: Fix

#2662 [Mirror]Лампы в морге мигают зеленым если внутри тела есть игрок
  code/game/objects/structures/morgue.dm
Labels: Feature

#2665 Woops, now sec consoles definitely work fine
  code/game/machinery/computer/camera.dm
Labels: Fix

#2667 [Mirror]Микробаг с выводом в чат
  code/game/objects/structures/displaycase.dm
Labels: Tweak

#2677 map-remap fixes
  code/game/mecha/mech_fabricator.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/signs/signs_maps.dm
  icons/obj/decals.dmi
  maps/z1.dmm
  nano/images/nanomap_z1.png
Labels: Interactive Diff Map, Map Edit, Sprites

#2614 Fixing sprays.
  code/modules/reagents/reagent_containers/spray.dm
Labels: Fix

#2615 Fixing being unable to spray unclothed beings.
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Fix

#2630 [Mirror]Species shown in examine
  code/modules/mob/living/carbon/human/examine.dm
Labels: Tweak

#2632 [Mirror]M66 кевларовая броня получила нормальную защиту.
  code/game/objects/WalterJ_Items_Pack/NT PMC/WJ_NT_PMC.dm
Labels: Balance

#2633 [Mirror]Ботинки PMC получили защиту от подскальзываний.
  code/game/objects/WalterJ_Items_Pack/NT PMC/WJ_NT_PMC.dm
Labels: Balance

#2636 [Mirror]Фикс вечноломающихся канистр.
  code/modules/atmospheric/machinery/portable/canister.dm
Labels: Fix

#2645 [Mirror]Новые эмодзи.
  code/modules/goonchat/browserassets/css/emoji.css
  code/modules/goonchat/browserassets/css/emoji/at.png
  code/modules/goonchat/browserassets/css/emoji/cat.png
  code/modules/goonchat/browserassets/css/emoji/crash.png
  code/modules/goonchat/browserassets/css/emoji/dpepe.gif
  code/modules/goonchat/browserassets/css/emoji/duck.png
  code/modules/goonchat/browserassets/css/emoji/flash.png
  code/modules/goonchat/browserassets/css/emoji/glul.png
  code/modules/goonchat/browserassets/css/emoji/happyman.png
  code/modules/goonchat/browserassets/css/emoji/honk.png
  code/modules/goonchat/browserassets/css/emoji/jerry.png
  code/modules/goonchat/browserassets/css/emoji/kek.png
  code/modules/goonchat/browserassets/css/emoji/lul.png
  code/modules/goonchat/browserassets/css/emoji/ohmycat.png
  code/modules/goonchat/browserassets/css/emoji/peka.png
  code/modules/goonchat/browserassets/css/emoji/peka1.png
  code/modules/goonchat/browserassets/css/emoji/peka2.png
  code/modules/goonchat/browserassets/css/emoji/pekaanon.png
  code/modules/goonchat/browserassets/css/emoji/pekabaton.png
  code/modules/goonchat/browserassets/css/emoji/pekabloody.png
  code/modules/goonchat/browserassets/css/emoji/pekadoom.png
  code/modules/goonchat/browserassets/css/emoji/pekagachi.png
  code/modules/goonchat/browserassets/css/emoji/pekahmm.png
  code/modules/goonchat/browserassets/css/emoji/pekainsanededadvice.png
  code/modules/goonchat/browserassets/css/emoji/pekamorcrate.png
  code/modules/goonchat/browserassets/css/emoji/pekamrazish.png
  code/modules/goonchat/browserassets/css/emoji/pekaolt.png
  code/modules/goonchat/browserassets/css/emoji/pekapepe.png
  code/modules/goonchat/browserassets/css/emoji/pekarage.png
  code/modules/goonchat/browserassets/css/emoji/pekaragec.png
  code/modules/goonchat/browserassets/css/emoji/pekarp.png
  code/modules/goonchat/browserassets/css/emoji/pekasmart.png
  code/modules/goonchat/browserassets/css/emoji/pekaspace.png
  code/modules/goonchat/browserassets/css/emoji/pekathink.png
  code/modules/goonchat/browserassets/css/emoji/pepeamazing.png
  code/modules/goonchat/browserassets/css/emoji/pepecop.png
  code/modules/goonchat/browserassets/css/emoji/pepecross.png
  code/modules/goonchat/browserassets/css/emoji/pepecry.png
  code/modules/goonchat/browserassets/css/emoji/pepedamn.png
  code/modules/goonchat/browserassets/css/emoji/pepedetectiv.png
  code/modules/goonchat/browserassets/css/emoji/pepefeelsup.png
  code/modules/goonchat/browserassets/css/emoji/pepehmm.png
  code/modules/goonchat/browserassets/css/emoji/pepejoy.png
  code/modules/goonchat/browserassets/css/emoji/pepelove.png
  code/modules/goonchat/browserassets/css/emoji/pepemanok.png
  code/modules/goonchat/browserassets/css/emoji/peperage.png
  code/modules/goonchat/browserassets/css/emoji/pepesalut.png
  code/modules/goonchat/browserassets/css/emoji/pepesur.png
  code/modules/goonchat/browserassets/css/emoji/pepewhat.gif
  code/modules/goonchat/browserassets/css/emoji/pepewhy.png
  code/modules/goonchat/browserassets/css/emoji/pepewow.png
  code/modules/goonchat/browserassets/css/emoji/peporage.png
  code/modules/goonchat/browserassets/css/emoji/pominki.png
  code/modules/goonchat/browserassets/css/emoji/shrug.png
  code/modules/goonchat/browserassets/css/emoji/soqa.png
  code/modules/goonchat/browserassets/css/emoji/think.gif
  code/modules/goonchat/browserassets/css/emoji/thinkgun.png
  code/modules/goonchat/browserassets/css/emoji/topbestever.png
  code/modules/goonchat/browserassets/css/emojib64.css
  code/modules/goonchat/browserassets/js/emojiList.json
Labels: Fix, Sprites

#2658 [Mirror]Фикс фальшстен
  code/game/objects/structures/false_walls.dm
Labels: Fix

#2660 [Mirror]Радшторм не затрагивает СПУ
  code/datums/weather/weather_types.dm
Labels: Fix

#2663 Немного переписываю код ММИ.
  code/modules/mob/living/carbon/brain/MMI.dm
Labels: Fix

#2671 [Mirror]Ехидные пИИ теперь не смогут засечь нюку по ПДА
  code/modules/mob/living/silicon/pai/software.dm
Labels: Fix

#2676 Роботы могут забирать провода из катушек.
  code/modules/power/cable.dm
Labels: Fix

#2649 [Mirror]Синди-кеки и посыпка.
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Contentious, Feature

#2688 Фикс хлыста, неприменяющего эффекты.
  code/game/gamemodes/changeling/powers/Whip.dm
Labels: Fix

#2689 [Mirror]Фикс стоимости генератора синга
  code/modules/cargo/exports/large_objects.dm
Labels: Fix

#2644 [Mirror]При вхождении в криостазис в мед. рекордсах будет пометка, что у косм…
  code/game/machinery/cryopod.dm
Labels: Feature

#2683 Сделать Fossil Satchel более полезным
  code/modules/research/xenoarchaeology/tools/tools.dm
Labels: Feature

#2685 Корекция доставания батарейки из СПУ.
  code/modules/organs/organ_internal.dm
  code/modules/surgery/ribcage.dm
Labels: Fix

#2687 Коэффициент электрического умерщвления у разных рас.
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
Labels: Feature

#2686 Ограничение на слоты ксеноты.
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/species.dm
Labels: Contentious, Feature

#2656 Реворкаем еду, переносим вещи.
  code/__DEFINES/flags.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_types/Chemistry-Core.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  code/modules/reagents/reagent_types/Chemistry-Foods.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
  taucetistation.dme
Labels: Fix, Test Merge, Tweak

#2684 Убран спавн шкафов глав с мусорки.
  code/game/objects/random/random_structures.dm
Labels: Tweak
