Repository TauCetiStation/TauCetiClassic, pull requests merged in 2018-12, with the labels that each got.

#2875 guestpass changes
  code/game/machinery/computer/guestpass.dm
  icons/obj/card.dmi
  icons/obj/computer.dmi
  maps/z1.dmm
Labels: Map Edit, Ready for Review, Sprites

#2881 Центрирует кучу спрайтов предметов.
  icons/obj/abductor.dmi
  icons/obj/ammo.dmi
  icons/obj/apc_repair.dmi
  icons/obj/apiary_bees_etc.dmi
  icons/obj/autopsy_scanner.dmi
  icons/obj/basketball.dmi
  icons/obj/biogenerator.dmi
  icons/obj/christmas.dmi
  icons/obj/cigarettes.dmi
  icons/obj/cloning.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/coatrack.dmi
  icons/obj/cryobag.dmi
  icons/obj/dice.dmi
  icons/obj/grenade.dmi
  icons/obj/gun.dmi
  icons/obj/hacktool.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/inflatable.dmi
  icons/obj/janitor.dmi
  icons/obj/library.dmi
  icons/obj/makeshift.dmi
  icons/obj/musician.dmi
  icons/obj/paper.dmi
  icons/obj/radio.dmi
  icons/obj/stock_parts.dmi
  icons/obj/surgery.dmi
  icons/obj/syringe.dmi
  icons/obj/tools.dmi
  icons/obj/vending_restock.dmi
  icons/obj/watercloset.dmi
  icons/obj/weapons.dmi
Labels: Sprites

#2874 Plushies
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/dehy_carp.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/gift_wrappaper.dm
  code/game/objects/items/weapons/storage/boxes.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/toy.dmi
  maps/z1.dmm
Labels: Feature, Ready for Review

#2878 Тормоз для коляски + фикс
  code/_onclick/hud/alert.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/modules/organs/organ.dm
  icons/mob/screen_alert.dmi
Labels: Fix, Ready for Review, Tweak

#2880 Electronic cigarette tweaks
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/random/random_cloth.dm
  code/modules/client/character menu/loadout/loadout_general.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/customitems/item_defines.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/custom_items.dmi
Labels: Ready for Review, Tweak

#2883 Делает громкие звуковые эффекты шлюзов тише.
  code/game/machinery/biogenerator.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/kitchen/processor.dm
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Ready for Review

#2884 Alt-clicking a jumpsuit removes accessories from it
  code/modules/clothing/clothing.dm
Labels: Ready for Review, Tweak

#2866 [WiP]Переработанные бутылки для таблеток, startswith для storage/ и другое
  code/__DEFINES/colors.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/lists.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/medical.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/reagent_containers/pill.dm
  icons/obj/chemical.dmi
  maps/z1.dmm
  maps/z2.dmm
  sound/effects/peelz.ogg
  sound/effects/pillbottle.ogg
Labels: Feature, Map Edit, Ready for Review, Sprites

#2891 Жирные интерны и исследователи паранормальщины больше не спавнятся голыми
  code/modules/clothing/under/color.dm
  code/modules/customitems/item_defines.dm
  icons/mob/uniform_fat.dmi
Labels: Fix, Ready for Review, Sprites

#2892 Изменяет лого приложения
  icons/ss13_32.png
  icons/ss13_64.png
Labels: Ready for Review, Sprites

#2894 АВД update.
  code/game/jobs/job/civilian.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/cards_ids.dm
  icons/mob/ears.dmi
  icons/mob/hud.dmi
  icons/obj/card.dmi
  icons/obj/pda.dmi
  icons/obj/radio.dmi
Labels: Ready for Review, Sprites, Tweak

#2897 Remains можно пуллить
  code/game/objects/effects/decals/remains.dm
Labels: Ready for Review, Tweak

#2896 Новые лого в лобби и их рандомизация
  code/game/turfs/unsimulated/walls.dm
  icons/misc/fullscreen.dmi
  icons/misc/fullscreen_halloween.dmi
  icons/misc/fullscreen_leshiy.dmi
  icons/misc/fullscreen_loading.dmi
  icons/misc/fullscreen_newyear.dmi
  icons/misc/fullscreen_standart.dmi
Labels: Ready for Review, Sprites

#2791 Ports asteroid sprites from Bay.
  code/modules/mining/mine_turfs.dm
  code/modules/research/xenoarchaeology/artifact/artifact_bluespace_crystal.dm
  icons/obj/items.dmi
  icons/obj/mining.dmi
  icons/turf/asteroid.dmi
  icons/turf/floors.dmi
  icons/turf/walls.dmi
Labels: Resprite, Sprites, Work In Progress

#2907 Фикс невидимого грилля
  code/game/objects/structures/grille.dm
Labels: Fix, Merge Ready

#2908 Добавляет "Emote" в нижнюю строку чата.
  interface/skin.dmf
Labels: Ready for Review, Tweak

#2911 Фикс выделяющегося цвета АВД в setup character
  code/game/jobs/job/civilian.dm
Labels: Merge Ready

#2912 Locked step variables from VV
  code/modules/admin/verbs/massmodvar.dm
  code/modules/admin/verbs/modifyvariables.dm
Labels: Merge Ready

#2916 Добавляю новые игрушки
  code/game/objects/items/toys.dm
  icons/obj/toy.dmi
  sound/items/moo.ogg
Labels: Feature, Sprites

#2864 Новые растения и настольный звонок
  code/game/machinery/autolathe.dm
  code/game/objects/items/weapons/bell.dm
  code/game/objects/structures/flora.dm
  icons/obj/flora/plants.dmi
  icons/obj/objects.dmi
  maps/z1.dmm
  sound/items/manydings.ogg
  sound/items/oneding.ogg
  taucetistation.dme
Labels: Feature, Map Edit, Ready for Review, Sprites

#2928 Фикс проблемы секхудов.
  icons/mob/hud.dmi
Labels: Fix, Ready for Review, Sprites

#2937 Gateway refactoring
  code/_onclick/observer.dm
  code/controllers/configuration.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/gateway_locker.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/awaymissions/gateway.dm
  code/modules/awaymissions/zlevel.dm
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/arcticwaste.dmm
  maps/RandomZLevels/beach.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/example.dmm
  maps/RandomZLevels/jungle.dmm
  maps/RandomZLevels/listeningpost.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/wildwest.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/testmap.dmm
  maps/z1.dmm
  maps/z7.dmm
Labels: Map Edit, Ready for Review, Tweak

#2936 Добавление ID книг в окно их просмотра, а также в заголовок окна
  code/modules/library/lib_machines.dm
Labels: Ready for Review

#2939 Fix scooped punpun clothes
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/monkey/punpun.dm
  icons/mob/head.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Fix, Sprites

#2940 Santa Bum
  code/game/objects/random/random_cloth.dm
  code/game/objects/random/random_scrap.dm
  code/modules/scrap/scrap.dm
  code/modules/scrap/scrap_turfs.dm
Labels: Feature
