Repository TauCetiStation/TauCetiClassic, pull requests merged in 2018-06, with the labels that each got.

#2516 Reworking выкидывание нимф из дионы.
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
Labels: Fix

#2528 Открытие створок на ЦК
  maps/z2.dmm
Labels: Map Edit

#2537 Убрал шторки у барбера, добавил черные шкафы. Фиксы
  maps/z1.dmm
Labels: Map Edit

#2541 Hotfix всратого ящика
  maps/z1.dmm
Labels: Map Edit

#2465 Библиотекапдейт
  SQL/tgstation_schema.sql
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/library.dm
  code/modules/library/lib_machines.dm
Labels: Feature

#2519 Небольшой реворк химии.
  code/datums/spells/conjure.dm
  code/game/gamemodes/blob/blobs/factory.dm
  code/game/gamemodes/shadowling/shadowling_abilities.dm
  code/game/objects/items/weapons/paint.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/reagents/Chemistry-Reagents-Antidepressants.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/research/xenoarchaeology/machinery/coolant.dm
  code/modules/virus2/antibodies.dm
Labels: Fix, Test Merge, Tweak

#2524 Reworking выдача различным расам предметов.
  code/controllers/subsystem/jobs.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/mob/living/carbon/species.dm
Labels: Tweak

#2531 Чистка кода
  code/datums/uplinks_items.dm
Labels: Revert / Removal

#2539 Antag objectives tweaks
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: Tweak

#2540 Logs
  code/__HELPERS/logging.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/scoreboard.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/say.dm
Labels: Admin, Fix

#2552 Новые костюмы для клоуна и исправление для фальшивого шлема синдиката
  code/game/machinery/vending.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Fix, Sprites

#2557 Improved centcomm dog cage
  code/modules/cargo/supplyshuttle.dm
  maps/z2.dmm
Labels: Map Edit

#2534 Разноцветные перчатки с обрезанными пальцами, которые можно красить во время стирки
  code/game/machinery/washing_machine.dm
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Feature, Fix

#2543 Лампы в морге мигают зеленым если внутри тела есть игрок
  code/game/objects/structures/morgue.dm
  icons/obj/stationobjs.dmi
Labels: Feature, Sprites

#2553 Бакарди (и фиксы)
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  icons/obj/drinks.dmi
Labels: Feature, Fix, Sprites
