Repository TauCetiStation/TauCetiClassic, pull requests merged in 2018-03, with the labels that each got.

#2250 Твики гнилых респрайтов.
  code/controllers/subsystem/jobs.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/organ_internal.dm
  code/modules/virus2/effect.dm
Labels: SQUASH, Tweak

#2255 Однорукие держащие двуручное оружие.
  code/game/objects/items/weapons/twohanded.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/rocket.dm
Labels: Fix

#2283 Heater repsrite
  icons/obj/atmos.dmi
Labels: Sprites

#2287 Syndicate Merchandise
  code/datums/uplinks_items.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Merge Ready, Sprites

#2262 Нимфы. Вёрбы. Перепил.
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/living.dm
Labels: Feature, Tweak

#2271 Рефактор и ребаланс стелс костюмов
  code/__DEFINES/clothing.dm
  code/_onclick/item_attack.dm
  code/game/gamemodes/abduction/abduction_gear.dm
  code/game/gamemodes/events/ninja_equipment.dm
  code/game/objects/items.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/alien.dm
  code/modules/projectiles/guns/projectile/bow.dm
  code/modules/projectiles/guns/projectile/pneumatic.dm
  code/modules/reagents/dartgun.dm
Labels: Balance, Merge Ready, Tweak

#2296 Фиксы по карте #2183, #1349, #2263. Редизайн приемной медбея
  code/game/machinery/iv_drip.dm
  maps/z1.dmm
  maps/z5.dmm
  nano/images/nanomap_z1.png
Labels: Map Edit

#2289 Подбор поясом нескольких предметов за раз
  code/game/machinery/kitchen/smartfridge.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/projectiles/ammunition.dm
  code/modules/reagents/reagent_containers/glass.dm
Labels: Tweak

#2290 Wiz fixes
  code/datums/spells/ethereal_jaunt.dm
  code/datums/spells/in_hand.dm
  code/modules/projectiles/projectile/magic.dm
Labels: Fix

#2293 В ящики с броней из карго добавлены соответствующие шлема.
  code/modules/cargo/packs.dm
Labels: Tweak

#2295 Симулируемые турфы на заброшенный корабль.
  maps/z3.dmm
Labels: Map Edit

#2298 Дионы теперь не могут виртуозно играть на инструментах.
  code/datums/music_player.dm
Labels: Feature

#2299 Косметология для стиралки и кулера
  icons/obj/machines/washing_machine.dmi
  icons/obj/vending.dmi
Labels: Sprites

#2264 Апдейты шахтёрки
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/weapons/autoinjectors.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/modules/mining/drilling/circuitboard.dm
  code/modules/mining/equipment_locker.dm
  code/modules/mining/mining_fabricator/mining_research.dm
  code/modules/reagents/reagent_containers/food/glowsticks.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/research/designs.dm
Labels: Balance

#2294 Дроп поды и модули мехов для ОБР.
  code/game/gamemodes/nuclear/nuclearbomb.dm
  code/game/machinery/droppod.dm
  code/game/objects/effects/overlays.dm
  icons/obj/structures/droppod.dmi
  maps/z2.dmm
Labels: Map Edit

#2300 Нерф хлыста и мимобагфиксы
  code/datums/spells/Time_stop.dm
  code/game/gamemodes/changeling/headcrab.dm
  code/game/gamemodes/changeling/powers/Whip.dm
  code/modules/projectiles/effects.dm
  code/modules/projectiles/projectile.dm
Labels: Balance, Fix

#2301 Добавление профессии АВД в консоль ХоПа
  code/game/jobs/access.dm
  code/game/jobs/jobs.dm
Labels: Tweak

#2305 Новые спрайты для ячеек хранения трупов
  icons/obj/stationobjs.dmi
Labels: Sprites

#2306 Новый спрайт для комода с нижним бельем
  icons/obj/stationobjs.dmi
Labels: Sprites

#2310 Новая анимация появления Нарси
  icons/effects/narsie_spawn_anim.dmi
Labels: Sprites

#2313 Палочки для еды в Mr. Chang
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/kitchen.dm
  icons/obj/kitchen.dmi
Labels: Feature, Sprites

#2320 Иконки коробки с барьерами в руке
  code/game/objects/structures/inflatable.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Sprites

#2316 Фикс невозможности клонирования при пересадке головы или мозга
  code/modules/mob/living/carbon/brain/brain_item.dm
  code/modules/surgery/headreattach.dm
Labels: Fix

#2323 Новые платья для трапов
  code/game/machinery/vending.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#2332 Декоративных вещей в лоадауте и вне ПР. (re)
  code/modules/client/character menu/loadout.dm
  code/modules/client/character menu/loadout/loadout_accessories.dm
  code/modules/client/character menu/loadout/loadout_clothing.dm
  code/modules/client/character menu/loadout/loadout_general.dm
  code/modules/client/character menu/loadout/loadout_hats.dm
  code/modules/client/character menu/loadout/loadout_shoes.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/pants.dm
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites, Tweak

#2333 m65_pants_hotfix
  icons/mob/uniform.dmi
Labels: Sprites

#2337 униформа_equipment_hotfix
  code/modules/client/character menu/loadout/loadout_clothing.dm
Labels: Fix

#2354 Mapmerge
  .gitconfig
  code/controllers/subsystem/shuttles.dm
  code/game/machinery/doors/door.dm
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/arcticwaste.dmm
  maps/RandomZLevels/assistantChamber.dmm
  maps/RandomZLevels/beach.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/challenge.dmm
  maps/RandomZLevels/example.dmm
  maps/RandomZLevels/jungle.dmm
  maps/RandomZLevels/listeningpost.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/wildwest.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/templates/holodeck/basketball.dmm
  maps/templates/holodeck/beach.dmm
  maps/templates/holodeck/boxingcourt.dmm
  maps/templates/holodeck/burntest.dmm
  maps/templates/holodeck/courtroom.dmm
  maps/templates/holodeck/desert.dmm
  maps/templates/holodeck/emptycourt.dmm
  maps/templates/holodeck/meetinghall.dmm
  maps/templates/holodeck/picnicarea.dmm
  maps/templates/holodeck/snowfield.dmm
  maps/templates/holodeck/space.dmm
  maps/templates/holodeck/theatre.dmm
  maps/templates/holodeck/thunderdomecourt.dmm
  maps/templates/holodeck/turnoff.dmm
  maps/templates/holodeck/wildlifecarp.dmm
  maps/templates/shelter_2.dmm
  maps/testmap.dmm
  maps/z1.dmm
  maps/z2.dmm
  maps/z3.dmm
  maps/z4.dmm
  maps/z5.dmm
  maps/z6.dmm
  maps/z7.dmm
  tools/jmerge/1prepare_maps_all.bat
  tools/jmerge/1prepare_maps_torch.bat
  tools/jmerge/2clean_maps_all.bat
  tools/jmerge/2clean_maps_torch.bat
  tools/jmerge/JMerge.jar
  tools/jmerge/clean_map_git.sh
  tools/jmerge/git_merge_installer.bat
  tools/jmerge/git_merge_installer.sh
  tools/jmerge/install.txt
  tools/jmerge/mapmerge.sh
  tools/mapmerge/1prepare_map.bat
  tools/mapmerge/2run_map_merge.bat
  tools/mapmerge/MapMerge.jar
Labels: Map Edit

#2258 Интеграция нимфо-функционала ММИ.
  code/modules/mob/living/carbon/brain/MMI.dm
  icons/obj/assemblies.dmi
Labels: Feature, Sprites

#2285 Предпросмотр причесок при использовании ножниц
  code/game/objects/items/weapons/cosmetics.dm
Labels: Tweak

#2304 Возможность сканировать дион плэнт-аналайзером.
  code/defines/obj/hydro.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/scanners.dm
Labels: Feature, Tweak

#2325 Твики нимф.
  code/__DEFINES/items_clothing.dm
  code/game/machinery/podmen.dm
  code/game/turfs/simulated.dm
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/species.dm
Labels: Fix, Tweak

#2331 Цветастые гейм-киты, и гейм-кит капеллана.
  code/game/machinery/autolathe.dm
  code/game/objects/game_kit.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  icons/obj/items.dmi
Labels: Feature, Sprites, Tweak

#2347 Абсолютно все зоны в техах должны защищать от радиации.
  code/datums/weather/weather_types.dm
Labels: Tweak

#2351 Фиксы карандашика.
  code/game/objects/items/crayons.dm
Labels: Fix

#2180 Добавление сущностей генокраду
  code/__DEFINES/combat.dm
  code/__DEFINES/flags.dm
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/other_mobs.dm
  code/datums/diseases/advance/symptoms/voice_change.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/changeling/headcrab.dm
  code/game/gamemodes/changeling/powers/absorb.dm
  code/game/gamemodes/changeling/powers/essences.dm
  code/game/gamemodes/changeling/powers/fakedeath.dm
  code/game/gamemodes/changeling/powers/humanform.dm
  code/game/gamemodes/changeling/powers/lesserform.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/iv_drip.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/structures.dm
  code/game/objects/structures/tables_racks.dm
  code/game/sound.dm
  code/modules/admin/player_panel.dm
  code/modules/mob/emote.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/alien/facehugger/facehugger_abilities.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/login.dm
  code/modules/mob/living/carbon/logout.dm
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/parasite/meme.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/mob.dm
  code/modules/paperwork/paperbin.dm
  code/modules/projectiles/targeting.dm
  code/modules/recycling/disposal.dm
  code/modules/vehicles/spacebike.dm
  code/modules/ventcrawl/ventcrawl.dm
  icons/mob/screen_alert.dmi
  icons/mob/screen_gen.dmi
  taucetistation.dme
Labels: Feature

#2372 Имена беретов.
  code/modules/clothing/head/misc.dm
Labels: Fix

#2357 Дорабатываю #2255.
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/rocket.dm
Labels: Fix

#2361 Нитриловые перчатки и фартук хирурга
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/suits/jobs.dm
  icons/mob/hands.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#2364 В РнД добавлены отсутствующие импланты и сам имплантер.
  code/game/objects/items/weapons/implants/implantcase.dm
  code/modules/research/designs.dm
Labels: Tweak

#2380 Конъюнкция в проке health_analyze.
  code/game/objects/items.dm
  code/game/objects/items/devices/scanners.dm
Labels: Fix

#2383 Fixes
  code/game/jobs/job/science.dm
  code/game/jobs/jobs.dm
  code/game/machinery/computer/intruder_station.dm
  maps/z2.dmm
Labels: Map Edit

#2356 Перезалив #2319. Рефакторинг табличек/указателей с ТГ
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/inventory_sizes.dm
  code/game/objects/effects/decals/floor_stripes.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/signs.dm
  code/game/objects/structures/signs/_signs.dm
  code/game/objects/structures/signs/signs_departments.dm
  code/game/objects/structures/signs/signs_maps.dm
  code/game/objects/structures/signs/signs_plaques.dm
  code/game/objects/structures/signs/signs_warning.dm
  icons/obj/decals.dmi
  maps/z1.dmm
  maps/z2.dmm
  maps/z4.dmm
  maps/z5.dmm
  taucetistation.dme
Labels: Feature, Fix, Map Edit, Sprites

#2396 Редизайн и фиксы около барбершопа, редизайн криминалистики, фиксы RC …
  maps/z1.dmm
Labels: Map Edit

#2398 Кладу на место открытый шкаф КМ-а
  icons/obj/closet.dmi
Labels: Sprites

#2400 Хотфикс ландмарки парикмахера и удаление шаттерсов
  maps/z1.dmm
Labels: Map Edit
