Repository TauCetiStation/TauCetiClassic, pull requests merged in 2018-10, with the labels that each got.

#2763 Map
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/arcticwaste.dmm
  maps/RandomZLevels/assistantChamber.dmm
  maps/RandomZLevels/beach.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/challenge.dmm
  maps/RandomZLevels/example.dmm
  maps/RandomZLevels/jungle.dmm
  maps/RandomZLevels/listeningpost.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/wildwest.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/templates/holodeck/basketball.dmm
  maps/templates/holodeck/beach.dmm
  maps/templates/holodeck/boxingcourt.dmm
  maps/templates/holodeck/burntest.dmm
  maps/templates/holodeck/courtroom.dmm
  maps/templates/holodeck/desert.dmm
  maps/templates/holodeck/emptycourt.dmm
  maps/templates/holodeck/meetinghall.dmm
  maps/templates/holodeck/picnicarea.dmm
  maps/templates/holodeck/snowfield.dmm
  maps/templates/holodeck/space.dmm
  maps/templates/holodeck/theatre.dmm
  maps/templates/holodeck/thunderdomecourt.dmm
  maps/templates/holodeck/turnoff.dmm
  maps/templates/holodeck/wildlifecarp.dmm
  maps/templates/shelter_2.dmm
  maps/testmap.dmm
  maps/z1.dmm
  maps/z2.dmm
  maps/z3.dmm
  maps/z4.dmm
  maps/z5.dmm
  maps/z6.dmm
  maps/z7.dmm
  tools/dmm-merge-tool/scripts/precommit.groovy
Labels: Map Edit

#2757 Удаляем дубликаты
  icons/obj/food.dmi
Labels: Sprites

#2762 Новые спрайты лент.
  code/game/objects/items/weapons/policetape.dm
  icons/policetape.dmi
  maps/z1.dmm
Labels: Map Edit, Sprites, Tweak

#2764 Обновление спрайтов беретов офицера и капитана ЦК.
  code/modules/admin/verbs/debug.dm
  code/modules/clothing/head/misc.dm
  icons/mob/head.dmi
Labels: Sprites

#2765 [Mirror]Джетпак для капитанской брони.
  code/modules/clothing/spacesuits/captain.dm
Labels: Tweak

#2770 [Mirror]Новый плейлист в джукбокс
  code/modules/media/jukebox.dm
Labels: Feature

#2750 Xenoarcheologist изменён на Xenoarchaeologist, или к чему может привести…
  code/game/jobs/job/science.dm
  code/game/jobs/jobs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/economy/Job_Departments.dm
Labels: Fix

#2759 Порт инвентаря с бейстейшен
  code/__DEFINES/inventory_sizes.dm
  code/_onclick/hud/screen_objects.dm
  code/defines/obj/weapon.dm
  code/game/mecha/mecha_control_console.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/radio/beacon.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/game/objects/items/weapons/storage/secure.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/storage/storage_ui/default.dm
  code/game/objects/items/weapons/storage/storage_ui/storage_ui.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/game/objects/structures/inflatable.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/accessories/storage.dm
  code/modules/projectiles/guns/projectile/pneumatic.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/tools/tools.dm
  code/modules/research/xenoarchaeology/tools/tools_pickaxe.dm
  code/modules/scrap/oldificator.dm
  code/modules/scrap/scrap.dm
  code/modules/scrap/scrap_tools.dm
  icons/mob/screen1.dmi
  taucetistation.dme
Labels: Feature, Sprites, Test Merge

#2781 Респрайт Ксеноархеологии+Добавление Wave Scanner Backpack
  code/modules/research/xenoarchaeology/misc.dm
  code/modules/research/xenoarchaeology/tools/gearbelt.dm
  code/modules/research/xenoarchaeology/tools/tools.dm
  code/modules/research/xenoarchaeology/tools/tools_anoscanner.dm
  code/modules/research/xenoarchaeology/tools/tools_coresampler.dm
  code/modules/research/xenoarchaeology/tools/tools_depthscanner.dm
  code/modules/research/xenoarchaeology/tools/tools_locater.dm
  code/modules/research/xenoarchaeology/tools/tools_pickaxe.dm
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/belt_mirror.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/closet.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/device.dmi
  icons/obj/storage.dmi
  icons/obj/xenoarchaeology.dmi
  maps/z5.dmm
Labels: Map Edit, Sprites, Tweak

#2784 При выключении guest pass terminal из сети его спрайт исчезал.
  icons/obj/computer.dmi
Labels: Fix, Sprites

#2786 Добавляет берет ХоСа.
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/jobs.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites

#2782 Фикс берета дедсквада[mergeready]
  code/modules/clothing/spacesuits/miscellaneous.dm
  icons/mob/head.dmi
Labels: Sprites

#2794 Adds Shiba-Inu!
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/structures/crates_lockers/closets/crittercrate.dm
  code/modules/cargo/packs.dm
  code/modules/mob/living/simple_animal/friendly/shiba.dm
  code/modules/research/xenoarchaeology/artifact/artifact_autocloner.dm
  icons/mob/animal.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/items.dmi
  taucetistation.dme
Labels: Feature, Sprites

#2795 Фиксы спрайтов инструментов.
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/mining/mine_items.dm
  icons/obj/items.dmi
  icons/obj/mining/hand_tools.dmi
  icons/obj/tools.dmi
Labels: Fix, Sprites

#2804 Update JTGMerge
  tools/dmm-merge-tool/JTGMerge.jar
Labels: Tools

#2801 фикс водички.
  code/game/turfs/simulated/floor_types.dm
Labels: Fix, Sprites

#2813 Book bags
  code/game/jobs/job/civilian.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/belt_mirror.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/library.dmi
Labels: Feature, Sprites

#2810 Небольшой фикс
  code/modules/mining/monsters.dm
Labels: Fix
