Repository TauCetiStation/TauCetiClassic, pull requests merged in 2018-07, with the labels that each got.

#2554 Asteroid
  code/datums/helper_datums/map_template.dm
  code/game/turfs/turf.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/drop_asteroid.dm
  code/modules/mining/mine_turfs.dm
  sound/effects/Explosion3.ogg
  taucetistation.dme
Labels: Admin, Feature, Test Merge

#2559 Новый шаттл эвакуации и отбытие
  maps/z1.dmm
  maps/z2.dmm
  nano/images/nanomap_z1.png
Labels: Map Edit

#2588 Фикс нестакающихся досок
  code/defines/obj/hydro.dm
Labels: Fix

#2567 Experimental Welding Tool регенерирует топливо
  code/game/objects/items/weapons/tools.dm
Labels: Fix

#2582 maint access for RD
  code/game/jobs/job/science.dm
Labels: Tweak

#2590 Ограничение количества наличных в банкомате
  code/modules/economy/ATM.dm
Labels: Feature

#2597 cargo bay remap
  code/modules/locations/shuttles/cargo.dmi
  code/modules/locations/shuttles/cargofloor.dmi
  code/modules/locations/shuttles/wagon.dmi
  maps/z1.dmm
  maps/z2.dmm
Labels: Map Edit, Sprites, Test Merge

#2600 Test merge changelog
  html/assets/css/changelog.css
  html/changelog.html
Labels: Tools

#2601 Updates JMerge
  tools/jmerge/JMerge.jar
Labels: Tools

#2607 Переименование спрайта для интеркомов
  code/modules/locations/shuttles/intercom.dmi
Labels: Fix, Sprites

#2608 Текстуры у advanced kit-ов, зависящие от кол-ва.
  code/game/objects/items/stacks/medical.dm
  icons/obj/items.dmi
Labels: Feature, Sprites

#2517 Рутсонг
  code/modules/mob/hear_say.dm
  code/modules/mob/language.dm
Labels: Feature

#2631 [Mirror]New IPC screens w/ colours
  code/modules/client/character menu/general.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#2638 [Mirror]Теперь в Body Scanner можно Drag and Drop'ать пациентов.
  code/game/machinery/adv_med.dm
Labels: Tweak

#2605 Ремап восточного и западного крыла.
  code/game/area/Space Station 13 areas.dm
  code/game/objects/structures/flora.dm
  code/modules/holodeck/HolodeckControl.dm
  icons/obj/flora/jungleflora.dmi
  icons/obj/flora/jungletrees.dmi
  icons/obj/flora/jungletreesmall.dmi
  icons/obj/flora/largejungleflora.dmi
  icons/obj/flora/rocks.dmi
  icons/turf/areas.dmi
  icons/turf/floors.dmi
  maps/templates/holodeck/basketball.dmm
  maps/templates/holodeck/beach.dmm
  maps/templates/holodeck/courtroom.dmm
  maps/templates/holodeck/emptycourt.dmm
  maps/templates/holodeck/meetinghall.dmm
  maps/templates/holodeck/picnicarea.dmm
  maps/templates/holodeck/theatre.dmm
  maps/templates/holodeck/thunderdomecourt.dmm
  maps/z1.dmm
  nano/images/nanomap_z1.png
Labels: Feature, Map Edit, Sprites, Test Merge
