Repository TauCetiStation/TauCetiClassic, pull requests merged in 2019-07, with the labels that each got.

#3577 Минимальное время до взрыва нюки увеличено на 5 минут (с 7 до 12)
  code/game/gamemodes/nuclear/nuclearbomb.dm
Labels: Balance, Feedback required, Test Merge Candidate

#3602 Чистка основных слоёв
  maps/z1.dmm
  maps/z2.dmm
  maps/z5.dmm
  maps/z7.dmm
Labels: Map Edit

#3456 Фичи, звуки и фиксы разговора, эмоутов и способностей ксеноморфов
  code/_globalvars/lists/misc.dm
  code/game/gamemodes/cult/cult_datums.dm
  code/game/sound.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/alien/death.dm
  code/modules/mob/living/carbon/alien/facehugger/emote.dm
  code/modules/mob/living/carbon/alien/facehugger/facehugger_abilities.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/alien/humanoid/emote.dm
  code/modules/mob/living/carbon/alien/larva/emote.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/alien/say.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/research/xenoarchaeology/machinery/artifact_harvester.dm
  sound/effects/mob/ear_ring_single.ogg
  sound/effects/mob/earring_15s.ogg
  sound/effects/mob/earring_30s.ogg
  sound/effects/mob/earring_yell_female.ogg
  sound/effects/mob/earring_yell_male.ogg
  sound/effects/resin_build.ogg
  sound/voice/xenomorph/big_hiss.ogg
  sound/voice/xenomorph/death_1.ogg
  sound/voice/xenomorph/growl_1.ogg
  sound/voice/xenomorph/growl_2.ogg
  sound/voice/xenomorph/hiss_1.ogg
  sound/voice/xenomorph/hiss_2.ogg
  sound/voice/xenomorph/hiss_3.ogg
  sound/voice/xenomorph/queen_roar.ogg
  sound/voice/xenomorph/roar_1.ogg
  sound/voice/xenomorph/roar_2.ogg
  sound/voice/xenomorph/small_roar.ogg
  sound/voice/xenomorph/talk_1.ogg
  sound/voice/xenomorph/talk_2.ogg
  sound/voice/xenomorph/talk_3.ogg
  sound/voice/xenomorph/talk_4.ogg
  sound/voice/xenomorph/whimper.ogg
  taucetistation.dme
Labels: Fix, Revert / Removal, Sound

#3587 Летальная дробь дробовика, становится разлетающейся дробью, без фантомно исчезающих пуль
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Balance, Test Merge Candidate

#3592 Порт фичи с выталкиванием моба из шлюза при зажимании с бея. Звуки шлюзов с бея
  code/__DEFINES/misc.dm
  code/_globalvars/lists/misc.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/simple_animal/hulk.dm
  sound/machines/airlock/access_denied.ogg
  sound/machines/airlock/airlockForced.ogg
  sound/machines/airlock/airlockToggle.ogg
  sound/machines/airlock/bolts_down_1.ogg
  sound/machines/airlock/bolts_down_2.ogg
  sound/machines/airlock/bolts_up_1.ogg
  sound/machines/airlock/bolts_up_2.ogg
  sound/machines/airlock/close.ogg
  sound/machines/airlock/close_force.ogg
  sound/machines/airlock/creaking.ogg
  sound/machines/airlock/open.ogg
  sound/machines/airlock/open_force.ogg
  sound/machines/airlock/toggle.ogg
  sound/machines/firedoor_close.ogg
  sound/machines/firedoor_open.ogg
Labels: Sound, Tweak

#3607 Изменение конфига stale-бота
  .github/stale.yml
Labels: Maintainability Improvements, Tools

#3605 Fix sound save
  code/game/sound.dm
Labels: Fix

#3606 Фикс превращения в слайма через экстракт
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
Labels: Fix

#3600 Фикс исчезновения отростков скреллов от радиации и при ожогах
  code/modules/holidays/new_year/presents.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Fix

#3604 Возможность пулла движущихся атомов через Z-уровни
  code/game/atoms_movable.dm
  code/game/turfs/space/space.dm
Labels: Tweak

#3614 Chatbridge2
  code/game/machinery/fax.dm
  code/game/world.dm
  code/modules/admin/verbs/custom_event.dm
Labels: Quality Of Life

#3615 Bugfixes 5
  code/game/machinery/OpTable.dm
  code/game/machinery/bots/secbot.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/verbs/ooc.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/organ_external.dm
Labels: Fix

#3616 Уменьшение шрифта кнопок гунчата
  code/modules/goonchat/browserassets/css/browserOutput.css
Labels: Tweak

#3621 фиксы виндоров на кухне
  maps/z1.dmm
Labels: Map Edit

#3617 Чистка папки тулзов
  tools/MapFXDrawer/MapFXDrawer.jar
  tools/MapFXDrawer/README.md
  tools/MapFXDrawer/configs/README.md
  tools/MapFXDrawer/configs/clean.json
  tools/MapFXDrawer/start.bat
  tools/MapFXDrawer/start.sh
  tools/tmcl.sh
Labels: Tools

#3620 Фикс звука объявления дельты. Вариативность звукам кашля с кровью
  code/game/gamemodes/heist/fulton.dm
  code/game/sound.dm
  code/modules/mob/living/carbon/human/emote.dm
  sound/misc/fbcough.ogg
  sound/misc/mbcough.ogg
  sound/voice/mob/fbcough_1.ogg
  sound/voice/mob/fbcough_2.ogg
  sound/voice/mob/fbcough_3.ogg
  sound/voice/mob/femalescream_1.ogg
  sound/voice/mob/femalescream_2.ogg
  sound/voice/mob/femalescream_3.ogg
  sound/voice/mob/femalescream_4.ogg
  sound/voice/mob/femalescream_5.ogg
  sound/voice/mob/frigvomit_1.ogg
  sound/voice/mob/frigvomit_2.ogg
  sound/voice/mob/fvomit_1.ogg
  sound/voice/mob/fvomit_2.ogg
  sound/voice/mob/malescream_1.ogg
  sound/voice/mob/malescream_2.ogg
  sound/voice/mob/malescream_3.ogg
  sound/voice/mob/malescream_4.ogg
  sound/voice/mob/malescream_5.ogg
  sound/voice/mob/malescream_6.ogg
  sound/voice/mob/malescream_7.ogg
  sound/voice/mob/mbcough_1.ogg
  sound/voice/mob/mbcough_2.ogg
  sound/voice/mob/mbcough_3.ogg
  sound/voice/mob/mrigvomit_1.ogg
  sound/voice/mob/mrigvomit_2.ogg
  sound/voice/mob/mvomit_1.ogg
  sound/voice/mob/mvomit_2.ogg
Labels: Sound

#3626 изменение pretty dress
  icons/mob/uniform.dmi
Labels: Merge Ready, Sprites

#3631 Набор Византийской одежды
  code/game/machinery/vending.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#3603 Новая система исследований
  code/__DEFINES/research.dm
  code/_globalvars/lists/objects.dm
  code/game/gamemodes/events/ninja_equipment.dm
  code/game/gamemodes/scoreboard.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/explosion_recursive.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/cargo/exports/research.dm
  code/modules/clothing/spacesuits/ninja.dm
  code/modules/detectivework/autopsy.dm
  code/modules/mining/mining_fabricator/mining_research.dm
  code/modules/mob/living/simple_animal/friendly/robot.dm
  code/modules/power/fusion/fusion_circuits.dm
  code/modules/research/circuitprinter.dm
  code/modules/research/designs.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/destructive_analyzer.dm
  code/modules/research/experiment.dm
  code/modules/research/protolathe.dm
  code/modules/research/rd-readme.dm
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
  code/modules/research/server.dm
  code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm
  code/modules/scrap/scrap_burner.dm
  code/modules/shieldgen/circuits_and_designs.dm
  code/modules/virus2/analyser.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/device.dmi
  maps/templates/space_structures/abandoned_ship.dmm
  maps/templates/space_structures/derelict_station.dmm
  maps/templates/space_structures/derelict_teleporter.dmm
  maps/templates/space_structures/dj_station.dmm
  maps/templates/space_structures/teleporter.dmm
  maps/templates/space_structures/toilet.dmm
  maps/z1.dmm
  nano/css/shared.css
  nano/images/science.png
  nano/templates/rdconsole.tmpl
  taucetistation.dme
Labels: Experimental, Map Edit, Sprites, Test Merge Candidate

#3622 Звуки галлюцинаций и их улучшения в коде
  code/modules/flufftext/Dreaming.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/research/xenoarchaeology/finds/finds_special.dm
  sound/hallucinations/demons_1.ogg
  sound/hallucinations/demons_2.ogg
  sound/hallucinations/demons_3.ogg
  sound/hallucinations/fake_announcement.ogg
  sound/hallucinations/fake_battle_1.ogg
  sound/hallucinations/fake_battle_2.ogg
  sound/hallucinations/fake_battle_3.ogg
  sound/hallucinations/fake_death.ogg
  sound/hallucinations/fake_poweroff.ogg
  sound/hallucinations/i_see_you_1.ogg
  sound/hallucinations/i_see_you_2.ogg
  sound/hallucinations/i_see_you_3.ogg
  sound/hallucinations/liar.ogg
  sound/hallucinations/scary_sound_1.ogg
  sound/hallucinations/scary_sound_2.ogg
  sound/hallucinations/scary_sound_3.ogg
  sound/hallucinations/scary_sound_4.ogg
  sound/hallucinations/whispers_1.ogg
  sound/hallucinations/whispers_2.ogg
  sound/voice/growl1.ogg
  sound/voice/growl2.ogg
  sound/voice/growl3.ogg
Labels: Sound, Test Merge Candidate

#3630 Добавлена кнопка Send Emergency Message ИИшке
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Feature

#3632 Тасовка иконок оружия и удаление родителя у посохов
  code/game/gamemodes/wizard/spellbook.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/projectiles/guns/magic/staff.dm
  icons/obj/gun.dmi
Labels: Maintainability Improvements, Sprites

#3636 Нельзя писать в закрытый тикет
  code/modules/admin/verbs/adminpm.dm
Labels: Fix

#3638 Меню camera bug не обновлялось при режиме Cancel camera view
  code/game/objects/items/devices/camera_bug.dm
Labels: Fix

#3635 Less map variables
  code/game/jobs/access.dm
  code/game/machinery/door_control.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/vending.dm
  code/modules/locations/centcomm/velocity.dm
  code/modules/research/rdconsole.dm
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/beach.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/challenge.dmm
  maps/RandomZLevels/example.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/templates/space_structures/derelict_station.dmm
  maps/templates/space_structures/dj_station.dmm
  maps/z1.dmm
  maps/z2.dmm
  maps/z5.dmm
Labels: Maintainability Improvements, Map Edit, Merge Ready

#3639 Armoury windows require security access instead of warden access.
  maps/z1.dmm
Labels: Map Edit

#3642 Фикс доступа у консоли восстановления ИИ
  code/game/machinery/computer/aifixer.dm
Labels: Fix

#3645 Фикс обрывающегося звука при переходе между зонами с одинаковым эмбие…
  code/__HELPERS/lists.dm
  code/game/area/areas.dm
Labels: Fix

#3650 Fixing the req_access list being null.
  code/game/machinery/deployable.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/windoor_assembly.dm
Labels: Fix

#3653 Хаулер и берцы в шкаф Вардена
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Tweak

#3660 Менторы могут отвечать на Mhelp
  code/modules/admin/verbs/adminpm.dm
Labels: Fix

#3651 Новая рандомная структура
  code/datums/space_structures.dm
  code/game/area/Space Station 13 areas.dm
  maps/templates/space_structures/abandoned_lab.dmm
Labels: Map Edit

#3575 Квас
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/packs.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  icons/obj/drinks.dmi
  icons/obj/objects.dmi
Labels: Feature, Help Wanted, I ded, Sprites

#3672 Make client hard deleted
  code/modules/client/client procs.dm
Labels: Fix

#3657 Фикс дион и мартышек
  code/modules/mob/living/life.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#3665 Космические структуры для теленауки
  code/datums/space_structures.dm
  code/game/area/Space Station 13 areas.dm
  code/modules/awaymissions/planetarium_spawner.dm
  maps/templates/space_structures/agrosphere.dmm
  maps/templates/space_structures/ghost_ship_1.dmm
  maps/templates/space_structures/ghost_ship_2.dmm
  maps/templates/space_structures/planetarium.dmm
  maps/templates/space_structures/robostation.dmm
  taucetistation.dme
Labels: Map Edit, Test Merge Candidate

#3687 Chat Subsystem ported from TG
  code/__DEFINES/subsystem.dm
  code/controllers/subsystem/chat.dm
  code/modules/goonchat/browserOutput.dm
  taucetistation.dme
Labels: Performance, Test Merge Candidate

#3686 Ленивый фикс дыхательной маски
  icons/mob/mask.dmi
Labels: Sprites, Test Merge Candidate

#3679 Janitor Rework
  code/__DEFINES/misc.dm
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/game/gamemodes/heist/heist_prices.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/items/weapons/mop.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/objs.dm
  code/game/objects/random/random_structures.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/reagents/reagent_containers/spray.dm
  icons/obj/janitor.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
  sound/effects/roll.ogg
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#3685 Убираем звуки кликов КПК и клавиатуры у ИИ
  code/game/machinery/computer/computer.dm
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Fix, Test Merge Candidate

#3688 tie - accessory
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/ties.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/accessory.dmi
  icons/mob/ties.dmi
  icons/obj/clothing/accessory.dmi
  icons/obj/clothing/accessory_overlay.dmi
  icons/obj/clothing/ties_overlay.dmi
Labels: Sprites

#3659 Forcing vomit with fingers, reagents and punches.
  code/datums/diseases/advance/symptoms/vomit.dm
  code/game/atoms.dm
  code/game/gamemodes/abduction/gland.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/candle.dm
  code/game/turfs/simulated.dm
  code/modules/mining/equipment_locker.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  code/modules/scrap/scrap.dm
  code/modules/virus2/effect.dm
Labels: Contentious, Feature, Test Merge Candidate

#3655 Three chemicals to help patient stabilization.
  code/game/atoms.dm
  code/game/objects/items/weapons/autoinjectors.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/organs/blood.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  icons/obj/syringe.dmi
Labels: Feature, Sprites, Test Merge Candidate

#3662 Healthanalyzer scans in a seperate window.
  code/defines/obj/hydro.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/mob/living/silicon/robot/analyzer.dm
  code/modules/research/xenoarchaeology/finds/finds_pipboy.dm
Labels: Feature, Test Merge Candidate

#3648 Респрайт EGun
  icons/obj/gun.dmi
Labels: Contentious, Feedback required, Sprites, Test Merge Candidate

#3652 Изменения доступных для вкладывания в кобуру вещей
  code/game/objects/items.dm
  code/game/objects/items/toys.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/launcher.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/rocket.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/reagents/grenade_launcher.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Balance, Test Merge Candidate

#3670 Нёрф големом
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/species.dm
Labels: Balance, Contentious, Test Merge Candidate

#3678 Вечернее освещение
  code/__DEFINES/subsystem.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/nightshift.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  code/modules/security levels/security levels.dm
  config/example/game_options.txt
  nano/templates/apc.tmpl
  taucetistation.dme
Labels: Feature, Test Merge Candidate

#3680 Ленивый фикс еды
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Balance, Test Merge Candidate

#3703 Звуки пожарной и атмосферной тревоги с бея
  code/game/machinery/alarm.dm
  sound/machines/alarm_air.ogg
  sound/machines/alarm_fire.ogg
Labels: Sound, Test Merge Candidate

#3716 Добавляем немного "хитбокса" пробирке
  icons/obj/chemical.dmi
Labels: Sprites

#3706 2 небольших фикса pAI
  code/game/objects/items/devices/paicard.dm
  code/modules/mob/living/silicon/pai/life.dm
  code/modules/mob/living/silicon/pai/software.dm
Labels: Fix
