Repository TauCetiStation/TauCetiClassic, pull requests merged in 2019-06, with the labels that each got.

#3536 Нерф соча и фикс бага связанного с перезарядкой посохов
  code/modules/projectiles/guns/magic.dm
  code/modules/projectiles/guns/magic/staff.dm
Labels: Balance, Fix, Tweak

#3535 Добавление в блэклист билдов с критическими багами
  code/modules/client/client procs.dm
Labels: Fix, byond

#3537 Decoy AI removed from silicon_list, they should not affect round end statistics
  code/modules/mob/living/silicon/decoy/decoy.dm
Labels: Fix

#3437 Rewrited chat bot
  code/__DEFINES/bridge.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/text.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/shuttles.dm
  code/controllers/subsystem/ticker.dm
  code/game/machinery/fax.dm
  code/game/verbs/ooc.dm
  code/game/world.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/custom_event.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/admin/verbs/pray.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/whitelist.dm
  code/modules/bridge/chat_bridge.dm
  code/modules/client/client procs.dm
  code/modules/ext_scripts/get_webpage.dm
  code/modules/ext_scripts/python.dm
  code/modules/ext_scripts/shell.dm
  code/modules/ext_scripts/slack.dm
  code/modules/mentor/mentorhelp.dm
  code/modules/mentor/mentorpm.dm
  code/world.dm
  config/example/config.txt
  scripts/get.py
  scripts/slackbot_message.py
  taucetistation.dme
Labels: Admin, Code Improvements, Refactor

#3512 Round ID
  SQL/feedback_schema.sql
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/voting.dm
  code/defines/procs/statistics.dm
  code/game/gamemodes/abduction/abduction.dm
  code/game/gamemodes/autotraitor/autotraitor.dm
  code/game/gamemodes/blob/blob_finish.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/epidemic/epidemic.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gang/gang.dm
  code/game/gamemodes/heist/heist.dm
  code/game/gamemodes/malfunction/malfunction.dm
  code/game/gamemodes/meteor/meteor.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/nuclear/nuclearbomb.dm
  code/game/gamemodes/revolution/anti_revolution.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/revolution/rp_revolution.dm
  code/game/gamemodes/sandbox/sandbox.dm
  code/game/gamemodes/shadowling/shadowling.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/wizard/wizard.dm
  code/game/json.dm
  code/game/magic/archived_book.dm
  code/game/world.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/admin.dm
  code/modules/admin/permissionverbs/permissionedit.dm
  code/modules/mob/mob.dm
  code/modules/research/message_server.dm
Labels: Code Improvements, Feature, database

#3507 Стелс модуль и стелс костюм для ЕРТ
  code/game/objects/random/random_cloth.dm
  code/modules/clothing/spacesuits/rig/ert.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Contentious, Feature

#3487 Балансируем культ
  code/game/gamemodes/cult/cult_datums.dm
Labels: Balance, Fix, Merge Ready, Test Merge Candidate

#3550 Bridge changes for better life
  code/controllers/subsystem/ticker.dm
  code/game/world.dm
  code/modules/bridge/chat_bridge.dm
Labels: Fix

#3554 SQL errors log
  code/__DEFINES/bridge.dm
  code/__HELPERS/logging.dm
  code/defines/procs/dbcore.dm
  code/game/world.dm
Labels: Code Improvements, database

#3405 [MIRROR] Влажной тряпочкой можно протереть стакан в руках
  code/modules/detectivework/footprints_and_rag.dm
Labels: Merge Ready, Tweak

#2773 [Mirror]Changeling stasis fix
  code/game/gamemodes/changeling/headcrab.dm
  code/game/gamemodes/changeling/powers/revive.dm
Labels: Fix, Merge Ready

#3389 Добавлено логирования при смене законов синтетикам.
  code/datums/uplinks_items.dm
  code/game/gamemodes/factions.dm
  code/game/gamemodes/game_mode.dm
  code/game/objects/items/weapons/AI_modules.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/random/random_science.dm
  code/game/objects/random/random_syndie.dm
  code/modules/research/designs.dm
  maps/z1.dmm
  maps/z2.dmm
Labels: Admin

#3552 Propper disconnection from db on restart
  code/game/world.dm
Labels: Test Merge Candidate, database

#3534 Round stats
  code/__HELPERS/logging.dm
  code/_globalvars/misc.dm
  code/controllers/subsystem/ticker.dm
  code/datums/datacore.dm
  code/defines/procs/announces.dm
  code/game/gamemodes/abduction/abduction.dm
  code/game/gamemodes/blob/blob_finish.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/epidemic/epidemic.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gang/gang.dm
  code/game/gamemodes/heist/heist.dm
  code/game/gamemodes/heist/heist_old.dm
  code/game/gamemodes/infestation/infestation.dm
  code/game/gamemodes/malfunction/malfunction.dm
  code/game/gamemodes/meme/meme.dm
  code/game/gamemodes/meteor/meteor.dm
  code/game/gamemodes/mutiny/mutiny.dm
  code/game/gamemodes/ninja/ninja.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/revolution/anti_revolution.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/revolution/rp_revolution.dm
  code/game/gamemodes/scoreboard.dm
  code/game/gamemodes/shadowling/shadowling.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/wizard/wizard.dm
  code/game/jobs/job/captain.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/skills.dm
  code/game/machinery/fax.dm
  code/game/machinery/records_scanner.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/transform_procs.dm
  code/modules/security levels/security levels.dm
Labels: Feature, Test Merge Candidate

#3520 Отключен вывод информации о схожих айпи/айди пользователям бег R LOG
  code/modules/mob/login.dm
Labels: Admin

#3548 Fix the problem with early 'dp_vent_pump/update_icon' call from mapload initialization
  code/game/turfs/simulated.dm
Labels: Fix

#3561 Database schemas update
  SQL/feedback_schema.sql
  SQL/ss13.sql
  SQL/ss13_feed.sql
  SQL/tgstation_schema.sql
Labels: database

#3452 Респрайт кучи всего в 3/4.
  code/game/dna/dna_modifier.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/atmo_control.dm
  code/game/machinery/computer/Operating.dm
  code/game/machinery/computer/area_atmos_computer.dm
  code/game/machinery/computer/atmos_alert.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/cloning.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/pod.dm
  code/game/machinery/computer/prisoner.dm
  code/game/machinery/computer/robot.dm
  code/game/machinery/computer/shuttle.dm
  code/game/machinery/computer/skills.dm
  code/game/machinery/computer/station_alert.dm
  code/game/machinery/computer/syndicate_shuttle.dm
  code/game/machinery/computer/syndicate_specops_shuttle.dm
  code/game/machinery/computer/vox_shuttle.dm
  code/game/machinery/teleporter.dm
  code/game/mecha/mech_bay.dm
  code/game/mecha/mecha_control_console.dm
  code/modules/cargo/console.dm
  code/modules/detectivework/detective_work.dm
  code/modules/library/lib_machines.dm
  code/modules/locations/shuttles/mine_sci_shuttle.dm
  code/modules/mob/living/silicon/robot/drone/drone_console.dm
  code/modules/power/gravitygenerator.dm
  code/modules/power/solar.dm
  code/modules/power/turbine.dm
  code/modules/stock_market/computer.dm
  code/modules/virus2/curer.dm
  code/modules/virus2/diseasesplicer.dm
  icons/obj/computer.dmi
  icons/obj/machines/particle_accelerator.dmi
  icons/obj/machines/particle_accelerator2.dmi
  icons/obj/machines/power/fusion.dmi
  icons/obj/power.dmi
  icons/obj/stock_parts.dmi
  icons/obj/virology.dmi
  maps/z1.dmm
  maps/z2.dmm
  maps/z3.dmm
  maps/z4.dmm
  maps/z5.dmm
Labels: Map Edit, Sprites

#3538 Status display updated
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/status_display.dm
  icons/obj/status_display.dmi
Labels: Sprites

#3540 Продолжение настенных спрайтов от WalterJe
  icons/obj/airlock_machines.dmi
  icons/obj/computer.dmi
  icons/obj/items.dmi
  icons/obj/monitors.dmi
  icons/obj/power.dmi
  icons/obj/radio.dmi
  icons/obj/stationobjs.dmi
  icons/obj/terminals.dmi
Labels: Sprites

#3566 Clean shutdown, round log helper
  code/__HELPERS/logging.dm
  code/game/world.dm
  scripts/hooks/round_end.sh.example
  scripts/hooks/round_reboot.example
Labels: Code Improvements

#3570 Bugfixes
  code/game/machinery/doors/airlock.dm
  code/game/machinery/hydroponics.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/modules/cargo/supplyshuttle.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  icons/obj/Cryogenic3.dmi
Labels: Fix, Sprites

#3572 Bugfixes 2
  code/game/machinery/bots/secbot.dm
  code/game/objects/items/devices/radio/beacon.dm
  code/game/objects/items/weapons/tape.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/floor.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix

#3551 Status display fixes
  code/controllers/subsystem/shuttles.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/status_display.dm
  nano/templates/pda.tmpl
Labels: Tweak

#3491 Генерация космических структур в случайных координатах
  code/_globalvars/mapping.dm
  code/controllers/subsystem/mapping.dm
  code/datums/helper_datums/map_template.dm
  code/datums/space_structures.dm
  code/modules/client/asset_cache.dm
  code/modules/maps/reader_optimized.dm
  code/modules/paperwork/paper.dm
  icons/paper_icons/bluentlogo.png
  maps/templates/space_structures/abandoned_ship.dmm
  maps/templates/space_structures/clown_shuttle.dmm
  maps/templates/space_structures/derelict_station.dmm
  maps/templates/space_structures/derelict_teleporter.dmm
  maps/templates/space_structures/dj_station.dmm
  maps/templates/space_structures/teleporter.dmm
  maps/templates/space_structures/toilet.dmm
  maps/z1.dmm
  maps/z3.dmm
  maps/z4.dmm
  taucetistation.dme
Labels: Map Edit, Test Merge Candidate

#3578 Status display frame and radiation image updated
  icons/obj/status_display.dmi
Labels: Sprites

#3573 Bugfixes 3
  code/defines/procs/AStar.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/client/client procs.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/power/apc.dm
  code/modules/power/cable.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
Labels: Fix

#3581 Быстрофикс невидимых бинтов
  code/game/objects/items/stacks/medical.dm
  icons/obj/items.dmi
Labels: Sprites

#3576 Bugfixes 4
  code/game/machinery/computer/guestpass.dm
  code/game/objects/items/weapons/storage/storage_ui/default.dm
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  code/modules/organs/organ_external.dm
Labels: Fix, Tweak
