Repository TauCetiStation/TauCetiClassic, pull requests merged in 2019-10, with the labels that each got.

#3996 бьем бутылки/стаканы
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
Labels: Feature, Test Merge Candidate

#3998 Update таймера закрывающего камеры в бриге.
  code/game/machinery/doors/brigdoors.dm
Labels: Test Merge Candidate, Tweak

#3988 Невозможность дизармить спиной и разброс при стрельбе за спину.
  code/__DEFINES/mob.dm
  code/_onclick/click.dm
  code/game/atoms_movable.dm
  code/game/objects/buckling.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/firing.dm
  code/modules/projectiles/gun.dm
Labels: Experimental, Test Merge Candidate

#4012 новые звуки медбея
  code/game/objects/items/weapons/defibrillator.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/modules/economy/EFTPOS.dm
  code/modules/organs/blood.dm
  code/modules/surgery/surgery.dm
  sound/effects/ArterialBleed.ogg
  sound/items/defib_charge.ogg
  sound/items/defib_failed.ogg
  sound/items/defib_ready.ogg
  sound/items/defib_safetyOff.ogg
  sound/items/defib_safetyOn.ogg
  sound/items/defib_success.ogg
  sound/items/defib_zap.ogg
  sound/items/surgery/BonSet.ogg
  sound/items/surgery/Bone_Gel.ogg
  sound/items/surgery/Bone_Saw.ogg
  sound/items/surgery/Fix-O-vein.ogg
  sound/items/surgery/Hemostat.ogg
  sound/items/surgery/Retract.ogg
  sound/items/surgery/SurgDrill.ogg
  sound/items/surgery/cautery.ogg
  sound/items/surgery/defib_charge.ogg
  sound/items/surgery/defib_failed.ogg
  sound/items/surgery/defib_ready.ogg
  sound/items/surgery/defib_safetyOff.ogg
  sound/items/surgery/defib_safetyOn.ogg
  sound/items/surgery/defib_success.ogg
  sound/items/surgery/defib_zap.ogg
  sound/items/surgery/laserscalp.ogg
Labels: Feature, Sound, Test Merge Candidate

#4017 Перемещаем снаряжение СБ туда-сюда
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Test Merge Candidate, Tweak

#4058 Removed over shoulder belts on mobs.
  icons/mob/back.dmi
Labels: Sprites, Test Merge Candidate

#4051 Different age limits for different Xeno.
  code/__DEFINES/mob.dm
  code/game/gamemodes/heist/heist.dm
  code/game/gamemodes/heist/heist_old.dm
  code/game/jobs/job/captain.dm
  code/game/response_team.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/admin/verbs/striketeam.dm
  code/modules/admin/verbs/striketeam_syndicate.dm
  code/modules/client/character menu/general.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/species.dm
Labels: Test Merge Candidate, Tweak

#4107 Hardsuit sprites fixes
  icons/mob/head.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites

#4102 Powerfist resprited
  code/game/objects/powerfist.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/weapons.dmi
Labels: Sprites

#4099 Fixed outdated harm objective check
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/traitor/traitor.dm
Labels: Fix

#4079 fix #4065
  code/modules/client/preferences.dm
Labels: Fix

#4078 No red lighting presets
  code/controllers/subsystem/nightshift.dm
Labels: Tweak

#4069 Фикс бага с не прерываемым эмбиенсом после гостайза
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#4083 nuke base tweaks
  maps/centcom/centcom.dmm
Labels: Map Edit, Tweak

#4014 Воксам добавлена еда, убрано оружие из рук
  code/game/gamemodes/heist/vox_role.dm
  code/game/objects/items/weapons/autoinjectors.dm
  code/game/objects/items/weapons/medical.dm
  icons/obj/storage.dmi
  icons/obj/syringe.dmi
  maps/centcom/centcom.dmm
Labels: Map Edit, Merge Conflict, Tweak

#4010 Additional medbay sounds
  code/modules/clothing/under/accessories/accessory.dm
  sound/machines/cardio/crackles.ogg
  sound/machines/cardio/normal.ogg
  sound/machines/cardio/pulse.ogg
  sound/machines/cardio/wheezes.ogg
Labels: Feature, Sound, Test Merge Candidate

#3989 Фикс шрапнель=стекло.
  code/defines/obj/weapon.dm
  code/game/objects/items/stacks/sheets/glass.dm
  sound/effects/metalstep.ogg
Labels: Fix, Merge Ready

#4035 shlapa
  code/game/objects/items/weapons/badmin.dm
  code/game/objects/items/weapons/pedalbag.dm
  taucetistation.dme
Labels: HONK, Merge Ready

#4085 Фикс бага взаимодействия игрушки лицехвата с шлемом
  code/game/objects/random/random_cloth.dm
  code/modules/mining/equipment_locker.dm
  code/modules/mob/living/carbon/alien/special/facehugger/facehugger.dm
Labels: Fix, Merge Ready

#4094 Ещё два ИИ для ригов
  code/modules/clothing/spacesuits/rig/modules/ai.dm
Labels: Feature, Merge Ready

#4098 Звуки взлома борга
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/recycling/disposal.dm
Labels: Merge Ready, Sound

#4100 Ребаланс джерков и филе карпа
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Merge Ready, Tweak

#4104 Опустошение патронника в оружии
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/pistol.dm
Labels: Feature, Merge Ready

#3708 Extinguishers rework
  code/__HELPERS/unsorted.dm
  code/game/gamemodes/heist/heist_prices.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/doors/airlock.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/effects/foam.dm
  code/game/objects/items.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/random/random_science.dm
  code/game/objects/random/random_tools.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/extinguisher.dm
  code/game/objects/structures/janicart.dm
  code/game/turfs/simulated/walls_mineral.dm
  code/modules/cargo/exports/tools.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/extinguisher.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/reagents/reagent_types/Chemistry-Core.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  code/modules/scrap/scrap_light.dm
  icons/effects/effects.dmi
  icons/obj/objects.dmi
  icons/obj/smooth_objects/afff_foam1.dmi
  icons/obj/smooth_objects/afff_foam2.dmi
  icons/obj/smooth_objects/afff_foam3.dmi
  icons/obj/smooth_objects/afff_foam4.dmi
  maps/RandomZLevels/jungle.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
  maps/templates/space_structures/dj_station.dmm
  taucetistation.dme
Labels: Balance, Contentious, Feedback required, Map Edit, Sprites, Test Merge Candidate

#4042 No more lobby antags, resolve #1187
  code/__DEFINES/preferences.dm
  code/controllers/subsystem/jobs.dm
  code/modules/client/preferences.dm
Labels: Test Merge Candidate, Tweak

#4077 Changelings sting balance
  code/game/gamemodes/changeling/powers/stings.dm
Labels: Balance, Feature, Test Merge Candidate

#4091 Визуальное отображение облачком когда моб в отключке
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/mob.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/indicators.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/life.dm
  icons/mob/indicators.dmi
  taucetistation.dme
Labels: Feature, Sprites, Test Merge Candidate

#4096 Новые спрайты-коробочки для рамена. Острый рамен добавлен в вендоматы.
  code/game/machinery/vending.dm
  code/game/objects/random/random_foods.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_types/Chemistry-Foods.dm
  icons/obj/drinks.dmi
Labels: Sprites, Test Merge Candidate, Tweak

#4124 Fixes security helmet sprite
  icons/mob/head.dmi
Labels: Sprites

#4117 Фиксит положение спрайта сигареты и трубки на мобе.
  icons/mob/mask.dmi
Labels: Sprites, Tweak

#4105 Блобо-стенки теперь непрозрачные
  code/game/gamemodes/blob/overmind.dm
  code/game/gamemodes/blob/theblob.dm
Labels: Feature

#4122 Sinta'unathi v2.1
  code/modules/goonchat/browserassets/css/browserOutput.css
Labels: Merge Conflict, Tweak

#4119 Bandanas and flashlight added to loadout, security armbands tweak
  code/modules/client/character menu/loadout/loadout_accessories.dm
  code/modules/client/character menu/loadout/loadout_general.dm
  code/modules/client/character menu/loadout/loadout_hats.dm
Labels: Tweak

#4155 Пофиксил atom_init для бадминшапки. Убрал из рандомспавна
  code/game/objects/items/weapons/badmin.dm
  code/game/objects/random/random_cloth.dm
Labels: Quality Of Life

#4176 реверт #3655
  code/game/atoms.dm
  code/game/objects/items/weapons/autoinjectors.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/organs/blood.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  icons/obj/syringe.dmi
Labels: Revert / Removal, Sprites

#4068 Оптимизация муз. инструментов (или спасение от возможных ограничений с выпилом).
  code/datums/music_player.dm
Labels: Performance, Test Merge Candidate

#4076 Возрождаем старый ПР. Увеличено число игроков для старта режимов генокрад и РП-революция
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/revolution/rp_revolution.dm
Labels: Test Merge Candidate, Tweak

#4108 Сон хилит
  code/modules/organs/external/flesh.dm
Labels: Contentious, Feature, Test Merge Candidate

#4114 Library bookshelves resprited
  icons/obj/objects.dmi
Labels: Sprites, Test Merge Candidate

#4115 Реворк плазменного оружия и фиксы.
  code/__DEFINES/colors.dm
  code/__DEFINES/misc.dm
  code/game/gamemodes/heist/heist_prices.dm
  code/game/machinery/recharger.dm
  code/game/objects/items.dm
  code/game/objects/random/random_guns.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/special.dm
  code/modules/projectiles/effects.dm
  code/modules/projectiles/firing.dm
  code/modules/projectiles/guns/plasma/plasma.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/research/designs.dm
  icons/effects/projectiles.dmi
  icons/mob/belt.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  icons/obj/projectiles.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
  sound/weapons/guns/plasma10_hit.ogg
  sound/weapons/guns/plasma10_load.ogg
  sound/weapons/guns/plasma10_overcharge_load.ogg
  sound/weapons/guns/plasma10_overcharge_massive_shot.ogg
  sound/weapons/guns/plasma10_overcharge_shot.ogg
  sound/weapons/guns/plasma10_shot.ogg
  sound/weapons/guns/plasma10_unload.ogg
  taucetistation.dme
Labels: Feature, Fix, Map Edit, Sound, Sprites, Test Merge Candidate, Tweak

#4140 Girders now can smoothing.
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/simulated/walls.dm
  icons/obj/smooth_structures/girder.dmi
  icons/obj/smooth_structures/girder_reinforced.dmi
Labels: Sprites, Test Merge Candidate

#4173 Reverts cigarette sprite tweaks
  icons/mob/mask.dmi
Labels: Sprites

#4183 Исправление бага с консолью, которое при попытке выделения изучения, рантаймило и ломало консоль
  code/game/objects/items/weapons/power_cells.dm
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
Labels: Fix
