Repository TauCetiStation/TauCetiClassic, pull requests merged in 2019-02, with the labels that each got.

#3047 Фиксит баг с перчатками
  code/modules/clothing/gloves/stungloves.dm
Labels: Fix

#3061 shuttle airlock fix
  maps/z1.dmm
Labels: Map Edit

#3059 Указание авторства спрайтов для флафа
  code/modules/clothing/suits/labcoat.dm
  code/modules/fluff/customitems.dm
  code/modules/fluff/fluffmenu.dm
Labels: Tweak

#3048 Респрайт harvest.dmi [Kitchen Overhaul p.1]
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/hydroponics/growing_flowers.dmi
  icons/obj/hydroponics/growing_fruits.dmi
  icons/obj/hydroponics/growing_mushrooms.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/power.dmi
Labels: Ready for Review, Sprites

#3052 Респрайт ящуров.
  icons/effects/species.dmi
  icons/mob/human_races/r_lizard.dmi
Labels: Merge Ready, Sprites

#3068 Update coolant.dm
  code/modules/research/xenoarchaeology/machinery/coolant.dm
Labels: Merge Ready

#3062 Карточки в ПДА
  code/game/objects/items/devices/PDA/PDA.dm
  icons/obj/pda.dmi
Labels: Sprites

#3076 Полные пути для переменных и немного другого.
  code/__DATASTRUCTURES/linked_lists.dm
  code/__HELPERS/heap.dm
  code/__HELPERS/matrices.dm
  code/_globalvars/database.dm
  code/_globalvars/unused.dm
  code/controllers/configuration.dm
  code/datums/cob_highlight.dm
  code/game/area/areas.dm
  code/game/gamemodes/mutiny/mutiny_admin.dm
  code/game/gamemodes/objective.dm
  code/game/machinery/kitchen/juicer.dm
  code/game/machinery/machinery.dm
  code/game/objects/items/ashtray.dm
  code/game/objects/structures/transit_tubes.dm
  code/game/socket_talk.dm
  code/game/turfs/simulated/walls.dm
  code/modules/admin/admin_report.dm
  code/modules/admin/verbs/SDQL.dm
  code/modules/admin/verbs/SDQL_2.dm
  code/modules/admin/verbs/SDQL_2_parser.dm
  code/modules/atmospheric/machinery/atmospherics.dm
  code/modules/atmospheric/machinery/portable/scrubber.dm
  code/modules/cargo/exports/intel.dm
  code/modules/client/client defines.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/human/MedicalSideEffects.dm
  code/modules/mob/living/carbon/monkey/npc.dm
  code/modules/nano/JSON Reader.dm
  code/modules/organs/blood.dm
  code/modules/power/apc.dm
  code/modules/projectiles/targeting.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/shieldgen/shield_gen_external.dm
  code/world.dm
  config/example/forumdbconfig.txt
  taucetistation.dme
Labels: Fix

#3078 Fast Food
  code/game/machinery/vending.dm
  code/game/objects/items/trash.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
  icons/obj/trash.dmi
  icons/obj/vending.dmi
  maps/z1.dmm
Labels: Feature, Map Edit, Sprites

#3033 Ports a bunch of 3/4 sprites from /tg/ and Eris.
  code/game/machinery/biogenerator.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/modules/shieldgen/energy_field.dm
  code/modules/shieldgen/shield_capacitor.dm
  code/modules/shieldgen/shield_gen.dm
  code/modules/shieldgen/shielding.dmi
  icons/candle.dmi
  icons/obj/biogenerator.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/items.dmi
  icons/obj/library.dmi
  icons/obj/machines/biogenerator.dmi
  icons/obj/machines/floodlight.dmi
  icons/obj/machines/mining_machines.dmi
  icons/obj/machines/research.dmi
  icons/obj/machines/shielding.dmi
  icons/obj/machines/telecomms.dmi
  icons/obj/mining.dmi
  icons/obj/objects.dmi
  icons/obj/stationobjs.dmi
Labels: Sprites, Test Merge

#3111 Configuration for probot-stale
  .github/stale.yml
Labels: Tools

#3088 Сколько осталось мази и бинтов?
  code/game/objects/items/stacks/medical.dm
  icons/obj/items.dmi
Labels: Sprites

#3095 loadout fix
  code/modules/client/character menu/loadout/loadout_clothing.dm
Labels: Fix

#3097 Удаляет очки у офицера нравов
  code/game/jobs/job/assistant.dm
Labels: Balance, Contentious

#3110 making text visible on papers
  code/game/gamemodes/blob/blob_report.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/mutiny/mutiny_fluff.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/revolution/rp_revolution.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/guestpass.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/message.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/skills.dm
  code/game/machinery/records_scanner.dm
  code/game/objects/effects/manifest.dm
  code/game/objects/items/devices/tabletop_assistant.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/structures/crates_lockers/closets/syndicate.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/verbs/striketeam.dm
  code/modules/detectivework/autopsy.dm
  code/modules/detectivework/detective_work.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/Accounts_DB.dm
  code/modules/economy/EFTPOS.dm
  code/modules/mob/living/simple_animal/friendly/robot.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/paperwork/photocopier.dm
  code/modules/research/rdconsole.dm
  code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm
  code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
  code/modules/research/xenoarchaeology/misc.dm
  code/modules/virus2/analyser.dm
  code/modules/virus2/centrifuge.dm
  code/modules/virus2/isolator.dm
Labels: Fix

#3112 Перебрал аргументы для Move() проков.
  code/game/atoms_movable.dm
  code/game/gamemodes/blob/overmind.dm
  code/game/gamemodes/cult/narsie.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/pipe/construction.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/shooting_range.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/game/objects/structures/target_stake.dm
  code/game/objects/structures/window.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/proximity.dm
  code/modules/atmospheric/machinery/portable/portable_atmospherics.dm
  code/modules/europa/fluids/fluid_update.dm
  code/modules/liquid/splash_simulation.dm
  code/modules/media/machinery.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/ai/freelook/update_triggers.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/kobold.dm
  code/modules/mob/living/simple_animal/worm.dm
  code/modules/mob/mob_movement.dm
  code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
  code/modules/power/singularity/singularity.dm
  code/modules/projectiles/targeting.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
  code/modules/sports/PedalGen.dm
  code/modules/vehicles/spacebike.dm
  code/modules/vehicles/vehicle.dm
Labels: Code Improvements, Fix

#3116 СПУ нельзя клонировать
  code/game/machinery/computer/cloning.dm
Labels: Fix

#3121 фикс Реджува
  code/modules/mob/living/living.dm
Labels: Fix

#3057 Выключатели видно в темноте
  code/game/machinery/lightswitch.dm
  icons/obj/power.dmi
Labels: Fix, Sprites

#3079 Небольшие изменения weapon.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/weapons.dmi
Labels: Sprites

#3087 newscasters fix and more
  maps/z1.dmm
Labels: Map Edit

#3096 fixes misspell
  code/game/machinery/computer/computer.dm
Labels: Fix

#3030 Мультизадачность как перк.
  code/__DEFINES/traits.dm
  code/__HELPERS/mobs.dm
  code/datums/traits/positive.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_helpers.dm
  taucetistation.dme
Labels: Feature, Test Merge

#3122 Специя слаймов для экстракта слизня.
  code/__DEFINES/mob.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
  icons/mob/human_races/r_slime.dmi
Labels: Sprites

#3131 print scan on callback call instead of spawn()
  code/game/machinery/adv_med.dm
Labels: Bug

#3032 Перк на заедание боли стрессом.
  code/__DEFINES/traits.dm
  code/controllers/subsystem/quirks.dm
  code/datums/traits/negative.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/living.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/reagent_types/Chemistry-Foods.dm
  code/modules/virus2/effect.dm
Labels: Feature

#3125 New player notification for mentors
  code/__HELPERS/game.dm
  code/modules/mentor/mentor.dm
Labels: Feature

#3127 Одежда в ClothesMate и HolyVend
  code/game/machinery/vending.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/accessories/accessory.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/ties_overlay.dmi
Labels: Sprites, Tweak

#3056 Перк "Дитя Природы".
  code/__DEFINES/clothing.dm
  code/__DEFINES/traits.dm
  code/controllers/subsystem/quirks.dm
  code/datums/traits/positive.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/hostile/cyber_horror.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/hulk.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Contentious, Feature

#3157 Fix problem with gateway activation when gateway is hacked
  code/modules/awaymissions/gateway.dm
Labels: Fix

#3080 Респрайт карт
  icons/obj/card.dmi
Labels: Sprites

#3149 Поправляет спрайты надувных дверей
  code/game/objects/structures/inflatable.dm
  icons/obj/inflatable.dmi
Labels: Sprites

#3163 Фиксит взаимодействие со спорт-установками
  code/game/objects/fitness.dm
Labels: Fix

#3139 Свой item_state телебатону
  code/game/objects/items/weapons/swords_axes_etc.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Sprites

#3102 Fix atmos in AI Satellite
  maps/z1.dmm
Labels: Map Edit, Merge Conflict

#3178 fixing borgs not being able to do surgeries
  code/__HELPERS/mobs.dm
Labels: Fix

#3154 Fix goonchat scroll problem when reaching a msg limit
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/js/browserOutput.js
Labels: Fix, Test Merge Candidate

#3155 Fix to_chat invalid message runtime
  code/modules/flufftext/Hallucination.dm
Labels: Fix

#3135 Новые звуки + описания(клон моего ПРа, переношу всё сюда)
  code/defines/obj/weapon.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/portable_turret.dm
  code/game/machinery/recharger.dm
  code/game/machinery/washing_machine.dm
  code/game/mecha/mech_bay.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
  code/game/sound.dm
  code/modules/atmospheric/machinery/portable/canister.dm
  code/modules/economy/EFTPOS.dm
  code/modules/mining/mine_items.dm
  code/modules/paperwork/stamps.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/reagents/reagent_containers/glass.dm
  sound/effects/Liquid_transfer_mono.ogg
  sound/effects/stamp.ogg
  sound/items/bandage.ogg
  sound/items/bandage2.ogg
  sound/items/bandage3.ogg
  sound/machines/analysis.ogg
  sound/weapons/cannon.ogg
  sound/weapons/captainwhip.ogg
  sound/weapons/desceration.ogg
Labels: Merge Ready, Test Merge Candidate, Tweak

#3086 Небольшие изменения касательно ingame age
  code/__DEFINES/varedit.dm
  code/controllers/configuration.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/buildmode.dm
  code/modules/admin/verbs/massmodvar.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/character menu/occupation.dm
  code/modules/fluff/customitems.dm
  taucetistation.dme
Labels: Feature, Test Merge Candidate

#3151 Ребаланс флешбенгов
  code/game/objects/items/weapons/grenades/flashbang.dm
Labels: Balance

#3153 Теперь быстрое голодание влияет только на голод а не на метаболизм
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Feature

#3160 Фикс флэша
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#3162 Фикс щитка ХоСа
  code/game/objects/items/weapons/shields.dm
Labels: Fix, Merge Ready

#3100 Fix atmospherics in Docks
  maps/z1.dmm
Labels: Map Edit, Merge Conflict

#3046 Шкафы в 3/4
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/locations/centcomm/closet.dmi
  icons/obj/closet.dmi
Labels: Map Edit, Merge Ready, Sprites, Test Merge Candidate

#3180 Фикс фальшстен
  code/game/objects/structures/false_walls.dm
Labels: Fix

#3200 Фикс причёски
  icons/mob/human_face.dmi
Labels: Merge Ready, Sprites

#3207 Исправление неработающих бросков при низких значениях в некоторых слу…
  code/controllers/subsystem/throwing.dm
Labels: Fix

#3184 Реворк инвентаря и взаимодействий с ним.
  code/__DEFINES/clothing.dm
  code/__DEFINES/flags.dm
  code/__HELPERS/mobs.dm
  code/game/objects/items.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/carbon/ian/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/carbon/monkey/inventory.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/power/antimatter/fuel.dm
  taucetistation.dme
Labels: Test Merge Candidate, Tweak

#3182 Перевод сообщения о том куда тыкать чтоб ответить на пмку
  code/modules/admin/verbs/adminpm.dm
Labels: DO NOT MERGE

#3187 Вырезки
  code/game/objects/items/devices/cardboard.dm
  icons/obj/cardboard_cutout.dmi
Labels: Sprites

#3168 peaked caps and tweaks
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites, Tweak

#3170 День святого валентина
  code/controllers/subsystem/jobs.dm
  code/game/gamemodes/events/holidays/AprilFools.dm
  code/game/gamemodes/events/holidays/Easter.dm
  code/game/gamemodes/events/holidays/valentines/heart_box.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/valentines.dmi
  taucetistation.dme
Labels: Sprites, Tweak

#3186 Лечение обгоревшей кожи
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Labels: Tweak

#3215 Допиленное после ремапа РнД и опять фиксы
  icons/obj/window.dmi
  maps/z1.dmm
Labels: Map Edit, Sprites

#3156 More visible silicon chat and admin announces
  code/modules/admin/admin.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/mob/living/silicon/say.dm
Labels: Feature, Test Merge Candidate

#3199 Пак спрайтов с /tg/ и /bay12/
  code/game/machinery/fax.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/random/random_meds.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/items.dmi
  icons/obj/library.dmi
  icons/obj/objects.dmi
  icons/obj/power.dmi
  icons/obj/storage.dmi
  icons/obj/surgery.dmi
  icons/obj/tools.dmi
Labels: Merge Ready, Sprites, Test Merge Candidate

#3193 Small satellite fix
  maps/z1.dmm
Labels: Map Edit

#3203 Фиксит взаимодействие ведра с janicart
  code/game/objects/structures/janicart.dm
Labels: Tweak

#3210 Fixing all surgery whitelists.
  code/modules/surgery/implant.dm
  code/modules/surgery/ribcage.dm
  code/modules/surgery/robolimbs.dm
Labels: Fix

#3120 Небольшой рефакторинг надевание и снятия ригов
  code/modules/mob/inventory.dm
Labels: Fix

#3137 Новые взаимодействия на help интент
  code/modules/mob/living/carbon/carbon.dm
Labels: HONK, Tweak

#3208 несколько небольших багфиксов
  code/datums/uplinks_items.dm
  code/game/machinery/bots/farmbot.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/reagents/grenade_launcher.dm
Labels: Fix, Tweak

#3211 Фикс спрайта берета
  code/game/jobs/job/civilian.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/onlyone.dm
  code/modules/client/character menu/loadout/loadout_hats.dm
  code/modules/clothing/head/beret.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/food/recipes_microwave.dm
  code/modules/mob/living/carbon/ian/inventory.dm
  code/modules/mob/living/simple_animal/friendly/crab.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
  taucetistation.dme
Labels: Sprites

#3214 Чистка граба и его хелперы.
  code/__DEFINES/combat.dm
  code/__DEFINES/mob.dm
  code/_onclick/item_attack.dm
  code/datums/spells/area_teleport.dm
  code/game/gamemodes/abduction/abduction_gear.dm
  code/game/gamemodes/abduction/machinery/pad.dm
  code/game/gamemodes/changeling/powers/Whip.dm
  code/game/machinery/OpTable.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/alien/facehugger/facehugger_abilities.dm
  code/modules/mob/living/carbon/alien/human_attackalien.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
  code/modules/mob/mob_movement.dm
Labels: Balance

#3221 Fixes guest access
  code/game/verbs/ooc.dm
  code/modules/client/client procs.dm
Labels: Fix

#3226 Shadowling cloning fix
  code/modules/mob/living/carbon/species.dm
Labels: Fix

#3227 Fix randm event "Infestation"
  code/modules/events/infestation.dm
Labels: Fix

#3228 Исправление quick_equip который не учитывал слоты скрытые экипировкой.
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix

#3222 Чистка z1 слоя от ненужных и ошибочных переменных (и фиксы опять)
  code/game/machinery/hydroponics.dm
  maps/z1.dmm
Labels: Map Edit

#3237 shieldgen tweaks
  code/game/machinery/shieldgen.dm
  icons/effects/effects.dmi
Labels: Balance, Sprites

#3238 arcade resprite + guestpass sprite fixes
  icons/obj/computer.dmi
Labels: Sprites

#3244 Ребаланс цен карго
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/exports/sheets.dm
  code/modules/cargo/exports/tools.dm
  code/modules/cargo/exports/weapons.dm
  code/modules/cargo/packs.dm
Labels: Balance

#3098 Добавляет логирование метеоритам.
  code/game/gamemodes/meteor/meteors.dm
Labels: Fix

#3255 Фикс harvest.dmi
  code/defines/obj/weapon.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/power_cells.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/reagents/reagent_containers/spray.dm
  icons/obj/harvest.dmi
  icons/obj/hydroponics/harvest.dmi
Labels: Sprites

#3204 Халкам нельзя давать маленькие предметы
  code/modules/mob/living/carbon/give.dm
Labels: Fix

#3258 Фиксит пиксель на носках
  icons/mob/human_socks.dmi
Labels: Merge Ready, Sprites
