Repository TauCetiStation/TauCetiClassic, pull requests merged in 2019-09, with the labels that each got.

#3926 Перенос сглаживания столов на актуальный метод.
  code/game/gamemodes/abduction/abduction_gear.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/holodeck/HolodeckObjects.dm
  icons/obj/smooth_structures/abductor_table.dmi
  icons/obj/smooth_structures/fancy_black_table.dmi
  icons/obj/smooth_structures/fancy_table.dmi
  icons/obj/smooth_structures/glass_table.dmi
  icons/obj/smooth_structures/poker_table.dmi
  icons/obj/smooth_structures/reinforced_table.dmi
  icons/obj/smooth_structures/table.dmi
  icons/obj/smooth_structures/wooden_table.dmi
  icons/obj/tables.dmi
Labels: Sprites, Test Merge Candidate

#3901 фейковые окна в космос на уровне цк
  code/game/turfs/unsimulated/walls.dm
  icons/turf/walls.dmi
  icons/turf/walls/fakeglass.dmi
  maps/centcom/centcom.dmm
Labels: Map Edit, Sprites, Test Merge Candidate

#3932 Удаление ненужных файлов
  code/game/gamemodes/abduction/machinery/experiment.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  icons/48x48/walls48.dmi
  icons/PSD files/asteroiddustoverlay.psd
  icons/PSD files/door.psd
  icons/effects/160x160.dmi
  icons/effects/288x288.dmi
  icons/effects/lighting.dmi
  icons/effects/species.dmi
  icons/mob/species/tail.dmi
Labels: Sprites

#3939 2 окошка около шатлла ерт которые заменяются на фейковые
  maps/centcom/centcom.dmm
Labels: Map Edit

#3921 Шесть новых структур для теленауки.
  code/datums/space_structures.dm
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/computer/camera.dm
  code/modules/paperwork/paper.dm
  maps/templates/space_structures/cloning_lab.dmm
  maps/templates/space_structures/delivery_shuttle.dmm
  maps/templates/space_structures/escape_pod.dmm
  maps/templates/space_structures/iss.dmm
  maps/templates/space_structures/listening_post.dmm
  maps/templates/space_structures/syndicate_fighter.dmm
Labels: Map Edit, Test Merge Candidate

#3897 Изменение доступа заслонок в арсенале тактического снаряжения
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Test Merge Candidate

#3936 New tanks
  icons/obj/tank.dmi
Labels: Sprites, Test Merge Candidate

#3846 Модуль взаимодействия для пИИ, новый флаг
  code/__DEFINES/flags.dm
  code/_onclick/item_attack.dm
  code/defines/obj/weapon.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/weapons/paiwire.dm
  code/modules/mob/living/silicon/pai/life.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/software.dm
Labels: Feature, Test Merge Candidate

#3890 Изменение баланса унатхов на реакции к температуре
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/species.dm
Labels: Balance, Test Merge Candidate, Tweak

#3902 Делаем скелетов более скелетными
  code/__DEFINES/flags.dm
  code/__DEFINES/mob.dm
  code/_globalvars/misc.dm
  code/_onclick/other_mobs.dm
  code/game/atoms.dm
  code/modules/mob/living/carbon/brain/brain.dm
  code/modules/mob/living/carbon/brain/say.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/external/skeleton.dm
  code/modules/organs/organ_external.dm
  taucetistation.dme
Labels: Feature, Test Merge Candidate

#3916 квирк на "крепкий рассудок"
  code/__DEFINES/traits.dm
  code/controllers/subsystem/quirks.dm
  code/datums/traits/positive.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/say.dm
Labels: Feature, Test Merge Candidate

#3920 Добавление ящиков поставки 9мм пистолета и боеприпасов к нему
  code/modules/cargo/packs.dm
Labels: Test Merge Candidate, Tweak

#3935 В бургеры с мясом добавлен протеин. В бургеры с сыром добавлен сыр
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Balance, Test Merge Candidate

#3957 Supporters can bypass bunker limit too
  code/modules/client/client procs.dm
Labels: Tweak

#3956 fix mhelp message encoding
  code/_compile_options_cyrillic.dm
  code/modules/mentor/mentorpm.dm
Labels: &#255;, Fix

#3946 Фикс спрайта унаthi
  icons/mob/human_races/r_lizard.dmi
  icons/mob/species/tail.dmi
Labels: Sprites

#3945 медальон теперь маленький
  code/modules/clothing/masks/miscellaneous.dm
Labels: Fix

#3968 Фикс рантайма с компьютером в часном офисе
  code/modules/detectivework/detective_work.dm
Labels: Fix

#3964 Чиним встроенные макбуты
  code/__DEFINES/flags.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/mob_movement.dm
Labels: Fix

#3962 Фикс полетевшей кодировки после обновлений пИИ
  code/modules/mob/living/silicon/pai/software.dm
Labels: &#255;, Fix

#3959 Убрал лишний пиксел хвоста унатха, добавил нужный
  icons/mob/species/tail.dmi
Labels: Sprites

#3955 Делает вендоматы со снэками и колой разноцветными.
  code/game/machinery/constructable_frame.dm
  code/game/machinery/vending.dm
  code/game/objects/random/random_structures.dm
  icons/obj/vending.dmi
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
  maps/templates/space_structures/cloning_lab.dmm
  maps/templates/space_structures/dj_station.dmm
  maps/templates/space_structures/listening_post.dmm
Labels: Map Edit, Sprites, Test Merge Candidate

#3944 переписывание кода эффектов брейн дамага
  code/modules/mob/living/carbon/human/life.dm
Labels: Code Improvements, Test Merge Candidate

#3961 fix shuttle being called by random people when EMPing AI
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#3977 Шлем вокса теперь не защищает все тело.
  code/modules/clothing/spacesuits/alien.dm
Labels: Fix

#3979 Флаг для мышей
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Fix

#3865 Бутылочка
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Labels: Tweak

#3896 Removed Staff of Change from spellbook
  code/game/gamemodes/wizard/spellbook.dm
Labels: Fix

#3907 Ребаланс ударостойкой брони СБ
  code/modules/clothing/suits/armor.dm
Labels: Balance, Contentious, Test Merge Candidate

#3911 Engineering hardsuits buff
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Balance, Contentious, Test Merge Candidate

#3919 Добавление 9мм пистолетов WJPP в шкаф СБ
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  maps/gamma/gamma.dmm
Labels: Balance, Contentious, Map Edit, Test Merge Candidate

#3960 new bots
  icons/obj/aibots.dmi
Labels: Sprites, Test Merge Candidate

#3963 Звуки обслуживания боргов + микробаф.
  code/game/machinery/doors/firedoor.dm
  code/game/objects/items/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/robot.dm
  icons/mob/robots.dmi
  sound/items/card.ogg
  sound/misc/robot_close.ogg
  sound/misc/robot_open.ogg
Labels: Balance, Sound, Test Merge Candidate

#3967 Исправление поведения курсора сквозь оверлей слепоты и прожектайла поверх худа.
  code/_onclick/hud/fullscreen.dm
  code/modules/projectiles/effects.dm
  icons/mob/screen1_full.dmi
Labels: Fix, Test Merge Candidate

#3969 BartNixon buildmode
  icons/misc/buildmode.dmi
Labels: Admin, Sprites, Test Merge Candidate

#3976 Добавлены кусачки в бриг и в медбей
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#3954 Убираем дюп металл родов
  code/game/objects/structures/grille.dm
  maps/RandomZLevels/jungle.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
  maps/templates/space_structures/abandoned_lab.dmm
  maps/templates/space_structures/derelict_station.dmm
  maps/templates/space_structures/ghost_ship_1.dmm
  maps/templates/space_structures/robostation.dmm
  maps/templates/space_structures/teleporter.dmm
Labels: Fix, Map Edit

#4004 добавляет форму кадетов в ящик с гардеробом сб
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
Labels: Tweak

#4000 Фикс места занимаемого разбитыми бутылками в инвентаре.
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Labels: Fix

#4018 revert robots.dmi
  icons/mob/robots.dmi
Labels: Sprites

#4036 ERT camera fix
  code/modules/clothing/spacesuits/rig/ert.dm
Labels: Fix

#3934 Переделка кода гранат
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/ghettobomb.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
Labels: Fix, Sound, Test Merge Candidate

#3965 2(1) новых квирка.
  code/__DEFINES/traits.dm
  code/controllers/subsystem/quirks.dm
  code/datums/traits/negative.dm
  code/datums/traits/positive.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
Labels: Feature, Test Merge Candidate

#3972 Исправления болы
  code/defines/obj/weapon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/ian/inventory.dm
  code/modules/mob/living/carbon/monkey/examine.dm
  code/modules/mob/living/carbon/monkey/inventory.dm
Labels: Feature, Fix, Test Merge Candidate

#3974 Пихаем щитами или жестко катаем персонал ими по полу
  code/game/objects/items/weapons/shields.dm
Labels: Test Merge Candidate, Tweak

#3978 Цыплята из яиц
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Feature, Test Merge Candidate

#3985 Меняем звук селфдестракта на ии
  code/game/gamemodes/malfunction/malfunction.dm
  sound/AI/DeltaBOOM.ogg
Labels: Sound, Test Merge Candidate

#3986 Добавляем хамелеонке КД
  code/game/objects/items/devices/chameleonproj.dm
Labels: Balance, Test Merge Candidate

#4041 Masks on mob sprites fixes.
  icons/mob/mask.dmi
Labels: Sprites

#4039 Запрет на самоубийство тем, что даже урона не наносит
  code/modules/projectiles/gun.dm
Labels: Fix

#4028 Исправления диспенсера
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#3866 удаление space/transit
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/turfs/space/space.dm
  code/game/turfs/space/transit.dm
  icons/turf/space.dmi
  maps/centcom/centcom.dmm
  taucetistation.dme
Labels: Map Edit, Sprites

#3966 New Hardsuit sprites
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/rig/ert.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  icons/mob/back.dmi
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/rig_modules.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/storage.dmi
Labels: Feature, Sprites, Test Merge Candidate

#3993 Floors & walls resprite
  icons/turf/floors.dmi
  icons/turf/walls/has_false_walls/reinforced_wall.dmi
  icons/turf/walls/has_false_walls/wall.dmi
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Sprites, Test Merge Candidate

#3885 Переработка скорости движения у людей
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Balance

#4061 атакующие галлюцинации были у людей с квирком "Strong mind"
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Fix

#4060 Nuke righelm action button changing mode instead of light.
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Tweak

#4044 Разрешение ситуации с "На старте сервера инициализируются тысячи мусорных объектов".
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/storage/storage_ui/default.dm
Labels: Performance, Test Merge Candidate

#4002 Обновление кода операций
  code/game/gamemodes/abduction/abduction_gear.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/surgery/surgery.dm
Labels: Balance, Fix, Test Merge Candidate

#4040 Wizard's tophat that gets dem monkeys out, and dem peoplez in.
  code/game/area/Space Station 13 areas.dm
  code/game/gamemodes/wizard/spellbook.dm
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/modules/clothing/head/wiz_tophat.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/monkey/inventory.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/say.dm
  icons/turf/areas.dmi
  maps/centcom/centcom.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#4008 Космическая структура и поды с выжившими
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/misc.dm
  code/datums/space_structures.dm
  code/game/area/Space Station 13 areas.dm
  code/game/objects/structures/survivor_cryopod.dm
  code/modules/admin/topic.dm
  icons/turf/shuttle.dmi
  maps/templates/space_structures/satellite.dmm
  taucetistation.dme
Labels: Map Edit, Sprites, Test Merge Candidate

#4029 Исправления зума
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/mob_movement.dm
  code/modules/projectiles/guns/energy/special.dm
Labels: Fix, Test Merge Candidate

#4034 Анимации для боргов.
  icons/mob/robots.dmi
Labels: Sprites, Test Merge Candidate

#4037 Безголовых нельзя брать и держать в 3 и 4 грабе
  code/modules/mob/mob_grab.dm
Labels: Fix, Test Merge Candidate
