Repository TauCetiStation/TauCetiClassic, pull requests merged in 2019-01, with the labels that each got.

#2948 Обновление мапмержера (фикс undefined map symbol)
  tools/dmm-merge-tool/JTGMerge.jar
Labels: Tools

#2954 фикс пропавшего спрайта коробки.
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Ready for Review

#2962 Фикс поля зрения у ИИ.
  code/modules/mob/living/silicon/ai/freelook/chunk.dm
Labels: Fix, Ready for Review

#2785 Портирует новые спрайты ригов ERT.
  icons/mob/back.dmi
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/storage.dmi
Labels: Contentious, Ready for Review, Sprites

#2973 Оперативники унатхи и таяран получили ботинки
  code/game/gamemodes/nuclear/nuclear.dm
  code/modules/clothing/shoes/miscellaneous.dm
Labels: Ready for Review, Tweak

#2769 [Mirror]Телепортоабуз NO MORE
  code/game/machinery/teleporter.dm
  code/game/objects/items/weapons/teleportation.dm
Labels: Fix

#2976 TrapBay или юбки в мед бей (попытка №3)
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/under/jobs/medsci.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Ready for Review, Sprites

#2974 Наручники из кабелей делаются через меню крафта
  code/modules/crafting/recipes.dm
  code/modules/power/cable.dm
Labels: Ready for Review, Tweak

#2731 [Mirror]Walktoggle removed from targeting victim
  code/modules/projectiles/targeting.dm
Labels: Contentious, Tweak

#2777 [Mirror]Не все расы режутся об стекло, мусор etc.
  code/__DEFINES/flags.dm
  code/defines/obj/weapon.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/weapons/dice.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/paperwork/paper.dm
  code/modules/scrap/scrap.dm
Labels: Tweak

#2705 [Mirror]Уменьшил weaken у болы
  code/defines/obj/weapon.dm
Labels: Balance

#2730 [Mirror]Фикс кластербенгов
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
Labels: Tweak

#3001 Перенос чейнджлогов во внешний репозиторий
  .gitattributes
  .gitignore
  code/_globalvars/configuration.dm
  code/controllers/configuration.dm
  code/modules/mob/dead/new_player/login.dm
  code/world.dm
  config/example/config.txt
  html/assets/css/bootstrap.min.css
  html/assets/css/changelog.css
  html/assets/images/Space.png
  html/assets/images/icons/Balance.png
  html/assets/images/icons/BugFix.png
  html/assets/images/icons/CircledMinus.png
  html/assets/images/icons/CircledPlus.png
  html/assets/images/icons/Map.png
  html/assets/images/icons/NukeBurn.png
  html/assets/images/icons/Performance.png
  html/assets/images/icons/Picture.png
  html/assets/images/icons/Sound.png
  html/assets/images/icons/SpellCheck.png
  html/assets/images/icons/Wrench.png
  html/assets/scripts/bootstrap.min.js
  html/assets/scripts/changelog.js
  html/assets/scripts/jquery-3.2.1.min.js
  html/changelog.html
  interface/interface.dm
  tools/test-merge-changelog/README.md
  tools/test-merge-changelog/script.groovy
  tools/tmcl.sh
Labels: Tools, Tweak

#2991 Фиксит рантайм при реджуве не живой куклы.
  code/modules/organs/organ_external.dm
Labels: Ready for Review

#2850 [wip] Nuclear
  code/datums/wires/nuclearbomb.dm
Labels: Fix

#3004 Исправил правую ногу по реквесту.
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/organ_external.dm
Labels: Balance

#2949 Fixed runtimes
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
Labels: Fix

#2969 Оптимизация генерации превью персонажей с tgstation для префов и ножниц.
  code/__DEFINES/qdel.dm
  code/__HELPERS/lists.dm
  code/datums/wires/_wires.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/modules/client/character menu/general.dm
  code/modules/client/character menu/load_slot.dm
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  interface/skin.dmf
Labels: Performance

#2975 Небольшие фиксы карты и перестановки в отсеках
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/cloning.dm
  maps/z1.dmm
  nano/images/nanomap_z1.png
Labels: Map Edit

#2978 [Mirror] Stool resprite
  icons/obj/objects.dmi
Labels: Sprites

#2922 Снег с оверлеями + твик декораций.
  code/modules/holidays/new_year/decorations.dm
  code/modules/holidays/new_year/snow.dm
  code/modules/holidays/new_year/snowball.dm
  icons/turf/snow.dmi
  taucetistation.dme
Labels: Merge Ready, Sprites

#2989 Ковры с бея
  code/game/objects/items/stacks/tiles/light.dm
  code/game/objects/items/stacks/tiles/plasteel.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_types.dm
  code/modules/cargo/packs.dm
  icons/turf/carpets.dmi
Labels: Feature, Ready for Review, Sprites

#2988 New Player Panel tweaks
  SQL/feedback_schema.sql
  code/modules/mob/dead/new_player/login.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/new_player/poll.dm
  taucetistation.dme
Labels: Ready for Review, Tweak

#2995 Выпилил бленд из update_body() в хуманах.
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/organ_external.dm
  icons/mob/human_races/husk.dmi
  icons/mob/human_races/r_armalis.dmi
  icons/mob/human_races/r_def_human.dmi
  icons/mob/human_races/r_def_lizard.dmi
  icons/mob/human_races/r_def_plant.dmi
  icons/mob/human_races/r_def_skrell.dmi
  icons/mob/human_races/r_def_tajaran.dmi
  icons/mob/human_races/r_def_vox.dmi
  icons/mob/human_races/r_diona.dmi
  icons/mob/human_races/r_golem.dmi
  icons/mob/human_races/r_human.dmi
  icons/mob/human_races/r_machine.dmi
  icons/mob/human_races/r_plant.dmi
  icons/mob/human_races/r_shadowling.dmi
  icons/mob/human_races/r_skrell.dmi
  icons/mob/human_races/r_tajaran.dmi
  icons/mob/human_races/r_vox.dmi
  icons/mob/human_races/r_zombie.dmi
  icons/mob/human_races/r_zombie_lizard.dmi
  icons/mob/human_races/r_zombie_skrell.dmi
  icons/mob/human_races/r_zombie_tajaran.dmi
Labels: Sprites

#3005 Revert "Исправил правую ногу по реквесту."
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/organ_external.dm
Labels: Sprites

#2993 Новый фон для параллакса.
  code/__DEFINES/preferences.dm
  code/_onclick/hud/parallax.dm
  code/controllers/subsystem/parallax.dm
  code/modules/client/character menu/global.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  icons/effects/parallax.dmi
  icons/effects/parallax_classic.dmi
  icons/effects/parallax_tg.dmi
Labels: Fix, Ready for Review, Sprites, Test Merge, Tweak

#2992 Ambient occlusion фильтр с tgstation.
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/misc.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/plane_master.dm
  code/game/machinery/ai_slipper.dm
  code/game/machinery/hologram.dm
  code/game/machinery/igniter.dm
  code/game/objects/effects/decals/decal.dm
  code/game/objects/structures/lattice.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/walls.dm
  code/modules/atmospheric/machinery/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospheric/machinery/components/binary_devices/passive_gate.dm
  code/modules/atmospheric/machinery/components/binary_devices/pump.dm
  code/modules/atmospheric/machinery/components/binary_devices/shutoff.dm
  code/modules/atmospheric/machinery/components/binary_devices/valve.dm
  code/modules/atmospheric/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospheric/machinery/components/components_base.dm
  code/modules/atmospheric/machinery/components/omni_devices/omni_devices.dm
  code/modules/atmospheric/machinery/components/trinary_devices/filter.dm
  code/modules/atmospheric/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospheric/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospheric/machinery/components/unary_devices/portables_connector.dm
  code/modules/atmospheric/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospheric/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/client/character menu/global.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/mob/living/carbon/alien/effects/aliens.dm
  taucetistation.dme
Labels: Feature, Ready for Review, Test Merge

#3006 Уменьшение звука полета шаттла прибытия + some other small tweaks
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/computer/arrival_shuttle.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Ready for Review, Tweak

#2913 Добавляет на велосити рекламу
  code/modules/locations/centcomm/monitor.dmi
  code/modules/locations/centcomm/reklama.dmi
  code/modules/locations/centcomm/soda_ad.dmi
  code/modules/locations/centcomm/velocity.dm
  maps/z2.dmm
Labels: Map Edit, Ready for Review, Sprites

#3009 Возможность менять режим скалирования иконок на карте.
  interface/skin.dmf
Labels: Feature, Ready for Review

#2958 Причёски
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites, Work In Progress

#2990 Система особенностей (трейтов/перков/квирков) с тг.
  code/__DEFINES/genetics.dm
  code/__DEFINES/mob.dm
  code/__DEFINES/subsystem.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/lists.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/jobs.dm
  code/controllers/subsystem/quirks.dm
  code/controllers/subsystem/ticker.dm
  code/datums/datum.dm
  code/datums/status_traits.dm
  code/datums/traits/_quirk.dm
  code/datums/traits/negative.dm
  code/game/dna/dna_modifier.dm
  code/game/dna/genes/monkey.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/structures.dm
  code/modules/admin/verbs/pray.dm
  code/modules/client/character menu/general.dm
  code/modules/client/character menu/quirks.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/transform_procs.dm
  code/modules/projectiles/firing.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  code/modules/scrap/scrap.dm
  code/modules/surgery/lipoplasty.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
  taucetistation.dme
Labels: Feature, Ready for Review, Sprites, Test Merge

#3011 Поправил некорректное сохранение некоторых переменных в преференсах.
  code/modules/client/preferences_savefile.dm
Labels: Ready for Review

#2694 [Mirror]Запрет на использование ряда предметов живностью
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/devices/remote_device.dm
  code/game/objects/items/weapons/teleportation.dm
Labels: Tweak

#2732 [Mirror]Огнемёт, который таки бросает огонь.
  code/game/objects/items/weapons/flamethrower.dm
Labels: Fix

#2859 Делает возможным очищение голых ног
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
Labels: Fix, Work In Progress

#3023 Fixes "is empty"
  nano/templates/chem_dispenser.tmpl
Labels: Fix, Ready for Review

#2869 Xenoarchaeology Overhaul: Part 4
  code/game/machinery/washing_machine.dm
  code/game/objects/items.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/gloves/stungloves.dm
  code/modules/holidays/new_year/snow.dm
  code/modules/paperwork/folders.dm
  code/modules/research/designs.dm
  code/modules/research/xenoarchaeology/artifact/artifact.dm
  code/modules/research/xenoarchaeology/artifact/artifact_crystal.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_defines.dm
  code/modules/research/xenoarchaeology/finds/finds_fossils.dm
  code/modules/research/xenoarchaeology/finds/finds_pipboy.dm
  code/modules/research/xenoarchaeology/finds/finds_special.dm
  code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm
  code/modules/research/xenoarchaeology/machinery/artifact_scanner.dm
  code/modules/research/xenoarchaeology/machinery/coolant.dm
  code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
  code/modules/research/xenoarchaeology/tools/suspension_generator.dm
  code/modules/research/xenoarchaeology/tools/tools.dm
  code/modules/research/xenoarchaeology/tools/tools_anoscanner.dm
  code/modules/scrap/scrap.dm
  icons/mob/hands.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/decals.dmi
  icons/obj/device.dmi
  icons/obj/xenoarchaeology.dmi
  maps/z5.dmm
  taucetistation.dme
Labels: Feature, Interactive Diff Map, Map Edit, Sprites, Tweak

#3003 Clouds to indicate mob's emotes.
  code/datums/diseases/appendicitis.dm
  code/game/gamemodes/shadowling/shadowling_abilities.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/organ_internal.dm
  icons/mob/emote.dmi
Labels: Feature, Test Merge

#3014 Непростительные баффы клоуна.
  code/defines/obj/weapon.dm
  code/game/objects/items/weapons/clown_items.dm
  icons/obj/toy.dmi
  maps/z1.dmm
  sound/voice/fake_laugh/laugh1.ogg
  sound/voice/fake_laugh/laugh2.ogg
  sound/voice/fake_laugh/laugh3.ogg
Labels: Feature, HONK, Map Edit, Ready for Review, Sprites, Tweak

#3015 возвращаю дионам слоты
  code/modules/mob/living/carbon/species.dm
Labels: Balance, Ready for Review

#3019 carpets, tables, fixes
  maps/z1.dmm
Labels: Map Edit

#3016 Небольшой ребаланс магов
  code/datums/spells/mind_transfer.dm
  code/game/gamemodes/wizard/artefact.dm
  code/game/objects/items/weapons/implants/mindshield.dm
Labels: Balance, Tweak

#2792 Фикс отображения объектов класса chair.
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/holidays/new_year/snow.dm
  code/modules/locations/shuttles/bench.dm
  code/modules/locations/shuttles/bench.dmi
  icons/obj/objects.dmi
Labels: Fix, Merge Ready, Sprites

#3021 Исправление на некорректный цвет глаз ксеносов, поинт то верба и сохранение выбранного скалирования.
  code/__DEFINES/colors.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob.dm
  code/modules/organs/organ_external.dm
  interface/skin.dmf
Labels: Fix, Tweak

#3025 Не то облачко у когхс ап блад.
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/organs/organ_internal.dm
Labels: Tweak

#3054 Красивые спрайты улучшенных горелок
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/tools.dmi
Labels: Sprites
