Repository TauCetiStation/TauCetiClassic, pull requests merged in 2019-11, with the labels that each got.

#4111 Альт клики для некоторых вещей.
  code/game/machinery/computer/card.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
  sound/machines/terminal_insert.ogg
Labels: Feature, Test Merge Candidate

#4150 Rework wrappaper from var to contents and from contents to locate()
  code/defines/obj/weapon.dm
  code/game/atoms.dm
  code/game/gamemodes/cult/cult_datums.dm
  code/game/objects/items/weapons/gift_wrappaper.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/EFTPOS.dm
  code/modules/recycling/sortingmachinery.dm
Labels: Fix

#4157 New melon liquor and blue curacao sprites.
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  icons/obj/drinks.dmi
  icons/obj/reagentfillings.dmi
Labels: Sprites

#4164 Bolglars resprite
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
Labels: Sprites

#4201 Даггер поджигает сигареты и сигары.
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: Fix

#4214 Removed old unused exploitable topic
  code/modules/mob/mob.dm
Labels: Fix

#4106 Xenoarchaeology Overhaul: Part 6
  code/__DEFINES/xenoarchaeology.dm
  code/_globalvars/lists/misc.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  code/modules/research/xenoarchaeology/artifact/effects/badfeeling.dm
  code/modules/research/xenoarchaeology/artifact/effects/cellcharge.dm
  code/modules/research/xenoarchaeology/artifact/effects/celldrain.dm
  code/modules/research/xenoarchaeology/artifact/effects/cold.dm
  code/modules/research/xenoarchaeology/artifact/effects/dnaswitch.dm
  code/modules/research/xenoarchaeology/artifact/effects/emp.dm
  code/modules/research/xenoarchaeology/artifact/effects/forcefield.dm
  code/modules/research/xenoarchaeology/artifact/effects/gasco2.dm
  code/modules/research/xenoarchaeology/artifact/effects/gasnitro.dm
  code/modules/research/xenoarchaeology/artifact/effects/gasoxy.dm
  code/modules/research/xenoarchaeology/artifact/effects/gasplasma.dm
  code/modules/research/xenoarchaeology/artifact/effects/gassleeping.dm
  code/modules/research/xenoarchaeology/artifact/effects/goodfeeling.dm
  code/modules/research/xenoarchaeology/artifact/effects/heal.dm
  code/modules/research/xenoarchaeology/artifact/effects/heat.dm
  code/modules/research/xenoarchaeology/artifact/effects/hurt.dm
  code/modules/research/xenoarchaeology/artifact/effects/radiate.dm
  code/modules/research/xenoarchaeology/artifact/effects/roboheal.dm
  code/modules/research/xenoarchaeology/artifact/effects/robohurt.dm
  code/modules/research/xenoarchaeology/artifact/effects/sleepy.dm
  code/modules/research/xenoarchaeology/artifact/effects/stun.dm
  code/modules/research/xenoarchaeology/artifact/effects/teleport.dm
  code/modules/research/xenoarchaeology/artifact/effects/tesla.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_badfeeling.dm
  code/modules/research/xenoarchaeology/genetics/prehistoric_plants.dm
  code/modules/research/xenoarchaeology/genetics/reconstitutor.dm
  code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm
  code/modules/research/xenoarchaeology/machinery/artifact_harvester.dm
  code/modules/research/xenoarchaeology/tools/particles_battery_utilizer.dm
  taucetistation.dme
Labels: Feature, Fix, Test Merge Candidate

#4139 New backpack sprites
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/subsystem/jobs.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/wizard/wizard.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/client/character menu/general.dm
  code/modules/client/preferences.dm
  icons/mob/back.dmi
  icons/obj/storage.dmi
Labels: Sprites, Test Merge Candidate

#4146 Different IPC heads added, IPC bodies resprited
  code/__HELPERS/mobs.dm
  code/modules/client/character menu/general.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/organs/external/ipc.dm
  icons/mob/human_face.dmi
  icons/mob/human_races/r_machine.dmi
Labels: Sprites, Test Merge Candidate

#4166 Добавление дополнительных вещей на свалку и возможность копать ресурсы из турфов на свалке
  code/controllers/subsystem/junkyard.dm
  code/game/objects/random/random_meds.dm
  code/game/objects/random/random_science.dm
  code/game/objects/random/random_syndie.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/scrap/scrap_turfs.dm
Labels: Balance, Test Merge Candidate, Tweak

#4182 Добавление некоторых вещей в лодаут
  code/modules/client/character menu/loadout/loadout_accessories.dm
  code/modules/client/character menu/loadout/loadout_hats.dm
  code/modules/clothing/head/misc.dm
Labels: Test Merge Candidate, Tweak

#4189 nullify_debuff у костюмов для IPC.
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Test Merge Candidate, Tweak

#4193 Респрайт Инженерки
  code/modules/clothing/suits/jobs.dm
  icons/mob/belt.dmi
  icons/mob/belt_mirror.dmi
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Test Merge Candidate

#4194 Статусная информация для IPC.
  code/modules/mob/living/carbon/human/human.dm
Labels: Test Merge Candidate, Tweak

#4213 Ребаланс плазменного дробовика.
  code/modules/projectiles/guns/plasma/plasma.dm
Labels: Balance, Test Merge Candidate

#4218 Fixing a runtime in randomly generating a preference obj.
  code/modules/mob/dead/new_player/preferences_setup.dm
Labels: Fix

#4208 Логи для устройства удаленного доступа aka Remote Controller Device
  code/game/objects/items/devices/remote_device.dm
Labels: Admin, Quality Of Life

#4207 Фикс крашеных ботинок.
  code/game/machinery/washing_machine.dm
Labels: Fix

#4163 Фикс бага взаимодействия лицехвата-игрока с мобом, на котором был шлем
  code/modules/mob/living/carbon/alien/special/facehugger/facehugger.dm
  code/modules/mob/living/carbon/alien/special/facehugger/facehugger_playable.dm
Labels: Fix

#4219 random_blood_type, SSfastprocess, ui_style, alerts.
  code/__DEFINES/subsystem.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/type2type.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/monkey.dm
  code/_onclick/hud/other_mobs.dm
  code/controllers/subsystem/processing/fastprocess.dm
  code/game/gamemodes/changeling/powers/essences.dm
  code/game/gamemodes/changeling/powers/fakedeath.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/robot.dm
  code/game/objects/buckling.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/modules/client/character menu/global.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/laws.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob.dm
  code/modules/organs/organ_external.dm
  code/modules/tooltip/tooltip.html
  icons/mob/screen_alert.dmi
  taucetistation.dme
Labels: Sprites, Test Merge Candidate

#4132 При занятой профессии по умолчанию будет возвращать в лобби
  code/controllers/subsystem/jobs.dm
  code/modules/client/preferences.dm
Labels: Tweak

#4234 Тестовая карта с конфига, фреймворк статус эффектов, влив var monkeyizing в notransform, голод не alert.
  code/__DEFINES/status_effects.dm
  code/_onclick/click.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/human.dm
  code/controllers/configuration.dm
  code/datums/diseases/gbs.dm
  code/datums/diseases/rhumba_beat.dm
  code/datums/diseases/robotic_transformation.dm
  code/datums/diseases/xeno_transformation.dm
  code/datums/map_config.dm
  code/datums/mind.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/status_effect.dm
  code/game/dna/genes/monkey.dm
  code/game/gamemodes/blob/blob.dm
  code/game/gamemodes/changeling/powers/humanform.dm
  code/game/gamemodes/changeling/powers/lesserform.dm
  code/game/gamemodes/shadowling/special_shadowling_abilities.dm
  code/game/objects/items/bodybag.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/alien/death.dm
  code/modules/mob/living/carbon/alien/humanoid/update_icons.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/brain/death.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/carbon/monkey/death.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/death.dm
  code/modules/mob/living/silicon/robot/death.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/transform_procs.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
  config/example/config.txt
  icons/mob/screen_alert.dmi
  icons/mob/screen_gen.dmi
  taucetistation.dme
Labels: Sprites, Test Merge Candidate

#4232 Возможность класть кукол на операционный стол драг энд дропом
  code/game/machinery/OpTable.dm
Labels: Feature

#4220 Tanks sprites update
  icons/mob/back.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/tank.dmi
Labels: Sprites

#4221 Исправления некоторых вызовов для повреждений частей тела
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/surgery/appendix.dm
  code/modules/surgery/bones.dm
  code/modules/surgery/braincore.dm
  code/modules/surgery/eye.dm
  code/modules/surgery/face.dm
  code/modules/surgery/gender_reassignment.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/limbs.dm
  code/modules/surgery/lipoplasty.dm
  code/modules/surgery/other.dm
  code/modules/surgery/plastic_surgery.dm
  code/modules/surgery/ribcage.dm
Labels: Tweak

#4224 Фикс фотографий в альбоме.
  code/modules/paperwork/photography.dm
Labels: Fix

#4243 use() should validate passed amount
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/airlock_painter.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/power/cell.dm
Labels: Fix

#4249 Операция по смене аккамулятора у СПУ не учитывала голод
  code/modules/surgery/ribcage.dm
Labels: Fix

#4242 шахтёрский раздатчик
  icons/obj/machines/mining_machines.dmi
Labels: Sprites

#4152 Универсальный Язык Жестов
  code/modules/mob/hear_say.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/say.dm
Labels: Feature, Test Merge Candidate

#4174 Цикл поглощения заряда из APC с уведомлением для IPC.
  code/modules/power/apc.dm
Labels: Test Merge Candidate, Tweak

#4175 Добавление фич в настенную газету
  code/game/machinery/newscaster.dm
  code/modules/client/asset_cache.dm
  icons/newscaster_icons/dislike.png
  icons/newscaster_icons/dislike_clck.png
  icons/newscaster_icons/like.png
  icons/newscaster_icons/like_clck.png
Labels: Feature, Test Merge Candidate

#4142 Возможность выливать жидкости
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Feature, Test Merge Candidate

#4181 Add alarm sound for delta level.
  code/modules/security levels/security levels.dm
  sound/machines/alarm_delta.ogg
Labels: Sound, Test Merge Candidate

#4216 Огонь работает как огонь
  code/game/objects/effects/decals/Cleanable/fuel.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/examine.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/pai/life.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Feature, Test Merge Candidate, Tweak

#4245 Рефактор проков трансформ monkeyize(), добавление humanize().
  code/__DEFINES/DNA.dm
  code/__HELPERS/game.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/text.dm
  code/datums/mind.dm
  code/game/dna/dna2.dm
  code/game/dna/genes/monkey.dm
  code/game/gamemodes/changeling/powers/humanform.dm
  code/game/gamemodes/changeling/powers/lesserform.dm
  code/game/mecha/combat/honker.dm
  code/modules/genetics/side_effects.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/alien/special/facehugger/life.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/transform_procs.dm
  code/modules/surgery/plastic_surgery.dm
  taucetistation.dme
Labels: Refactor, Test Merge Candidate

#4247 Добавлены дополнительные источники инфекции при операции
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/surgery/surgery.dm
Labels: Test Merge Candidate, Tweak

#4261 Сообщения о голодании при осмотре IPC.
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature, Test Merge Candidate

#4269 Добавление конвейров и шахтерского оборудования в быстрый процессинг
  code/game/machinery/machinery.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_unloading.dm
  code/modules/recycling/conveyor2.dm
Labels: Feature, Test Merge Candidate

#4266 Bow rebalance
  code/modules/projectiles/guns/projectile/bow.dm
  maps/centcom/centcom.dmm
Labels: Balance, Map Edit

#4270 Remove obsolete areas
  code/modules/mining/mine_areas.dm
Labels: Code Improvements

#4267 Баг: овердоз дермалина не удаляет хаска
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Labels: Fix

#4273 Правки гостшипа
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  icons/mob/animal.dmi
  maps/templates/space_structures/ghost_ship_1.dmm
Labels: Map Edit, Sprites

#4282 Маленькие фиксы глухих
  code/modules/mob/hear_say.dm
Labels: Fix, Tweak
