Repository TauCetiStation/TauCetiClassic, pull requests merged in 2019-08, with the labels that each got.

#3700 personal closet нельзя забронировать картой внутри ПДА
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
Labels: Fix

#3664 Pouches.
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/random/pouches.dm
  code/game/objects/random/random_misc.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/syndicate.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  icons/obj/pouches.dmi
  taucetistation.dme
Labels: Feature, Sprites, Test Merge Candidate

#3722 Armoury access fix
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#3720 Паник бункер по лимиту игроков
  code/__DEFINES/_logging.dm
  code/controllers/configuration.dm
  code/modules/client/client procs.dm
  config/example/config.txt
Labels: Admin, Test Merge Candidate

#3735 Streamlining Velocity Officers spawn.
  code/game/communications.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/presets.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/admin/verbs/debug.dm
  code/modules/locations/centcomm/velocity.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/card.dmi
  icons/obj/pda.dmi
  icons/obj/radio.dmi
  maps/centcom/centcom.dmm
Labels: Map Edit, Sprites

#3732 Фикс взрыва нюки
  code/controllers/subsystem/ticker.dm
Labels: Fix

#3728 Немного "новых" эмодзи
  code/modules/goonchat/browserassets/css/emoji.css
  code/modules/goonchat/browserassets/css/emoji/dovolen.png
  code/modules/goonchat/browserassets/css/emoji/nedovolen.png
  code/modules/goonchat/browserassets/css/emoji/rastroen.png
  code/modules/goonchat/browserassets/css/emojib64.css
  code/modules/goonchat/browserassets/js/emojiList.json
Labels: Sprites

#3725 удаление "модуля" содержащего один не компилируемый файл
  code/modules/games/cards.dm
Labels: Code Improvements

#3711 Ремап кабинета Досмотра
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#3702 Фикс банок с красками
  code/game/objects/items/weapons/paint.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
Labels: Fix, Test Merge Candidate

#3692 Очень мелкие изменения с прожектайлами магии
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/magic/staff.dm
  code/modules/projectiles/projectile/animate.dm
  code/modules/projectiles/projectile/change.dm
  code/modules/projectiles/projectile/force.dm
  code/modules/projectiles/projectile/magic.dm
  taucetistation.dme
Labels: Fix

#3739 Finetunning Velocity officer experience.
  code/game/jobs/access.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/admin/verbs/debug.dm
  code/modules/locations/centcomm/velocity.dm
  icons/mob/hud.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/device.dmi
  maps/centcom/centcom.dmm
Labels: Map Edit, Sprites

#3743 Фикс названия пунктов назначения в телепортной
  code/game/area/Space Station 13 areas.dm
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#3751 Another set of changes to Velocity.
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/random/random.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/admin/verbs/debug.dm
  code/modules/locations/centcomm/velocity.dm
  code/modules/paperwork/stamps.dm
  icons/obj/bureaucracy.dmi
  maps/centcom/centcom.dmm
Labels: Map Edit, Sprites

#3718 Small add-ons#1
  code/game/machinery/camera/camera.dm
  code/game/objects/items/devices/paicard.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_bundle.dm
Labels: Feature

#3731 Ускорение генерации иконок личных дел
  code/__HELPERS/icons.dm
  code/datums/datacore.dm
Labels: Performance

#3745 не поверите, но стан револьер это тазер, а не просто лазган
  code/game/gamemodes/heist/heist_prices.dm
  code/game/machinery/portable_turret.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/research/designs.dm
  maps/centcom/centcom.dmm
Labels: Code Improvements, Map Edit

#3758 Fixing the fact that speech cloud was invisible.
  code/modules/mob/typing_indicator.dm
Labels: Fix

#3761 Доступ у VV закрыт + оповещение в АХ
  code/datums/datumvars.dm
  code/modules/admin/verbs/adminpm.dm
Labels: Admin, Fix

#3740 Небольшое облегчение цели воксов на кражу ресурсов
  code/game/gamemodes/objective.dm
Labels: Balance, Test Merge Candidate

#3765 Фикс флафа
  code/modules/fluff/customitems.dm
  code/modules/fluff/history.dm
  code/modules/fluff/premoderation.dm
Labels: Fix, Test Merge Candidate

#3773 Фикс маски СБ
  code/modules/clothing/masks/gasmask.dm
Labels: Fix

#3782 If client connection interupts, they can still type.
  code/modules/mob/typing_indicator.dm
Labels: Fix

#3780 Fixing spilling liquids onto janicart.
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/mop_bucket.dm
Labels: Fix

#3777 Фикс немых чейнжлингов
  code/modules/mob/living/carbon/human/say.dm
Labels: Fix

#3774 Resprite and rebrand of 9mm security handgun.
  code/game/gamemodes/heist/heist_prices.dm
  code/game/machinery/autolathe.dm
  code/game/objects/random/random_guns.dm
  code/game/objects/random/random_mecha.dm
  code/modules/paperwork/paper.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
  maps/templates/space_structures/abandoned_lab.dmm
Labels: Map Edit, Merge Ready, Sprites

#3771 The weapon to surpass metal gear
  code/modules/reagents/reagent_containers/spray.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/weapons.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Feature, Map Edit, Merge Ready, Sprites

#3786 Forgotten inhands for handgun.
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
Labels: Sprites

#3783 Travis
  .travis.yml
  scripts/install-byond.sh
Labels: Tools

#3754 Officer role prohibiting, contraband crates with actual contraband.
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/objective.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/objects/random/random.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/admin/verbs/debug.dm
  code/modules/customitems/item_defines.dm
  code/modules/locations/centcomm/velocity.dm
  code/modules/scrap/scrap.dm
  maps/centcom/centcom.dmm
Labels: Map Edit, Test Merge Candidate

#3772 Fixes kit items for species for jobs that didn't get them.
  code/controllers/subsystem/jobs.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/random/random_misc.dm
  code/modules/admin/verbs/debug.dm
  code/modules/mob/living/carbon/species.dm
Labels: Fix, Test Merge Candidate

#3787 FixTelebaton
  code/game/objects/items/weapons/swords_axes_etc.dm
Labels: Balance, Fix

#3794 Holster repsrite, tweaks and fixes
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/holidays/new_year/presents.dm
  icons/mob/accessory.dmi
  icons/obj/clothing/accessory.dmi
Labels: Sprites

#3793 заменяем танки
  icons/obj/objects.dmi
Labels: Sprites

#3790 Fixed ja character on loading screen, for authentic ban messages.
  code/__HELPERS/logging.dm
  code/__HELPERS/text.dm
  code/modules/admin/IsBanned.dm
Labels: Admin

#3770 Режим абдукторов теперь играбелен
  code/game/gamemodes/abduction/abduction.dm
Labels: Fix

#3797 Быстрофикс телебатона
  code/game/objects/items/weapons/swords_axes_etc.dm
Labels: Fix

#3801 Небольшие изменения в скрипт для хуков
  tools/_git-hooks/_install.bat
  tools/_git-hooks/_install.sh
  tools/_git-hooks/pre_install.sh
Labels: Tools

#3791 Еганы от Вальтера
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
Labels: Feature, Sprites

#3802 Uplink spawn before gamestart bootleg.
  code/game/objects/items/devices/uplinks.dm
Labels: Fix

#3815 [hotfix] Fixed wrong holster path
  maps/asteroid/asteroid.dmm
Labels: Map Edit

#3814 перенос walllocker в crates_lockers
  code/game/objects/structures/crates_lockers/walllocker.dm
  taucetistation.dme
Labels: Balance, Code Improvements

#3811 Baldness allowed to diona, unathi and female humans
  code/modules/mob/dead/new_player/sprite_accessories.dm
Labels: Tweak

#3817 Map fix
  code/game/area/Space Station 13 areas.dm
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/arcticwaste.dmm
  maps/RandomZLevels/assistantChamber.dmm
  maps/RandomZLevels/beach.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/challenge.dmm
  maps/RandomZLevels/example.dmm
  maps/RandomZLevels/jungle.dmm
  maps/RandomZLevels/listeningpost.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/wildwest.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/centcom/centcom.dmm
  maps/templates/holodeck/basketball.dmm
  maps/templates/holodeck/boxingcourt.dmm
  maps/templates/holodeck/courtroom.dmm
  maps/templates/holodeck/desert.dmm
  maps/templates/holodeck/emptycourt.dmm
  maps/templates/holodeck/meetinghall.dmm
  maps/templates/holodeck/theatre.dmm
  maps/templates/holodeck/thunderdomecourt.dmm
  maps/templates/shelter_2.dmm
  maps/templates/space_structures/abandoned_ship.dmm
  maps/templates/space_structures/agrosphere.dmm
  maps/templates/space_structures/clown_shuttle.dmm
  maps/templates/space_structures/derelict_station.dmm
  maps/templates/space_structures/dj_station.dmm
  maps/templates/space_structures/robostation.dmm
  maps/testmap/testmap.dmm
Labels: Map Edit

#3818 Апдейт юнит тестов
  .travis.yml
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/gamma/gamma.dmm
  scripts/include-additional-files.py
  scripts/maps-tgm-checker.py
  scripts/tag-matcher.py
  test/run-test.sh
Labels: Maintainability Improvements

#3681 ИИ лицехватов. Возможность педально менять тип контроля лицехватами
  code/__DEFINES/misc.dm
  code/__DEFINES/mob.dm
  code/__HELPERS/game.dm
  code/_globalvars/lists/objects.dm
  code/_globalvars/misc.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/events.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/events/alien_infestation.dm
  code/modules/events/borers.dm
  code/modules/mob/living/carbon/alien/effects/aliens.dm
  code/modules/mob/living/carbon/alien/facehugger/facehugger.dm
  code/modules/mob/living/carbon/alien/facehugger/facehugger_abilities.dm
  code/modules/mob/living/carbon/alien/facehugger/inventory.dm
  code/modules/mob/living/carbon/alien/facehugger/life.dm
  code/modules/mob/living/carbon/alien/facehugger/powers.dm
  code/modules/mob/living/carbon/alien/facehugger/update_icons.dm
  code/modules/mob/living/carbon/alien/larva/larva.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  code/modules/mob/living/carbon/alien/special/facehugger/facehugger.dm
  code/modules/mob/living/carbon/alien/special/facehugger/facehugger_playable.dm
  code/modules/mob/living/carbon/alien/special/facehugger/life.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/surgery/ribcage.dm
  taucetistation.dme
Labels: Balance, Feature, Test Merge Candidate

#3822 Фикс тональности звука включения ламп
  code/modules/power/lighting.dm
Labels: Fix, Merge Ready

#3812 Unathi resprited by WalterJe
  icons/effects/species.dmi
  icons/mob/human_races/r_lizard.dmi
Labels: Sprites, Test Merge Candidate

#3807 Звуки попадания снарядов по мобу
  code/__DEFINES/sound.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/special.dm
  sound/effects/projectiles_acts/acid_1.ogg
  sound/effects/projectiles_acts/acid_2.ogg
  sound/effects/projectiles_acts/acid_3.ogg
  sound/effects/projectiles_acts/bullet_1.ogg
  sound/effects/projectiles_acts/bullet_2.ogg
  sound/effects/projectiles_acts/bullet_3.ogg
  sound/effects/projectiles_acts/laser_1.ogg
  sound/effects/projectiles_acts/laser_2.ogg
  sound/effects/projectiles_acts/laser_3.ogg
  sound/effects/projectiles_acts/miss_1.ogg
  sound/effects/projectiles_acts/miss_2.ogg
  sound/effects/projectiles_acts/miss_3.ogg
  sound/effects/projectiles_acts/miss_4.ogg
  sound/effects/projectiles_acts/weakbullet_1.ogg
  sound/effects/projectiles_acts/weakbullet_2.ogg
  sound/effects/projectiles_acts/weakbullet_3.ogg
Labels: Sound, Test Merge Candidate

#3827 Detective's colt and magazines repsrited by WalterJe
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
Labels: Sprites

#3831 Фикс спавна структур друг в друге
  code/controllers/subsystem/mapping.dm
Labels: Fix, Performance

#3824 офицеры подчиняются хосу и вардену
  code/game/jobs/job/security.dm
Labels: Tweak

#3820 показываем записи по сикею
  code/modules/admin/admin.dm
Labels: Admin

#3738 Ребаланс скафандров воксов
  code/modules/clothing/spacesuits/alien.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/mob/living/carbon/human/life.dm
  sound/rig/stealthrig_starting_up.ogg
  sound/rig/stealthrig_turn_off.ogg
  sound/rig/stealthrig_turn_on.ogg
Labels: Balance, Test Merge Candidate

#3833 Замена дефайнов soundin'ов на листы
  code/__DEFINES/sound.dm
  code/_globalvars/lists/sound.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/special.dm
  taucetistation.dme
Labels: Performance, Test Merge Candidate

#3813 Прицеливание на альт-клик
  code/modules/projectiles/gun.dm
Labels: Test Merge Candidate, Tweak

#3850 Fix holo desert tiles
  maps/templates/holodeck/desert.dmm
Labels: Map Edit

#3775 Lasertag rework
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/portable_turret.dm
  code/game/objects/structures/crates_lockers/closets/fitness.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/projectiles/ammunition/energy.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/research/xenoarchaeology/machinery/coolant.dm
Labels: Refactor, Test Merge Candidate

#3788 Возможность разобрать взорванный АПЦ, спаси и сохрани
  code/modules/power/apc.dm
Labels: Fix, Test Merge Candidate

#3800 новые камеры от вальтера
  icons/obj/monitors.dmi
Labels: Sprites, Test Merge Candidate

#3842 Немного оптимизаций
  code/__DEFINES/mc.dm
  code/controllers/subsystem/timer.dm
  code/datums/wires/vending.dm
  code/game/area/areas.dm
  code/game/machinery/alarm.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/modules/client/client procs.dm
  code/modules/power/apc.dm
  code/modules/scrap/oldificator.dm
Labels: Performance, Test Merge Candidate

#3744 lasertag armor aror - armor
  code/modules/clothing/suits/miscellaneous.dm
Labels: Fix

#3854 Баланс замедления брони оперативников
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/suits/armor.dm
Labels: Balance, Test Merge Candidate

#3839 Добавлено больше окон в отделы
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Test Merge Candidate, Tweak

#3864 случайный h; i из-за /
  code/modules/mob/living/carbon/human/human.dm
  code/modules/research/xenoarchaeology/finds/finds_special.dm
Labels: Code Improvements

#3823 ERT Message
  code/game/response_team.dm
Labels: Tweak

#3816 небольшое изменение воздействия на гроб
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
Labels: Fix, Tweak

#3821 дионы теряли зрение в гештальте
  code/modules/mob/living/life.dm
Labels: Fix

#3852 Изменено содержимое спец. ящика в карго, удалён парапен (опять)
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/cargo/packs.dm
Labels: Revert / Removal, Tweak

#3871 Фикс Bridge East камеры
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#3872 убираем 2 раковины на одном тайле в хирургии
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#3883 Ребаланс по причине токсик, попытка джва
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/research/experiment.dm
Labels: Balance

#3829 пофиксил бесконечную сварку в некоторых местах
  code/game/machinery/bots/bots.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/objects/structures/signs/_signs.dm
  code/modules/mining/equipment_locker.dm
Labels: Fix

#3845 Небольшая сортировка under
  code/game/gamemodes/abduction/abduction.dm
  code/game/gamemodes/wizard/artefact.dm
  code/game/gamemodes/wizard/wizard.dm
  code/game/jobs/job/assistant.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/random/random_cloth.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/game/objects/structures/pit.dm
  code/modules/admin/verbs/debug.dm
  code/modules/cargo/packs.dm
  code/modules/client/character menu/loadout/loadout_clothing.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/miscellaneous.dm
  maps/RandomZLevels/Academy.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
  maps/templates/holodeck/theatre.dmm
Labels: Code Improvements, Map Edit, Test Merge Candidate

#3849 Added B/Ctrl+B hotkeys binded to Apply Item To Self verb
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob.dm
  interface/interface.dm
  interface/skin.dmf
Labels: Feature, Test Merge Candidate

#3868 Поднял пороговое значение времени для ролек
  code/_globalvars/lists/misc.dm
  code/controllers/configuration.dm
Labels: Balance

#3880 WindowFix
  maps/asteroid/asteroid.dmm
Labels: Map Edit

#3886 ERT_Gas_Mask
  maps/centcom/centcom.dmm
Labels: Map Edit

#3888 Fix_Rad_Storm_Defence
  code/datums/weather/weather_types.dm
Labels: Balance

#3899 Сумма защиты частей тела от температур не достигала 100%
  code/__DEFINES/clothing.dm
Labels: Fix

#3904 Посохи теперь не имеют экшон кнопки
  code/modules/projectiles/guns/magic.dm
Labels: Fix

#3903 Fix #3900 Доступ в медбей повышен до прежнего
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#3909 Revert "Небольшая сортировка under"
  code/game/gamemodes/abduction/abduction.dm
  code/game/gamemodes/wizard/artefact.dm
  code/game/gamemodes/wizard/wizard.dm
  code/game/jobs/job/assistant.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/random/random_cloth.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/game/objects/structures/pit.dm
  code/modules/admin/verbs/debug.dm
  code/modules/cargo/packs.dm
  code/modules/client/character menu/loadout/loadout_clothing.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/miscellaneous.dm
  maps/RandomZLevels/Academy.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
  maps/templates/holodeck/theatre.dmm
Labels: Map Edit

#3857 гладкие стены с Oracle station
  code/game/turfs/unsimulated/walls.dm
  icons/turf/walls.dmi
  icons/turf/walls/riveted.dmi
Labels: Map Edit, Sprites, Test Merge Candidate

#3912 New game mode startup sounds
  code/datums/mind.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/malfunction/malfunction.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/traitor/traitor.dm
  sound/antag/ling_aler.ogg
  sound/antag/malf.ogg
  sound/antag/ops.ogg
  sound/antag/tatoralert.ogg
Labels: Feature

#3906 Changeling stasis fix
  code/game/gamemodes/changeling/powers/fakedeath.dm
Labels: Fix

#3730 Баф еды. Дебаф рамена
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_types/Chemistry-Core.dm
  code/modules/reagents/reagent_types/Chemistry-Foods.dm
Labels: Balance, Test Merge Candidate

#3867 Добавление адреналинового и емп импланта
  code/datums/uplinks_items.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/game/objects/items/weapons/implants/implantfreedom.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Labels: Feature

#3917 Туррет и Епилепсия находились под одним датумом (Турет заменял эпилепсию)
  code/datums/traits/negative.dm
Labels: Fix

#3862 Resprite of mining shuttle by WalterJe.
  code/modules/locations/shuttles/closet.dm
  code/modules/locations/shuttles/closet.dmi
  code/modules/locations/shuttles/computer_shuttle_mining.dmi
  code/modules/locations/shuttles/shuttle_doors.dm
  code/modules/locations/shuttles/shuttle_mining.dmi
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit, Sprites
