Repository TauCetiStation/TauCetiClassic, pull requests merged in 2020-03, with the labels that each got.

#4771 Фиск таймингов дверей и звуков открытия/закрытия
  code/game/machinery/doors/door.dm
  sound/machines/airlock/close.ogg
  sound/machines/airlock/open.ogg
Labels: Sound

#4765 Код безопасности в PDA и Fire alarm examine
  code/game/machinery/alarm.dm
  code/game/objects/items/devices/PDA/PDA.dm
  nano/templates/pda.tmpl
Labels: Feature, Test Merge Candidate

#4746 fix people being deleted from closets
  code/modules/recycling/sortingmachinery.dm
Labels: Fix

#4767 Фильтрация O2 и N2 в Scrubber'ах
  code/game/machinery/alarm.dm
  code/modules/atmospheric/machinery/components/unary_devices/vent_scrubber.dm
Labels: Fix, Test Merge Candidate, Tweak

#4768 Отображение отсутствующих конечностей на кукле здоровья
  code/modules/mob/living/carbon/human/life.dm
  icons/mob/screen_gen.dmi
Labels: Feature, Sprites, Test Merge Candidate

#4770 Speedloaders
  code/datums/uplinks_items.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  icons/obj/ammo.dmi
Labels: Sprites, Test Merge Candidate, Tweak

#4781 Update gamma.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit

#4752 Респрайты одежды охранки, инженерки, уборщика и перчаток медиков
  icons/mob/belt.dmi
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Test Merge Candidate

#4718 Spritesheet-based species restriction
  code/__DEFINES/clothing.dm
  code/__DEFINES/flags.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/mob.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/gloves/ninja.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/suits/alien.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
Labels: Refactor, Test Merge Candidate

#4792 Lasertag update
  code/game/objects/structures/crates_lockers/closets/fitness.dm
  code/modules/projectiles/ammunition/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  sound/weapons/guns/lasertag.ogg
Labels: Balance, Sound, Sprites

#4791 delete
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Sound

#4090 Рефактор системы эмоутов людей
  code/__DEFINES/preferences.dm
  code/__HELPERS/names.dm
  code/datums/diseases/appendicitis.dm
  code/datums/spells/in_hand.dm
  code/game/gamemodes/blob/overmind.dm
  code/game/gamemodes/shadowling/shadowling_abilities.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implantfreedom.dm
  code/game/objects/items/weapons/implants/implantuplink.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/client/character menu/global.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/blob/blob.dm
  code/modules/mob/living/carbon/brain/brain.dm
  code/modules/mob/living/carbon/brain/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/ian/emote.dm
  code/modules/mob/living/carbon/metroid/emote.dm
  code/modules/mob/living/carbon/monkey/emote.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/emote.dm
  code/modules/mob/living/carbon/xenomorph/larva/emote.dm
  code/modules/mob/living/carbon/xenomorph/special/alien_embryo.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
  code/modules/mob/living/parasite/meme.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/say.dm
  code/modules/organs/external/flesh.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/reagent_types/Chemistry-Foods.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
  code/modules/scrap/scrap_light.dm
  code/modules/scrap/scrap_pileripper.dm
  code/modules/scrap/scrap_refinery.dm
  code/modules/virus2/effect.dm
Labels: Pinned, Revert / Removal, Sound, Test Merge Candidate, Tweak

#4750 Исправления работы с счетами
  code/game/machinery/vending.dm
  code/game/objects/structures/watercloset.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/Accounts_DB.dm
  code/modules/economy/EFTPOS.dm
  code/modules/events/money_hacker.dm
  code/modules/events/money_lotto.dm
  code/modules/stock_market/computer.dm
  code/modules/stock_market/stocks.dm
Labels: Fix, Test Merge Candidate

#4810 Fix Runtime Cryo
  code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
Labels: Fix

#4811 Fix Runtime Surgery Brain
  code/modules/surgery/braincore.dm
Labels: Fix

#4813 Fix Runtime Hulk Power
  code/modules/mob/living/simple_animal/hulk_powers.dm
Labels: Fix

#4727 Фиксим 3 бага у аленей и плохой атом инит
  code/__DEFINES/flags.dm
  code/game/objects/items.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/humanoid.dm
  code/modules/mob/living/carbon/xenomorph/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/mob.dm
  code/modules/power/lighting.dm
Labels: Fix

#4825 Фикс стата в проверках CanHug() и is_facehuggable()
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
  code/modules/mob/mob.dm
Labels: Fix

#4816 Fix Runtime Null Ammo
  code/modules/projectiles/firing.dm
Labels: Fix

#4836 Runtime in door.dm:149 : Cannot execute null.SetNextMove()
  code/game/machinery/doors/door.dm
Labels: Fix

#4748 Липкие баны
  SQL/ss13_feed.sql
  code/__DEFINES/admin.dm
  code/__DEFINES/subsystem.dm
  code/__HELPERS/_lists.dm
  code/_globalvars/admin.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/demo.dm
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/stickyban.dm
  code/defines/procs/dbcore.dm
  code/game/world.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/stickyban.dm
  code/modules/admin/topic.dm
  code/modules/goonchat/browserOutput.dm
  taucetistation.dme
Labels: :atom: BYOND, Admin, Database, Test Merge Candidate

#4728 vox rigs and modkits and stuff
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/modkit.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mob/living/carbon/species.dm
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/suit.dmi
  icons/obj/clothing/species/vox/hats.dmi
  icons/obj/clothing/species/vox/suits.dmi
Labels: Sprites, Test Merge Candidate

#4735 Vox, as a playable race.
  code/__HELPERS/icons.dm
  code/_globalvars/database.dm
  code/controllers/subsystem/quirks.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/species.dm
Labels: Feature, Test Merge Candidate

#4797 BoxStation Update
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#4817 рантайм логи с +logs
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/getlogs.dm
Labels: Tweak

#4818 Перенос железных стен под формат текстур новых стен
  code/game/turfs/unsimulated/walls.dm
  icons/turf/walls.dmi
  icons/turf/walls/iron.dmi
  maps/centcom/centcom.dmm
Labels: Map Edit, Sprites

#4823 Space cleaners
  code/modules/reagents/reagent_dispenser.dm
  icons/obj/objects.dmi
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Sprites

#4829 Мелкие изменения мап
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit

#4834 Отбытие Гаммы
  maps/gamma/gamma.dmm
Labels: Map Edit

#4845 Фикс жирноспрайтов
  icons/mob/human_races/r_human.dmi
  icons/mob/human_races/r_skrell.dmi
  icons/mob/human_races/r_tajaran.dmi
Labels: Sprites

#4838 Fixing runtimes on simple_animal deletion kills.
  code/_onclick/item_attack.dm
  code/modules/mob/living/silicon/robot/drone/drone_damage.dm
  code/modules/mob/living/silicon/robot/robot_damage.dm
Labels: Fix

#4851 Фикс спрайтов ящеролюдов.
  icons/mob/human_races/r_lizard.dmi
Labels: Sprites

#4880 Апдейт причуд
  code/controllers/subsystem/quirks.dm
Labels: Tweak

#4862 Correct damage report for IPC
  code/modules/organs/organ_internal.dm
Labels: Fix

#4783 Изменения аутопсии
  code/game/machinery/doors/airlock.dm
  code/modules/detectivework/autopsy.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/mob_grab.dm
  code/modules/organs/external/flesh.dm
  code/modules/organs/organ.dm
Labels: Test Merge Candidate, Tweak

#4782 Фикс ботов починки плитки
  code/game/machinery/bots/floorbot.dm
  code/modules/mob/living/silicon/pai/software.dm
Labels: Fix, Test Merge Candidate

#4780 wooden shield
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/weapons/shields.dm
  code/modules/crafting/recipes.dm
  code/modules/projectiles/guns/projectile/bow.dm
  code/modules/projectiles/guns/projectile/pneumatic.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/weapons.dmi
  sound/effects/hits_to_w_shield.ogg
  sound/weapons/metal_shield_hit.ogg
  sound/weapons/wood_shield_hit.ogg
Labels: Refactor, Sound, Sprites, Test Merge Candidate

#4766 Исправление T-Вентилей
  code/__DEFINES/atmospherics.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/modules/atmospheric/machinery/components/trinary_devices/tvalve.dm
  code/modules/atmospheric/machinery/datum_pipeline.dm
  icons/obj/pipe-item.dmi
Labels: Feature, Fix, Sprites, Test Merge Candidate, Tweak

#4865 Починка операция по восстановлению камер у спу
  code/modules/surgery/eye.dm
Labels: Fix

#4888 Grab removed from vox leap for balance reasons; weaken effect reduced
  code/modules/mob/living/carbon/human/human.dm
Labels: Balance, Tweak

#4628 Geoip rework, guard system
  code/__DEFINES/admin.dm
  code/__DEFINES/varedit.dm
  code/__HELPERS/game.dm
  code/__HELPERS/sanitize_values.dm
  code/controllers/configuration.dm
  code/game/area/shuttle_areas.dm
  code/game/machinery/computer/arrival_shuttle.dm
  code/game/world.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  code/modules/client/geoip.dm
  code/modules/client/guard.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserassets/js/browserOutput.js
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/login.dm
  config/example/config.txt
  taucetistation.dme
Labels: Test Merge Candidate

#4835 VOX Hair and Color
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/species.dm
  icons/mob/human_face.dmi
  icons/mob/human_races/r_def_vox.dmi
  icons/mob/human_races/r_vox.dmi
Labels: Sprites, Test Merge Candidate

#4867 Иммунитет Спу против части типов урона и вычёркивание их из целей слаймов
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/carbon/species.dm
Labels: Fix, Test Merge Candidate

#4871 A4
  icons/obj/storage.dmi
Labels: Sprites, Test Merge Candidate

#4894 Второй ребаланс режимов
  code/game/gamemodes/abduction/abduction.dm
  code/game/gamemodes/changeling/traitor_chan.dm
Labels: Balance

#4903 golemrunesprite
  icons/obj/rune.dmi
Labels: Sprites

#4884 Апдейт спрайта баллона с фороном
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/tank.dmi
Labels: Merge Conflict, Sprites

#4896 Candles boxes now fits bibles
  code/game/objects/items/weapons/storage/fancy.dm
Labels: Fix

#4897 vagonetkasprite
  icons/obj/storage.dmi
Labels: Sprites

#4900 Hot Black Pepper
  code/defines/obj/hydro.dm
  code/game/machinery/vending.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  icons/obj/hydroponics/growing_vegetables.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/hydroponics.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Sprites, Tweak

#4906 Dorms toilet APC and camera fix by Kildjen
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Tweak

#4908 Xenoarheology update by Nejdlik
  maps/asteroid/asteroid.dmm
Labels: Map Edit, Tweak

#4917 Фикс вылезающих пикселей СПУ, скрелла
  icons/mob/human_races/r_machine.dmi
  icons/mob/human_races/r_skrell.dmi
Labels: Sprites

#4923 Фикс направления мусорки
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Tweak
