Repository TauCetiStation/TauCetiClassic, pull requests merged in 2020-08, with the labels that each got.

#5921 Fix513
  code/game/gamemodes/changeling/powers/essences.dm
  code/modules/mob/living/carbon/brain/say.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/say.dm
  code/modules/nano/nanoui.dm
Labels: Fix

#5939 Противогазы и Разрыв лёгких работает внутри обьектов
  code/modules/mob/living/carbon/human/life.dm
Labels: Fix

#5907 Borgs can modify airlock electronics access
  code/game/machinery/doors/airlock_electronics.dm
Labels: Fix

#5853 Расы, у которых VIRUS_IMMUNE больше не смогут болеть
  code/datums/disease.dm
  code/modules/mob/mob_cleanup.dm
Labels: Fix

#5942 rig-syndie-space fix
  icons/mob/species/tajaran/suit.dmi
Labels: Sprites

#5932 subprofs preview
  code/game/jobs/job/job.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
Labels: Tweak

#5933 toggle darkness to ghost hud
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ghost.dm
  icons/mob/screen_ghost.dmi
Labels: Sprites, Tweak

#5895 Обновление шахтёрского ящика с лутом
  code/modules/mining/abandonedcrates.dm
Labels: Balance, Tweak

#5906 И ещё рантайм
  code/game/machinery/kitchen/monkeyrecycler.dm
Labels: Fix

#5953 blobs, borers, ninjas to antagpanel
  code/game/gamemodes/blob/blob.dm
  code/game/gamemodes/blob/blob_finish.dm
  code/game/gamemodes/blob/overmind.dm
  code/modules/admin/player_panel.dm
  code/modules/events/space_ninja.dm
  code/modules/mob/living/simple_animal/borer.dm
Labels: Fix

#5959 Makes new player panel update on round start.
  code/controllers/subsystem/ticker.dm
Labels: Tweak

#5960 click cooldown for attacking mmi with mobs
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/mob/living/carbon/brain/MMI.dm
Labels: Fix

#5968 Изменение эффекта ночного зрения у таяр
  code/__HELPERS/matrices.dm
Labels: Tweak

#5987 suit_storage_unit CSS_THEME_LIGHT
  code/game/machinery/suit_storage_unit.dm
Labels: Tweak

#5989 chat scrolling fix
  code/modules/goonchat/browserassets/css/browserOutput.css
Labels: Fix

#5920 Разноцветные гранаты 40x46mm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  icons/obj/ammo.dmi
  icons/obj/storage.dmi
Labels: Sprites

#5891 Анимации низкого заряда для ионки, егана и лазер гана
  icons/obj/gun.dmi
Labels: Sprites

#5885 Куча мелкофиксов коробки
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#5982 Making gods not become visible after staff is destroyed
  code/game/objects/items/weapons/chaplain_weapons.dm
Labels: Revert / Removal

#6003 save ghostsight
  code/modules/client/preferences_savefile.dm
Labels: Fix

#5711 Изменения Синди страйкеров, их базы и шатла
  code/game/area/custom_areas.dm
  code/game/machinery/computer/syndicate_specops_shuttle.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/striketeam_syndicate.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  icons/mob/head.dmi
  icons/mob/nuclear_helm_overlays.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/turf/areas.dmi
  maps/centcom/centcom.dmm
Labels: Map Edit, Sprites

#6008 "Add hover indicator for body zone selector" from TG
  code/_onclick/hud/screen_objects.dm
Labels: Feature

#6010 Makes pen click when you click on them
  code/modules/paperwork/pen.dm
Labels: Tweak

#6011 ghosts can no longer rotate a suspension gen
  code/modules/research/xenoarchaeology/machinery/suspension_generator.dm
Labels: Fix

#5996 Радиальное меню при смене облика ид-карты трейтора, ид и пда пейнтера
  code/game/machinery/IDpainter.dm
  code/game/machinery/PDApainter.dm
  code/game/objects/items/weapons/cards_ids.dm
Labels: Tweak

#5993 Радиальное меню в выбор цели заклинания
  code/datums/spell.dm
Labels: Tweak

#5892 Перевод на радиалку расскрашивание картоных хуманоидов.
  code/game/objects/items/devices/cardboard.dm
Labels: Feature

#5994 Чиним 2 прока у дрона, которые должны позволять ему ходить по безгравитационному полу
  code/modules/mob/living/silicon/robot/drone/drone.dm
Labels: Fix

#5706 Daltonism
  code/__DEFINES/quirks.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/matrices.dm
  code/__HELPERS/type2type.dm
  code/_globalvars/lists/misc.dm
  code/datums/traits/neutral.dm
  code/datums/traits/positive.dm
  code/datums/wires/_wires.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/mob_defines.dm
Labels: Feature, Test Merge Candidate

#5965 Ребаланс и респрайт Воксотни
  code/game/gamemodes/heist/heist_old.dm
  code/game/gamemodes/heist/vox_role.dm
  code/modules/clothing/glasses/hud.dm
  icons/mob/species/vox/eyes.dmi
  icons/mob/species/vox/gloves.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/shoes.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/species/vox/uniform.dmi
  icons/obj/ammo.dmi
  icons/obj/clothing/accessory.dmi
  icons/obj/clothing/accessory_overlay.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/species/vox/suits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/gun.dmi
Labels: Sprites

#6017 На шейде и боге нельзя делать комбо
  code/modules/unarmed_combat/combat_combo.dm
Labels: Fix

#6034 Другие ручки теперь тоже клацают
  code/modules/paperwork/pen.dm
Labels: Fix

#5992 Game Kit style fix
  code/game/objects/game_kit.dm
  html/browser/common.css
Labels: Fix

#5943 Splits scanners.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/devices/scanners/contraband_finder.dm
  code/game/objects/items/devices/scanners/gas.dm
  code/game/objects/items/devices/scanners/health_analyzer.dm
  code/game/objects/items/devices/scanners/mass_spectrometer.dm
  code/game/objects/items/devices/scanners/occult_pinpointer.dm
  code/game/objects/items/devices/scanners/occult_scanner.dm
  code/game/objects/items/devices/scanners/reagent_scanner.dm
  code/game/objects/items/devices/scanners/t_scanner.dm
  taucetistation.dme
Labels: Code Improvements

#6044 Хотфиксы спрайтов #5965
  icons/mob/species/vox/shoes.dmi
  icons/mob/species/vox/suit.dmi
Labels: Sprites

#6048 Фикс сообщений от менторов
  code/modules/mentor/mentorpm.dm
Labels: Fix
