Repository TauCetiStation/TauCetiClassic, pull requests merged in 2020-02, with the labels that each got.

#4586 Добавил больше возможностей для пальпации
  code/modules/mob/mob_grab.dm
Labels: Feature

#4210 more nukebase tweaks
  maps/centcom/centcom.dmm
Labels: Fix, Map Edit

#4583 Soundsound
  sound/effects/grillehit.ogg
  sound/effects/rustle1.ogg
  sound/effects/spray2.ogg
  sound/effects/squeak.ogg
  sound/effects/woodhit.ogg
  sound/items/PSHOOM_2.ogg
  sound/items/megaphone.ogg
  sound/machines/cfieldbeforestart.ogg
  sound/weapons/Genhit.ogg
  sound/weapons/guns/reload_ak74.ogg
  sound/weapons/punch1.ogg
  sound/weapons/punch2.ogg
  sound/weapons/punch3.ogg
  sound/weapons/punch4.ogg
  sound/weapons/smash.ogg
  sound/weapons/tablehit1.ogg
Labels: Sound, Test Merge Candidate

#4616 No more grabs dissapearing into the tophat.
  code/modules/clothing/head/wiz_tophat.dm
Labels: Fix

#4632 Обновление паникбункера и релоад конфигов
  code/controllers/configuration.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client procs.dm
  code/modules/mob/mob.dm
  config/example/config.txt
Labels: Admin

#4517 Аннонсер событий серверов
  code/controllers/configuration.dm
  code/game/world.dm
  code/modules/admin/DB ban/functions.dm
  config/.gitignore
  config/example/announcer/ban.txt
  config/example/announcer/serverlist.txt
Labels: Admin, Tools

#4605 Добавлен вывод банов из базы в нотисы
  code/__DEFINES/admin.dm
  code/__HELPERS/time.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/admin.dm
  code/modules/admin/player_notes.dm
Labels: Admin, Test Merge Candidate

#4433 Отделение РП-ревы от ревы (частичное?)
  code/controllers/subsystem/shuttles.dm
  code/game/gamemodes/objective.dm
  code/game/gamemodes/revolution/rp_revolution.dm
  code/game/gamemodes/scoreboard.dm
Labels: Fix

#4642 replays & stat folder
  code/__HELPERS/logging.dm
  code/controllers/subsystem/demo.dm
  code/game/world.dm
Labels: Fix

#4637 лямбда
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Sound

#4614 Еще больше тегов для бюрократии
  code/__HELPERS/text.dm
  code/modules/paperwork/paper.dm
Labels: Feature, Test Merge Candidate

#4597 Респрайт шприцов (ППШ)
  icons/obj/items.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/syringe.dmi
Labels: Sprites, Test Merge Candidate

#4651 Кик за афк всех и всегда, кроме педалей и донатеров
  code/game/world.dm
Labels: Admin, Tweak

#4548 Система Spritesheet с tg и иконки в торговых автоматах
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/assets.dm
  code/datums/browser.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/client/asset_cache.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/spray.dm
  scripts/strip_metadata.py
Labels: Feature, Test Merge Candidate

#4584 RnD changes.
  code/__DEFINES/research.dm
  code/_globalvars/lists/objects.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/empulse.dm
  code/game/objects/explosion_recursive.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/research/circuitprinter.dm
  code/modules/research/designs.dm
  code/modules/research/experiment.dm
  code/modules/research/protolathe.dm
  code/modules/research/prototipify.dm
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
  nano/templates/rdconsole.tmpl
  taucetistation.dme
Labels: Balance, Feature, Test Merge Candidate

#4631 kitchen!
  code/_globalvars/lists/sound.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  sound/items/esword_cutting.ogg
  sound/items/knife_cutting1.ogg
  sound/items/knife_cutting2.ogg
  sound/items/knife_cutting3.ogg
  sound/items/rolling_pin.ogg
  sound/items/shard_cutting.ogg
Labels: Sound, Test Merge Candidate

#4634 Звук факса на ЦК
  code/game/machinery/fax.dm
  sound/machines/fax_centcomm.ogg
Labels: Admin, Sound, Test Merge Candidate

#4652 Runtime in alarm.dm,30: type mismatch: 0 |= /list (/list)
  code/game/machinery/computer/camera.dm
Labels: Test Merge Candidate

#4593 Лизард бутсы доступны всем
  code/modules/clothing/shoes/miscellaneous.dm
Labels: Fix

#4656 Stress no feed
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/damage_procs.dm
Labels: Fix

#4663 Атака и здоровье томатов-убийц зависят от potency
  code/modules/mob/living/simple_animal/friendly/tomato.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Tweak

#4676 Fixed datum/browser 'я'
  code/datums/browser.dm
Labels: &#255;

#4659 Чайник из мед бея заваривает чай из воды
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Tweak

#4673 Access not split for sub-proffesions of scientist
  code/game/jobs/job/science.dm
Labels: Balance

#4554 Апгрейд ксенобиологии. Порт slime management console + небольшой ремап
  code/__DEFINES/components.dm
  code/__DEFINES/maps.dm
  code/game/machinery/camera/camera_advanced.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/kitchen/monkeyrecycler.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/carbon/metroid/powers.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  code/modules/research/xenobiology/xenobio_camera.dm
  icons/mob/actions.dmi
  icons/mob/slimes.dmi
  icons/obj/chemical.dmi
  maps/boxstation/boxstation.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#4594 Admins can force status effects onto people and put people to sleep
  code/datums/admin_arguments_request.dm
  code/datums/datumvars.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/status_effect.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  taucetistation.dme
Labels: Admin, Test Merge Candidate

#4626 Pyrometer
  code/__DEFINES/math.dm
  code/__DEFINES/math_physics.dm
  code/datums/spells/in_hand.dm
  code/game/atoms.dm
  code/game/gamemodes/changeling/powers/Whip.dm
  code/game/gamemodes/heist/heist_role_equip.dm
  code/game/machinery/igniter.dm
  code/game/machinery/machinery.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/weapons/flamethrower.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/anomaly/anomalies.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/hulk_powers.dm
  code/modules/organs/organ_external.dm
  code/modules/power/singularity/singularity.dm
  code/modules/power/tesla/energy_ball.dm
  code/modules/projectiles/ammunition/energy.dm
  code/modules/projectiles/effects.dm
  code/modules/projectiles/firing.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/energy/temperature.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  code/modules/scrap/scrap_light.dm
  icons/effects/projectiles.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
  maps/boxstation/boxstation.dmm
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#4638 Фикс задержки перед войной
  code/game/gamemodes/nuclear/nuclear_challenge.dm
  code/game/machinery/computer/syndicate_shuttle.dm
  code/game/machinery/droppod.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/devices/gateway_locker.dm
Labels: Fix, Test Merge Candidate

#4665 fix cryo dupe
  code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Balance, Test Merge Candidate

#4666 Fifth law, preventing a removal from crew exploit
  code/datums/ai_laws.dm
  code/game/machinery/computer/ai_core.dm
  code/game/objects/items/weapons/AI_modules.dm
Labels: Balance, Test Merge Candidate

#4674 Shotgun ammo sprites
  code/modules/projectiles/ammunition/boxes.dm
  icons/obj/ammo.dmi
Labels: Sprites, Test Merge Candidate

#4694 запрещает писать анонсы с реквест консоли криминалиста
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#4664 New fire extinguisher sprites
  code/game/gamemodes/objective.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/extinguisher.dm
  code/modules/reagents/reagent_containers/extinguisher.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/closet.dmi
  icons/obj/items.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Sprites

#4639 Assistants now have no time restriction.
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
Labels: Balance, Test Merge Candidate

#4687 shock_sound
  code/modules/mob/living/carbon/carbon.dm
  sound/effects/electric_shock.ogg
Labels: Sound, Test Merge Candidate

#4700 Борги могут разбирать компьютеры
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/computer/robot.dm
Labels: Revert / Removal, Test Merge Candidate

#4703 Починка разделения щупалец скреллов по полу
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/character menu/general.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
Labels: Fix, Test Merge Candidate

#4704 Прячем ненужные переменные при создании персонажа
  code/__DEFINES/flags.dm
  code/modules/client/character menu/general.dm
  code/modules/mob/living/carbon/species.dm
Labels: Test Merge Candidate, Tweak

#4667 Logs, last part. JS error handler refactoring, some fixes and misc
  code/__DEFINES/logging.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/logging.dm
  code/_globalvars/logging.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/garbage.dm
  code/datums/browser.dm
  code/game/world.dm
  code/modules/admin/host_announcements.dm
  code/modules/admin/verbs/custom_event.dm
  code/modules/client/asset_cache.dm
  code/modules/client/client procs.dm
  code/modules/error_handler/error_handler.dm
  code/modules/error_handler_js/error_handler.dm
  code/modules/error_handler_js/error_handler.js
  code/modules/nano/nanoui.dm
  config/example/config.txt
Labels: Test Merge Candidate

#4719 Спу не получают урон который менее суммы 1
  code/modules/organs/external/flesh.dm
  code/modules/organs/external/robotic.dm
Labels: Tweak

#4720 Возвращаем инхенды Стечкина и Стан-револьвера
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
Labels: Fix

#4717 Перекраска CПУ
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/external/ipc.dm
  icons/mob/human_races/r_machine.dmi
Labels: Sprites, Test Merge Candidate, Tweak

#4738 pyrosound
  code/modules/projectiles/ammunition/energy.dm
  sound/weapons/pyrometr_shot.ogg
Labels: Sound

#4729 Убил спам зажигалкой
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: Tweak

#4536 The doors
  code/datums/wires/airlock.dm
  code/game/gamemodes/shadowling/shadowling_abilities.dm
  code/game/machinery/doors/airlock.dm
  code/game/turfs/simulated/walls.dm
  icons/obj/doors/airlocks/centcom/centcom.dmi
  icons/obj/doors/airlocks/centcom/overlays.dmi
  icons/obj/doors/airlocks/external/external.dmi
  icons/obj/doors/airlocks/external/overlays.dmi
  icons/obj/doors/airlocks/hatch/centcom.dmi
  icons/obj/doors/airlocks/hatch/maintenance.dmi
  icons/obj/doors/airlocks/hatch/overlays.dmi
  icons/obj/doors/airlocks/highsec/highsec.dmi
  icons/obj/doors/airlocks/highsec/overlays.dmi
  icons/obj/doors/airlocks/multi_tile/multi_tile.dmi
  icons/obj/doors/airlocks/multi_tile/overlays.dmi
  icons/obj/doors/airlocks/station/atmos.dmi
  icons/obj/doors/airlocks/station/bananium.dmi
  icons/obj/doors/airlocks/station/command.dmi
  icons/obj/doors/airlocks/station/diamond.dmi
  icons/obj/doors/airlocks/station/engineering.dmi
  icons/obj/doors/airlocks/station/freezer.dmi
  icons/obj/doors/airlocks/station/gold.dmi
  icons/obj/doors/airlocks/station/maintenance.dmi
  icons/obj/doors/airlocks/station/medical.dmi
  icons/obj/doors/airlocks/station/mining.dmi
  icons/obj/doors/airlocks/station/neutral.dmi
  icons/obj/doors/airlocks/station/overlays.dmi
  icons/obj/doors/airlocks/station/phoron.dmi
  icons/obj/doors/airlocks/station/public.dmi
  icons/obj/doors/airlocks/station/research.dmi
  icons/obj/doors/airlocks/station/sandstone.dmi
  icons/obj/doors/airlocks/station/science.dmi
  icons/obj/doors/airlocks/station/security.dmi
  icons/obj/doors/airlocks/station/silver.dmi
  icons/obj/doors/airlocks/station/uranium.dmi
  icons/obj/doors/airlocks/station/virology.dmi
  icons/obj/doors/airlocks/station2/glass.dmi
  icons/obj/doors/airlocks/station2/overlays.dmi
  icons/obj/doors/airlocks/vault/overlays.dmi
  icons/obj/doors/airlocks/vault/vault.dmi
Labels: Sprites, Tweak

#4749 Все A in B в условиях с приоритетом
  code/__DEFINES/misc.dm
  code/game/dna/dna_modifier.dm
  code/game/dna/genes/gene.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/revolution/rp_revolution.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/communications.dm
  code/game/mecha/mecha.dm
  code/game/mecha/working/ripley.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/implants/mindshield.dm
  code/game/objects/structures/transit_tubes.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/assembly/mousetrap.dm
  code/modules/client/character menu/quirks.dm
  code/modules/client/client procs.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/clothing.dm
  code/modules/economy/Accounts_DB.dm
  code/modules/economy/EFTPOS.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/organs/organ_external.dm
  code/modules/paperwork/stamps.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/alien.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/targeting.dm
  code/modules/reagents/reagent_types/Chemistry-Core.dm
  code/modules/reagents/reagent_types/Chemistry-Foods.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/research/xenoarchaeology/finds/finds_special.dm
  code/modules/shieldgen/shield_capacitor.dm
  code/modules/shieldgen/shield_gen.dm
Labels: Refactor

#4696 hydrogen tank for phoron researchers
  code/modules/atmospheric/machinery/portable/canister.dm
  icons/obj/atmos.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#4742 recycler_sound
  code/modules/scrap/scrap_beacon.dm
  code/modules/scrap/scrap_dropholder.dm
  sound/effects/scrap_fall.ogg
  sound/machines/scrap_beacon_start.ogg
Labels: Sound, Test Merge Candidate

#4340 New disappear effect
  code/__HELPERS/icons.dm
  code/datums/datumvars.dm
  code/game/objects/effects/decals/remains.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/monkey/death.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/silicon/death.dm
  code/modules/mob/living/silicon/robot/death.dm
  icons/effects/blood.dmi
  icons/effects/effects.dmi
Labels: Sprites, Test Merge Candidate

#4679 Add singularity spawn effect
  code/__DEFINES/_planes+layers.dm
  code/modules/power/singularity/generator.dm
  code/modules/power/singularity/singularity.dm
  icons/effects/singularity_effect.dmi
Labels: Sprites, Test Merge Candidate

#4715 Замена спрайтов зажигалок
  icons/obj/items.dmi
Labels: Sprites, Test Merge Candidate

#4732 Фикс телепортации в стену
  code/datums/helper_datums/teleport.dm
  code/datums/spells/ethereal_jaunt.dm
  code/game/gamemodes/shadowling/shadowling_abilities.dm
  code/game/objects/effects/portals.dm
  code/game/turfs/turf.dm
Labels: Fix, Test Merge Candidate, Tweak

#4740 Обновление спрайтов таблеток
  icons/obj/chemical.dmi
Labels: Sprites, Test Merge Candidate

#4744 Автолат на системе Spitesheet
  code/game/machinery/autolathe.dm
  code/modules/client/asset_cache.dm
Labels: Test Merge Candidate, Tweak

#4745 add ability to remove your bandages
  code/modules/mob/living/carbon/human/human.dm
Labels: Test Merge Candidate, Tweak

#4753 firesound
  code/modules/mob/living/living_defense.dm
  sound/effects/extinguish_mob.ogg
Labels: Sound, Test Merge Candidate

#4755 ghostly!
  icons/mob/mob.dmi
Labels: Sprites, Test Merge Candidate

#4747 Доступ к выборе нимфы дионы из настроек персонажа
  code/modules/client/character menu/roles.dm
Labels: Fix
