Repository TauCetiStation/TauCetiClassic, pull requests merged in 2020-04, with the labels that each got.

#4889 adds syndicate heavy rig
  code/game/machinery/computer/intruder_station.dm
  code/game/objects/items/devices/modkit.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  icons/mob/head.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites, Test Merge Candidate

#4905 Управление финансами с помощью PDA
  code/_onclick/click.dm
  code/controllers/subsystem/jobs.dm
  code/datums/datacore.dm
  code/defines/obj.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/economy/Accounts.dm
  nano/templates/pda.tmpl
Labels: Feature, Test Merge Candidate

#4918 FixCloth
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/gloves/stungloves.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  icons/mob/species/vox/eyes.dmi
  icons/mob/species/vox/gloves.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/masks.dmi
  icons/mob/species/vox/shoes.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/species/vox/uniform.dmi
Labels: Fix, Sprites, Test Merge Candidate, Tweak

#4947 Респрайт мусорки
  icons/obj/pipes/disposal.dmi
Labels: Sprites

#4949 Респрайт пожарного топора
  icons/mob/back.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/weapons.dmi
Labels: Sprites

#4958 Респрайт футболок
  icons/mob/human.dmi
  icons/mob/human_undershirt.dmi
Labels: Sprites

#4966 Hair
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#4970 Виноградный сок
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Fix

#4832 Передел спрайтов файла tools
  code/game/objects/items/weapons/tools.dm
  code/modules/customitems/item_defines.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/custom_items.dmi
  icons/obj/flamethrower.dmi
  icons/obj/tools.dmi
Labels: Sprites, Test Merge Candidate

#4915 Xenos Hair
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#4944 Фикс предметов в крио
  code/game/machinery/cryopod.dm
Labels: Fix

#4945 Turning the tides of battle.
  code/modules/cargo/packs.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Balance, Map Edit

#4989 Исправления научного скафандра и скафандра переработчика.
  code/modules/mining/mining_fabricator/mining_research.dm
  code/modules/research/research.dm
  icons/obj/clothing/hats.dmi
Labels: Sprites, Tweak

#4993 Атмос на шахтёрском аванпосте
  maps/asteroid/asteroid.dmm
Labels: Map Edit

#4998 Хотфикс пикселя у футболок
  icons/mob/human_undershirt.dmi
Labels: Sprites

#4946 combat shotgun re-sprite
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/mob/back.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
Labels: Sprites, Test Merge Candidate

#4929 Затемнение тёмного пола чтобы он был достаточно тёмный для другого тёмного пола
  icons/turf/floors.dmi
  maps/boxstation/boxstation.dmm
Labels: Sprites

#4973 Makes taking items out of medkits and toolbelts less annoying
  code/game/objects/items/weapons/storage/storage_ui/default.dm
Labels: Test Merge Candidate, Tweak

#4994 Раздевалка на Велосити
  maps/centcom/centcom.dmm
Labels: Map Edit, Test Merge Candidate

#5003 хотфикс ригов синдиката на ксеносах
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/species/vox/suit.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  icons/obj/clothing/species/vox/suits.dmi
Labels: Sprites

#4999 Уменьшение огнеопасности фороновых дверей
  code/game/objects/structures/mineral_doors.dm
Labels: Tweak

#4809 nuke abuse no more
  code/game/gamemodes/nuclear/nuclearbomb.dm
Labels: Fix

#4990 Prototype quality is synced between devices.
  code/game/mecha/mech_fabricator.dm
  code/modules/research/designs.dm
  code/modules/research/protolathe.dm
  code/modules/research/research.dm
Labels: Fix, Test Merge Candidate

#4974 Гардероб воксов снова увеличен
  icons/mob/species/vox/eyes.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/masks.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/species/vox/uniform.dmi
Labels: Sprites, Test Merge Candidate

#5032 Респрайт нижнего белья
  icons/mob/human.dmi
  icons/mob/human_undershirt.dmi
Labels: Sprites

#5042 Хот фикс респрайта инструментов
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Fix, Sprites

#5041 Remove target overlay
  code/game/objects/items/shooting_range.dm
Labels: Fix, Revert / Removal

#4072 Добавляет Синдикатский язык.
  code/datums/uplinks_items.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/objects/items/weapons/manuals.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/mob/language.dm
  icons/obj/library.dmi
Labels: Feature, Sprites

#5057 Язык жестов без префикса для немых
  code/modules/mob/living/carbon/human/say.dm
Labels: Tweak

#5037 ИИ трейтор, кнопка для ТП и небольшое изменение хака
  code/datums/mind.dm
  code/game/machinery/computer/robot.dm
Labels: Fix

#5069 Рефактор гипоспреев
  code/game/objects/items/weapons/autoinjectors.dm
  code/game/objects/items/weapons/medical.dm
  code/modules/customitems/item_defines.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Code Improvements

#5024 Респрайт инженерных разгрузок и фикс одежды
  icons/mob/accessory.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/clothing/accessory.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#5065 Твик Риеталина
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Labels: Tweak

#5000 СПУ не могут стать трэллами или быть оглушены взглядом
  code/game/gamemodes/shadowling/shadowling_abilities.dm
Labels: Balance

#4920 Из загрузки в кэш убраны картинки для game_kit и space_ninja
  code/controllers/subsystem/assets.dm
  code/game/gamemodes/events/ninja_equipment.dm
  code/game/machinery/newscaster.dm
  code/game/objects/game_kit.dm
  code/modules/client/asset_cache.dm
  code/modules/paperwork/paper.dm
Labels: Test Merge Candidate

#5087 Хотфикс белого пикселя у воксов
  icons/mob/human_face.dmi
Labels: Fix, Sprites

#4870 Добавление говорящего посоха каппелану
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/misc.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/objects/items/weapons/chaplain_weapons.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/simple_animal/shade.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/mob.dmi
  icons/obj/wizard.dmi
  taucetistation.dme
Labels: Feature, Sprites

#4978 Добавление больше смысла прототипам
  code/game/objects/items/weapons/defibrillator.dm
  code/game/objects/items/weapons/power_cells.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/research/prototipify.dm
Labels: Tweak

#5066 Новые силовые установки
  icons/obj/machines/field_generator.dmi
  icons/obj/singularity.dmi
Labels: Sprites

#5092 should-be fix for xenos languages localization
  code/modules/mob/living/say.dm
Labels: Fix

#3172 Waddling при ходьбе у клоуна
  code/datums/components/waddle.dm
  code/game/objects/items/weapons/clown_items.dm
  code/modules/clothing/shoes/miscellaneous.dm
  taucetistation.dme
Labels: Balance, Pinned, Tweak

#5096 Sycode spaces between words
  code/modules/mob/language.dm
Labels: Tweak

#5098 Хотфикс спрайтов ватлера
  icons/obj/singularity.dmi
Labels: Sprites

#5101 Хот(?)фикс предметов в оберточной бумаге
  code/modules/recycling/sortingmachinery.dm
Labels: Fix

#5010 Ребаланс перидаксона, добавление Декстрометорфана
  code/datums/diseases/advance/symptoms/cough.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  code/modules/virus2/effect.dm
Labels: Balance

#4892 Bonefixing reagent & uplink bonefixing injector
  code/datums/uplinks_items.dm
  code/game/objects/items/weapons/autoinjectors.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  icons/obj/syringe.dmi
Labels: Sprites

#4991 Фикс ленты
  code/game/gamemodes/changeling/headcrab.dm
  code/game/objects/items/weapons/tape.dm
Labels: Feature, Fix

#5018 Ремап гражданского сектора
  maps/boxstation/boxstation.dmm
  nano/images/nanomap_exodus_1.png
Labels: Map Edit, Test Merge Candidate

#4841 Респрайт скафандра космического
  code/__DEFINES/clothing.dm
  code/__DEFINES/flags.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/Skafandr_kosmicheskiy.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/tajaran/suit_fat.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/species/unathi/suit_fat.dmi
  icons/mob/suit.dmi
  icons/mob/suit_fat.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites, Test Merge Candidate

#5111 Godly additions
  code/__DEFINES/components.dm
  code/datums/components/bound.dm
  code/game/atoms_movable.dm
  code/game/objects/items/weapons/chaplain_weapons.dm
  code/modules/mob/living/simple_animal/shade.dm
  taucetistation.dme
Labels: Feature

#5115 Heels can now poke eyes out.
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/clothing/shoes/miscellaneous.dm
Labels: Feature

#4822 Свечение монитора у спу и выключение его, удаление смены экрана через операцию
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/external/ipc.dm
  code/modules/surgery/face.dm
  icons/mob/human_face.dmi
  icons/mob/human_races/r_machine.dmi
Labels: Revert / Removal, Sprites, Tweak

#5103 liquid_eat_sound
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/wildwest.dmm
  maps/centcom/centcom.dmm
  maps/templates/space_structures/robostation.dmm
Labels: Map Edit, Sound

#5119 Prayerchanges
  code/_globalvars/lists/mob.dm
  code/game/objects/items/weapons/chaplain_weapons.dm
  code/game/say.dm
  code/modules/admin/verbs/pray.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  icons/effects/effects.dmi
  taucetistation.dme
Labels: Feature, Sprites, Tweak

#5121 Gods can't crawl into disposal bins no longer.
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/recycling/disposal.dm
Labels: Fix

#5122 Ghosts now see prays.
  code/modules/admin/verbs/pray.dm
Labels: Feature

#5110 Gamma Fix
  maps/gamma/gamma.dmm
Labels: Map Edit, Test Merge Candidate

#5124 Golodek for gamma
  maps/templates/holodeck/theatre.dmm
Labels: Map Edit

#5126 Фиксы плитки в медбее и труб Gammastation
  maps/gamma/gamma.dmm
Labels: Map Edit

#5128 Быстрые фиксы камер
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#5137 mouse opacity on human overlays
  code/game/objects/items/devices/whistle.dm
  code/modules/admin/verbs/pray.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/say.dm
Labels: Tweak

#5139 fix #5132
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#5140 fake death changelings can pray
  code/modules/admin/verbs/pray.dm
Labels: Tweak

#5142 Moghes playlist name fixed; New skrellian vaporfunk playlist added
  code/modules/media/jukebox.dm
Labels: Sound

#5130 Temp-banish god out of the staff
  code/game/objects/items/weapons/chaplain_weapons.dm
Labels: Fix

#5151 Детектив Бипски, вы разжалованы!
  code/game/machinery/bots/secbot.dm
Labels: Tweak

#4854 Фикс доступа у наномедов
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#5153 Респрайт мусорки (фикс лампочек)
  icons/obj/pipes/disposal.dmi
Labels: Sprites

#5118 Твики ремапа гражданки Улианза
  code/game/area/station_areas.dm
  icons/turf/areas.dmi
  maps/boxstation/boxstation.dmm
  nano/images/nanomap_exodus_1.png
Labels: Map Edit

#4027 Изменение начального оружия нюкеров, добавление С20-r в аплинк нюке, добавление новых типов патронов
  code/datums/uplinks_items.dm
  code/game/gamemodes/events/cellular_biomass/biome_nanite.dm
  code/game/gamemodes/heist/heist_prices.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/machinery/computer/tc_station.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/obj/ammo.dmi
Labels: Experimental, Feature, Sprites, Test Merge Candidate

#5155 Tiny Chaplain refactor.
  code/__DEFINES/religion.dm
  code/_globalvars/misc.dm
  code/controllers/subsystem/ticker.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/admin/verbs/pray.dm
  code/modules/library/lib_machines.dm
  code/modules/religion/bible_info.dm
  code/modules/religion/religion.dm
  icons/obj/storage.dmi
  taucetistation.dme
Labels: Feature, Sprites

#5033 Модификация костра
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/scrap/scrap_light.dm
Labels: Feature

#5156 Posters refactor
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/decals/posters/bs12.dm
  code/game/objects/effects/decals/posters/tgposters.dm
  icons/obj/contraband.dmi
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
  maps/templates/space_structures/listening_post.dmm
  maps/templates/space_structures/robostation.dmm
Labels: Feature, Map Edit, Revert / Removal, Sprites

#5157 Traitor tweaks
  code/datums/uplinks_items.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/projectile/revolver.dm
Labels: Feature

#5158 Pews
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/structures/chapel.dm
  code/modules/religion/bible_info.dm
  code/modules/religion/religion.dm
  icons/obj/structures/chapel.dmi
  maps/boxstation/boxstation.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Sprites

#5162 Исправление в работе крио
  code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
Labels: Tweak

#5164 Chaplain's staff God speaks in languages
  code/modules/mob/hear_say.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Feature

#5146 Зарплаты
  code/controllers/subsystem/economy.dm
  code/controllers/subsystem/jobs.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/structures/watercloset.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/economy_misc.dm
  nano/templates/identification_computer.tmpl
  nano/templates/pda.tmpl
  taucetistation.dme
Labels: Feature, Test Merge Candidate

#5165 Ремап церкви под будущие изменения капеллана
  maps/boxstation/boxstation.dmm
  nano/images/nanomap_exodus_1.png
Labels: Map Edit

#5161 Обновление футболок
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#5175 Заменяю /turf/simulated на /turf/simulated/floor/plating
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#5176 Фикс сломанной трубы и зоны у КМ
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#5171 Замена зеленого креста в НаноМеде на голубой
  icons/obj/vending.dmi
Labels: Sprites

#5177 minor changes to bar, locker room and private office
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#5182 Extinguishers are "closed" containers by default
  code/modules/reagents/reagent_containers/extinguisher.dm
Labels: Fix

#5180 God features: Crew manifest, spacemove, staff pulling
  code/modules/mob/living/simple_animal/shade.dm
Labels: Feature, Fix

#5187 Фиксы ксенобиологии
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#5190 Clown shoes waddle only when in proper slot
  code/modules/clothing/shoes/miscellaneous.dm
Labels: Fix

#5191 Jolly Gravedigger shoes: Waddle when pulling coffins
  code/__DEFINES/components.dm
  code/game/machinery/vending.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/mob/mob.dm
Labels: Feature

#5181 Изменен метаболизм скреллов и их взаимодействие с ядами.
  code/__DEFINES/flags.dm
  code/__DEFINES/mob.dm
  code/controllers/subsystem/quirks.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
Labels: Tweak

#5194 Фикс вытаскивания ПДА из покрасчика
  code/game/machinery/PDApainter.dm
Labels: Fix

#5200 Удаляю мусор в стене
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#5198 All mobs get pray animation, with almost 0 checks
  code/modules/admin/verbs/pray.dm
  code/modules/mob/living/carbon/brain/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/ian/emote.dm
  code/modules/mob/living/carbon/metroid/emote.dm
  code/modules/mob/living/carbon/monkey/emote.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/emote.dm
  code/modules/mob/living/carbon/xenomorph/larva/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
Labels: Tweak

#5205 Proper bound component logic, lessening entities
  code/__DEFINES/components.dm
  code/datums/components/bound.dm
Labels: Code Improvements

#5197 Исправление бага у бармена
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Fix

#5206 waddle component improvements.
  code/__DEFINES/components.dm
  code/datums/components/waddle.dm
Labels: Code Improvements, Tweak

#5143 Халкоизменения
  code/__DEFINES/genetics.dm
  code/datums/mind.dm
  code/datums/weather/weather_types.dm
  code/game/dna/genes/powers.dm
  code/game/machinery/computer/computer.dm
  code/game/objects/fitness.dm
  code/game/turfs/simulated/walls.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hulk.dm
  code/modules/mob/living/simple_animal/hulk_powers.dm
  code/modules/organs/external/flesh.dm
  code/modules/projectiles/projectile/beams.dm
  sound/effects/hulk_attack.ogg
  sound/effects/hulk_hit_airlock.ogg
  sound/effects/hulk_hit_computer.ogg
  sound/effects/hulk_hit_wall.ogg
  sound/effects/scary_honk.ogg
Labels: Feature, Sound, Test Merge Candidate
