Repository TauCetiStation/TauCetiClassic, pull requests merged in 2020-01, with the labels that each got.

#4212 Изменение доступа ксеносов к профам
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Test Merge Candidate, Tweak

#4391 Даёт парамедикам доступ к аварийным створкам.
  code/game/machinery/doors/firedoor.dm
Labels: Tweak

#4393 Выключение крю и рестарт голосвание до старта раунда
  code/controllers/master.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/voting.dm
Labels: Tweak

#4402 Добавление звуков для ручки
  code/_globalvars/lists/sound.dm
  code/modules/paperwork/paper.dm
  sound/effects/writing/keyboard1.ogg
  sound/effects/writing/keyboard2.ogg
  sound/effects/writing/keyboard3.ogg
  sound/effects/writing/keyboard4.ogg
  sound/effects/writing/keyboard5.ogg
  sound/effects/writing/pda1.ogg
  sound/effects/writing/pda2.ogg
  sound/effects/writing/pda3.ogg
  sound/effects/writing/pda4.ogg
  sound/effects/writing/pda5.ogg
  sound/effects/writing/pen1.ogg
  sound/effects/writing/pen2.ogg
  sound/effects/writing/pen3.ogg
Labels: Sound, Test Merge Candidate

#4430 Нерф частного детектива
  code/game/jobs/job/assistant.dm
Labels: Balance

#4428 EMP имплат теперь лимитируется корректно
  code/game/objects/items/weapons/implants/implant.dm
Labels: Fix

#4426 Больше нельзя рисовать руны, стоя на столе.
  code/game/gamemodes/cult/ritual.dm
Labels: Fix

#4359 rp-revolution tweak
  code/__DEFINES/objectives.dm
  code/game/gamemodes/abduction/abduction.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/objective.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/revolution/rp_revolution.dm
  taucetistation.dme
Labels: Experimental, Test Merge Candidate

#4399 New rnd area sprites
  code/game/area/station_areas.dm
  icons/turf/areas.dmi
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Sprites

#4410 Девайс нюки для объявления войны доступен без админов
  code/game/gamemodes/nuclear/nuclear_challenge.dm
  code/game/machinery/computer/intruder_station.dm
  maps/centcom/centcom.dmm
Labels: Map Edit, Tweak

#4411 Одинаковые имена теперь работают корректно в манифесте
  code/defines/obj.dm
  code/game/machinery/computer/skills.dm
Labels: Fix, Test Merge Candidate

#4420 Patreon
  code/controllers/configuration.dm
  code/game/world.dm
  code/modules/client/client procs.dm
  code/modules/ext_scripts/shell.dm
  config/example/config.txt
Labels: Tools

#4431 Sandbox sever mode, R_LOG changes
  code/__DEFINES/varedit.dm
  code/controllers/configuration.dm
  code/datums/datumvars.dm
  code/modules/admin/verbs/massmodvar.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/client/client procs.dm
  config/example/config.txt
Labels: Admin, Experimental

#4422 Генерация имени позитронки и нормальный доступ в бинарный чат
  code/modules/mob/living/carbon/brain/posibrain.dm
  code/modules/mob/living/silicon/say.dm
Labels: Fix, Test Merge Candidate

#4427 Пустой рамен выдает корректное сообщение
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Fix, Test Merge Candidate

#4438 extinguisher off
  code/modules/reagents/reagent_containers/extinguisher.dm
Labels: Fix

#4440 делает общественные наномеды действительно общественными
  code/game/machinery/vending.dm
Labels: Fix

#4446 fix debrain
  code/modules/organs/organ_external.dm
Labels: Fix

#4449 Fixing a bunch of wizard-tophat related bugs
  code/datums/spells/summon_item.dm
  code/game/objects/random/random_cloth.dm
  code/modules/clothing/head/wiz_tophat.dm
Labels: Fix

#4455 Фикс Cannot execute null.ClientLogout()
  code/modules/client/client procs.dm
Labels: Fix

#4432 Оповещения именем ИИ прибытия шатла на станцию
  code/game/machinery/computer/arrival_shuttle.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Feature, Test Merge Candidate

#4457 Fix dreamchecker
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/math.dm
  code/__HELPERS/game.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/unsorted.dm
  code/_compile_options.dm
  code/_onclick/hud/fullscreen.dm
  code/controllers/subsystem/mapping.dm
  code/defines/procs/announces.dm
  code/game/machinery/alarm.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/bots/secbot.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/door_control.dm
  code/game/machinery/newscaster.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/economy/Events.dm
  code/modules/economy/economy_misc.dm
  code/modules/library/lib_items.dm
  code/modules/media/mediamanager.dm
  code/modules/mining/monsters.dm
  code/modules/mob/living/carbon/alien/effects/aliens.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/projectiles/guns/plasma/plasma.dm
  code/modules/projectiles/targeting.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/_chemistry.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/scrap/scrap_turfs.dm
  code/modules/supermatter/supermatter.dm
  taucetistation.dme
Labels: Code Improvements

#4456 "Водяной пистолет стал быстрее"
  code/modules/reagents/reagent_containers/spray.dm
Labels: Balance

#4463 Hulk skin color fix
  code/__DEFINES/colors.dm
Labels: Fix

#4465 Fixes sechud displaying agent card's assignment as an unknown profession.
  code/game/jobs/access.dm
Labels: Fix

#4468 fixed nades
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
Labels: Fix

#4471 Runtime in demo.dm,218: Cannot read null.gc_destroyed
  code/controllers/subsystem/demo.dm
Labels: Fix

#4472 Исправлен вывод проверки своего здоровья
  code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#4464 Rolling Start DAYTONA 500
  icons/obj/rollerbed.dmi
Labels: Sprites, Test Merge Candidate

#4490 Fixes Runtime in fuel.dm, line 43: undefined variable /obj/effect/decal/chempuff/var/crawling
  code/game/objects/effects/decals/Cleanable/fuel.dm
Labels: Fix

#4489 Fixes Runtime in braincore.dm, line 12: undefined proc or verb /mob/living/carbon/slime/orange/get bodypart().
  code/_onclick/item_attack.dm
  code/modules/surgery/braincore.dm
  code/modules/surgery/generic.dm
Labels: Fix

#4370 Немного новых логов
  code/game/objects/items/weapons/dna_injector.dm
  code/modules/assembly/igniter.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/proximity.dm
  code/modules/assembly/signaler.dm
  code/modules/assembly/timer.dm
  code/modules/assembly/voice.dm
Labels: Admin

#4494 Поправлен сбор в ботантке
  code/game/machinery/hydroponics.dm
Labels: Fix

#4493 Убрана орбита обзервера со статпанели
  code/_onclick/observer.dm
Labels: Fix

#4459 Респрайт трёх настенных шкафчиков.
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/crates_lockers/walllocker.dm
  icons/obj/closet.dmi
  icons/obj/vending.dmi
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit, Sprites, Test Merge Candidate

#4474 Исправлен рецепт кебаба
  code/datums/recipe.dm
  code/modules/food/recipes_grill.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Fix, Test Merge Candidate

#4477 Barber Sprites Update
  icons/obj/items.dmi
Labels: Sprites, Test Merge Candidate

#4481 Звуки для хим.раздатчика
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Sound, Test Merge Candidate

#4483 Таблицы и фотокопирка
  code/modules/paperwork/photocopier.dm
  icons/obj/bureaucracy.dmi
Labels: Fix, Sprites

#4501 No more vacuum flask. Only shaker.
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#4361 Возвращение бассейна в качалку. Частичная перепланировка дорм
  code/game/objects/structures/watercloset.dm
  code/game/turfs/simulated/floor_types.dm
  icons/misc/beach.dmi
  maps/boxstation/boxstation.dmm
  sound/effects/water_turf_entered_mob.ogg
  sound/effects/water_turf_entered_obj.ogg
  sound/effects/water_turf_exited_mob.ogg
Labels: Map Edit, Sound, Sprites, Test Merge Candidate

#4460 Список режимов в описании к голосованию
  code/controllers/configuration.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/voting.dm
  code/game/gamemodes/autotraitor/autotraitor.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/heist/heist.dm
  code/game/gamemodes/heist/heist_old.dm
  code/game/gamemodes/infestation/infestation.dm
  code/game/gamemodes/malfunction/malfunction.dm
  code/game/gamemodes/meme/meme.dm
  code/game/gamemodes/ninja/ninja.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/shadowling/shadowling.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: Feature, Test Merge Candidate

#4478 Sleeping status effect.
  code/__DEFINES/status_effects.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/alert.dm
  code/datums/status_effects/debuffs.dm
  code/game/gamemodes/abduction/abduction_gear.dm
  code/game/gamemodes/abduction/machinery/experiment.dm
  code/game/gamemodes/heist/fulton.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/weapons/surgery_limbattachment.dm
  code/game/objects/structures.dm
  code/game/objects/structures/survivor_cryopod.dm
  code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/blob/blob.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/alien/humanoid/update_icons.dm
  code/modules/mob/living/carbon/alien/larva/emote.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/carbon/ian/emote.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/logout.dm
  code/modules/mob/living/parasite/meme.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/transform_procs.dm
  code/modules/organs/external/flesh.dm
  code/modules/reagents/reagent_types/Chemistry-Core.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
  code/modules/research/xenoarchaeology/finds/finds_special.dm
  code/modules/virus2/effect.dm
Labels: Refactor, Test Merge Candidate

#4487 Новый вид штампов на бумаге
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/EFTPOS.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/photocopier.dm
  code/modules/paperwork/stamps.dm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Feature, Map Edit, Test Merge Candidate

#4500 Some fax things
  code/game/machinery/fax.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Admin, Test Merge Candidate

#4506 Varset callback
  code/__DEFINES/_util.dm
  code/__DEFINES/callbacks.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/portable_turret.dm
  code/game/objects/items/weapons/tape.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
  code/modules/paperwork/paper.dm
  code/modules/power/tesla/coil.dm
  code/modules/virus2/curer.dm
  taucetistation.dme
Labels: Code Improvements, Test Merge Candidate

#4507 Замена старых методов добавления оверлеев на новый
  code/game/objects/effects/foam.dm
  code/modules/mob/living/living.dm
  code/modules/mob/typing_indicator.dm
Labels: Code Improvements, Test Merge Candidate

#4514 показываются коммента в статье
  code/game/machinery/newscaster.dm
Labels: Tweak

#4515 Госты и остальные не могут юзать аутопси сканер
  code/modules/detectivework/autopsy.dm
Labels: Fix

#4520 OOC color normalization
  code/__HELPERS/icons.dm
  code/__HELPERS/normalize.dm
  code/game/verbs/ooc.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preferences_savefile.dm
Labels: Tweak

#4118 Beating up a clown became way funnier.
  code/modules/organs/external/flesh.dm
  sound/effects/squeak.ogg
Labels: Sound, Test Merge Candidate

#4392 Фикс шаттлов
  code/controllers/subsystem/shuttles.dm
  code/game/area/shuttle_areas.dm
  code/game/machinery/computer/arrival_shuttle.dm
  code/modules/locations/shuttles/mine_sci_shuttle.dm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit, Test Merge Candidate, Tweak

#4498 Стилистические правки отправки на мостик
  code/game/machinery/fax.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/bridge/chat_bridge.dm
Labels: Code Improvements, Test Merge Candidate

#4504 fix various chemicals
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
Labels: Balance, Fix, Test Merge Candidate

#4505 Вокс в стелсе невидим для: курсора, ПКМ, трекера ИИ, датчика слежения
  code/game/machinery/camera/motion.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/mob/hear_say.dm
Labels: Test Merge Candidate, Tweak

#4508 thrower is not longer a variable, since it is contained in throwingdatum.
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/throwing.dm
  code/defines/obj/weapon.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/events/ninja_equipment.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/shieldgen.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/ashtray.dm
  code/game/objects/items/devices/biocan.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/structures/window.dm
  code/game/turfs/turf.dm
  code/modules/assembly/mousetrap.dm
  code/modules/holidays/new_year/snow.dm
  code/modules/mining/monsters.dm
  code/modules/mob/living/carbon/alien/effects/aliens.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/alien/special/facehugger/facehugger.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/living_defense.dm
  code/modules/power/lighting.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/research/xenoarchaeology/genetics/prehistoric_plants.dm
  code/modules/telesci/bscrystal.dm
Labels: Code Improvements, Test Merge Candidate

#4511 Новые звуки для фонариков, флейров, факелов
  code/game/machinery/floodlight.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/mining/mine_items.dm
  code/modules/power/lighting.dm
  code/modules/scrap/scrap_light.dm
  sound/effects/light-break.ogg
  sound/items/buttonclick.ogg
  sound/items/flare.ogg
  sound/items/flashlight.ogg
  sound/items/lantern.ogg
  sound/items/penlight.ogg
  sound/items/torch.ogg
  sound/machines/floodlight.ogg
Labels: Sound, Test Merge Candidate

#4524 Pumps and Scrubbers resprite
  icons/atmos/vent_pump.dmi
  icons/atmos/vent_scrubber.dmi
Labels: Sprites, Test Merge Candidate

#4527 Открученный чеммастер и чемдиспенсер не работают
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Fix

#4528 Установлены округления для значения урона куклы
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Fix

#4529 Огнетушитель в мехе не выкидывает куклу
  code/game/mecha/equipment/tools/tools.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Fix

#4531 Перевод денег через банкомат восстановлен
  code/modules/economy/Accounts.dm
Labels: Fix

#4539 Heist fix
  code/game/gamemodes/heist/heist.dm
  code/game/gamemodes/heist/heist_old.dm
Labels: Fix

#4542 Запрещены голосования до запуска подсистем
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/voting.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Fix

#4526 Исправлены пропавшие панели вендоматов
  icons/obj/vending.dmi
Labels: Sprites

#4538 Новый плейлист в жукбокс.
  code/modules/media/jukebox.dm
Labels: Sound

#4534 Ризон мута корректно записывается в заметки игрока.
  code/modules/admin/verbs/randomverbs.dm
Labels: Admin, Fix

#4551 examine fixes
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix, Tweak

#4549 Малфа больше не разрывает если никто не поставил на него высший преференс
  code/controllers/subsystem/jobs.dm
Labels: Fix

#4419 добавляет легкую броню трейторам
  code/datums/uplinks_items.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/clothing/suits/armor.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites

#4546 Самоизвлечение головы из Biogel Can
  code/game/objects/items/devices/biocan.dm
Labels: Fix

#4562 CC stamps fix
  maps/centcom/centcom.dmm
Labels: Fix, Map Edit

#4543 Правки Power-fist
  code/game/objects/items/weapons/melee/powerfist.dm
  taucetistation.dme
Labels: Balance

#4571 Исправление несмываемой крови на предметах в инвентаре
  code/game/objects/items.dm
Labels: Fix

#4570 Мегафон для нюки
  maps/centcom/centcom.dmm
Labels: Map Edit

#4572 Fix overlay ops
  code/game/objects/effects/foam.dm
  code/modules/mob/living/silicon/robot/life.dm
Labels: Code Improvements

#4523 Небольшие правки в карго для инженерных заказов
  code/modules/cargo/packs.dm
Labels: Merge Ready, Tweak

#4573 Звук блюспейс транслокации
  code/game/sound.dm
  code/modules/anomaly/anomaly_bluespace.dm
Labels: Sound

#4581 Менторы больше не игнорируют лимит сервера по количеству игроков
  code/modules/client/client procs.dm
Labels: Admin

#4578 Логирование шприцов и таблеток при употреблении
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Admin

#4556 Borgi sound
  code/game/machinery/computer/robot.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/carbon/brain/posibrain.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/paperwork/silicon_photography.dm
  sound/effects/click_off.ogg
  sound/effects/click_on.ogg
  sound/effects/robot_locked.ogg
  sound/effects/robot_unlocked.ogg
  sound/effects/triple_beep.ogg
  sound/items/polaroid3.ogg
  sound/misc/robot_restart.ogg
Labels: Sound, Test Merge Candidate

#4568 Новые звуки для предметов с главного склада и не только
  code/game/objects/items.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/clothing/clothing.dm
  code/modules/library/lib_items.dm
  code/modules/paperwork/clipboard.dm
  code/modules/paperwork/folders.dm
  code/modules/power/cable.dm
  code/modules/reagents/reagent_containers/syringes.dm
  sound/items/misc/balloon_big-hit.ogg
  sound/items/misc/balloon_small-hit.ogg
  sound/items/misc/belt-slap.ogg
  sound/items/misc/book-slap.ogg
  sound/items/misc/folder-slap.ogg
  sound/items/misc/glove-slap.ogg
  sound/items/tools/cable-slap.ogg
  sound/items/tools/crowbar-hit.ogg
  sound/items/tools/device_big-hit.ogg
  sound/items/tools/device_small-hit.ogg
  sound/items/tools/screwdriver-stab.ogg
  sound/items/tools/tool-hit.ogg
  sound/items/tools/toolbox-hit.ogg
  sound/items/tools/wirecutters-cut.ogg
  sound/items/tools/wirecutters-pinch.ogg
Labels: Balance, Sound, Test Merge Candidate

#4601 cargotech access to navbeacon
  code/game/machinery/navbeacon.dm
Labels: Tweak
