Repository TauCetiStation/TauCetiClassic, pull requests merged in 2020-07, with the labels that each got.

#5745 sanity checking combatant locs
  code/_onclick/click.dm
  code/modules/unarmed_combat/combat_combo.dm
  code/modules/unarmed_combat/combos/combos.dm
Labels: Fix

#5679 Убирает give у боргов и самому себе
  code/modules/mob/living/carbon/give.dm
Labels: Fix

#5740 Возможность выбрать юбочную униформу
  code/datums/outfits/jobs/medical.dm
  code/datums/outfits/outfit.dm
  code/modules/client/character menu/general.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Tweak

#5687 Новая сварочная маска
  code/modules/customitems/item_defines.dm
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/custom_items.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
  maps/templates/space_structures/listening_post.dmm
Labels: Sprites

#5747 hit items with items only on harm
  code/_onclick/item_attack.dm
Labels: Tweak

#5755 AnotherGammaFix
  maps/gamma/gamma.dmm
Labels: Map Edit

#5762 СПУ теперь могут снимать лампочки без перчаток
  code/modules/power/lighting.dm
Labels: Tweak

#5713 Chapel resprite
  code/datums/wires/vending.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/random/random_cloth.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/cargo/packs.dm
  code/modules/client/character menu/loadout/loadout_accessories.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/jobs/civilian.dm
  icons/mob/accessory.dmi
  icons/mob/back.dmi
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/mask.dmi
  icons/mob/suit.dmi
  icons/mob/suit_fat.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/clothing/accessory.dmi
  icons/obj/clothing/accessory_overlay.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/storage.dmi
  icons/obj/vending.dmi
  maps/boxstation/boxstation.dmm
  maps/templates/space_structures/ghost_ship_2.dmm
Labels: Sprites

#5756 Удалена лишняя труба в изоляторе РнД
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#5772 goonplaque on gamma
  maps/gamma/gamma.dmm
Labels: Map Edit

#5769 evidence bag doesn't bug wabbajack hat out
  code/modules/clothing/head/wiz_tophat.dm
Labels: Fix

#5774 Поправил вёрстку настройки в Setup Character - general
  code/modules/client/character menu/global.dm
Labels: Fix

#5761 Фикс калибров резины.
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
Labels: Fix

#5753 К медицинскому шкафу добавлен доступ парамедика
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
Labels: Fix

#5744 Порт градиентных волос с PolarisSS13
  code/__HELPERS/mobs.dm
  code/game/machinery/barber.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/modules/client/character menu/general.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/gradient.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/organ_external.dm
  code/modules/surgery/limbs.dm
  icons/mob/hair_gradients.dmi
  taucetistation.dme
Labels: Feature, Sprites

#5686 Расширение доступа уборщика
  code/game/jobs/job/civilian.dm
Labels: Test Merge Candidate, Tweak

#5757 Реагент-диспенсеры круче
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: Tweak

#5789 AI preview and eyeobj.loc fixes
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/transform_procs.dm
Labels: Fix

#5796 Закрывает преференс окно при спавне
  code/modules/mob/dead/new_player/new_player.dm
Labels: Fix

#5798 locked check
  code/game/machinery/kitchen/smartfridge.dm
Labels: Fix

#5655 Переписывание синематика взрыва станции
  code/controllers/subsystem/ticker.dm
Labels: Fix

#5802 Фикс кол-ва ресурсов на научке
  maps/asteroid/asteroid.dmm
Labels: Fix, Map Edit

#5803 structures that break down break down only on harm and have cooldown
  code/game/gamemodes/events/cellular_biomass/cellular_structures.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor_assembly.dm
  code/game/machinery/droppod.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/coathanger.dm
  code/game/objects/structures/displaycase.dm
  code/game/objects/structures/window.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/locations/shuttles/shuttle_window.dm
  code/modules/scrap/scrap_light.dm
Labels: Fix, Tweak

#5787 Фикс невозможности спавна руды из банана
  code/modules/religion/rites.dm
  code/modules/religion/rites/misc.dm
  code/modules/religion/rites/spawn_item.dm
Labels: Tweak

#5806 robokey and aikey fix - добавлены проверки на mind
  code/controllers/subsystem/ticker.dm
Labels: Fix

#5814 Добавил священнику новую секту на аспект Mortem
  code/modules/religion/religion_sects.dm
Labels: Tweak

#5818 remove /obj/machinery/mecha_part_fabricator/check_access()
  code/game/mecha/mech_fabricator.dm
Labels: Fix

#5821 sweep cooldown no matter the disruption
  code/_onclick/click.dm
  code/datums/components/swiping.dm
  code/game/objects/items/weapons/twohanded.dm
Labels: Fix

#5816 Нельзя отправить деньги по ПДА при потере связи
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Fix

#5834 фикс "Спавнится два соулстона, вместо одного"
  code/datums/spells/conjure.dm
Labels: Fix

#5826 Bell changes
  code/game/objects/structures/chapel.dm
  code/modules/mob/mob_helpers.dm
Labels: Fix, Sound, Tweak

#5835 Больше нельзя емагнуть створку на базе нюки
  code/game/machinery/doors/shutters.dm
Labels: Fix

#5836 Борги больше не получают стан во время полета на шаттле
  code/controllers/subsystem/shuttles.dm
Labels: Tweak

#5837 проверка на eyecheck() для флэша из химии
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Fix

#5777 Звуки одежды
  code/modules/mob/living/carbon/human/inventory.dm
  sound/effects/equip_belt.ogg
  sound/effects/equip_shoes.ogg
  sound/effects/equip_uniform.ogg
Labels: Sound, Test Merge Candidate

#5724 Женские юбки для женского персонала офицеров сб и кадетов
  code/datums/outfits/jobs/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Test Merge Candidate

#5861 Adds an incapacitated check to table pulling up
  code/game/objects/structures.dm
Labels: Fix

#5857 Возможность пихать в слот хранилища брони шлем
  code/modules/clothing/suits/armor.dm
Labels: Tweak

#5862 not allowing to destroy blob on anything except harm
  code/game/gamemodes/blob/theblob.dm
Labels: Fix

#5775 Пластическая хирургия приводит даёт выбрать новое имя пациента
  code/modules/surgery/plastic_surgery.dm
  code/modules/surgery/surgery.dm
Labels: Tweak

#5838 С оперативников-симплмобов больше не падает их снаряжение.
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
Labels: Balance, Sprites

#5872 barsigns update!
  code/game/objects/effects/barsign.dm
  code/game/objects/structures/barsign.dm
Labels: Feature

#5881 Adds ghost HUD
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/other_mobs.dm
  code/_onclick/observer.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/login.dm
  code/modules/mob/mob_defines.dm
  icons/mob/screen_ghost.dmi
  taucetistation.dme
Labels: Feature, Sprites

#5842 Шахтерский фонарь
  code/modules/mining/mine_items.dm
Labels: Tweak

#5858 Buffs stoplag
  code/__DEFINES/tick.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/unsorted.dm
  code/controllers/master.dm
  code/datums/browser.dm
  code/game/objects/explosion.dm
  code/modules/client/asset_cache.dm
  code/modules/projectiles/projectile.dm
Labels: Performance

#5868 Ленивый нерф термита.
  code/game/turfs/simulated/walls.dm
  code/game/turfs/simulated/walls_reinforced.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
Labels: Balance

#5888 Fixes writing multi-line IC notes
  code/modules/mob/mob.dm
Labels: Fix

#5847 Картинки в карго консоли
  code/modules/cargo/console.dm
  code/modules/client/asset_cache.dm
  code/modules/clothing/head/collectable.dm
  html/browser/common.css
  icons/obj/vending.dmi
  icons/obj/vending_restock.dmi
Labels: Sprites, Test Merge Candidate, Tweak

#5889 Реворк звуковой кнопки клоуна.
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/weapons/clown_items.dm
  icons/obj/toy.dmi
  maps/boxstation/boxstation.dmm
Labels: Feature, Map Edit, Sprites, Test Merge Candidate, Tweak

#5893 Радиальное меню в ваучер.
  code/modules/mining/equipment_locker.dm
Labels: Feature
