Repository TauCetiStation/TauCetiClassic, pull requests merged in 2020-12, with the labels that each got.

#6464 Переход с Travis на Github Actions
  .github/workflows/ci_suite.yml
  .travis.yml
  README.md
  code/game/machinery/computer/message.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/suit_cooling.dm
  scripts/install-spaceman-dmm.sh
Labels: Tools

#6444 нерф флешбенгов
  code/game/objects/items/weapons/grenades/grenade.dm
Labels: Balance

#6435 Фикс цвета текста при проигрыше ниндзей.
  code/game/gamemodes/ninja/ninja.dm
Labels: Fix

#6447 Запрет воскрешения мобов.
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#6422 Хайвлорд, его изменение и мелкие фиксы мобов
  code/game/gamemodes/abduction/abduction_gear.dm
  code/modules/mining/equipment_locker.dm
  code/modules/mining/monsters.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/roguelike/mob_modifiers/negative.dm
  icons/mob/monsters.dmi
Labels: Feature, Fix, Sprites, Tweak

#6441 air alarm office fix
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#6454 Перевод Daily Key Reset.
  code/game/machinery/computer/message.dm
Labels: Translation/Localization

#6432 Респрайт блюспейс червоточины
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/effects/portals.dm
  code/modules/events/wormholes.dm
  code/modules/mining/equipment_locker.dm
  icons/obj/objects.dmi
Labels: Sprites

#6433 Лут стал ложиться в шкаф
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#6490 solution to all hand-breaking combo bugs.
  code/modules/unarmed_combat/combo_handler.dm
Labels: Fix

#6434 Фикс пропавшего спрайта тыквы.
  code/game/machinery/vending.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Fix

#6431 Логи при активации игнайтера.
  code/modules/assembly/igniter.dm
Labels: Admin

#6442 нерфит сварочные очки
  code/modules/mob/living/carbon/human/life.dm
Labels: Balance

#6488 Фикс камеры под бригом
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#6409 Шкафы вываливают содержимое при удалении симпл мобом.
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#6406 Перевод Dissection Guide.
  code/game/gamemodes/abduction/abduction_gear.dm
Labels: Translation/Localization

#6463 Фикс худов на борерах
  code/datums/atom_huds/atom_hud_data.dm
Labels: Fix

#6381 Видимость заряда чарджера в одном тайле от него.
  code/game/machinery/cell_charger.dm
Labels: Tweak

#6495 Фикс верба "Deflate".
  code/game/objects/structures/inflatable.dm
Labels: Fix

#6415 Пофикшена неработавшая руна обмена сознания у культа
  code/game/gamemodes/cult/cult_datums.dm
Labels: Fix

#6380 Перевод газет
  code/game/machinery/newscaster.dm
Labels: Translation/Localization

#6481 Расширение возможностей научного киборга
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature

#6382 Добавлена кнопка фоллоу для мертвых
  code/modules/mob/say.dm
Labels: Tweak

#6440 sleeper layer = BELOW_CONTAINERS_LAYER
  code/game/machinery/Sleeper.dm
Labels: Fix

#6468 Блоб удаляет консоли.
  code/game/machinery/computer/computer.dm
Labels: Fix

#6347 Добавление компонентов машинерии в ассортимент инженерного торгового автомата
  code/game/machinery/vending.dm
Labels: Feature

#6310 some meadbay fixes
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#6348 Revert "Fifth law, preventing a removal from crew exploit (#4666)"
  code/datums/ai_laws.dm
  code/game/machinery/computer/ai_core.dm
  code/game/objects/items/weapons/AI_modules.dm
Labels: Revert / Removal

#6227 Убрал урон по СПУ, от импланта лояльности
  code/game/objects/items/weapons/implants/mindshield.dm
Labels: Fix

#6465 Перевод spellbook и названий заклинаний.
  code/datums/spells/Time_stop.dm
  code/datums/spells/barnyardcurse.dm
  code/datums/spells/charge.dm
  code/datums/spells/ethereal_jaunt.dm
  code/datums/spells/gnomecurse.dm
  code/datums/spells/in_hand.dm
  code/datums/spells/knock.dm
  code/datums/spells/lighting_shock.dm
  code/datums/spells/mind_transfer.dm
  code/datums/spells/repulse.dm
  code/datums/spells/spacetime_distrortion.dm
  code/datums/spells/summon_item.dm
  code/datums/spells/wizard.dm
  code/game/gamemodes/wizard/spellbook.dm
Labels: Translation/Localization

#6528 ghost follow hotfix
  code/modules/mob/say.dm
Labels: Fix

#6523 Фикс невидимого вируса
  code/datums/atom_huds/atom_hud_data.dm
  icons/mob/hud.dmi
Labels: Fix

#6500 Disposal pipes remap
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#6371 Исключение добавления shock_stage при получении урона для IPC.
  code/modules/organs/external/flesh.dm
Labels: Fix

#6466 Фикс стазиса генокрадов.
  code/game/gamemodes/changeling/powers/fakedeath.dm
Labels: Fix

#6559 Suicide теперь "лечится" rejuv'ом
  code/modules/mob/living/living.dm
Labels: Fix

#6425 Перевод арканного тома.
  code/game/gamemodes/cult/ritual.dm
Labels: Translation/Localization

#6428 Перевод спам-сообщений ПДА на русский язык.
  code/modules/events/pda_spam.dm
Labels: Translation/Localization

#6483 Переключение платы консоли рнд.
  code/game/machinery/computer/buildandrepair.dm
Labels: Fix

#6531 Спецэффекты гост-свечки из хеллоувина перезжают в основу
  code/game/objects/items/candle.dm
  code/modules/religion/rites/misc.dm
  icons/mob/human.dmi
Labels: Feature, Sprites

#6313 Обновление для мехов(Порт + пару фишек)
  code/game/mecha/combat/combat.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/game/mecha/mecha_topic.dm
  icons/mob/actions_mecha.dmi
  taucetistation.dme
Labels: Feature, Sprites, Test Merge Candidate, Tweak

#6504 small fix centcom
  maps/centcom/centcom.dmm
Labels: Fix, Map Edit

#6396 Ребаланс цен телепортера и генератора вормхолов в фабрикаторе мехов
  code/modules/research/designs/mechfabricator_designs.dm
Labels: Balance

#6546 Gamemode Bundle fixes
  code/game/gamemodes/abduction/abduction.dm
  code/game/gamemodes/blob/blob.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/changeling/traitor_chan.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/epidemic/epidemic.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gang/gang.dm
  code/game/gamemodes/heist/heist.dm
  code/game/gamemodes/heist/heist_old.dm
  code/game/gamemodes/infestation/infestation.dm
  code/game/gamemodes/malfunction/malfunction.dm
  code/game/gamemodes/meme/meme.dm
  code/game/gamemodes/mutiny/mutiny.dm
  code/game/gamemodes/ninja/ninja.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/revolution/rp_revolution.dm
  code/game/gamemodes/shadowling/shadowling.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: Balance, Fix

#6585 transfer_to update
  code/datums/mind.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Code Improvements

#6589 Фикс атмоса в техах
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#6575 Латексные перчатки на хирургический фартук
  code/modules/clothing/suits/jobs.dm
Labels: Tweak

#6558 time stop mutes people
  code/datums/spells/Time_stop.dm
Labels: Tweak

#6603 Фикс отображения цены в вендомате.
  code/game/machinery/vending.dm
Labels: Fix

#6361 Edit Color Matrix from goonstation
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  html/admin/color_matrix.html
Labels: Tools

#6362 Автоматические записи в базу данных Службы Безопасности
  code/datums/atom_huds/atom_hud_data.dm
  code/datums/datacore.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/doors/brigdoors.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Test Merge Candidate, Translation/Localization, Tweak

#6572 vision colormatrix fix
  code/__HELPERS/matrices.dm
Labels: Fix

#6624 космические костюмы можно кинуть только на 2 турфа
  code/modules/clothing/clothing.dm
  taucetistation.dme
Labels: Balance
