Repository TauCetiStation/TauCetiClassic, pull requests merged in 2020-09, with the labels that each got.

#6051 Anomaly fixes
  code/modules/events/anomaly.dm
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_pyro.dm
Labels: Fix, Tweak

#6045 Updated rnd files to dowload reliabilities properly
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
Labels: Fix

#5981 Новые капсулы для шахтеров и еще пару доработок.
  code/game/asteroid.dm
  code/modules/mining/equipment_locker.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/shelters.dm
  icons/obj/mining.dmi
  maps/templates/shelter_1.dmm
  maps/templates/shelter_2.dmm
  maps/templates/shelter_3.dmm
Labels: Map Edit, Sprites, Test Merge Candidate

#5963 Ура, наконец-то поды работают как шаттлы
  code/controllers/subsystem/shuttles.dm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
Labels: Fix, Map Edit, Test Merge Candidate

#5894 Радиальное меню для силиконов
  code/_onclick/hud/radial.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/robot.dm
  icons/mob/custom-synthetic.dmi
Labels: Balance, Test Merge Candidate, Tweak

#5991 CEV Eris vote subsystem port
  code/__HELPERS/mobs.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/jobs.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  code/controllers/subsystem/voting.dm
  code/controllers/subsystem/voting/poll.dm
  code/controllers/subsystem/voting/poll_types.dm
  code/controllers/subsystem/voting/vote_choice.dm
  code/datums/mind.dm
  code/game/world.dm
  config/example/config.txt
  taucetistation.dme
Labels: Feature, Refactor, Test Merge Candidate

#6058 <!DOCTYPE html>
  code/datums/browser.dm
  code/game/objects/items/devices/paicard.dm
  code/modules/mob/living/silicon/pai/recruit.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/nano/nanoui.dm
Labels: Fix

#6050 Починил say-hear в объектах
  code/game/objects/objs.dm
Labels: Fix

#6075 Двери эвака ЦК
  code/controllers/subsystem/shuttles.dm
  maps/centcom/centcom.dmm
Labels: Fix, Map Edit

#6071 report issue button
  interface/interface.dm
  interface/skin.dmf
Labels: Tweak

#6085 Фикс доступа у бухломата в капсуле
  maps/templates/shelter_3.dmm
Labels: Map Edit

#6074 СПУ теперь не могут пить жидкости
  code/game/objects/objs.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/glowsticks.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Fix, Test Merge Candidate

#6078 removes "Disease Outbreak"
  code/modules/events/_event_container.dm
  code/modules/events/disease_outbreak.dm
  taucetistation.dme
Labels: Fix, Revert / Removal

#6038 Порт русских кодовых слов
  code/__DEFINES/mob.dm
  code/__HELPERS/names.dm
  code/_globalvars/lists/names.dm
  code/controllers/subsystem/ticker.dm
  code/datums/mind.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/mob.dm
  config/.gitignore
  config/names/adjectives.txt
  config/names/eng_adjectives.txt
  config/names/eng_drinks.txt
  config/names/eng_nouns.txt
  config/names/eng_verbs.txt
  config/names/rus_adjectives.txt
  config/names/rus_bays.txt
  config/names/rus_local_terms.txt
  config/names/rus_nouns.txt
  config/names/rus_occupations.txt
  config/names/rus_verbs.txt
  config/names/verbs.txt
Labels: Feature, Tweak

#6103 fixing swiping while being disguised using chameleon projector
  code/datums/components/swiping.dm
Labels: Fix

#6043 Смена источника звука от ударов.
  code/_onclick/item_attack.dm
Labels: Sound

#6002 Ports "Smart Asset Cache" from TG
  code/__HELPERS/logging.dm
  code/_globalvars/logging.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/assets.dm
  code/datums/browser.dm
  code/game/gamemodes/ninja/suit/SpiderOS/display_spideros.dm
  code/game/machinery/newscaster.dm
  code/game/objects/game_kit.dm
  code/game/world.dm
  code/modules/admin/verbs/debug.dm
  code/modules/asset_cache/asset_cache.dm
  code/modules/asset_cache/asset_cache_client.dm
  code/modules/asset_cache/asset_cache_item.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/asset_cache/validate_assets.html
  code/modules/client/asset_cache.dm
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/paperwork/paper.dm
  code/modules/tooltip/tooltip.dm
  code/modules/tooltip/tooltip.html
  config/example/config.txt
  interface/skin.dmf
  taucetistation.dme
Labels: Performance, Refactor, Test Merge Candidate

#6105 Boxstation fixes
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#6114 highlight_traitor_codewords hotfix
  code/__HELPERS/names.dm
Labels: Fix

#6122 Фикс атмоса на гамме
  maps/gamma/gamma.dmm
Labels: Fix, Map Edit

#6119 Фикс дока карго
  maps/gamma/gamma.dmm
Labels: Map Edit

#6129 Нарси больше не в лобби
  code/game/gamemodes/cult/narsie.dm
Labels: Fix

#6124 Ящик для руды фикс
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/machine_unloading.dm
  code/modules/mining/satchel_ore_boxdm.dm
Labels: Fix, Tweak

#6133 Изменение скорости дидонам без обуви
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/species.dm
Labels: Tweak

#6117 Больше иконок для статус дисплеев ИИ
  code/game/machinery/status_display.dm
  code/game/verbs/AI_status.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Feature

#6123 Теперь у каждого цвета мелка своя одежда, или я так на это надеюсь
  code/modules/clothing/gloves/boxing.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/customitems/item_defines.dm
  maps/gamma/gamma.dmm
Labels: Fix, Map Edit

#6135 Перерисованный рюкзак и не только для дионы-младшей
  code/modules/mob/living/carbon/monkey/update_icons.dm
  icons/mob/diona_back.dmi
Labels: Fix, Sprites

#6161 Фикс аиралярма
  maps/gamma/gamma.dmm
Labels: Fix, Map Edit

#6113 добавляет хосу личную пушку
  code/datums/outfits/jobs/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/ammunition/energy.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/projectile/special.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
Labels: Feature, Sprites

#6168 New desc for puddle
  code/game/objects/structures/watercloset.dm
Labels: Fix

#6162 Claymore
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/weapons.dmi
Labels: Sprites

#6170 Фикс мед. телепортер не анбаклил при телепортации
  code/game/objects/items/devices/radio/beacon.dm
Labels: Fix

#6171 Medkits
  code/game/objects/items/weapons/storage/firstaid.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/aibots.dmi
  icons/obj/storage.dmi
Labels: Sprites

#6132 Теперь спелл божка на призыв животных работает
  code/datums/spells/religion.dm
Labels: Fix
