Repository TauCetiStation/TauCetiClassic, pull requests merged in 2020-11, with the labels that each got.

#6319 Mecharesprite
  code/game/mecha/equipment/tools/tools.dm
  icons/mecha/mecha_equipment.dmi
Labels: Sprites

#6329 У АВД и СБ зарплата не будет снижаться при революции
  code/game/gamemodes/revolution/rp_revolution.dm
Labels: Fix, Tweak

#6315 Hard hat icon fix
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/hardhat.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Fix

#6318 Шахтерский худ в научный модуль киборга
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Tweak

#6337 Beeps for IPC
  code/modules/mob/living/carbon/human/emote.dm
Labels: Feature

#6325 Фикс ремонта нанопастой.
  code/game/objects/items/stacks/nanopaste.dm
Labels: Fix

#6216 респрайт куртки парамедика добавление им шапок
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/head/beret.dm
  code/modules/clothing/head/soft_caps.dm
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites

#6355 быстрое возвращение шляпе парамедика спрайта
  icons/obj/clothing/hats.dmi
Labels: Sprites

#6366 Сингулярные мобы теперь не тянут после смерти
  code/modules/roguelike/mob_modifiers/positive.dm
Labels: Tweak

#6389 User_unbuckle_mob для труб.
  code/modules/atmospheric/machinery/pipes/pipes.dm
Labels: Fix

#6404 trays are now a storages
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/centcom/centcom.dmm
Labels: Fix

#6416 Заменены устаревшие противогазы у парамедов на новые
  maps/boxstation/boxstation.dmm
Labels: Map Edit
