Repository TauCetiStation/TauCetiClassic, pull requests merged in 2021-02, with the labels that each got.

#6799 inhands для барбишопа
  code/modules/reagents/reagent_containers/spray.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Sprites

#6802 [PORT] Refactor bitfields global
  code/__DEFINES/bitfields.dm
  code/_globalvars/bitfields.dm
  code/game/atoms.dm
  taucetistation.dme
Labels: Admin, Refactor

#6833 Follow for LOOC
  code/game/verbs/ooc.dm
Labels: Admin, Tweak

#6825 fix server tech deleting
  code/modules/research/server.dm
Labels: Fix

#6815 [Alien] Рефактор кода структур ксеноморфов
  code/modules/mob/living/carbon/xenomorph/effects/aliens.dm
Labels: Balance, Fix, Refactor

#6828 Аномалии не должны рантаймить
  code/__HELPERS/_lists.dm
  code/__HELPERS/unsorted.dm
  code/modules/events/anomaly.dm
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_grav.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/anomaly_vortex.dm
Labels: Fix

#6801 [Alien] Прогресс режима infestation в check_antagonists()
  code/__DEFINES/xenomorph.dm
  code/_globalvars/lists/mob.dm
  code/game/gamemodes/infestation/infestation.dm
  code/modules/admin/player_panel.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/drone.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/sentinel.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/queen.dm
  code/modules/mob/living/carbon/xenomorph/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/larva/powers.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Admin, Tweak

#6852 респрайт автоинъекторов
  code/game/objects/items/weapons/autoinjectors.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/syringe.dmi
Labels: Resprite, Sprites

#6660 Feature/tg camera port
  code/__HELPERS/game.dm
  code/_onclick/hud/map_popups.dm
  code/_onclick/hud/parallax.dm
  code/_onclick/hud/plane_master.dm
  code/_onclick/hud/screen_objects.dm
  code/game/area/areas.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/camera.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/atmospheric/machinery/portable/canister.dm
  code/modules/atmospheric/machinery/portable/pump.dm
  code/modules/atmospheric/machinery/portable/scrubber.dm
  code/modules/client/client defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/recycling/disposal.dm
  code/modules/tgui/states/default.dm
  code/modules/tgui/states/machinery_state.dm
  icons/hud/map_backgrounds.dmi
  interface/skin.dmf
  nano/templates/sec_camera.tmpl
  nano/templates/sec_camera_map_content.tmpl
  nano/templates/sec_camera_map_header.tmpl
  taucetistation.dme
  tgui/packages/tgui/components/Section.js
  tgui/packages/tgui/interfaces/CameraConsole.js
  tgui/packages/tgui/public/tgui.bundle.css
  tgui/packages/tgui/public/tgui.bundle.js
  tgui/packages/tgui/styles/components/Section.scss
Labels: Feature, Fix, Sprites, Test Merge Candidate, UI

#6746 Респрайт/ремап эвакуационного шаттла/отбытия.
  code/controllers/subsystem/shuttles.dm
  code/game/area/shuttle_areas.dm
  code/game/area/station_areas.dm
  code/game/machinery/computer/arrival_shuttle.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/shuttle.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/structures/signs/_signs.dm
  code/modules/locations/shuttles/bench.dmi
  code/modules/locations/shuttles/closet.dm
  code/modules/locations/shuttles/closet.dmi
  code/modules/locations/shuttles/evac_shuttle.dmi
  code/modules/locations/shuttles/floor.dm
  code/modules/locations/shuttles/mine_sci_shuttle.dm
  code/modules/locations/shuttles/object_wall.dm
  code/modules/locations/shuttles/pod_doors.dmi
  code/modules/locations/shuttles/shuttle_doors.dm
  code/modules/locations/shuttles/shuttle_window.dm
  code/modules/locations/shuttles/wall.dm
  code/modules/paperwork/paper.dm
  icons/obj/computer.dmi
  icons/obj/decals.dmi
  icons/obj/doors/airlocks/shuttle/eng.dmi
  icons/obj/doors/airlocks/shuttle/med.dmi
  icons/obj/doors/airlocks/shuttle/sec.dmi
  icons/turf/areas.dmi
  icons/turf/floors.dmi
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
  nano/images/nanomap_exodus_1.png
  nano/images/nanomap_gamma_1.png
Labels: Map Edit, Sprites, Test Merge Candidate

#6858 Исправление логической ошибки в моем старом коде
  code/modules/detectivework/autopsy.dm
Labels: Fix

#6664 Возможность вскрывать полы без РЦД и маленькая переработка починки обычных стен, фикс бага при сварке открытой двери
  code/game/machinery/doors/airlock.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/turf.dm
  code/modules/mining/mine_turfs.dm
  code/modules/scrap/scrap_turfs.dm
Labels: Balance, Feature, Tweak

#6860 Нинжу в инвизе НЕвидно через худы
  code/game/gamemodes/ninja/suit/n_suit_verbs/ninja_stealth.dm
Labels: Fix

#6863 Обновление старых звуков/Добавление новых
  code/_globalvars/lists/sound.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/buckling.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/projectiles/guns/plasma/plasma.dm
  sound/effects/mob_buckle.ogg
  sound/effects/robot_initialization.ogg
  sound/effects/robot_reset_module.ogg
  sound/effects/window_broken_1.ogg
  sound/effects/window_broken_2.ogg
  sound/effects/window_broken_3.ogg
  sound/weapons/guns/plasma10_shotgun.ogg
Labels: Sound

#6870 Config/Preferences Update Метки при изменении конкретных файлов
  .repoxbot.config.json
Labels: Tools

#6845 [Alien] Урон от огня, нерф ХП + фиксы и фичи
  code/_onclick/hud/alien.dm
  code/modules/cargo/supplyshuttle.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/drone.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/sentinel.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/queen.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/larva/life.dm
  code/modules/mob/living/carbon/xenomorph/larva/powers.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
  code/modules/mob/living/carbon/xenomorph/special/alien_embryo.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/life.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  icons/mob/alienqueen.dmi
  icons/mob/xenomorph.dmi
Labels: Balance, Fix, Sprites, Tweak

#6810 mobs no longer hard delete by default
  code/modules/mob/mob.dm
Labels: Performance, Test Merge Candidate

#6871 fix nutriment autoinjector
  code/game/objects/items/weapons/autoinjectors.dm
Labels: Fix

#6873 Revert "Обновление старых звуков/Добавление новых"
  code/_globalvars/lists/sound.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/buckling.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/projectiles/guns/plasma/plasma.dm
  sound/effects/mob_buckle.ogg
  sound/effects/robot_initialization.ogg
  sound/effects/robot_reset_module.ogg
  sound/effects/window_broken_1.ogg
  sound/effects/window_broken_2.ogg
  sound/effects/window_broken_3.ogg
  sound/weapons/guns/plasma10_shotgun.ogg
Labels: Sound

#6862 Аномалии теперь точно не будут рантаймить
  code/__HELPERS/game.dm
  code/game/gamemodes/heist/heist.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/structures/windows-colored.dm
Labels: :atom: BYOND, Fix, Refactor

#6875 Фикс бага при старте режима infestation
  code/game/gamemodes/infestation/infestation.dm
Labels: Fix

#6876 Удаляю старую систему желудка
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/mob_grab.dm
  code/modules/ventcrawl/ventcrawl.dm
Labels: Revert / Removal

#6755 Оптимизация при изменении человечка в лобби
  code/__DEFINES/misc.dm
  code/__DEFINES/tick.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/unsorted.dm
  code/datums/datacore.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/external/ipc.dm
  code/modules/organs/external/stump.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/organ_internal.dm
  code/modules/surgery/braincore.dm
  taucetistation.dme
Labels: Performance, Preferences Update, Test Merge Candidate, Tweak

#6814 Небольшие исправления работы грипперов боргов
  code/game/objects/items/robot/robot_parts.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/research/xenobiology/xenobio_camera.dm
Labels: Fix, Test Merge Candidate

#6880 admin staffwho update
  code/game/verbs/who.dm
  code/modules/client/client procs.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
Labels: Admin, Refactor, Tweak

#6837 Компонента баунда теперь показывает визуально свой радиус
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/dcs/signals.dm
  code/datums/atom_huds/alternate_apperance.dm
  code/datums/components/bound.dm
  code/datums/components/visible_radius.dm
  code/game/objects/structures/chapel.dm
  icons/mob/screen1.dmi
  taucetistation.dme
Labels: Sprites, Test Merge Candidate, Tweak

#6891 У парикмахера не было видно превью куклы
  code/game/objects/items/weapons/cosmetics.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#6782 Подсветка предметов
  code/_onclick/drag_drop.dm
  code/_onclick/hud/screen_objects.dm
  code/game/atoms_movable.dm
  code/game/objects/game_kit.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/defibrillator.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/tanks/watertank.dm
  code/modules/client/character menu/global.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/clothing/clothing.dm
  code/modules/paperwork/paperbin.dm
  code/modules/paperwork/picture_frame.dm
  code/modules/projectiles/guns/projectile/rocket.dm
  code/modules/research/xenoarchaeology/tools/tools_wave_scanner.dm
Labels: Feature, Preferences Update, Test Merge Candidate

#6789 Обновление для астероида
  code/controllers/subsystem/mapping.dm
  code/game/asteroid.dm
  code/game/turfs/simulated/walls.dm
  code/modules/events/rogue_drones.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/jungle/jungle_animals.dm
  code/modules/jungle/jungle_tribe.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/mining/equipment_locker.dm
  code/modules/mining/mine_areas.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/monsters.dm
  code/modules/mob/living/simple_animal/bees.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/crab.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/shiba.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/living/simple_animal/head.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/hulk.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/special/scp.dm
  code/modules/mob/living/simple_animal/worm.dm
  code/modules/projectiles/guns/energy/special.dm
  icons/mob/animal.dmi
  icons/mob/monsters.dmi
  sound/misc/goliath_tentacle_hit.ogg
  sound/misc/mining_crate_fail.ogg
  sound/misc/mining_crate_success.ogg
  sound/misc/mining_reward_0.ogg
  sound/misc/mining_reward_1.ogg
  sound/misc/mining_reward_2.ogg
  sound/misc/mining_reward_3.ogg
  tgui/packages/tgui/interfaces/Lootcrate.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Code Improvements, Sound, Sprites, Test Merge Candidate, Translation/Localization, UI
