Repository TauCetiStation/TauCetiClassic, pull requests merged in 2021-12, with the labels that each got.

#8304 Fix ventcrawl
  code/modules/mob/living/carbon/xenomorph/humanoid/humanoid.dm
  code/modules/mob/living/carbon/xenomorph/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
  code/modules/ventcrawl/ventcrawl.dm
Labels: Fix

#8255 Бафф некоторых ритуалов культа
  code/modules/religion/religion_sects.dm
  code/modules/religion/rites/instant/instant.dm
  maps/centcom/centcom.dmm
Labels: Map Edit, Tweak

#8274 Во время джаунта даётся иксрей
  code/_onclick/hud/action.dm
  code/datums/spells/ethereal_jaunt.dm
  code/game/machinery/wishgranter.dm
  code/modules/maps/maps_code/wildwest.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/silicon/robot/life.dm
Labels: Tweak

#8249 При деконверте ролька удаляется, а не остаётся висеть
  code/_globalvars/lists/misc.dm
  code/datums/components/gamemodes/gamemode.dm
  code/datums/components/gamemodes/syndicate.dm
  code/datums/mind.dm
  code/game/gamemodes/factions/blob.dm
  code/game/gamemodes/factions/cops.dm
  code/game/gamemodes/factions/cult.dm
  code/game/gamemodes/factions/families.dm
  code/game/gamemodes/factions/props.dm
  code/game/gamemodes/factions/revolution.dm
  code/game/gamemodes/factions/syndicate.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/core.dm
  code/game/gamemodes/modes_gameplays/families/families.dm
  code/game/gamemodes/modes_gameplays/families/gang_handler.dm
  code/game/gamemodes/objectives/families/become_captain.dm
  code/game/gamemodes/objectives/families/church_tradition.dm
  code/game/gamemodes/objectives/families/destroy_gangs.dm
  code/game/gamemodes/objectives/families/kill_undercover_cops.dm
  code/game/gamemodes/objectives/families/rob_nt.dm
  code/game/gamemodes/objectives/families/save_bottle.dm
  code/game/gamemodes/objectives/families/steal_gold.dm
  code/game/gamemodes/role.dm
  code/game/gamemodes/roles/blob.dm
  code/game/gamemodes/roles/changeling.dm
  code/game/gamemodes/scoreboard.dm
  code/game/machinery/computer/ai_core.dm
  code/game/objects/items/weapons/chaplain_weapons.dm
  code/game/objects/items/weapons/implants/mindshield.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/silicon/login.dm
  code/modules/reagents/reagent_types/Chemistry-Core.dm
Labels: Tweak

#8286 Синга получила прикольный эффект
  code/__DEFINES/_planes+layers.dm
  code/_onclick/hud/rendering/plane_master.dm
  code/_onclick/hud/rendering/plane_master_controller.dm
  code/_onclick/hud/rendering/render_plate.dm
  code/game/gamemodes/modes_gameplays/cult/cult_datums.dm
  code/game/gamemodes/modes_gameplays/cult/narsie.dm
  code/modules/power/singularity/generator.dm
  code/modules/power/singularity/singularity.dm
  code/modules/power/tesla/energy_ball.dm
  code/modules/scrap/scrap_tornado.dm
Labels: Tweak, Test Merge Candidate

#8310 New emag features
  code/game/machinery/vending.dm
  code/game/machinery/vending/eat.dm
  code/game/machinery/vending/other.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/structures/morgue.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/scrap/scrap_beacon.dm
Labels: Feature

#8308 [Alien] Action buttons
  code/datums/spell.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/drone.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/sentinel.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/humanoid.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/queen.dm
  code/modules/mob/living/carbon/xenomorph/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/larva/powers.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  icons/mob/actions.dmi
  taucetistation.dme
Labels: Sprites, Tweak

#8342 Эквипа парамедикам
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#8347 Фикс зрения кисок в очках
  code/modules/mob/living/carbon/human/life.dm
Labels: Fix

#8315 [Alien] Ребаланс помощи с ЦК
  code/__DEFINES/xenomorph.dm
  code/modules/cargo/packs.dm
Labels: Balance

#8303 Ремап брига
  code/game/area/station_areas.dm
  code/game/objects/structures/signs/signs_departments.dm
  code/modules/paperwork/stamps.dm
  icons/obj/decals.dmi
  icons/turf/areas.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
  nano/images/nanomap_exodus_1.png
Labels: Map Edit, Sprites, Test Merge Candidate

#8373 Adds request console in cargo
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#8364 Добавил квирк быстрого надевания и снимания рига
  code/__DEFINES/quirks.dm
  code/__DEFINES/traits.dm
  code/datums/traits/positive.dm
  code/modules/mob/inventory.dm
Labels: Feature

#8377 Добавляем наномед шахтёрам и ксеноархеологам.
  maps/asteroid/asteroid.dmm
Labels: Map Edit

#8186 делает сообщения в чатик при инициализации
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/icon_smooth.dm
  code/controllers/subsystem/jobs.dm
  code/controllers/subsystem/junkyard.dm
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/machines.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/shuttles.dm
  code/controllers/subsystem/stickyban.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/weather.dm
  code/controllers/subsystem/xenoarch.dm
Labels: Contentious, Tweak

#8327 Новые дереликты
  code/datums/space_structures.dm
  code/game/area/space_structures_areas.dm
  code/modules/awaymissions/corpse.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  icons/turf/areas.dmi
  maps/templates/space_structures/broken_breacher.dmm
  maps/templates/space_structures/clown_shuttle.dmm
  maps/templates/space_structures/resource_shuttle.dmm
  maps/templates/space_structures/secrete_lab.dmm
  maps/templates/space_structures/ships_squad.dmm
  maps/templates/space_structures/tree_asteroid.dmm
Labels: Map Edit, Sprites

#8336 ИИ может быстро включать и активировать Liquid Dispenser
  code/_onclick/ai.dm
  code/game/machinery/ai_slipper.dm
Labels: Feature

#8348 Отобран чат синтетов у позитронки
  code/modules/mob/living/carbon/brain/posibrain.dm
Labels: Revert / Removal

#8375 Changing colors and fonts of dmg in crew monitoring computer
  nano/css/shared.css
Labels: Tweak

#8338 бафф генок
  code/game/gamemodes/modes_gameplays/changeling/powers/biodegrade.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/epinephrine.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/lesserform.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/spiders.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/stings.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/stings_range.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/strained_muscles.dm
Labels: Balance, Test Merge Candidate

#8292 Fix emag, stackable items on borgs
  code/_onclick/cyborg.dm
  code/_onclick/hud/robot.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
Labels: Fix, Test Merge Candidate

#8390 Добавляем набор для зашивания ран на шаттл нюкеров
  maps/centcom/centcom.dmm
Labels: Map Edit

#8391 Обсерверы не видели других обсерверов
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#8383 Адаптация медбея под высокий онлайн + мелкие изменения
  code/game/machinery/holosign.dm
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Test Merge Candidate

#8396 Нёрф отрезания бошки кусачками
  code/_onclick/item_attack.dm
Labels: Balance

#8400 снятие ксеноограничений на блоба
  code/game/gamemodes/roles/blob.dm
Labels: Tweak

#8398 Возвращаю распространение вирусов только через кровь
  code/__DEFINES/diseases2.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/living.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  code/modules/virus2/disease2.dm
  code/modules/virus2/helpers.dm
  taucetistation.dme
Labels: Fix

#8392 Changeling can use hivechat while unconscious
  code/modules/mob/living/carbon/human/say.dm
Labels: Tweak, Test Merge Candidate

#8394 Убраны лишние тайлы в коде boxstation.dmm
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#8340 Абоминация - последняя форма генокрадуса.
  code/__DEFINES/mob.dm
  code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
  code/game/gamemodes/modes_gameplays/changeling/headcrab.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/Chameleon_skin.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/changespecies.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/fakedeath.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/fleshmend.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/lesserform.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/strained_muscles.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/transform.dm
  code/game/gamemodes/roles/changeling.dm
  code/game/objects/structures/window.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/organ_internal.dm
  code/modules/projectiles/gun.dm
  icons/mob/human_races/r_abomination.dmi
  sound/antag/abomination_start.ogg
  sound/voice/abomination.ogg
Labels: Sprites, Test Merge Candidate

#8410 фикс бага с крю мониторчиком
  nano/templates/crew_monitor_map_content.tmpl
Labels: Fix

#8381 Из дрозда можно доставать гранаты
  code/game/objects/random/random_guns.dm
  code/modules/cargo/packs.dm
  code/modules/cargo/prices.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/launcher.dm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit, Tweak

#8412 Автоматические точки в конце сообщений игрока
  code/modules/assembly/voice.dm
  code/modules/mob/living/carbon/human/say.dm
Labels: Tweak

#8316 Ремап инженерного отдела.
  icons/turf/floors.dmi
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Test Merge Candidate

#8423 Фиксит общий доступ кнопок управления дверьми общака
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#8419 Fix runtime
  code/game/objects/structures/window.dm
Labels: Fix

#8280 Радиоуправляемый дрон для Синдиката
  code/datums/uplinks_items.dm
  code/game/jobs/access.dm
  code/game/machinery/cryopod.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/living/silicon/robot/drone/maintenance.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_damage.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/syndi/drone/drone.dm
  code/modules/mob/living/silicon/robot/syndi/drone/rc.dm
  code/modules/mob/living/silicon/robot/syndi/drone/upgrades.dm
  code/modules/mob/living/silicon/robot/syndi/drone/upgrades_spells.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  code/modules/reagents/reagent_containers/robodropper.dm
  icons/mob/actions.dmi
  icons/mob/head.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/robots.dmi
  icons/obj/objects.dmi
  sound/hallucinations/fake_battle_1_scaled.ogg
  sound/hallucinations/fake_battle_2_scaled.ogg
  sound/hallucinations/fake_battle_3_scaled.ogg
  taucetistation.dme
Labels: Feature, Sprites, Test Merge Candidate

#8402 Спавн меню для гостов
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/spawners.dm
  code/__HELPERS/game.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ghost.dm
  code/controllers/subsystem/junkyard.dm
  code/controllers/subsystem/ticker.dm
  code/datums/spawners_menu/spawners.dm
  code/datums/spawners_menu/spawners_menu.dm
  code/game/gamemodes/factions/cops.dm
  code/game/gamemodes/modes_gameplays/families/cops_handler.dm
  code/game/machinery/podmen.dm
  code/game/response_team.dm
  code/modules/admin/verbs/send_police.dm
  code/modules/client/client defines.dm
  code/modules/client/preferences_savefile.dm
  code/modules/events/alien_infestation.dm
  code/modules/events/blob.dm
  code/modules/events/borers.dm
  code/modules/events/space_ninja.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/religion/rites/standing/spawn_item.dm
  code/modules/scrap/scrap_people.dm
  icons/mob/screen_ghost.dmi
  maps/centcom/centcom.dmm
  taucetistation.dme
  tgui/packages/tgui/interfaces/SpawnersMenu.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Map Edit, Sprites, Tweak, Test Merge Candidate, UI, Preferences Update

#8427 Фикс иксрея
  code/_onclick/hud/action.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#8431 стечкин респрайт
  code/modules/projectiles/guns/projectile/pistol.dm
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
Labels: Sprites

#8441 Фикс бага у спавнер панели
  code/__HELPERS/_lists.dm
  code/datums/spawners_menu/spawners.dm
  code/datums/spawners_menu/spawners_menu.dm
Labels: Fix

#8424 Парочка фиксов hard del-итов
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/parallax.dm
  code/controllers/subsystem/parallax.dm
  code/controllers/subsystem/ticker.dm
  code/datums/progressbar.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/modules/client/client procs.dm
  code/modules/research/message_server.dm
Labels: Test Merge Candidate

#8436 simple tracker fix
  code/modules/power/singularity/emitter.dm
  code/modules/power/tracker.dm
Labels: Fix
