Repository TauCetiStation/TauCetiClassic, pull requests merged in 2021-05, with the labels that each got.

#7072 [Alien] Corrossive Acid fix
  code/modules/mob/living/carbon/xenomorph/effects/aliens.dm
Labels: Balance, Fix, Tweak

#7037 Респрайт газов
  icons/effects/plasma.dmi
  icons/effects/tile_effects.dmi
Labels: Sprites, Test Merge Candidate

#7082 Возможность создавать трубы с фильтрами для атмостехов
  code/game/machinery/pipe/pipe_dispenser.dm
Labels: Feature

#7097 Голем не сможет призвать голема
  code/modules/mob/living/carbon/metroid/metroid.dm
Labels: Fix

#7070 fixing shelter addressing everyone in the area
  code/modules/mining/mine_items.dm
Labels: Fix

#7084 fixes pipes and cables
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#7085 Obj Шаттлы
  code/modules/locations/shuttles/object_wall.dm
  icons/turf/shuttle.dmi
  maps/asteroid/asteroid.dmm
  maps/centcom/centcom.dmm
Labels: Map Edit, Sprites

#7110 Спрайт жирного форенсиксьюита корректно отображается на дире-восток
  icons/mob/uniform_fat.dmi
Labels: Sprites

#7111 добавляет лечащий уши препарат
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Labels: Feature

#7135 В карманный патронаж теперь можно засунуть клипсы для игрушечного револьвера
  code/game/objects/items/weapons/storage/pouches.dm
Labels: Tweak

#7133 Щит больше не станет и не кладет людей
  code/game/objects/items/weapons/shields.dm
Labels: Balance

#7157 toggling the kinetic energy scanner messaging module off
  code/modules/research/experiment.dm
Labels: Feature

#7147 making mechs and chairs break extinguisher foam
  code/game/objects/effects/foam.dm
Labels: Fix

#7073 [Alien] Увеличил ХП Квине и постройкам
  code/game/objects/structures/mineral_doors.dm
  code/modules/mob/living/carbon/xenomorph/effects/aliens.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/queen.dm
Labels: Balance, Test Merge Candidate

#7088 Подвигает Лимит Бутерброда До Чисто Символического Я Не Думаю Что Вы Сможете
  code/modules/admin/secrets.dm
  code/modules/reagents/reagent_containers/food/sandwich.dm
Labels: Balance, Test Merge Candidate

#7170 фикс пакетика для улик
  code/modules/detectivework/evidence.dm
Labels: Fix

#7086 fix fire extinguisher
  code/modules/reagents/reagent_containers/extinguisher.dm
  icons/obj/items.dmi
Labels: Fix

#7146 fixes #7145
  code/modules/unarmed_combat/combos/disarming.dm
Labels: Fix

#7116 Welcometotheminefields
  code/datums/uplinks_items.dm
  code/game/objects/effects/mines.dm
  code/game/objects/items/mines.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/cargo/packs.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  icons/obj/mines.dmi
  icons/obj/storage.dmi
  icons/obj/weapons.dmi
  maps/RandomZLevels/wildwest.dmm
  taucetistation.dme
Labels: Feature, Sprites

#7183 Ports "Orbit Menu" from TG
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/orbit.dm
  code/modules/mob/mob_defines.dm
  taucetistation.dme
  tgui/packages/tgui/interfaces/Orbit.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, UI

#7172 Point to на shift+средняя кнопка мыши
  code/__DEFINES/dcs/signals.dm
  code/_onclick/click.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: Tweak

#7199 фикс шлемов нюки
  icons/mob/head.dmi
Labels: Sprites

#7190 теперь флешбенг взорванный в руках станит намного сильнее
  code/game/objects/items/weapons/grenades/flashbang.dm
Labels: Balance

#7196 Ломать таблетки пополам
  code/modules/reagents/reagent_containers/pill.dm
  icons/obj/chemical.dmi
Labels: Feature, Sprites

#7195 незначительные улучшения анимаций у взаимодействий соулстона
  code/__HELPERS/game.dm
  code/game/gamemodes/wizard/soulstone.dm
  code/game/objects/effects/temp_visual/miscellaneous.dm
  code/modules/mob/living/simple_animal/constructs.dm
  icons/mob/mob.dmi
  taucetistation.dme
Labels: Sprites

#7185 Объединение медицинских модулей борга
  code/modules/events/_event_procs.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/reagent_containers/borghydro.dm
Labels: Experimental, Test Merge Candidate

#7200 В чатик сообщается о надевании наручников
  code/game/objects/items/weapons/handcuffs.dm
Labels: Tweak

#7212 Фикс неснимаеомого проклятия гомункулов
  code/modules/religion/rites/instant/instant.dm
Labels: Fix

#7194 добавляет арену для войны после конца раунда
  code/_globalvars/mapping.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/ticker.dm
  code/datums/outfits/misc/arena.dm
  code/game/area/custom_areas.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/random/random_melee.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  config/example/config.txt
  maps/centcom/centcom.dmm
  taucetistation.dme
Labels: Map Edit, Preferences Update, Special Test Merge, Test Merge Candidate

#7106 Отображение текста на экране СПУ
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/external/ipc.dm
  icons/mob/human_face.dmi
Labels: Feature, Sprites

#7220 Гриппер медборга может держать мозг и таблетки
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
Labels: Fix, Tweak

#7221 Fixing the Wake Up combo
  code/modules/unarmed_combat/combos/helping.dm
Labels: Fix

#7186 Ports "GPS TGUI" from Paradise
  code/__HELPERS/text.dm
  code/__HELPERS/unsorted.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/telesci/gps.dm
  tgui/packages/tgui/interfaces/GPS.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, UI

#7154 Раундстарт Ивенты имени Киборга04 (РИК04) ® ©
  code/__DEFINES/misc.dm
  code/__HELPERS/unsorted.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/events.dm
  code/controllers/subsystem/ticker.dm
  code/datums/helper_datums/events.dm
  code/game/gamemodes/abduction/abduction_gear.dm
  code/game/gamemodes/cult/cult_datums.dm
  code/game/gamemodes/cult/structures/rune.dm
  code/game/machinery/doors/airlock.dm
  code/game/magic/Uristrunes.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/tank_dispenser.dm
  code/game/objects/structures/watercloset.dm
  code/modules/events/_event.dm
  code/modules/events/_event_container.dm
  code/modules/events/_event_procs.dm
  code/modules/events/roundstart_events/area/area_event.dm
  code/modules/events/roundstart_events/area/armory_mess.dm
  code/modules/events/roundstart_events/area/break_light.dm
  code/modules/events/roundstart_events/area/cargo_storage.dm
  code/modules/events/roundstart_events/area/dirt.dm
  code/modules/events/roundstart_events/area/lasertag_ed.dm
  code/modules/events/roundstart_events/area/maintenance.dm
  code/modules/events/roundstart_events/area/minefield.dm
  code/modules/events/roundstart_events/area/replace/deathly_sec.dm
  code/modules/events/roundstart_events/area/replace/del_cable.dm
  code/modules/events/roundstart_events/area/replace/del_surgeon_tools.dm
  code/modules/events/roundstart_events/area/replace/med_morgue.dm
  code/modules/events/roundstart_events/area/replace/med_storage.dm
  code/modules/events/roundstart_events/area/replace/mince_back.dm
  code/modules/events/roundstart_events/area/replace/random_airlock.dm
  code/modules/events/roundstart_events/area/replace/replace.dm
  code/modules/events/roundstart_events/area/replace/sec_weapons.dm
  code/modules/events/roundstart_events/area/replace/vault_gold.dm
  code/modules/events/roundstart_events/misc_events.dm
  code/modules/events/roundstart_events/roundstart.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/robot.dm
  code/modules/mob/living/simple_animal/friendly/walle.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/power/cable.dm
  code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
  code/modules/projectiles/ammunition.dm
  code/modules/reagents/reagent_containers/extinguisher.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/scrap/scrap.dm
  taucetistation.dme
Labels: Config Update, Feature, Test Merge Candidate, Tweak

#7214 Раскрашивание банок для таблеток
  code/game/objects/items/weapons/storage/firstaid.dm
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Feature, Map Edit

#7225 Добавление возможности отправки сообщений напрямую из Crew Manifest в ПДА.
  code/game/objects/items/devices/PDA/PDA.dm
  nano/templates/pda.tmpl
Labels: Tweak

#7222 Update "Orbit Menu" v1.1
  code/modules/mob/dead/observer/orbit.dm
  tgui/packages/tgui/interfaces/Orbit.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Merge Conflict, Tweak, UI

#7187 Port [Guest Pass Terminal] from Paradise
  code/__DEFINES/misc.dm
  code/__HELPERS/text.dm
  code/game/jobs/access.dm
  code/game/machinery/computer/guestpass.dm
  tgui/packages/tgui/interfaces/GuestPass.js
  tgui/packages/tgui/interfaces/common/AccessList.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Merge Conflict, UI

#7090 Gulping bottles in one go
  code/game/machinery/bots/farmbot.dm
  code/game/objects/items/weapons/paint.dm
  code/game/objects/items/weapons/weldbackpack.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/research/xenoarchaeology/genetics/prehistoric_plants.dm
Labels: Feature

#7235 Фикс ширины окна PDA в соответствии с новой кнопкой "DM" в Crew Manifest
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Fix

#7251 fixing the #7090 ramen issue
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Fix

#7240 Стейлбот пока, Привет Стейлбот
  .github/stale.yml
  .github/workflows/stale.yml
Labels: Tools

#7230 Фикс бага с хирургическим столом
  code/game/machinery/OpTable.dm
Labels: Fix
