Repository TauCetiStation/TauCetiClassic, pull requests merged in 2021-11, with the labels that each got.

#8090 даёт хосу и кэпу дубинку власти
  code/__DEFINES/atom_hud.dm
  code/datums/atom_huds/atom_hud_data.dm
  code/datums/outfits/jobs/command.dm
  code/datums/outfits/jobs/security.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob_helpers.dm
  icons/mob/hud.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/weapons.dmi
  maps/boxstation/boxstation.dmm
Labels: Balance, Feature, Sprites

#8146 Более предсказуемый алгоритм перемещения по камерам
  code/modules/mob/mob_movement.dm
Labels: Tweak

#8152 Бафф трейтороброни.
  code/datums/uplinks_items.dm
  code/modules/clothing/suits/armor.dm
  icons/mob/suit.dmi
Labels: Sprites, Tweak

#8151 переименовывает лидера культа в предвестника
  code/__DEFINES/gamemodes.dm
  code/game/gamemodes/factions/cult.dm
Labels: Tweak

#8147 Фикс засовывания Яна в washing machine
  code/game/machinery/washing_machine.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#8115 Больше возможностей щитспавна для адменов
  code/__DEFINES/gamemodes.dm
  code/__HELPERS/game.dm
  code/datums/mind.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/factions/props.dm
  code/game/gamemodes/objectives/prop_points.dm
  code/game/gamemodes/roles/prop.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/chameleonproj.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm
  taucetistation.dme
Labels: Admin, Tweak, Test Merge Candidate

#8150 Drag 'n drop для раздатчиков труб
  code/game/machinery/pipe/pipe_dispenser.dm
Labels: Tweak

#8172 Фиолетовый имплант теперь виден в бодисканнере
  code/game/machinery/adv_med.dm
Labels: Tweak

#8102 Замена проверки istypа на проверку sharpа и температуры.
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/events/cellular_biomass/biomass.dm
  code/modules/events/cellular_biomass/spacevines.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Tweak

#8169 ящик стазисбагов
  code/modules/cargo/packs.dm
Labels: Feature

#8149 Выдаём боргам возможность вырезать мусорки
  code/modules/recycling/disposal.dm
Labels: Tweak

#8176 Пачка фиксов культа
  code/game/objects/items/weapons/storage/bible/bible.dm
  code/game/objects/items/weapons/storage/bible/tome_upgraded.dm
  code/modules/maps/maps_code/stationCollision.dm
  code/modules/paperwork/pen.dm
  code/modules/religion/atoms_religify.dm
  code/modules/religion/encyclopedia.dm
  code/modules/religion/religion.dm
  code/modules/religion/rites/instant/instant.dm
Labels: Fix

#7760 Dynamic Asteroid Mob Spawning
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/game.dm
  code/datums/components/spawn_area.dm
  code/modules/mining/mine_areas.dm
  code/modules/mining/mine_turfs.dm
  icons/turf/areas.dmi
  maps/asteroid/asteroid.dmm
  taucetistation.dme
Labels: Feature, Performance, Test Merge Candidate, Pinned

#8181 Fixed exotic particles power utilizer
  code/modules/research/xenoarchaeology/tools/particles_battery_utilizer.dm
Labels: Fix

#8180 Фикс заклинания телепортации мага
  code/datums/spells/area_teleport.dm
Labels: Fix, Tweak

#8188 Фикс определения ионного закона как emote
  code/__HELPERS/unsorted.dm
Labels: Fix, Tweak

#8194 Убраны лишние скобочки вокруг COORD макроса
  code/game/machinery/camera/camera.dm
  code/modules/lighting/lighting_object.dm
  code/modules/reagents/Chemistry-Holder.dm
Labels: Admin

#8191 fix xenomorph confusion
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Fix

#8049 Revert "Asteroid turfs transparent now"
  code/__HELPERS/icon_smoothing.dm
  code/controllers/subsystem/icon_smooth.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/turf.dm
  code/modules/mining/mine_turfs.dm
  icons/turf/asteroid.dmi
  icons/turf/floors.dmi
Labels: Test Merge Candidate

#8039 Пофиксил жукбокс, теперь он отключается от области при откручивании.
  code/modules/media/jukebox.dm
Labels: Fix, Test Merge Candidate

#8183 Фикс метода ghostize и его не установки времени смерти
  code/modules/mob/dead/observer/observer.dm
  code/modules/sports/pbag.dm
Labels: Fix, Test Merge Candidate

#8145 Мелкофиксы СПУ (снова я)
  code/game/objects/items/stacks/medical.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
  code/modules/mob/mob.dm
  code/modules/surgery/ribcage.dm
Labels: Fix, Feature

#8158 Респрайт одежды кадета.
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#8199 Удаление микса
  code/game/gamemodes/modesbundle.dm
Labels: Revert / Removal

#8202 Временное выключение воксов из ротации
  code/game/gamemodes/modes_declares/heist.dm
Labels: Revert / Removal

#8168 Зум компонента
  code/__DEFINES/dcs/signals.dm
  code/_onclick/hud/action.dm
  code/datums/components/zoom.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/mob_movement.dm
  code/modules/projectiles/guns/energy/special.dm
  icons/mob/actions.dmi
  taucetistation.dme
Labels: Fix, Refactor, Test Merge Candidate

#8164 клоны больше не могут быть клонированы
  code/game/machinery/computer/cloning.dm
Labels: Balance, Experimental, Test Merge Candidate

#8173 Больше голопадов на спутнике ИИ
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#8193 Fix runtime if try to jump on fake AI radio messages
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/autosay/autosay.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/carbon/brain/brain.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/say.dm
  taucetistation.dme
Labels: Fix, Test Merge Candidate

#8185 респрайт коктейлей
  icons/obj/drinks.dmi
Labels: Sprites

#8187 РП-БЛОБ
  code/__DEFINES/is_helpers.dm
  code/game/gamemodes/factions/blob.dm
  code/game/gamemodes/modes_gameplays/blob/blobmouse.dm
  code/game/gamemodes/modes_gameplays/blob/overmind.dm
  code/game/gamemodes/roles/blob.dm
  taucetistation.dme
Labels: Tweak, Test Merge Candidate

#8197 Убрал обновление окна Коммуникаций с ЦК, Атмос Алерта.
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/vending.dm
Labels: Fix, Tweak, Test Merge Candidate

#8205 Фикс бага админ блобайзинга
  code/game/gamemodes/modes_gameplays/blob/blobs/core.dm
  code/game/gamemodes/roles/blob.dm
  code/modules/admin/verbs/debug.dm
  code/modules/events/blob.dm
  code/modules/mob/transform_procs.dm
Labels: Fix, Test Merge Candidate

#8208 Добавлен анимированный point
  code/__DEFINES/_planes+layers.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/decals/misc.dm
  code/modules/mob/mob.dm
Labels: Feature, Test Merge Candidate

#8219 Добавлен эмоджи smoltaj
  code/modules/goonchat/browserassets/css/emoji.css
  code/modules/goonchat/browserassets/css/emoji/smoltaj.png
  code/modules/goonchat/browserassets/css/emojib64.css
  code/modules/goonchat/browserassets/js/emojiList.json
Labels: Tweak

#8215 Форматирование noob_notify и метод trim_margin()
  code/__HELPERS/game.dm
  code/__HELPERS/text.dm
  code/modules/admin/admin.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/mentor/mentor.dm
Labels: Admin

#8211 Event Manager Panel for +DEBUG
  code/modules/admin/admin_verbs.dm
Labels: Admin

#8210 Фикс рантайма ресурс блоба
  code/game/gamemodes/modes_gameplays/blob/blobs/resource.dm
Labels: Fix

#8148 аплинк в интерком
  code/_globalvars/lists/objects.dm
  code/datums/components/gamemodes/syndicate.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/modules/client/character menu/roles.dm
Labels: Feature, Test Merge Candidate, Preferences Update

#8178 Научные риги/Science hardsuits
  code/datums/helper_datums/teleport.dm
  code/game/machinery/telecomms/presets.dm
  code/game/machinery/teleporter.dm
  code/game/machinery/vending/modkit.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/devices/modkit.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mining/mining_fabricator/mining_research.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/rig_modules.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  icons/obj/clothing/species/vox/hats.dmi
  icons/obj/clothing/species/vox/suits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/rig_modules.dmi
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
Labels: Feature, Map Edit, Sprites

#8223 Цветой маркер READY
  code/controllers/subsystem/jobs.dm
  code/modules/mob/dead/new_player/lobby.dm
  code/modules/mob/dead/new_player/logout.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Tweak

#8222 Фикс сообщений при захвате зоны культом + фича
  code/game/gamemodes/modes_gameplays/cult/cult_datums.dm
  code/modules/religion/religion.dm
Labels: Tweak

#8166 Фикс рантайма в случаях когда передвигают подключаемых к ИВЛ
  code/game/machinery/life_assist.dm
Labels: Fix, Test Merge Candidate

#8235 Проклятый кубик больше не работает на культистов
  code/game/objects/items/weapons/dice.dm
Labels: Balance

#8241 Clear vis locs and vis_contetns
  code/game/atoms_movable.dm
  code/game/turfs/turf.dm
Labels: Tweak

#8221 Анимация дерганья чего-то всегда будет видна
  code/game/animation_helpers.dm
Labels: Fix, Test Merge Candidate

#8220 Эмоуты для игры "камень-ножницы-бумага"
  code/__DEFINES/misc.dm
  code/modules/mob/living/carbon/brain/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/ian/emote.dm
  code/modules/mob/living/carbon/metroid/emote.dm
  code/modules/mob/living/carbon/monkey/emote.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/emote.dm
  code/modules/mob/living/carbon/xenomorph/larva/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/rps_game.dm
  taucetistation.dme
Labels: Tweak

#8233 Фикс клонирования/дефибрилляции болванчиков
  code/modules/surgery/braincore.dm
  code/modules/surgery/limbs.dm
Labels: Fix

#8212 Новые напитки. / New Drinks.
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites, Awaiting Review [Sprite Dep]

#8251 smartfridge/secured access check
  code/game/machinery/kitchen/smartfridge.dm
Labels: Fix

#8258 New sprites of atmosia
  icons/obj/atmos.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#8247 Минорные фиксы связанного с антагами
  code/datums/components/gamemodes/syndicate.dm
  code/game/gamemodes/roles/revolution.dm
  code/game/gamemodes/roles/shadowling.dm
Labels: Fix

#8253 Return 1,0 -> Return TRUE,FALSE (1)
  code/__DEFINES/mc.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/sight.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/files.dm
  code/__HELPERS/game.dm
  code/__HELPERS/icon_smoothing.dm
  code/__HELPERS/time.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/adjacent.dm
  code/_onclick/hud/action.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/monkey.dm
  code/_onclick/hud/parallax.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/item_attack.dm
  code/_onclick/telekinesis.dm
Labels: Refactor

#8227 Улучшение защиты укрепленного стола
  code/game/objects/structures/tables_racks.dm
Labels: Tweak

#8250 mime verbs to spells
  code/datums/spells/mime.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/jobprocs.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  icons/mob/actions.dmi
  taucetistation.dme
Labels: Sprites, Tweak

#8259 Фикс двойного анонса об отыскании нарушителя
  code/game/gamemodes/modes_gameplays/malfunction/Malf_Modules.dm
Labels: Fix

#8229 [Alien] ЦК будет присылать помощь во время режима infestation
  code/__DEFINES/xenomorph.dm
  code/controllers/subsystem/shuttles.dm
  code/datums/announcements/gamemode.dm
  code/game/gamemodes/factions/infestation.dm
  code/modules/cargo/console.dm
  code/modules/cargo/packs.dm
Labels: Balance

#7885 фикс калибрации меха
  code/game/mecha/mecha_topic.dm
Labels: Fix, Stalled PR

#8236 Ритуал дезалярма
  code/_globalvars/lists/objects.dm
  code/datums/components/bell_death_alarm.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/structures/chapel.dm
  code/modules/religion/rites/instant/death_alarm.dm
  code/modules/religion/rites/instant/instant.dm
  taucetistation.dme
Labels: Feature

#8276 Добавил взрывной имплант в аплинк
  code/datums/uplinks_items.dm
Labels: Feature

#8271 Outpost miscellaneous research remap
  code/modules/research/xenoarchaeology/genetics/reconstitutor.dm
  maps/asteroid/asteroid.dmm
Labels: Map Edit

#8275 Фикс мили мехов
  code/game/mecha/combat/combat.dm
Labels: Fix

#8260 Cooldown for spells
  code/_onclick/hud/screen_objects.dm
  code/datums/spell.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
Labels: Tweak

#8268 Локализация квирков
  code/__DEFINES/quirks.dm
  code/datums/traits/negative.dm
  code/datums/traits/neutral.dm
  code/datums/traits/positive.dm
Labels: Translation/Localization

#8252 shuttle wont send atoms to centcom when arriving & always gibs livings
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/shuttles.dm
  code/modules/locations/shuttles/mine_sci_shuttle.dm
Labels: Fix, Tweak

#8254 Return 1,0 -> Return TRUE,FALSE (2)
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/demo.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/jobs.dm
  code/controllers/subsystem/shuttles.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/voting/poll.dm
  code/datums/components/swiping.dm
  code/datums/disease.dm
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/symptoms/damage_converter.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/robotic_transformation.dm
  code/datums/diseases/xeno_transformation.dm
  code/datums/helper_datums/construction_datum.dm
  code/datums/helper_datums/events.dm
  code/datums/helper_datums/teleport.dm
  code/datums/mind.dm
  code/datums/spell.dm
  code/datums/spells/conjure.dm
  code/datums/spells/in_hand.dm
  code/datums/spells/spacetime_distrortion.dm
  code/datums/spells/wizard.dm
  code/datums/uplinks_items.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_types.dm
  code/defines/obj/hydro.dm
  code/defines/procs/dbcore.dm
  maps/testmap/job_changes.dm
Labels: Refactor

#8295 Фикс пулла алиенов
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
Labels: Fix

#8234 Порт унификации плейнов и ретрансляции рендера c ТГ
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/flags.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/map_popups.dm
  code/_onclick/hud/parallax.dm
  code/_onclick/hud/plane_master.dm
  code/_onclick/hud/rendering/_render_readme.md
  code/_onclick/hud/rendering/plane_master.dm
  code/_onclick/hud/rendering/plane_master_controller.dm
  code/_onclick/hud/rendering/render_plate.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/subsystem/demo.dm
  code/datums/spells/in_hand.dm
  code/game/area/areas.dm
  code/game/gamemodes/modes_gameplays/shadowling/ascendant_shadowling.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/lightswitch.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/effects/decals/misc.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items/weapons/storage/storage_ui/default.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/lighting/lighting_object.dm
  code/modules/mafia/roles.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/silicon/ai/freelook/chunk.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/power/tesla/energy_ball.dm
  code/modules/projectiles/effects.dm
  code/modules/scrap/scrap_tornado.dm
  taucetistation.dme
Labels: Refactor, Tweak, Test Merge Candidate

#8239 гладиаторы = игроки
  code/controllers/subsystem/ticker.dm
Labels: Tweak, Test Merge Candidate

#8273 Fix converted heads not being counted in RP rev
  code/__DEFINES/is_helpers.dm
  code/game/gamemodes/factions/revolution.dm
  code/game/gamemodes/objectives/target/rp_rev.dm
Labels: Fix

#8288 Генокрад в стазисе больше не считается за мертвого в целях
  code/game/gamemodes/objectives/survive.dm
  code/game/gamemodes/objectives/target/assassinate.dm
Labels: Fix

#8270 Рефактор двуручной компоненты
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/traits.dm
  code/datums/components/mechanic_description.dm
  code/datums/components/twohanded.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/poddoor.dm
  code/game/objects/items/weapons/defibrillator.dm
  code/game/objects/items/weapons/makeshift.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/simulated/floor.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/rocket.dm
Labels: Fix, Refactor

#8237 Переработан способ получения эктоплазмы с фотки с призраками
  code/modules/paperwork/photography.dm
Labels: Fix, Refactor, Tweak

#8246 portalgun
  code/game/objects/effects/portals.dm
  code/modules/projectiles/ammunition/special.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
  icons/obj/stationobjs.dmi
  sound/weapons/guns/portalgun.ogg
Labels: Feature, Sprites, Test Merge Candidate

#8306 Небольшой фикс бумаги на робостанции
  maps/templates/space_structures/robostation.dmm
Labels: Map Edit

#8248 Новые папки
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/paperwork/folders.dm
  icons/obj/bureaucracy.dmi
  maps/boxstation/boxstation.dmm
Labels: Feature, Sprites, Awaiting Review [Sprite Dep]

#8117 Runlevels
  code/__DEFINES/flags.dm
  code/__DEFINES/math.dm
  code/__DEFINES/mc.dm
  code/__DEFINES/subsystem.dm
  code/__DEFINES/tick.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/unsorted.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/chat.dm
  code/controllers/subsystem/diseases.dm
  code/controllers/subsystem/events.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/mob_modifier.dm
  code/controllers/subsystem/mobs.dm
  code/controllers/subsystem/nanoui.dm
  code/controllers/subsystem/nightshift.dm
  code/controllers/subsystem/overlays.dm
  code/controllers/subsystem/parallax.dm
  code/controllers/subsystem/shuttles.dm
  code/controllers/subsystem/spacedrift.dm
  code/controllers/subsystem/sun.dm
  code/controllers/subsystem/tgui.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/timer.dm
  code/controllers/subsystem/vote.dm
  code/controllers/subsystem/weather.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/mob/dead/new_player/logout.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/unit_tests/unit_test.dm
Labels: Test Merge Candidate

#8242 Можно изменять фильтры прямо во время игры.
  code/__DEFINES/colors.dm
  code/__HELPERS/filters.dm
  code/datums/datumvars.dm
  code/modules/admin/holder2.dm
  code/modules/admin/verbs/filterrific.dm
  code/modules/client/client procs.dm
  taucetistation.dme
  tgui/packages/common/math.js
  tgui/packages/tgui/components/Dropdown.js
  tgui/packages/tgui/interfaces/Filteriffic.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Tweak, Test Merge Candidate, UI
