Repository TauCetiStation/TauCetiClassic, pull requests merged in 2021-08, with the labels that each got.

#7684 убирает дротики для дробовика из автолата
  code/game/machinery/autolathe.dm
Labels: Balance, Tweak

#7710 закрывает глоки в малой оружейке в шкафчик
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  icons/obj/closet.dmi
  maps/boxstation/boxstation.dmm
Labels: Balance, Map Edit, Sprites, Tweak

#7697 Correct economy account date
  code/modules/economy/Accounts.dm
Labels: Fix

#7693 перевод снов
  code/modules/flufftext/Dreaming.dm
Labels: Translation/Localization, Awaiting Review [Translation Dep]

#7702 Обновление инфы о ПДА теперь изменяет и имя владельца
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Tweak

#7750 SecHUD Icons Recolor&Resprite
  icons/mob/hud.dmi
Labels: Sprites

#7746 Чистая Система Настроения Без Надстроек
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mob.dm
  code/__DEFINES/subsystem.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/mobs.dm
  code/_onclick/click.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/subsystem/processing/moods.dm
  code/controllers/subsystem/processing/processing.dm
  code/datums/components/mood.dm
  code/datums/mood_events/_mood_event.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/login.dm
  code/modules/mob/mob_defines.dm
  icons/mob/screen1.dmi
  icons/mob/screen1_Midnight.dmi
  icons/mob/screen1_Orange.dmi
  icons/mob/screen1_White.dmi
  icons/mob/screen1_old.dmi
  taucetistation.dme
Labels: Feature, Sprites

#7736 фиксит реакцию в банке star-kist
  code/modules/reagents/reagent_containers/food/cans.dm
Labels: Tweak

#7765 conveyor are clickplaceable... again
  code/modules/recycling/conveyor2.dm
Labels: Fix

#7734 Добавил сахарный тростник в торговый автомат гидропоники.
  code/game/machinery/vending/hydroponics.dm
Labels: Tweak

#7764 part fix for #7762
  code/modules/admin/secrets/secrets_menu/custom_announcement.dm
Labels: Fix

#7779 изменение одежды и снаряжения копов
  code/game/gamemodes/modes_gameplays/families/outfit.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/back.dmi
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/storage.dmi
Labels: Sprites, Tweak

#7768 opening armour window doors with a push of just one button
  code/_globalvars/lists/objects.dm
  code/datums/wires/airlock.dm
  code/game/machinery/door_control.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/devices/multitool.dm
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Feature, Map Edit, Test Merge Candidate

#7789 Важные фиксы системы гейм мода
  code/game/gamemodes/factions.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/role.dm
  code/game/gamemodes/roles/revolution.dm
  code/modules/mob/living/carbon/xenomorph/effects/aliens.dm
  code/modules/religion/religion_types/cult.dm
Labels: Fix

#7795 post death vision/hallucinating fix
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  code/modules/reagents/reagent_types/Chemistry-Foods.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
  code/modules/virus2/effect.dm
Labels: Fix

#7801 Detectiverevolver
  code/game/machinery/autolathe.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  icons/obj/gun.dmi
Labels: Feature, Sprites

#7802 darkness planes
  code/_onclick/hud/action.dm
  code/game/gamemodes/modes_gameplays/blob/overmind.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/augmented_eyesight.dm
  code/game/gamemodes/modes_gameplays/shadowling/ascendant_shadowling.dm
  code/game/gamemodes/modes_gameplays/shadowling/shadowling_items.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/login.dm
  code/modules/mob/mob_defines.dm
Labels: Tweak

#7810 Добавление фиксов и фич культу
  code/__DEFINES/dcs/signals.dm
  code/datums/ai_laws.dm
  code/datums/mind.dm
  code/game/gamemodes/factions.dm
  code/game/gamemodes/factions/cult.dm
  code/game/gamemodes/factions/shadowling.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/misc_faction_procs.dm
  code/game/gamemodes/modes_gameplays/cult/cult_datums.dm
  code/game/gamemodes/role.dm
  code/game/gamemodes/roles/cultist.dm
  code/modules/religion/bible_info.dm
  code/modules/religion/religion.dm
  code/modules/religion/religion_types/cult.dm
  code/modules/religion/rites/standing/consent.dm
  code/modules/religion/tech.dm
Labels: Fix, Balance

#7813 Удалил не используемый механ
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/modes_declares/revolution.dm
  code/game/periodic_news.dm
Labels: Revert / Removal

#7816 Запрещает рисовать граффити под аирлоком, сквозь стекло, под столом и тд
  code/game/objects/items/crayons.dm
Labels: Fix

#7815 Пачка фиксов для глушителя
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/silencer.dm
Labels: Fix, Tweak

#7803 no extended in action bundles
  code/_globalvars/game_modes.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/modesbundle.dm
Labels: Revert / Removal

#7820 [Families ReBalance] Фултон помещен в рацию-аплинк дилера
  code/game/gamemodes/modes_gameplays/families/outfit.dm
  code/game/gamemodes/roles/families.dm
  code/game/objects/items/devices/uplinks.dm
  code/game/objects/items/weapons/fulton.dm
Labels: Balance

#7826 Removed engine access from HoP, HoS and IAA
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/security.dm
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#7708 Bridge discord commands
  code/__DEFINES/bridge.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/sanitize_values.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/ticker.dm
  code/game/machinery/fax.dm
  code/game/response_team.dm
  code/game/verbs/ooc.dm
  code/game/world.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/pray.dm
  code/modules/bridge/chat_bridge.dm
  code/modules/bridge/commands/bans.dm
  code/modules/bridge/commands/communications.dm
  code/modules/bridge/commands/help.dm
  code/modules/bridge/commands/misc.dm
  code/modules/bridge/commands/notes.dm
  code/modules/bridge/commands/ooc_chat.dm
  code/modules/bridge/commands/player_panel.dm
  code/modules/bridge/commands/round.dm
  code/modules/bridge/commands/status.dm
  code/modules/bridge/commands/tickets.dm
  code/modules/bridge/commands/who.dm
  code/modules/client/client procs.dm
  code/modules/client/guard.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  taucetistation.dme
Labels: Test Merge Candidate, Config Update

#7861 фиксит шлюзы в доке шаттла обр
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#7844 Почистил example-конфиг от возможно устаревшей информации
  config/example/config.txt
Labels: Config Update

#7799 take_overall_damage, electrocute_act fix
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/power/power.dm
Labels: Fix

#7865 514
  .github/workflows/ci_suite.yml
  code/_compile_options.dm
  code/_globalvars/bitfields.dm
  code/modules/roguelike/mob_modifiers/positive.dm
  config/example/config.txt
Labels: Config Update

#7871 Поправил описание модуля
  code/modules/research/research.dm
Labels: Tweak

#7882 Рецепт гиперцина перестал быть
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Balance, Revert / Removal

#7867 Улучшение пары присутствующих звуков
  sound/ambience/general_1.ogg
  sound/effects/writing/keyboard1.ogg
  sound/effects/writing/keyboard2.ogg
  sound/effects/writing/keyboard3.ogg
  sound/effects/writing/keyboard4.ogg
  sound/effects/writing/keyboard5.ogg
Labels: Sound

#7835 noticeboard !!!alert!!!
  code/datums/atom_huds/alternate_apperance.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/noticeboard.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/simulated/walls_reinforced.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/research/xenoarchaeology/misc.dm
  icons/obj/notice_board.dmi
  icons/obj/objects.dmi
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Feature, Map Edit, Sprites

#7886 добавляет потерявшийся турф на ферри шаттле
  maps/centcom/centcom.dmm
Labels: Map Edit
