Repository TauCetiStation/TauCetiClassic, pull requests merged in 2021-09, with the labels that each got.

#7758 Емагом теперь можно вызывать анонсы малфа.
  code/__DEFINES/misc.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/factions/malf_silicons.dm
  code/game/gamemodes/modes_gameplays/malfunction/Malf_Modules.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob.dm
  code/modules/power/apc.dm
Labels: Feature

#7749 Вариант Наполнения Фреймворка Настроений
  code/__DEFINES/beauty.dm
  code/__DEFINES/dcs/flags.dm
  code/__DEFINES/dcs/helpers.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mob.dm
  code/__DEFINES/subsystem.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/processing/dcs.dm
  code/datums/components/mood.dm
  code/datums/elements/_element.dm
  code/datums/elements/beauty.dm
  code/datums/modifiable_value/_modifiable_value.dm
  code/datums/mood_events/beauty_events.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/mood_events/needs_events.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/effects/decals/Cleanable/aliens.dm
  code/game/objects/effects/decals/Cleanable/fuel.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/effects/decals/Cleanable/robots.dm
  code/game/objects/effects/decals/Cleanable/tracks.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/defibrillator.dm
  code/game/objects/structures/flora.dm
  code/modules/clothing/clothing.dm
  code/modules/events/cellular_biomass/biome_bluespace.dm
  code/modules/events/cellular_biomass/biome_meat.dm
  code/modules/events/cellular_biomass/biome_mine.dm
  code/modules/events/cellular_biomass/biome_necro.dm
  code/modules/mining/mine_areas.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/blob/blob.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/ian/inventory.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_defines.dm
  code/modules/scrap/scrap.dm
  code/modules/scrap/scrap_refine.dm
  code/modules/surgery/surgery.dm
  code/modules/zwater/wet_stuff.dm
  taucetistation.dme
Labels: Feature, Sprites, Test Merge Candidate

#7883 readds some nightvision to thermals
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Fix

#7875 add examinate to AI
  code/_onclick/ai.dm
Labels: Feature

#7848 shadow_walk & phaseshift made into ethereal_jaunt
  code/datums/spells/ethereal_jaunt.dm
  code/datums/spells/wizard.dm
  code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
  code/game/gamemodes/modes_gameplays/wizard/artefact.dm
  code/game/gamemodes/modes_gameplays/wizard/rightandwrong.dm
  code/game/gamemodes/modes_gameplays/wizard/spellbook.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/constructs.dm
Labels: Tweak

#7901 There is no hyperzine in ambrosia deus
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Revert / Removal

#7892 T-ray scanner для дронов.
  code/modules/mining/drilling/drill.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Tweak

#7731 Баланс цен на всякие штуки
  code/modules/cargo/prices.dm
  code/modules/holodeck/HolodeckControl.dm
Labels: Stalled PR

#7874 Позволяет гостам открыть ТГУИшку и позырить че там нажмает юзер
  code/game/objects/objs.dm
Labels: Tweak

#7863 Фикс невозможности скелетофицировать рядового человека
  code/modules/religion/rites/pedestals/pedestals.dm
Labels: Fix

#7824 Baton holster bug fix
  code/game/objects/items/weapons/storage/pouches.dm
Labels: Fix, Stalled PR

#7914 Removed SES items from junk
  code/game/objects/random/random_cloth.dm
Labels: Fix

#7887 Фиксы и удаление столкновения у инвалидного кресла
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
Labels: Fix, Revert / Removal

#7701 Религиозная энциклопедия, интерфейс для алтаря
  code/__DEFINES/religion.dm
  code/modules/religion/altar_types/altar_of_gods.dm
  code/modules/religion/altar_types/cult/altar_of_gods.dm
  code/modules/religion/aspect.dm
  code/modules/religion/encyclopedia.dm
  code/modules/religion/religion.dm
  code/modules/religion/religion_sects.dm
  code/modules/religion/rites_type/rites.dm
  taucetistation.dme
  tgui/packages/tgui/interfaces/ReligiousTool.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Test Merge Candidate, UI

#7894 Понижение количества игроков до спавна двух магов
  code/game/gamemodes/factions/wizards.dm
Labels: Balance

#7900 Cult will produce random anomaly announcement
  code/datums/announcements/events.dm
  code/datums/announcements/gamemode.dm
  code/game/gamemodes/modes_gameplays/cult/cult_datums.dm
  code/modules/events/cult_portals.dm
Labels: Fix

#7889 Jukebox alive . . ?
  code/game/sound.dm
  code/modules/media/mediamanager.dm
Labels: Fix

#7924 Chemistry light fixture move
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#7905 new_moodlets
  code/datums/mood_events/antags_events.dm
  code/datums/mood_events/generic_negative_events.dm
  code/game/gamemodes/roles/revolution.dm
  code/game/gamemodes/roles/shadowling.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/living.dm
  taucetistation.dme
Labels: Feature

#7919 Фикс рантайма интерфейса алтаря
  tgui/packages/tgui/interfaces/ReligiousTool.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Fix, UI

#7860 Космонавтам теперь смешно
  code/_globalvars/lists/sound.dm
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/laugh/human_female/laugh_female-1.ogg
  sound/voice/laugh/human_female/laugh_female-2.ogg
  sound/voice/laugh/human_female/laugh_female-3.ogg
  sound/voice/laugh/human_female/laugh_female-4.ogg
  sound/voice/laugh/human_female/laugh_female-5.ogg
  sound/voice/laugh/human_female/laugh_female-6.ogg
  sound/voice/laugh/human_female/laugh_female-7.ogg
  sound/voice/laugh/human_female/laugh_female-8.ogg
  sound/voice/laugh/human_female/laugh_female-9.ogg
  sound/voice/laugh/human_male/laugh_male-1.ogg
  sound/voice/laugh/human_male/laugh_male-2.ogg
  sound/voice/laugh/human_male/laugh_male-3.ogg
  sound/voice/laugh/human_male/laugh_male-4.ogg
  sound/voice/laugh/human_male/laugh_male-5.ogg
  sound/voice/laugh/human_male/laugh_male-6.ogg
  sound/voice/laugh/human_male/laugh_male-7.ogg
  sound/voice/laugh/human_male/laugh_male-8.ogg
  sound/voice/laugh/human_male/laugh_male-9.ogg
  sound/voice/laugh/skrell_female/laugh_female-1.ogg
  sound/voice/laugh/skrell_female/laugh_female-2.ogg
  sound/voice/laugh/skrell_female/laugh_female-3.ogg
  sound/voice/laugh/skrell_female/laugh_female-4.ogg
  sound/voice/laugh/skrell_female/laugh_female-5.ogg
  sound/voice/laugh/skrell_female/laugh_female-6.ogg
  sound/voice/laugh/skrell_female/laugh_female-7.ogg
  sound/voice/laugh/skrell_female/laugh_female-8.ogg
  sound/voice/laugh/skrell_female/laugh_female-9.ogg
  sound/voice/laugh/skrell_male/laugh_male-1.ogg
  sound/voice/laugh/skrell_male/laugh_male-2.ogg
  sound/voice/laugh/skrell_male/laugh_male-3.ogg
  sound/voice/laugh/skrell_male/laugh_male-4.ogg
  sound/voice/laugh/skrell_male/laugh_male-5.ogg
  sound/voice/laugh/skrell_male/laugh_male-6.ogg
  sound/voice/laugh/skrell_male/laugh_male-7.ogg
  sound/voice/laugh/skrell_male/laugh_male-8.ogg
  sound/voice/laugh/skrell_male/laugh_male-9.ogg
Labels: Test Merge Candidate, Sound

#7935 Edagger now can't be embedded
  code/modules/paperwork/pen.dm
Labels: Tweak

#7939 Фикс тележки с мороженым
  code/game/machinery/icecream_vat.dm
Labels: Fix

#7932 Noticeboard Features and Fixes
  code/datums/atom_huds/alternate_apperance.dm
  code/game/objects/structures/noticeboard.dm
Labels: Fix

#7876 fix spill gease, spawn food and create bible
  code/datums/spell.dm
  code/datums/spells/charge.dm
  code/datums/spells/dumbfire.dm
  code/datums/spells/religion.dm
  code/game/gamemodes/modes_gameplays/wizard/artefact.dm
  code/game/gamemodes/modes_gameplays/wizard/rightandwrong.dm
  code/game/gamemodes/modes_gameplays/wizard/spellbook.dm
  code/modules/religion/rites/standing/legacy.dm
  code/modules/religion/tech.dm
Labels: Fix, Merge Conflict

#7908 Armor rebalance
  code/__DEFINES/flags.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/mutations.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/stings.dm
  code/game/gamemodes/modes_gameplays/shadowling/shadowling_items.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/weapons/defibrillator.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/new_hazmat.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/europa/fluids/fluid_mob.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/reagents/syringe_gun.dm
  code/modules/zwater/wet_stuff.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Fix, Balance, Sprites, Resprite, Test Merge Candidate

#7916 Play server sound is back
  code/game/sound.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/playsound.dm
Labels: Admin

#7913 The Gloves of Silence
  code/__DEFINES/dcs/signals.dm
  code/datums/components/silence.dm
  code/datums/uplinks_items.dm
  code/game/objects/random/random_cloth.dm
  code/game/objects/random/random_syndie.dm
  code/game/sound.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/gloves/silence.dm
  code/modules/clothing/under/chameleon.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
  taucetistation.dme
Labels: Feature

#7949 Fix Ian interfase after relogin
  code/modules/client/client procs.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#7922 ТауКита заимела оригинальный параллакс
  code/__DEFINES/preferences.dm
  code/_onclick/hud/parallax.dm
  code/modules/client/character menu/global.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  icons/effects/parallax.dmi
  icons/effects/parallax_classic.dmi
  icons/effects/parallax_tg.dmi
Labels: Sprites, Test Merge Candidate, Preferences Update

#7519 Purge icon2base64()
  code/datums/datumvars.dm
  code/game/gamemodes/factions.dm
  code/game/gamemodes/factions/changeling.dm
  code/game/gamemodes/factions/custom.dm
  code/game/gamemodes/role.dm
  code/game/gamemodes/roles/custom.dm
  code/game/gamemodes/roles/traitor.dm
  code/modules/crafting/craft.dm
  code/modules/goonchat/browserOutput.dm
Labels: Test Merge Candidate, Pinned

#7933 xenoarchaeology part code readability, some artifact changes
  code/__DEFINES/xenoarchaeology.dm
  code/_globalvars/lists/misc.dm
  code/datums/mood_events/artifact_events.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/research/experiment.dm
  code/modules/research/xenoarchaeology/artifact/artifact.dm
  code/modules/research/xenoarchaeology/artifact/artifact_bluespace_crystal.dm
  code/modules/research/xenoarchaeology/artifact/artifact_crystal.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  code/modules/research/xenoarchaeology/artifact/effects/badfeeling.dm
  code/modules/research/xenoarchaeology/artifact/effects/cellcharge.dm
  code/modules/research/xenoarchaeology/artifact/effects/celldrain.dm
  code/modules/research/xenoarchaeology/artifact/effects/cold.dm
  code/modules/research/xenoarchaeology/artifact/effects/dnaswitch.dm
  code/modules/research/xenoarchaeology/artifact/effects/emp.dm
  code/modules/research/xenoarchaeology/artifact/effects/feelings.dm
  code/modules/research/xenoarchaeology/artifact/effects/forcefield.dm
  code/modules/research/xenoarchaeology/artifact/effects/gas.dm
  code/modules/research/xenoarchaeology/artifact/effects/gasco2.dm
  code/modules/research/xenoarchaeology/artifact/effects/gasnitro.dm
  code/modules/research/xenoarchaeology/artifact/effects/gasoxy.dm
  code/modules/research/xenoarchaeology/artifact/effects/gasplasma.dm
  code/modules/research/xenoarchaeology/artifact/effects/gassleeping.dm
  code/modules/research/xenoarchaeology/artifact/effects/goodfeeling.dm
  code/modules/research/xenoarchaeology/artifact/effects/gravity.dm
  code/modules/research/xenoarchaeology/artifact/effects/heal.dm
  code/modules/research/xenoarchaeology/artifact/effects/health.dm
  code/modules/research/xenoarchaeology/artifact/effects/heat.dm
  code/modules/research/xenoarchaeology/artifact/effects/hurt.dm
  code/modules/research/xenoarchaeology/artifact/effects/light.dm
  code/modules/research/xenoarchaeology/artifact/effects/noise.dm
  code/modules/research/xenoarchaeology/artifact/effects/powernet.dm
  code/modules/research/xenoarchaeology/artifact/effects/radiate.dm
  code/modules/research/xenoarchaeology/artifact/effects/roboheal.dm
  code/modules/research/xenoarchaeology/artifact/effects/robohurt.dm
  code/modules/research/xenoarchaeology/artifact/effects/sleepy.dm
  code/modules/research/xenoarchaeology/artifact/effects/stun.dm
  code/modules/research/xenoarchaeology/artifact/effects/teleport.dm
  code/modules/research/xenoarchaeology/artifact/effects/tesla.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_defines.dm
  code/modules/research/xenoarchaeology/finds/finds_special.dm
  code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm
  code/modules/research/xenoarchaeology/machinery/artifact_harvester.dm
  code/modules/research/xenoarchaeology/machinery/artifact_scanner.dm
  code/modules/research/xenoarchaeology/machinery/coolant.dm
  code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
  code/modules/research/xenoarchaeology/tools/particles_battery_utilizer.dm
  taucetistation.dme
Labels: Fix, Feature

#7958 Все интересные штуки в одном файле
  code/_globalvars/lists/pois.dm
  code/game/gamemodes/modes_gameplays/cult/structures/statue.dm
  code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/anomalies.dm
  code/modules/events/immovable_rod.dm
  code/modules/power/singularity/singularity.dm
  code/modules/religion/altar_types/altar_of_gods.dm
  taucetistation.dme
Labels: Refactor

#7943 Airflow sound
  code/modules/atmospheric/ZAS/Airflow.dm
  code/modules/atmospheric/ZAS/ConnectionGroup.dm
  sound/effects/airflow.ogg
Labels: Sound

#7877 Пополнение ассортимента заказов карго и изменение содержимого старых ящиков.
  code/modules/cargo/packs.dm
Labels: Tweak

#7966 fixing dry item moodlets
  code/controllers/subsystem/drying.dm
  code/game/objects/items.dm
  code/game/objects/structures/watercloset.dm
  code/modules/zwater/wet_stuff.dm
Labels: Fix

#7982 Фикс экспорта карго.
  code/modules/cargo/exports.dm
Labels: Fix

#7960 bundles with no runnable modes in them will not be votable
  code/controllers/configuration.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/voting/poll_types.dm
  code/game/gamemodes/modesbundle.dm
Labels: Tweak, Config Update

#7961 Ghost examining naked does not make one sad
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix

#7977 Рольки пии и дионы были полностью удалены из игры
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/misc.dm
  code/modules/admin/topic.dm
  code/modules/client/character menu/roles.dm
  code/modules/client/preferences_savefile.dm
  code/modules/religion/rites/standing/consent.dm
Labels: Tweak, Preferences Update

#7962 Examining masked people doesn't reveal their mood
  code/modules/mob/living/carbon/human/examine.dm
Labels: Tweak

#7985 IsAdvancedToolUser for cryopod
  code/game/machinery/cryopod.dm
Labels: Fix

#7987 consumable/drink/on_general_digest temperature adjust works
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
Labels: Fix

#7974 Phoron overlay above everything yet not clickable
  code/modules/atmospheric/ZAS/Turf.dm
  code/modules/atmospheric/xgm/xgm_gas_data.dm
Labels: Tweak

#7986 crayons draw at the location you click
  code/game/objects/items/crayons.dm
Labels: Tweak

#7999 escape objective restrained check not tied to a specific floor type
  code/game/gamemodes/objectives/escape.dm
Labels: Fix

#7983 Wizard have more tasks
  code/game/gamemodes/roles/wizard.dm
Labels: Tweak

#7934 Asteroid turfs transparent now
  code/__HELPERS/icon_smoothing.dm
  code/controllers/subsystem/icon_smooth.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/turf.dm
  code/modules/mining/mine_turfs.dm
  icons/turf/asteroid.dmi
  icons/turf/floors.dmi
Labels: Fix, Sprites

#7923 Gateway remap
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#7995 Фикс меты на культе через спам порталами
  code/modules/religion/rites/pedestals/pedestals.dm
Labels: Balance

#8007 Фикс спасающих жизнь машинок, потому что я их сломал
  code/game/machinery/iv_drip.dm
  code/game/machinery/life_assist.dm
Labels: Fix

#7954 Повышение цены на Energy marksman crate.
  code/modules/cargo/packs.dm
Labels: Balance

#8000 remote view turf check
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#7981 Рефактор нар-си и фичи ему
  code/datums/mood_events/antags_events.dm
  code/game/gamemodes/modes_gameplays/cult/narsie.dm
  code/modules/events/cult_portals.dm
  code/modules/religion/religion_types/cult.dm
  code/modules/religion/rites/pedestals/pedestals.dm
Labels: Tweak

#8013 Фиксы камеры ИИ
  code/modules/paperwork/photocopier.dm
  code/modules/paperwork/photography.dm
  code/modules/paperwork/silicon_photography.dm
Labels: Fix

#8008 AltClick on /crayon to force drawing appear centered
  code/game/objects/items/crayons.dm
Labels: Tweak

#8023 Фикс настакивания выбора секты в алтаре
  code/modules/religion/altar_types/altar_of_gods.dm
Labels: Fix

#8010 Фикс пэйпер бандлов.
  code/modules/paperwork/paper_bundle.dm
Labels: Fix

#8001 Ghost role ignore list now can be settled from "SETUP"
  code/__DEFINES/role_preferences.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/game.dm
  code/__HELPERS/global_lists.dm
  code/game/gamemodes/factions/cops.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/core.dm
  code/game/objects/items/weapons/antagspawner.dm
  code/modules/admin/verbs/send_police.dm
  code/modules/client/character menu/roles.dm
  code/modules/client/preferences_savefile.dm
  code/modules/events/alien_infestation.dm
  code/modules/events/blob.dm
  code/modules/events/borers.dm
  code/modules/mob/living/carbon/xenomorph/special/alien_embryo.dm
  code/modules/mob/living/simple_animal/borer.dm
Labels: Preferences Update

#8016 [Autolathe] Adding stethoscope
  code/game/machinery/autolathe.dm
  code/modules/clothing/under/accessories/accessory.dm
Labels: Tweak

#8025 delay on mousedrop for rigs
  code/game/objects/items.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/inventory.dm
Labels: Fix

#7992 radial menu for implant removal surgery
  code/modules/surgery/implant.dm
Labels: Feature

#7969 охранные борги теперь только после исследований
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/research.dm
  maps/boxstation/boxstation.dmm
Labels: Balance, Feature, Test Merge Candidate

#8006 Небольшой фикс ИВЛ/Массажа сердца
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
Labels: Fix, Tweak

#7984 Возможность печатать фотографии из всех консолей, где они есть.
  code/game/machinery/computer/computer.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/skills.dm
  icons/obj/mugshot.dmi
Labels: Feature, Sprites

#8041 mobs who cant laugh dont
  code/modules/mob/living/carbon/human/emote.dm
Labels: Fix
