Repository TauCetiStation/TauCetiClassic, pull requests merged in 2021-04, with the labels that each got.

#6989 [Aliens] Увеличил кол-во игроков для старта режима. Алиены в ротацию!
  code/game/gamemodes/infestation/infestation.dm
Labels: Tweak

#6971 Добавляем возможность игрокам смотреть подробную информацию об имеющихся у них джоббанах
  code/modules/admin/banjob.dm
  code/modules/client/character menu/occupation.dm
  code/modules/client/character menu/roles.dm
  code/modules/client/preferences.dm
Labels: Feature

#6995 Исправление реле телекомов станции
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/presets.dm
  code/game/machinery/telecomms/telecomunications.dm
Labels: Fix

#6991 db connection encoding
  code/defines/procs/dbcore.dm
Labels: :atom: BYOND, DO NOT MERGE, Fix

#6951 Configs
  code/controllers/configuration.dm
  code/datums/mind.dm
  code/game/gamemodes/wizard/wizard.dm
  code/game/jobs/jobs.dm
  config/example/config.txt
Labels: Config Update, DO NOT MERGE

#6950 Автолат и патроны
  code/game/machinery/autolathe.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/research/designs.dm
  icons/obj/ammo.dmi
Labels: Sprites, Tweak

#6994 ребаланс тазеров
  code/modules/projectiles/ammunition/energy.dm
  code/modules/projectiles/guns/energy.dm
  maps/boxstation/boxstation.dmm
Labels: Balance, Test Merge Candidate

#6926 добавляет се гранатомёт для уничтожения сингулярности
  code/game/gamemodes/cult/narsie.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/modules/cargo/packs.dm
  code/modules/power/singularity/singularity.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/rocket.dm
  code/modules/projectiles/projectile/special.dm
  icons/mob/back.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Feature, Map Edit, Sprites

#6999 [Alien] Ксеноморфы видят в вентиляции
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Fix

#7000 Все карбоны смогут тушить друг друга на help intent
  code/modules/mob/living/carbon/carbon.dm
Labels: Tweak

#7016 [Alien] В ксенобиологию добавлены 5 мартышек
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit

#7015 [Alien] Нельзя ломать компьютеры, можно плавить APC, кислота быстрее и дешевле.
  code/game/gamemodes/infestation/infestation.dm
  code/game/machinery/alarm.dm
  code/game/machinery/computer/computer.dm
  code/modules/mob/living/carbon/xenomorph/effects/aliens.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/drone.dm
  code/modules/mob/living/carbon/xenomorph/larva/powers.dm
  code/modules/power/apc.dm
  code/modules/projectiles/projectile/special.dm
Labels: Balance, Fix, Tweak

#7018 [Alien] Невидимость охотника, нерф щитов
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/hunter.dm
  icons/mob/xenomorph.dmi
Labels: Balance, Sprites, Tweak

#7012 [Alien] Лицехваты не могли снять шлем, прикрепленный к ригу
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
Labels: Fix

#7020 [Alien] Грудоломы и лицехваты не будут получать урон от давления стоя на траве.
  code/__DEFINES/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/humanoid.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Balance

#7024 респрайт патронов от валтерже
  icons/obj/ammo.dmi
Labels: Sprites

#7021 [Alien] Лярва и хаггер быстрее залезают в вентиляцию. Задержка перед выходом из вентиляции.
  code/modules/ventcrawl/ventcrawl.dm
  code/modules/ventcrawl/ventcrawl_atmospherics.dm
Labels: Balance, Tweak

#7022 adds flash to explosions
  code/game/objects/explosion.dm
Labels: Tweak

#7026 Воксы получили уникальную раидочастоту
  code/game/communications.dm
  code/game/gamemodes/heist/vox_role.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/research/message_server.dm
Labels: Tweak

#7031 Не будет рево-боргов
  code/game/machinery/podmen.dm
  code/modules/mob/living/carbon/brain/posibrain.dm
Labels: Fix

#7039 теперь патроны вертятся не используя дополнительные диры.
  code/modules/projectiles/ammunition.dm
  icons/obj/ammo.dmi
Labels: Sprites

#7048 Обновление схемы баз данных
  SQL/README.md
  SQL/ss13.sql
  SQL/ss13_feed.sql
  code/__HELPERS/logging.dm
  code/_globalvars/database.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/stickyban.dm
  code/controllers/subsystem/ticker.dm
  code/defines/procs/dbcore.dm
  code/defines/procs/statistics.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/scoreboard.dm
  code/game/machinery/records_scanner.dm
  code/game/magic/archived_book.dm
  code/game/world.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/banjob.dm
  code/modules/admin/permissionverbs/permissionedit.dm
  code/modules/admin/player_notes.dm
  code/modules/admin/server_whitelist.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/library.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/whitelist.dm
  code/modules/client/client procs.dm
  code/modules/library/lib_machines.dm
  code/modules/mob/dead/new_player/poll.dm
  code/modules/mob/mob.dm
  code/modules/research/message_server.dm
  config/example/dbconfig.txt
  interface/interface.dm
Labels: Config Update, Database

#7044 Отображение труб при венткравле поверх эффекта слепоты
  code/modules/ventcrawl/ventcrawl.dm
Labels: Tweak

#7038 [Alien] Эмбрион не умрёт от давления внутри носителя
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#7052 sql fixes
  code/controllers/subsystem/stickyban.dm
  code/modules/library/lib_machines.dm
Labels: Database

#7053 Bunker pass for mentors
  code/controllers/configuration.dm
  code/modules/admin/permissionverbs/permissionedit.dm
  code/modules/client/client procs.dm
  code/modules/mentor/mentor.dm
Labels: Config Update, Tweak

#7042 Возможность залезать в вентиляцию через трубы
  code/modules/ventcrawl/ventcrawl.dm
  code/modules/ventcrawl/ventcrawl_atmospherics.dm
Labels: Tweak

#7049 Бореры видят внутри вентиляции
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/simple_animal/borer.dm
Labels: Fix

#7032 Вернуть алиенов как случайный эвент + небольшие изменения в контроллере эвентов
  code/_globalvars/configuration.dm
  code/controllers/configuration.dm
  code/modules/events/_event_container.dm
  code/modules/events/alien_infestation.dm
  config/example/config.txt
Labels: Config Update, Tweak

#7061 Whitelist by player age
  code/controllers/configuration.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/bunker.dm
  code/modules/admin/server_whitelist.dm
  code/modules/client/client procs.dm
  config/example/config.txt
  taucetistation.dme
Labels: Config Update

#7063 fixes
  code/controllers/configuration.dm
  code/modules/admin/admin.dm
  code/modules/admin/whitelist.dm
Labels: Config Update

#7064 Фикс ошибок при снятии шлема
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Fix

#7057 респрайтит рацию
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/radio.dmi
Labels: Sprites

#7060 Добавление главам книги возможных угроз
  code/game/objects/items/weapons/manuals.dm
  icons/obj/library.dmi
  maps/boxstation/boxstation.dmm
Labels: Feature, Map Edit, Sprites

#7069 Fixing PDA ringtone
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Fix

#7035 flare resprite
  code/game/objects/items/devices/flashlight.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/lighting.dmi
Labels: Sprites, Test Merge Candidate
