Repository TauCetiStation/TauCetiClassic, pull requests merged in 2021-10, with the labels that each got.

#7921 Announcements fixes
  code/datums/announcements.dm
  code/datums/announcements/centcomm.dm
  code/datums/announcements/events.dm
  code/datums/announcements/gamemode.dm
  code/datums/announcements/station.dm
  code/modules/admin/secrets/secrets_menu/custom_announcement.dm
  code/modules/events/communications_blackout.dm
Labels: Fix, Stalled PR

#8046 shake_camera update from tg
  code/modules/mob/mob_helpers.dm
Labels: Fix, Test Merge Candidate

#8047 Фикс использования алтаря без нуллрода
  code/modules/religion/altar_types/altar_of_gods.dm
  tgui/packages/tgui/interfaces/ReligiousTool.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Fix, UI

#8030 Таргетинг и турели лучше работают
  code/game/machinery/portable_turret.dm
  code/modules/projectiles/projectile.dm
Labels: Test Merge Candidate

#8060 Производство пасты менее затратнее
  code/game/machinery/kitchen/processor.dm
Labels: Balance

#8069 glassless borg lighting_alpha updates correctly
  code/modules/mob/living/silicon/robot/life.dm
Labels: Fix

#8133 Фикс ИВЛ. Очередной.
  code/game/machinery/life_assist.dm
Labels: Fix

#8128 У дилеров убрана крутая аптечка
  code/datums/uplinks_items.dm
Labels: Balance

#8120 Флафф итемы могут скрывать волосы
  code/modules/fluff/customitems.dm
  code/modules/fluff/fluffmenu.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Tweak

#8136 Фикс исчезнувшего хетча
  code/game/gamemodes/modes_gameplays/shadowling/special_shadowling_abilities.dm
Labels: Fix
