Repository TauCetiStation/TauCetiClassic, pull requests merged in 2022-09, with the labels that each got.

#9943 double barrel resprite
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/mob/back.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
Labels: Sprites

#9947 Выдал шахтёрам и переработчикам куртки на зимнем боксе
  code/game/jobs/job/civilian.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/mining/mine_items.dm
Labels: Map Edit

#9969 Закрытие консоли аккаунтов
  code/modules/economy/Accounts_DB.dm
Labels: Fix

#9727 tajaran resprite 2
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/organ_external.dm
  icons/mob/human_races/r_def_tajaran.dmi
  icons/mob/human_races/r_tajaran.dmi
  icons/mob/species/tail.dmi
Labels: Sprites, Test Merge Candidate

#9879 Переработка цветоматриц у некоторых очков
  code/__HELPERS/matrices.dm
  code/modules/clothing/glasses/glasses.dm
Labels: Tweak, Test Merge Candidate

#9930 Fix blood data
  code/modules/reagents/Chemistry-Holder.dm
Labels: Fix, Test Merge Candidate

#9961 Fawkes resprite
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Sprites

#9963 c20r and tommygun resprite
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
Labels: Sprites

#9934 Добавлены диры для сканера
  icons/obj/Cryogenic3.dmi
Labels: Sprites, Tweak

#9862 flash device for all borg modules
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Balance

#9868 Удаление большей части рандомности молота генокрада
  code/game/mecha/mecha.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/simulated/walls_reinforced.dm
Labels: Balance

#9940 Огнетушители киборгов теперь самозаряжаются
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/reagent_containers/extinguisher.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Feature

#9673 Фикс ТЭГов
  code/game/machinery/constructable_frame.dm
  code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
  code/modules/cargo/packs.dm
  code/modules/power/generator.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  icons/obj/machines/power/thermoelectric.dmi
  icons/obj/pipes.dmi
  maps/boxstation/boxstation.dmm
  taucetistation.dme
Labels: Fix, Feature, Test Merge Candidate

#10002 Починил столы на посте прослушки
  maps/templates/space_structures/listening_post.dmm
Labels: Fix, Map Edit

#9998 Слаймолюди при превращении восстанавливают кровь
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
Labels: Fix

#9872 Ребаланс захвата у хлыста генокрада
  code/game/gamemodes/modes_gameplays/changeling/powers/Whip.dm
Labels: Balance

#10003 Позволяет блобу бить по голове
  code/modules/mob/living/carbon/human/human.dm
Labels: Tweak

#9935 Альтернативный фикс абдукторов
  code/__DEFINES/is_helpers.dm
  code/game/gamemodes/modes_gameplays/abduction/abduction_gear.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/console.dm
Labels: Fix, Test Merge Candidate

#10017 Fixes our rendering for 514.1587
  code/_onclick/hud/rendering/plane_master.dm
Labels: Fix, :atom: BYOND

#9996 Фикс бодисканера в хирургии Прометея.
  code/game/machinery/adv_med.dm
Labels: Fix

#9999 c20r ammo rework
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
Labels: Balance, Sprites, Awaiting Review [Sprite Dep]

#9768 Cult appearance
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/human_layers.dm
  code/__DEFINES/traits.dm
  code/_onclick/hud/fullscreen.dm
  code/datums/components/cult_eyes.dm
  code/datums/components/cult_halo.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/transform.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/update_icons.dm
  code/modules/mob/transform_procs.dm
  code/modules/religion/religion_types/cult.dm
  icons/effects/32x64.dmi
  taucetistation.dme
Labels: Feature, Sprites, Test Merge Candidate

#10033 Sounds for Pacman on/off
  code/modules/power/port_gen.dm
  sound/machines/pacman_off.ogg
  sound/machines/pacman_on.ogg
Labels: Sound

#9844 RD eva access
  code/game/jobs/job/science.dm
Labels: Balance, Contentious

#9924 Changeling Statistic
  code/game/gamemodes/roles/changeling.dm
  code/modules/statistic/gamemode_stat.dm
  code/modules/statistic/statistics.dm
Labels: Tweak

#9938 Rename Files
  code/modules/admin/DB_ban/functions.dm
  code/modules/atmospheric/ZAS/Variable_Settings.dm
  code/modules/client/character_menu/customkeybindings.dm
  code/modules/client/character_menu/general.dm
  code/modules/client/character_menu/global.dm
  code/modules/client/character_menu/load_slot.dm
  code/modules/client/character_menu/loadout.dm
  code/modules/client/character_menu/loadout/gear_tweaks.dm
  code/modules/client/character_menu/loadout/loadout_accessories.dm
  code/modules/client/character_menu/loadout/loadout_clothing.dm
  code/modules/client/character_menu/loadout/loadout_general.dm
  code/modules/client/character_menu/loadout/loadout_glasses.dm
  code/modules/client/character_menu/loadout/loadout_hats.dm
  code/modules/client/character_menu/loadout/loadout_shoes.dm
  code/modules/client/character_menu/occupation.dm
  code/modules/client/character_menu/quirks.dm
  code/modules/client/character_menu/roles.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences_savefile.dm
  code/modules/security_levels/keycard_authentication.dm
  code/modules/security_levels/security_levels.dm
  taucetistation.dme
Labels: Preferences Update

#9753 Апдейт движения
  code/_onclick/click.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_movement.dm
Labels: Feature, Contentious, Tweak

#10045 фикс, которого не должно было быть
  eyes.dmi
  glasses.dmi
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Sprites

#9826 Mechs and aliens
  code/game/mecha/mecha.dm
  code/modules/projectiles/projectile/special.dm
Labels: Balance, Test Merge Candidate, Feedback required

#9931 Небольшой рефактор environment
  code/__DEFINES/maps.dm
  code/controllers/subsystem/environment.dm
  code/controllers/subsystem/weather.dm
  code/datums/environment/environment.dm
  code/datums/environment/environment_types.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_types.dm
  code/game/area/main_areas.dm
  code/game/area/station_areas.dm
  code/game/turfs/simulated/floor_types.dm
  code/modules/maps/space_management/space_level.dm
  code/modules/mining/mine_turfs.dm
  code/modules/procedural_mapping/mapGeneratorModules/flora.dm
  icons/effects/weather_effects.dmi
  maps/boxstation_snow.json
  taucetistation.dme
Labels: Sprites, Test Merge Candidate

#10009 Возвращает болам нормальную скорость
  code/defines/obj/weapon.dm
Labels: Balance

#9914 [MDB Ignore] Новая карта Прометей.
  .github/workflows/ci_suite.yml
  config/example/maps.txt
  maps/prometheus.json
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
  nano/images/nanomap_prometheus_1.png
Labels: Map Edit, Test Merge Candidate

#9243 Новые фотоаппараты и фильтры на них by Gisev
  code/__DEFINES/colors.dm
  code/datums/outfits/jobs/assistant.dm
  code/game/machinery/vending/other.dm
  code/modules/cargo/packs.dm
  code/modules/client/character_menu/loadout/loadout_general.dm
  code/modules/paperwork/photography.dm
  code/modules/paperwork/silicon_photography.dm
  icons/effects/160x160.dmi
  icons/effects/32x32.dmi
  icons/effects/96x96.dmi
  icons/obj/items.dmi
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Feature, Map Edit, Sprites

#9986 tajaran hair sprite tweaks
  icons/mob/human_face.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#9991 RnD resprite by WalterJe
  code/game/machinery/autolathe.dm
  code/game/mecha/mech_fabricator.dm
  code/modules/mining/mining_fabricator/mining_fabricator.dm
  code/modules/research/circuitprinter.dm
  code/modules/research/destructive_analyzer.dm
  code/modules/research/protolathe.dm
  code/modules/research/rdmachines.dm
  icons/obj/machines/research.dmi
  icons/obj/robotics.dmi
  icons/obj/stationobjs.dmi
Labels: Sprites

#10034 опять подчищаю звуки
  code/modules/mob/living/silicon/robot/robot.dm
  sound/items/bandage1.ogg
  sound/items/bandage2.ogg
  sound/items/bikehorn.ogg
  sound/items/insert_key.ogg
  sound/items/swipe_card.ogg
  sound/machines/terminal_insert.ogg
  sound/misc/cowbell.ogg
Labels: Sound

#10059 Небольшие добавления на пост прослушки.
  maps/templates/space_structures/listening_post.dmm
Labels: Map Edit

#9865 Миротворец
  code/_globalvars/misc.dm
  code/game/machinery/deployable.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/weapons/RSF.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/grenade_launcher.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  icons/mob/robots.dmi
  icons/obj/device.dmi
  sound/AI/harmalarm.ogg
Labels: Feature, Sprites, Tweak, Sound, Awaiting Review [Sprite Dep]

#10001 asteroid_update (part 1: "Костяк") (splitting #9557)
  code/modules/mining/mine_turfs.dm
  code/modules/research/xenoarchaeology/artifact/artifact.dm
  sound/misc/sledgehammer_hit_rock.ogg
Labels: Test Merge Candidate

#10058 Крафт через радиалку.
  code/__DEFINES/dcs/signals.dm
  code/datums/components/altcraft.dm
  code/game/objects/items.dm
  code/modules/crafting/craft.dm
  code/modules/crafting/recipes.dm
  code/modules/mob/living/carbon/human/human.dm
  taucetistation.dme
Labels: Tweak, Test Merge Candidate

#10115 Фикс занавесок прометея
  maps/prometheus/prometheus.dmm
Labels: Fix, Map Edit

#10138 Нательная кобура вновь видна на форме
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/clothing/under/accessories/holster.dm
  icons/obj/clothing/accessory.dmi
Labels: Sprites

#10129 Мыши, слаймы и прочие теперь не смогут подбирать стопку бумаг
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#10136 Divine power bug
  code/modules/religion/religion.dm
Labels: Fix

#9917 Поинт ту для призраков
  code/_onclick/observer.dm
  code/game/atoms.dm
  code/game/objects/effects/decals/misc.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  icons/hud/screen1.dmi
Labels: Feature, Merge Conflict, Sprites

#10077 Improved pylons
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/religion.dm
  code/__DEFINES/traits.dm
  code/_globalvars/misc.dm
  code/controllers/subsystem/aura_healing.dm
  code/datums/components/aura_healing.dm
  code/defines/obj/weapon.dm
  code/game/gamemodes/modes_gameplays/cult/structures/cult_structures.dm
  code/game/objects/buckling.dm
  code/game/objects/effects/temp_visual/cult.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/religion/building_agent.dm
  code/modules/religion/religion_types/cult.dm
  code/modules/religion/tech.dm
  icons/effects/effects.dmi
  taucetistation.dme
Labels: Feature, Sprites

#10085 Добавляет новый указ в реву
  code/game/gamemodes/factions/revolution.dm
Labels: Feature

#10110 Статичный оверлей Space Lube
  code/game/turfs/simulated.dm
Labels: Balance

#10123 Cult tome
  code/game/objects/items/weapons/storage/bible/tome.dm
Labels: Tweak

#10131 Aspects, cost and scale
  code/game/gamemodes/modes_gameplays/cult/structures/tech_table.dm
Labels: Balance

#10118 Откат перевода нулл роада
  code/game/objects/items/weapons/chaplain_weapons.dm
Labels: Revert / Removal, Test Merge Candidate

#10159 fix junkyard
  code/controllers/subsystem/junkyard.dm
  code/modules/admin/admin_verbs.dm
  code/modules/maps/reader_optimized.dm
Labels: Fix

#10069 теперь у мед борга полностью восстанавливается нанопаста и бинтики
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Fix, Stalled PR

#10070 Ремап базы ОБР
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit

#10081 DShotgun resprite
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/mob/back.dmi
  icons/mob/belt_mirror.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
Labels: Sprites

#10095 Твик простыни мага
  code/game/objects/structures/bedsheet_bin.dm
Labels: Balance, Tweak

#10137 Glasses with cult eyes
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix
