Repository TauCetiStation/TauCetiClassic, pull requests merged in 2022-12, with the labels that each got.

#10284 Выпускаем зомбе с гнёздышка админов. Фиксы
  code/__DEFINES/is_helpers.dm
  code/_globalvars/lists/mob.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/epinephrine.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/life.dm
  code/modules/organs/external/flesh.dm
  code/modules/organs/organ.dm
Labels: Fix, Balance, Tweak

#10463 Два пикселя фикс
  icons/mob/human_face.dmi
Labels: Sprites

#10354 New cult members-oriented objectives
  code/game/gamemodes/factions/cult.dm
  code/game/gamemodes/objectives/cult/cult_objectives.dm
Labels: Feature

#10352 Bone-hypospray
  code/game/objects/items/weapons/autoinjectors.dm
  code/game/objects/items/weapons/medical.dm
  code/game/objects/items/weapons/storage/pouches.dm
  icons/obj/items.dmi
Labels: Balance, Sprites

#10444 Blob attacks
  code/game/mecha/mecha.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Balance

#10461 Abductors, teleportations, jammers
  code/game/gamemodes/modes_gameplays/abduction/abduction_gear.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/console.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/pad.dm
Labels: Fix

#10464 бафф уборщика
  code/game/objects/items.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/suits/new_hazmat.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/zwater/wet_stuff.dm
Labels: Feature

#10465 Небольшая переработка модкитов
  code/datums/outfits/nuclear.dm
  code/game/machinery/vending/clothing.dm
  code/game/machinery/vending/modkit.dm
  code/game/objects/items/devices/modkit.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/rig/ert.dm
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Tweak

#10469 Лоты Грузторга мержатся
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/cargo/shop.dm
Labels: Tweak

#10472 фикс невозможности сувать слаймов и мартых в фуд процессор
  code/game/machinery/kitchen/processor.dm
Labels: Fix

#10488 "Facial hair" унатхов доступен обоим гендерам
  code/modules/mob/dead/new_player/sprite_accessories.dm
Labels: Tweak

#10483 твики видения снов
  code/datums/status_effects/debuffs.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/mob/hear_say.dm
Labels: Feature

#10154 asteroid_update (part 3: "Инструменты") (splitting #9557)
  code/game/turfs/turf_snow.dm
  code/modules/mining/equipment_locker.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/minerals.dm
  icons/obj/module.dmi
  sound/effects/resonator_effect_disappear.ogg
  sound/items/resonator_ready.ogg
  sound/items/resonator_use.ogg
Labels: Sprites, Tweak, Sound

#10171 Строечкастейшон Гефест для микроонлайна
  .github/workflows/ci_suite.yml
  code/modules/skills/skillset_stroechka.dm
  config/example/maps.txt
  maps/stroechka.json
  maps/stroechka/job_changes.dm
  maps/stroechka/stroechka.dmm
  nano/images/nanomap_stroechka_1.png
  taucetistation.dme
Labels: Map Edit, Config Update

#10127 [DNM] проблема с бумажкой
  code/__HELPERS/text.dm
Labels: DO NOT MERGE, Test Merge Candidate

#10492 Тотальное допиливание Прометея.
  code/controllers/subsystem/mapping.dm
  code/game/objects/items/station_map.dm
  code/game/objects/structures/signs/signs_maps.dm
  code/modules/locations/shuttles/mine_sci_shuttle.dm
  icons/obj/bureaucracy.dmi
  icons/obj/decals.dmi
  maps/prometheus.json
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
  nano/images/nanomap_prometheus_1.png
  nano/images/nanomap_prometheus_1_small.png
  taucetistation.dme
Labels: Map Edit, Sprites

#10500 Фикс операционных столов, допил того что забыл.
  code/game/gamemodes/modes_gameplays/abduction/abduction_gear.dm
  code/game/gamemodes/modes_gameplays/cult/structures/cult_structures.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/constructable_frame.dm
  icons/obj/cult.dmi
Labels: Map Edit, Sprites

#10487 AlienCrawlDance Fix
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#10491 Уменьшение кол-ва игроков необходимых для Воксо-нюки
  code/game/gamemodes/modes_declares/mixed/nukeheist.dm
Labels: Tweak

#10509 Trashcart resprite
  icons/obj/storage.dmi
Labels: Sprites

#10428 test subject pack osobka #5
  code/datums/qualities/quirkieish.dm
  code/modules/organs/external/ipc.dm
  code/modules/surgery/ribcage.dm
Labels: Contentious, Stalled PR

#10523 Cult objective fix
  code/game/gamemodes/objectives/cult/cult_objectives.dm
Labels: Fix

#10541 OCD small equip changes
  code/game/gamemodes/modes_gameplays/families/outfit.dm
Labels: Tweak

#10506 Изменения в генокрадах
  code/game/gamemodes/modes_gameplays/changeling/powers/Whip.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/hand_hammer.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/mutations.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/mecha/mecha.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/simulated/walls_reinforced.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Balance, Tweak

#10539 Фикс паверфиста
  code/game/objects/items/weapons/melee/powerfist.dm
Labels: Balance

#10532 фиксы новых дереликтов
  maps/templates/space_structures/agrosphere.dmm
  maps/templates/space_structures/cult_ship.dmm
  maps/templates/space_structures/research_ship.dmm
  maps/templates/space_structures/robostation2.dmm
  maps/templates/space_structures/space_villa.dmm
Labels: Fix, Map Edit

#10526 Eminence point_at
  code/datums/atom_huds/alternate_apperance.dm
  code/game/gamemodes/modes_gameplays/cult/eminence.dm
  code/game/objects/effects/decals/misc.dm
  icons/hud/screen1.dmi
Labels: Feature, Sprites

#10514 Бафф адреналина у генок
  code/game/gamemodes/modes_gameplays/changeling/powers/epinephrine.dm
Labels: Balance

#10388 Security gasmask hailer resound
  code/modules/clothing/masks/gasmask.dm
  sound/voice/complionator/asshole.ogg
  sound/voice/complionator/bash.ogg
  sound/voice/complionator/bobby.ogg
  sound/voice/complionator/compliance.ogg
  sound/voice/complionator/davai_poprobui_pobejat.ogg
  sound/voice/complionator/dontmove.ogg
  sound/voice/complionator/dredd.ogg
  sound/voice/complionator/floor.ogg
  sound/voice/complionator/freeze.ogg
  sound/voice/complionator/god.ogg
  sound/voice/complionator/halt.ogg
  sound/voice/complionator/harry.ogg
  sound/voice/complionator/imperial.ogg
  sound/voice/complionator/justice.ogg
  sound/voice/complionator/lawful_ne_dvigatsya.ogg
  sound/voice/complionator/lawful_ni_s_mesta.ogg
  sound/voice/complionator/lawful_stoyat.ogg
  sound/voice/complionator/lawful_stoyat_na_meste.ogg
  sound/voice/complionator/neudachnik_vybral.ogg
  sound/voice/complionator/robocop.ogg
  sound/voice/complionator/running.ogg
  sound/voice/complionator/seychas_uznaesh.ogg
  sound/voice/complionator/shutup.ogg
  sound/voice/complionator/stfu.ogg
  sound/voice/complionator/stoy_prestupnoe.ogg
  sound/voice/complionator/super.ogg
  sound/voice/complionator/tolko_dvineshsya.ogg
  sound/voice/complionator/u_vas_est_tolko.ogg
  sound/voice/complionator/ukrytsya_ot_pravosudia.ogg
  sound/voice/complionator/upal_mordoy_v.ogg
  sound/voice/complionator/vinoven_ili_nevinoven.ogg
  sound/voice/complionator/ya_zakon_ty.ogg
  sound/voice/complionator/zhivym_ili_mertvym.ogg
Labels: Sound

#10521 под щупальцами скреллов теперь не видно вещей за ушами
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature

#10511 переносит данные сенсоров из офиса рд в теленауку
  maps/boxstation/boxstation.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit, Tweak

#10518 Mass Driver Resprite
  icons/obj/stationobjs.dmi
Labels: Sprites

#10512 Для открытия склада в инженерном отсеке теперь нужен доступ инженера
  maps/boxstation/boxstation.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit, Tweak

#10540 Notifies for ghosts
  code/__DEFINES/misc.dm
  code/_onclick/hud/alert.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/core.dm
  code/game/gamemodes/modes_gameplays/cult/narsie.dm
  code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
  code/game/gamemodes/modes_gameplays/shadowling/special_shadowling_abilities.dm
  code/game/gamemodes/roles/changeling.dm
  code/game/gamemodes/roles/families.dm
  code/game/machinery/syndie_big_bomb.dm
  code/game/objects/effects/anomalies.dm
  code/modules/events/anomaly.dm
  code/modules/events/immovable_rod.dm
  code/modules/events/spacevine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/mob_helpers.dm
Labels: Feature

#10558 Changeling - now you can hear it (shriek)
  code/game/gamemodes/modes_gameplays/changeling/powers/shriek.dm
Labels: Fix

#10548 Metatrombine metabolism buff
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Labels: Balance

#10546 гомункулы теперь ругаются вместо нормальной речи
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/mob_helpers.dm
Labels: Feature

#10563 Poll time
  code/__HELPERS/game.dm
Labels: Tweak

#10489 Facehugger vomit_rebalanсe
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
Labels: Fix
