Repository TauCetiStation/TauCetiClassic, pull requests merged in 2022-08, with the labels that each got.

#9744 Женские купальники от Вальтера
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#9749 Staff' icon
  icons/obj/wizard.dmi
Labels: Sprites

#9563 Nuke recaller & Fake nuke
  code/datums/announcements/station.dm
  code/datums/atom_huds/alternate_apperance.dm
  code/datums/uplinks_items.dm
  code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
  code/game/objects/items/devices/traitordevices.dm
Labels: Test Merge Candidate

#9758 sawn-off shotgun icon-state fix
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
Labels: Fix, Sprites

#9592 Ремап базы синдиката. На этот раз без респрайта шаттла
  code/game/machinery/computer/arcade.dm
  code/modules/media/jukebox.dm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit

#9773 #9639 anti revert
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#9775 Фикс опечатки в ритуалах
  code/modules/religion/rites_type/rites.dm
Labels: Fix

#9645 Runtimes
  code/game/gamemodes/modes_gameplays/abduction/abduction_gear.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/console.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/dispenser.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/experiment.dm
  code/game/objects/effects/spiders.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/religion/altar_types/altar_of_gods.dm
Labels: Fix

#9590 Right click on prefs
  code/modules/client/character menu/occupation.dm
Labels: Tweak

#9736 Stacks and fixes
  code/game/objects/items/stacks/stack.dm
Labels: Fix, Test Merge Candidate

#9750 теперь у копов будут интересные префиксы+случайные фамилии
  code/datums/spawners_menu/spawners.dm
Labels: Feature

#9755 Boots Resprite by WJ
  code/modules/client/character menu/loadout/loadout_shoes.dm
  code/modules/clothing/shoes/boots.dm
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: Sprites, Test Merge Candidate

#9769 Lux and Obscurum rebalance
  code/modules/religion/aspect.dm
Labels: Balance

#9789 Telum and mana
  code/modules/religion/aspect.dm
Labels: Feature

#9795 sawn-off inhands fix
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
Labels: Fix, Sprites

#9797 Добавляет зум компоненту ПТРке
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Feature

#9802 Fixed sprite bugs
  icons/mob/inhands/items_righthand.dmi
  icons/obj/power.dmi
Labels: Sprites

#9767 Summon Nar-Sie
  code/datums/announcements/centcomm.dm
  code/modules/religion/rites/pedestals/pedestals.dm
  sound/effects/dimensional_rend.ogg
Labels: Balance, Sound

#9762 Повышение живучести мага. Щит от урона.
  code/game/objects/structures/bedsheet_bin.dm
Labels: Feature

#9817 абдукторы больше не могут телепортироваться в отсеки с джаммером телепортаций
  code/game/gamemodes/modes_gameplays/abduction/machinery/pad.dm
Labels: Balance

#9656 Чипы для изменения умений
  code/__DEFINES/skills.dm
  code/datums/mind.dm
  code/datums/skills.dm
  code/game/area/station_areas.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/adv_med.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/implants/mindshield.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/paperwork/paper.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  code/modules/skills/skill_changer/cartridges.dm
  code/modules/skills/skill_changer/circuits.dm
  code/modules/skills/skill_changer/skills_console.dm
  code/modules/skills/skill_changer/skills_scanner.dm
  code/modules/surgery/implant.dm
  icons/obj/computer.dmi
  icons/obj/skills/cartridges.dmi
  icons/obj/skills/skills_machinery.dmi
  icons/turf/areas.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
  taucetistation.dme
  tgui/packages/tgui/interfaces/SkillsConsole.js
  tgui/public/tgui.bundle.js
Labels: Feature, Map Edit, Sprites, Test Merge Candidate, UI

#9714 добавляет ионку в карго
  code/modules/cargo/packs.dm
Labels: Feature, Contentious

#9761 Исправлен абуз с получением научных очков
  code/modules/organs/external/flesh.dm
  code/modules/organs/organ.dm
Labels: Fix, Test Merge Candidate

#9765 Fixes #6000
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/flags.dm
  code/__HELPERS/game.dm
  code/datums/components/talking_atom.dm
  code/game/machinery/hologram.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/devices/aicard.dm
  code/game/objects/items/devices/paicard.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/weapons/badmin.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/assembly/bomb.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/voice.dm
  code/modules/clothing/head/wiz_tophat.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/accessories/storage.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/living/say.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_special.dm
  code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
  taucetistation.dme
Labels: Fix, Merge Conflict, Test Merge Candidate

#9827 Gib and helmet for rig
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Fix

#9814 fix #9811
  icons/mob/feet.dmi
Labels: Sprites

#9825 autopsy research nerf
  code/modules/research/experiment.dm
Labels: Tweak

#9770 Новые заклинания и артефакты для мага
  code/datums/spells/in_hand.dm
  code/datums/spells/wizard.dm
  code/game/gamemodes/modes_gameplays/wizard/spellbook.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/projectiles/ammunition/special.dm
  code/modules/projectiles/guns/magic/staff.dm
  icons/mob/actions.dmi
  icons/mob/back.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/wizard.dmi
Labels: Feature, Merge Conflict, Sprites

#9783 Небольшой рефактор movement delay
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/drone.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/maid.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/sentinel.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/humanoid.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/queen.dm
  code/modules/mob/living/carbon/xenomorph/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/organs/organ.dm
Labels: Fix, Feature, Test Merge Candidate

#9806 Changed condition "if" for inaccurate cutting
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Fix

#9840 atm wont eat your id
  code/modules/economy/ATM.dm
Labels: Fix

#9836 fixed surgical mask
  code/modules/clothing/masks/breath.dm
  icons/obj/clothing/masks.dmi
Labels: Fix, Sprites

#9843 Tommygun's icon_state fix+del useless
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/obj/gun.dmi
Labels: Fix, Sprites

#9841 Вы снова можете красить кроссовки в радужный
  code/modules/clothing/shoes/colour.dm
Labels: Fix

#9848 fix #9846
  code/modules/mining/mine_turfs.dm
Labels: Fix

#9858 Pixel Fix
  icons/mob/feet.dmi
Labels: Fix, Sprites

#9861 Fixed magic projectile light color
  code/__DEFINES/colors.dm
  code/datums/spells/in_hand.dm
  code/modules/projectiles/projectile/magic.dm
Labels: Fix

#9699 респрайт мольберта и добавление оверлея рисования
  code/game/objects/structures/art.dm
  icons/obj/artstuff.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#9885 Summon fix
  code/modules/religion/rites/pedestals/pedestals.dm
Labels: Fix

#9901 added missing emergency shutters in vacant office
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#9899 Обновление списков в редакторе персонажа
  code/modules/client/preferences_faction.dm
Labels: Tweak

#9906 fixes #9904
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Fix

#9605 Добавляет нюке ваучеры для выбора брони
  code/datums/outfits/nuclear.dm
  code/game/machinery/computer/intruder_station.dm
  code/game/machinery/vending/other.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/mining/equipment_locker.dm
  icons/obj/mining.dmi
Labels: Feature, Sprites, Test Merge Candidate

#9812 Фикс лазера боргов
  code/__DEFINES/dcs/signals.dm
  code/datums/components/cell_selfrecharge.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/power/cell.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  taucetistation.dme
Labels: Fix

#9791 Подствольник дрозда вновь работает
  code/modules/projectiles/firing.dm
Labels: Fix

#9850 Меняет скиллсет предвестника культа
  code/modules/skills/skillsets/roles.dm
Labels: Balance

#9615 Кормушка
  code/game/objects/structures/chicken_feeder.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  icons/obj/feeder.dmi
  maps/boxstation/boxstation.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  taucetistation.dme
Labels: Sprites

#9873 Ускорение пшика перцовки
  code/modules/reagents/reagent_containers/spray.dm
Labels: Tweak

#9903 Fire alarm bug + runtime null fix
  code/game/machinery/alarm.dm
Labels: Fix

#9909 Gamma fix
  maps/gamma/gamma.dmm
Labels: Map Edit
