Repository TauCetiStation/TauCetiClassic, pull requests merged in 2022-11, with the labels that each got.

#10309 remove newlist()
  maps/templates/space_structures/export_outpost.dmm
Labels: Map Edit

#10271 Aifixer and ghost
  code/game/machinery/computer/aifixer.dm
Labels: Tweak

#10282 Фикс звука тряпки и ведра при поднятии установке их на стол
  code/game/objects/items.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/research/xenoarchaeology/tools/tools_wave_scanner.dm
Labels: Fix

#10276 Плашки об инвалидности на карте зашедших после начала раунда
  code/controllers/subsystem/ticker.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#10315 velocity officer uniform fix & resprite
  code/modules/locations/centcomm/velocity.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#10316 Update atmos_control.dm
  code/game/machinery/computer/atmos_control.dm
Labels: Fix

#10320 velocity coat fix & resprite
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#10319 Очередная подчистка звуков
  code/_globalvars/lists/sound.dm
  sound/effects/3.ogg
  sound/effects/3.wav
  sound/effects/ArterialBleed.ogg
  sound/effects/attackblob.ogg
  sound/effects/forcefield_destroy.ogg
  sound/effects/forcefield_reactivate.ogg
  sound/effects/mob/footstep/snowstep1.ogg
  sound/effects/mob/footstep/snowstep2.ogg
  sound/effects/mob/footstep/snowstep3.ogg
  sound/effects/mob/footstep/snowstep4.ogg
  sound/effects/mob/footstep/snowstep5.ogg
  sound/effects/mob/footstep/snowstep6.ogg
  sound/effects/mob/footstep/snowstep7.ogg
  sound/effects/mob/footstep/snowstep8.ogg
  sound/effects/mob/footstep/snowstep9.ogg
  sound/effects/rustle1.ogg
  sound/effects/rustle2.ogg
  sound/effects/rustle3.ogg
  sound/effects/rustle4.ogg
  sound/effects/rustle5.ogg
  sound/effects/shieldbash.ogg
  sound/effects/singlebeat.ogg
  sound/effects/snap.ogg
  sound/effects/snowstep.ogg
  sound/effects/squelch1.ogg
  sound/effects/turret/move1.ogg
  sound/effects/turret/move1.wav
  sound/effects/turret/move2.ogg
  sound/effects/turret/move2.wav
  sound/effects/turret/open.ogg
  sound/effects/turret/open.wav
  sound/effects/writing/pen1.ogg
  sound/effects/writing/pen2.ogg
  sound/effects/writing/pen3.ogg
  sound/machines/copier.ogg
  sound/machines/hiss.ogg
  sound/machines/quite_beep.ogg
  sound/machines/warning-buzzer.ogg
  sound/weapons/bite.ogg
  sound/weapons/glowstick_bend.ogg
Labels: Sound

#9942 Revert "нерф смазки (#8647)"
  code/game/turfs/simulated.dm
Labels: Balance

#10008 Реворк кроссфаера
  code/__DEFINES/gamemodes.dm
  code/game/gamemodes/factions/heist.dm
  code/game/gamemodes/factions/syndicate.dm
  code/game/gamemodes/modes_declares/mixed/nukeheist.dm
  code/game/gamemodes/objectives/heist/stealnuke.dm
  code/game/machinery/computer/syndicate_shuttle.dm
  code/game/machinery/droppod.dm
  code/game/objects/items/devices/gateway_locker.dm
  taucetistation.dme
Labels: Fix, Feature

#10267 One space
  code/controllers/subsystem/voting/poll.dm
Labels: Stalled PR

#10306 Порт респрайта маяка для мусора
  icons/obj/structures/scrap/scrap_beacon.dmi
Labels: Sprites

#9875 небольшой реворк ревы
  code/datums/components/gamemodes/syndicate.dm
  code/datums/uplinks_items.dm
  code/game/gamemodes/roles/revolution.dm
  code/game/gamemodes/roles/syndicate.dm
  code/game/gamemodes/roles/traitor.dm
  code/game/gamemodes/roles/traitorchan.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/head.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/ammo.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/contraband.dmi
  icons/obj/gun.dmi
  icons/obj/storage.dmi
  sound/weapons/guns/reload_bolt.ogg
Labels: Feature, Sprites, Test Merge Candidate, Sound

#10103 Unbuckle alert and unbuckle
  code/_onclick/hud/alert.dm
Labels: Fix, Test Merge Candidate

#10292 нерф дроби
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Balance

#10329 Переделывает робу культа в hooded одежду
  code/game/gamemodes/modes_gameplays/cult/cult_items.dm
Labels: Fix, Tweak

#10335 теперь можно драться руками и ногами
  code/datums/components/swiping.dm
  code/game/objects/items.dm
  code/game/objects/weapons.dm
  code/modules/organs/external/skeleton.dm
  code/modules/organs/organ_external.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Feature, Sprites

#10350 cult_alert, intro sound
  code/game/gamemodes/roles/cultist.dm
  sound/antag/cultist_alert.ogg
Labels: Sound

#10212 Добавляет скиллы лингу и его треллам
  code/game/gamemodes/roles/shadowling.dm
  code/modules/skills/skillsets/roles.dm
Labels: Feature

#10170 ремап базы элиток синдикета
  maps/centcom/centcom.dmm
Labels: Map Edit

#10317 Туррет больше не станит и не только
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/mob_helpers.dm
Labels: Tweak

#10242 Небольшой бафф регенеративной комы
  code/modules/virus2/effect.dm
Labels: Balance, Tweak

#10337 Добавление хим мешков в химию.
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  icons/obj/chemical.dmi
  maps/boxstation/boxstation.dmm
  maps/falcon/falcon.dmm
  maps/prometheus/prometheus.dmm
Labels: Feature, Map Edit, Sprites

#10364 Заслонку забыли
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#10331 Divided divine power for shielding aura
  code/modules/religion/religion.dm
  code/modules/religion/rites/instant/instant.dm
Labels: Balance

#10255 Сапёр на ТГУИ
  code/modules/minigames/minesweeper.dm
  code/modules/mining/abandonedcrates.dm
  taucetistation.dme
  tgui/packages/tgui/interfaces/Minesweeper.js
  tgui/packages/tgui/styles/interfaces/Minesweeper.scss
  tgui/packages/tgui/styles/main.scss
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Feature

#10338 hmm emote
  code/_globalvars/lists/sound.dm
  code/datums/emotes/emote.dm
  code/datums/emotes/human/audible.dm
  code/datums/skills.dm
  code/modules/skills/helpers.dm
  sound/voice/hmm/hmm_exclaim_female_1.ogg
  sound/voice/hmm/hmm_exclaim_female_2.ogg
  sound/voice/hmm/hmm_exclaim_male_1.ogg
  sound/voice/hmm/hmm_exclaim_male_2.ogg
  sound/voice/hmm/hmm_exclaim_male_3.ogg
  sound/voice/hmm/hmm_exclaim_male_4.ogg
  sound/voice/hmm/hmm_exclaim_male_5.ogg
  sound/voice/hmm/hmm_question_female_1.ogg
  sound/voice/hmm/hmm_question_male_1.ogg
  sound/voice/hmm/hmm_question_male_2.ogg
  sound/voice/hmm/hmm_question_male_3.ogg
  sound/voice/hmm/hmm_question_male_4.ogg
  sound/voice/hmm/hmm_question_male_5.ogg
  sound/voice/hmm/hmm_question_male_6.ogg
  sound/voice/hmm/hmm_think_female_1.ogg
  sound/voice/hmm/hmm_think_female_2.ogg
  sound/voice/hmm/hmm_think_female_3.ogg
  sound/voice/hmm/hmm_think_male_1.ogg
  sound/voice/hmm/hmm_think_male_2.ogg
  sound/voice/hmm/hmm_think_male_3.ogg
  sound/voice/hmm/hmm_think_male_4.ogg
  sound/voice/hmm/hmm_think_male_5.ogg
  sound/voice/hmm/hmm_think_male_6.ogg
  sound/voice/hmm/hmm_think_male_7.ogg
Labels: Sound

#10380 Splint update
  code/game/objects/items/stacks/medical.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  sound/effects/splint_broke.ogg
Labels: Fix, Tweak

#10370 Fem sprites for hands and feet
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/feet.dmi
  icons/mob/hands.dmi
Labels: Sprites

#10312 Небольшой фикс в системе воздуха
  code/modules/atmospheric/ZAS/Debug.dm
  code/modules/atmospheric/ZAS/Turf.dm
Labels: Tweak, Test Merge Candidate

#10397 Мегаремап офиса хоса
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#10398 Фикс аккаунта станции и департаментов.
  code/modules/economy/economy_misc.dm
Labels: Tweak

#10410 Фикс бага - возможности посмотреть и достать предметы из lockbox
  code/game/objects/items/weapons/storage/lockbox.dm
Labels: Fix

#10416 БыстроДуши и точка
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/falcon/falcon.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit, Tweak

#10358 Operating Table
  code/game/gamemodes/modes_gameplays/abduction/abduction_gear.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/machinery.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  code/modules/skills/skill_changer/skills_scanner.dm
  icons/obj/abductor.dmi
  icons/obj/skills/skills_machinery.dmi
  icons/obj/surgery.dmi
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Sprites, Tweak

#10394 Woo emote
  code/_globalvars/lists/sound.dm
  code/datums/emotes/human/audible.dm
  sound/voice/woo/woo_female_1.ogg
  sound/voice/woo/woo_female_2.ogg
  sound/voice/woo/woo_female_3.ogg
  sound/voice/woo/woo_female_4.ogg
  sound/voice/woo/woo_female_5.ogg
  sound/voice/woo/woo_male_1.ogg
  sound/voice/woo/woo_male_2.ogg
  sound/voice/woo/woo_male_3.ogg
  sound/voice/woo/woo_male_4.ogg
  sound/voice/woo/woo_male_5.ogg
  sound/voice/woo/woo_male_6.ogg
Labels: Sound

#10401 Очередной нерф алиенов
  code/modules/mob/living/carbon/xenomorph/humanoid/humanoid.dm
Labels: Balance

#10286 plasma cutter rework
  code/game/asteroid.dm
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/simulated/walls_reinforced.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/projectiles/ammunition/energy.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/research/designs.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/gun.dmi
  maps/RandomZLevels/spacebattle.dmm
  maps/templates/space_structures/ghost_ship_2.dmm
Labels: Map Edit, Contentious, Sprites, Tweak, Test Merge Candidate

#10393 Wizard Statistic
  code/game/gamemodes/modes_gameplays/wizard/spellbook.dm
  code/game/gamemodes/roles/wizard.dm
  code/modules/statistic/gamemode_stat.dm
  code/modules/statistic/statistics.dm
Labels: DO NOT MERGE

#10425 test subject pack osobka 2
  code/datums/qualities/quirkieish.dm
  code/modules/mob/living/carbon/species.dm
Labels: Merge Conflict

#10262 Добавляет ЭМИ щит ригам антагонистов
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Balance, Contentious

#10395 Отделил сингу от сингулярности-типа.
  code/game/gamemodes/modes_gameplays/cult/narsie.dm
  code/modules/maps/maps_code/Academy.dm
  code/modules/power/singularity/generator.dm
  code/modules/power/singularity/singularity.dm
  code/modules/power/tesla/energy_ball.dm
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/templates/space_structures/planetarium.dmm
Labels: Tweak
