Repository TauCetiStation/TauCetiClassic, pull requests merged in 2022-07, with the labels that each got.

#9417 Смягчение скиллов для фалкона
  code/modules/skills/skillsets_falcon.dm
  maps/falcon/job_changes.dm
  taucetistation.dme
Labels: Tweak

#9561 Пауверфист больше не будет застревать в ранах
  code/game/objects/items/weapons/melee/powerfist.dm
Labels: Fix

#9544 Separated repetitive updates for savefiles
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/modules/client/preferences_savefile.dm
Labels: Preferences Update

#9471 Нерф бол
  code/defines/obj/weapon.dm
Labels: Balance, Contentious, Test Merge Candidate

#9436 Изменения в культе
  code/game/gamemodes/modes_gameplays/cult/cult_items.dm
  code/game/gamemodes/modes_gameplays/cult/structures/tech_table.dm
  code/game/objects/items/weapons/storage/bible/tome.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/religion/building_agent.dm
Labels: Fix, Balance, Feature, Tweak, Test Merge Candidate

#9541 Resprited flash, mounted flash & portable flasher
  code/game/objects/items/devices/flash.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/device.dmi
  icons/obj/stationobjs.dmi
Labels: Sprites

#9511 Ослабление нюки в космосе
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Balance

#9530 Relogick чипсов и других вкусняшек
  code/__DEFINES/size_classes.dm
  code/game/atoms_movable.dm
  code/game/machinery/vending/eat.dm
  code/game/objects/items/weapons/storage/food_package.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/food.dmi
  icons/obj/storage.dmi
  sound/items/chips_bite.ogg
  sound/items/snack.ogg
  taucetistation.dme
Labels: Sprites

#9532 Reverb for areas and drunkness from tg
  code/__DEFINES/sound.dm
  code/game/area/areas.dm
  code/game/area/station_areas.dm
  code/game/sound.dm
  code/modules/mining/mine_areas.dm
  code/modules/research/xenoarchaeology/areas.dm
Labels: Test Merge Candidate, Sound

#9553 добавляет смо солнцезащитные очки с медхудом
  code/modules/clothing/glasses/hud.dm
  icons/mob/eyes.dmi
  icons/mob/species/vox/eyes.dmi
  icons/obj/clothing/glasses.dmi
  maps/boxstation/boxstation.dmm
Labels: Feature, Map Edit, Sprites

#9558 СПУ теперь могут выбрать роль блоба в настройках
  code/modules/mob/living/carbon/species.dm
Labels: Tweak

#9566 Vote for the next round map
  code/controllers/configuration.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  code/controllers/subsystem/voting/poll.dm
  code/controllers/subsystem/voting/poll_types.dm
  code/controllers/subsystem/voting/vote_choice.dm
  code/datums/map_config.dm
  code/modules/admin/admin.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/topic.dm
  config/example/maps.txt
Labels: Feature, Tweak, Test Merge Candidate, Config Update

#7772 Artstuff!
  code/__HELPERS/unsorted.dm
  code/game/machinery/biogenerator.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/art.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/simulated/walls_reinforced.dm
  code/modules/clothing/clothing.dm
  code/modules/paperwork/pen.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  code/modules/scrap/scrap_light.dm
  code/modules/sports/pbag.dm
  icons/obj/artstuff.dmi
  scripts/create_png.py
  taucetistation.dme
  tgui/packages/tgui/interfaces/Canvas.js
  tgui/public/tgui.bundle.js
Labels: Feature, Sprites, Tweak, Test Merge Candidate, Pinned, UI

#9572 Reflect blob changes
  code/game/gamemodes/modes_gameplays/blob/blobs/shield.dm
  code/game/gamemodes/modes_gameplays/blob/powers.dm
  code/game/gamemodes/modes_gameplays/blob/theblob.dm
  icons/mob/blob.dmi
Labels: Fix, Sprites

#9507 Небольшие фиксы дион
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/organ_internal.dm
Labels: Fix

#9582 Fix tk
  code/__DEFINES/mob.dm
  code/_onclick/click.dm
  code/_onclick/telekinesis.dm
  code/game/machinery/doors/door.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/modules/power/cable.dm
  code/modules/power/singularity/singularity.dm
  code/modules/tgui/states/interactive_reach.dm
Labels: Fix

#9588 Перевод фраз попугаев.
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Translation/Localization

#9226 Удаляет хайперзин окончательно
  code/game/objects/items/weapons/autoinjectors.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/medical.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
  code/modules/virus2/effect.dm
Labels: DO NOT MERGE, Experimental, Contentious, Revert / Removal, Tweak, Test Merge Candidate

#9602 Admins without +Log should not see this
  code/modules/tgui_panel/telemetry.dm
Labels: Fix

#9562 Rcd
  code/game/objects/items/weapons/RCD.dm
Labels: Fix, Merge Conflict

#9599 RemoveSpell убирает и Action
  code/modules/mob/mob.dm
Labels: Fix

#9597 Добавление наушников авд в шкафы авд
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  maps/gamma/gamma.dmm
Labels: Map Edit

#9586 Cult preset: Darkness cult
  code/modules/religion/religion_sects.dm
Labels: Tweak

#9499 Blobbernaut and blob
  code/__DEFINES/gamemodes.dm
  code/_onclick/hud/ui_screens/other_mobs.dm
  code/game/gamemodes/factions/blob.dm
  code/game/gamemodes/modes_gameplays/blob/blobmouse.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/core.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/factory.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/node.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/resource.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/shield.dm
  code/game/gamemodes/modes_gameplays/blob/overmind.dm
  code/game/gamemodes/modes_gameplays/blob/powers.dm
  code/game/gamemodes/modes_gameplays/blob/theblob.dm
  code/game/gamemodes/roles/blob.dm
  icons/mob/blob.dmi
Labels: Balance, Feature, Sprites, Tweak, Performance

#9589 Добавлен аннонс для взлома гейтвея
  code/datums/announcements/gamemode.dm
  code/game/objects/items/devices/gateway_locker.dm
Labels: Feature

#9535 Shoes Resprite by WJ
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/fluff/customitems.dm
  code/modules/mob/living/carbon/species.dm
  icons/mob/feet.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/species/vox/shoes.dmi
  icons/obj/clothing/shoes.dmi
Labels: Sprites, Revert / Removal, Test Merge Candidate

#9570 Рефактор статусов paralysis, stunned, weakened
  code/__DEFINES/combat.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/mobs.dm
  code/_onclick/click.dm
  code/_onclick/cyborg.dm
  code/_onclick/hud/action.dm
  code/datums/components/zoom.dm
  code/datums/spells/Time_stop.dm
  code/datums/status_effects/debuffs.dm
  code/game/gamemodes/modes_gameplays/abduction/abduction_gear.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/Whip.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/epinephrine.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/doors/airlock.dm
  code/game/mecha/mecha_actions.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/surgery_limbattachment.dm
  code/modules/atmospheric/ZAS/Airflow.dm
  code/modules/awaymissions/gateway.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mob/living/blob/blob.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/hulk.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/transform_procs.dm
  code/modules/nano/nanointeraction.dm
  code/modules/organs/pain.dm
  code/modules/recycling/disposal.dm
  code/modules/unarmed_combat/combos/harmful.dm
Labels: Test Merge Candidate

#9587 ещё одна особка
  code/datums/outfits/jobs/civilian.dm
  code/datums/outfits/misc/spy.dm
  code/datums/qualities/positiveish.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/obj/gun.dmi
  maps/templates/space_structures/listening_post.dmm
  sound/weapons/guns/gunshot_derringer.ogg
Labels: Map Edit, Sprites, Sound

#9600 респрайт лампочек
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/lighting.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#9611 Апдейт игрушки-сингулярности
  code/game/objects/items/toys.dm
Labels: Tweak

#9637 нерф аплоада ии
  code/game/machinery/computer/law.dm
Labels: Balance

#9630 space cleaner resprite
  icons/mob/belt.dmi
  icons/mob/belt_mirror.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/janitor.dmi
Labels: Sprites

#9639 machinery overlaps each other fix pt2
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#9594 Examine prikol
  code/modules/mob/mob.dm
  tgui/packages/tgui-panel/styles/goon/chat-base.scss
  tgui/public/tgui-panel.bundle.css
Labels: Feature, Contentious

#9608 Небольшой бафф плазменного автомата
  code/modules/projectiles/guns/plasma/plasma.dm
  code/modules/projectiles/projectile/special.dm
Labels: Balance

#9674 Убирает маску анонимуса из автомата с одеждой.
  code/game/machinery/vending/clothing.dm
Labels: Revert / Removal

#9622 мобы теперь стреляют в кравлящих человечков
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Fix, Test Merge Candidate

#9683 Visible reflective blob
  icons/mob/blob.dmi
Labels: Fix, Sprites

#9684 Фикс доступа к аплоуду
  code/game/machinery/computer/law.dm
Labels: Fix

#9607 Сбор патрон по клику
  code/modules/projectiles/ammunition.dm
Labels: Tweak

#9619 Добавляет главам коробки с медалями
  code/datums/outfits/jobs/command.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/cargo/prices.dm
  code/modules/clothing/under/accessories/accessory.dm
  icons/obj/clothing/accessory.dmi
  icons/obj/storage.dmi
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
Labels: Feature, Map Edit, Sprites

#9659 Telespace jammer
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/flags.dm
  code/datums/components/teleblock.dm
  code/datums/helper_datums/teleport.dm
  code/datums/spells/ethereal_jaunt.dm
  code/datums/spells/turf_teleport.dm
  code/game/machinery/jammer.dm
  code/game/turfs/turf.dm
  code/modules/telesci/telesci_computer.dm
  icons/obj/machines/jammer.dmi
  maps/boxstation/boxstation.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#9692 Добавляет всякое для рисования на карту.
  maps/boxstation/boxstation.dmm
  maps/falcon/falcon.dmm
Labels: Map Edit

#9642 Удаляет остановку сердца от удара током
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix, Contentious, Revert / Removal, Test Merge Candidate

#9704 Фикс умений киборга что делался из бога
  code/modules/religion/rites/standing/consent.dm
  code/modules/skills/skillsets/roles.dm
Labels: Fix

#9700 респрайт слизнеей
  icons/mob/slimes.dmi
Labels: Sprites

#9691 Auto-merge for stacks
  code/game/objects/items/stacks/stack.dm
Labels: Feature

#9686 Hotline miami masks
  code/game/machinery/vending/other.dm
  code/modules/clothing/masks/boxing.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Feature, Sprites

#9693 Painkillers now kills the pain
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Labels: Tweak

#9680 Изменение звучания скрипки
  sound/musical_instruments/violin/A#1.ogg
  sound/musical_instruments/violin/A#2.ogg
  sound/musical_instruments/violin/A#3.ogg
  sound/musical_instruments/violin/A#4.ogg
  sound/musical_instruments/violin/A#5.ogg
  sound/musical_instruments/violin/A#6.ogg
  sound/musical_instruments/violin/A#7.ogg
  sound/musical_instruments/violin/A#8.ogg
  sound/musical_instruments/violin/Ab1.ogg
  sound/musical_instruments/violin/Ab2.ogg
  sound/musical_instruments/violin/Ab3.ogg
  sound/musical_instruments/violin/Ab4.ogg
  sound/musical_instruments/violin/Ab5.ogg
  sound/musical_instruments/violin/Ab6.ogg
  sound/musical_instruments/violin/Ab7.ogg
  sound/musical_instruments/violin/Ab8.ogg
  sound/musical_instruments/violin/An1.ogg
  sound/musical_instruments/violin/An2.ogg
  sound/musical_instruments/violin/An3.ogg
  sound/musical_instruments/violin/An4.ogg
  sound/musical_instruments/violin/An5.ogg
  sound/musical_instruments/violin/An6.ogg
  sound/musical_instruments/violin/An7.ogg
  sound/musical_instruments/violin/An8.ogg
  sound/musical_instruments/violin/B#1.ogg
  sound/musical_instruments/violin/B#2.ogg
  sound/musical_instruments/violin/B#3.ogg
  sound/musical_instruments/violin/B#4.ogg
  sound/musical_instruments/violin/B#5.ogg
  sound/musical_instruments/violin/B#6.ogg
  sound/musical_instruments/violin/B#7.ogg
  sound/musical_instruments/violin/B#8.ogg
  sound/musical_instruments/violin/Bb1.ogg
  sound/musical_instruments/violin/Bb2.ogg
  sound/musical_instruments/violin/Bb3.ogg
  sound/musical_instruments/violin/Bb4.ogg
  sound/musical_instruments/violin/Bb5.ogg
  sound/musical_instruments/violin/Bb6.ogg
  sound/musical_instruments/violin/Bb7.ogg
  sound/musical_instruments/violin/Bb8.ogg
  sound/musical_instruments/violin/Bn1.ogg
  sound/musical_instruments/violin/Bn2.ogg
  sound/musical_instruments/violin/Bn3.ogg
  sound/musical_instruments/violin/Bn4.ogg
  sound/musical_instruments/violin/Bn5.ogg
  sound/musical_instruments/violin/Bn6.ogg
  sound/musical_instruments/violin/Bn7.ogg
  sound/musical_instruments/violin/Bn8.ogg
  sound/musical_instruments/violin/Cb7.ogg
  sound/musical_instruments/violin/Cb9.ogg
  sound/musical_instruments/violin/Cn9.ogg
  sound/musical_instruments/violin/G#8.ogg
  sound/musical_instruments/violin/Gn8.ogg
Labels: Fix, Test Merge Candidate, Sound

#9710 more vv protected types
  code/__DEFINES/varedit.dm
  code/modules/admin/admin_report.dm
  code/modules/mob/living/carbon/monkey/punpun.dm
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Fix

#9616 Cleaning sound (effects && machines)
  sound/effects/curtain.ogg
  sound/effects/mousesqueek.ogg
  sound/effects/refill.ogg
  sound/effects/scrap_fall.ogg
  sound/effects/shieldbash.ogg
  sound/effects/shovel_digging.ogg
  sound/effects/singlebeat.ogg
  sound/effects/splat.ogg
  sound/effects/spray2.ogg
  sound/effects/spray3.ogg
  sound/effects/squeak.ogg
  sound/machines/cfieldbeforestart.ogg
  sound/machines/click.ogg
  sound/machines/scrap_beacon_start.ogg
  sound/machines/shutter_close.ogg
  sound/machines/shutter_open.ogg
  sound/machines/signal.ogg
  sound/machines/spring.ogg
  sound/weapons/saberoff.ogg
  sound/weapons/saberon.ogg
  sound/weapons/smash.ogg
Labels: Sound

#9712 небольшая правка спрайтов у синдиригов
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/suits.dmi
Labels: Sprites

#9729 фикс обреза
  icons/obj/gun.dmi
Labels: Sprites

#9724 Удаляет спейс нинжу из списка рандомных ивентов
  code/modules/events/_event_container.dm
Labels: Revert / Removal

#9698 Купальники для толстых
  code/modules/clothing/suits/miscellaneous.dm
Labels: Sprites

#9703 Обновлённый звук ПТРа
  sound/weapons/guns/gunshot_cannon.ogg
Labels: Sound

#9718 Позволяет вылазить из слипера одиссея
  code/game/mecha/equipment/tools/medical_tools.dm
Labels: Tweak

#9715 Shadowling's big voice & Harbinger's marker
  code/datums/spells/wizard.dm
  code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
  tgui/packages/tgui-panel/styles/goon/chat-base.scss
  tgui/public/tgui-panel.bundle.css
Labels: Tweak

#9694 Drugs will make you happier!
  code/datums/mood_events/generic_positive_events.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Feature

#9740 Melee damage fix
  code/_globalvars/lists/skills.dm
  code/modules/skills/skillset.dm
Labels: Fix

#9734 Фиксы синдиборга
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/syndi/syndiborg.dm
Labels: Fix
