Repository TauCetiStation/TauCetiClassic, pull requests merged in 2022-03, with the labels that each got.

#8614 unsim environment
  code/__DEFINES/flags.dm
  code/_onclick/item_attack.dm
  code/datums/components/footstep.dm
  code/datums/diseases/advance/symptoms/vomit.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/mutations.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/turfs/simulated.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated.dm
  code/modules/atmospheric/ZAS/Airflow.dm
  code/modules/atmospheric/ZAS/Connection.dm
  code/modules/atmospheric/ZAS/ConnectionGroup.dm
  code/modules/atmospheric/ZAS/Turf.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hulk.dm
Labels: Test Merge Candidate

#8674 Бафф и ренейм раундстартовых ивентов
  code/__DEFINES/misc.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/game.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/events.dm
  code/game/gamemodes/modes_gameplays/cult/structures/cult_structures.dm
  code/game/objects/items/toys.dm
  code/modules/events/_event.dm
  code/modules/events/_event_container.dm
  code/modules/events/anomaly.dm
  code/modules/events/cult_portals.dm
  code/modules/events/roundstart_events/area/area_event.dm
  code/modules/events/roundstart_events/area/armory_mess.dm
  code/modules/events/roundstart_events/area/break_light.dm
  code/modules/events/roundstart_events/area/cargo_storage.dm
  code/modules/events/roundstart_events/area/dirt.dm
  code/modules/events/roundstart_events/area/lasertag_ed.dm
  code/modules/events/roundstart_events/area/maintenance.dm
  code/modules/events/roundstart_events/area/mess.dm
  code/modules/events/roundstart_events/area/minefield.dm
  code/modules/events/roundstart_events/area/replace/deathly_sec.dm
  code/modules/events/roundstart_events/area/replace/del_cable.dm
  code/modules/events/roundstart_events/area/replace/del_surgeon_tools.dm
  code/modules/events/roundstart_events/area/replace/med_morgue.dm
  code/modules/events/roundstart_events/area/replace/med_storage.dm
  code/modules/events/roundstart_events/area/replace/mice_attack.dm
  code/modules/events/roundstart_events/area/replace/mince_back.dm
  code/modules/events/roundstart_events/area/replace/random_airlock.dm
  code/modules/events/roundstart_events/area/replace/replace.dm
  code/modules/events/roundstart_events/area/replace/sec_weapons.dm
  code/modules/events/roundstart_events/area/replace/vault_gold.dm
  code/modules/events/roundstart_events/misc_events.dm
  code/modules/events/roundstart_events/roundstart.dm
  code/modules/scrap/scrap.dm
  taucetistation.dme
Labels: Test Merge Candidate

#8736 Add and remove accessories via Alt Click
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/storage.dm
Labels: Tweak

#8739 Небольшие фиксы, связанные с режимами
  code/__DEFINES/gamemodes.dm
  code/game/gamemodes/factions/abductors.dm
  code/game/gamemodes/misc_faction_procs.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/experiment.dm
  code/game/gamemodes/modes_gameplays/wizard/soulstone.dm
  code/game/gamemodes/roles/slave.dm
  taucetistation.dme
Labels: Fix

#8756 чейнжлинги больше не чувствуют грусть
  code/datums/mood_events/antags_events.dm
  code/game/gamemodes/roles/changeling.dm
  icons/mob/screen1.dmi
Labels: Feature

#8770 add cold overlay and fix ZASDBG
  code/__DEFINES/atmos.dm
  code/modules/atmospheric/ZAS/Turf.dm
  code/modules/atmospheric/xgm/overlays.dm
  code/modules/atmospheric/xgm/xgm_gas_data.dm
  code/modules/atmospheric/xgm/xgm_gas_mixture.dm
  icons/effects/tile_effects.dmi
  taucetistation.dme
Labels: Sprites

#8750 Твик статистики смертей
  code/__HELPERS/time.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/statistic/stat_dto.dm
  code/modules/statistic/statistics.dm
  code/modules/statistic/statistics_helpers.dm
Labels: Merge Conflict

#8738 Перевод пары интерфейсов на новые компоненты
  tgui/packages/tgui/interfaces/MafiaPanel.js
  tgui/packages/tgui/interfaces/ReligiousTool.js
  tgui/public/tgui.bundle.js
Labels: UI

#8613 Облегчение хостайлов.
  code/controllers/subsystem/mobs/chunks.dm
  code/controllers/subsystem/mobs/mobs.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  taucetistation.dme
Labels: Test Merge Candidate

#8727 Подмены подмены, нерф скорости
  code/__DEFINES/dcs/signals.dm
  code/datums/spawners_menu/spawners.dm
  code/game/machinery/podmen.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/carbon/species.dm
Labels: Balance, Feature

#8677 skrell resprite
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/species.dm
  icons/mob/human_face.dmi
  icons/mob/human_races/r_def_skrell.dmi
  icons/mob/human_races/r_skrell.dmi
Labels: Sprites

#8605 no more deep conversations with abductors meme, also smoking?
  code/__DEFINES/flags.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/mood_events/needs_events.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/species.dm
Labels: Tweak, Test Merge Candidate

#8773 Смазка видима
  code/game/turfs/simulated.dm
Labels: Balance, Revert / Removal

#8819 Воксонёрфы
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagent_types/Chemistry-Core.dm
Labels: Balance, Feature

#8823 vox balloons very funny
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/species.dm
Labels: Balance

#8786 Lectern
  code/game/objects/items/weapons/storage/bible/bible.dm
  code/game/objects/structures/chapel.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
  code/modules/religion/atoms_religify.dm
  code/modules/religion/religion.dm
  code/modules/religion/religion_types/chaplain.dm
  code/modules/religion/religion_types/cult.dm
  icons/obj/lectern.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Feature, Map Edit, Sprites

#8798 add map configs
  code/controllers/configuration.dm
  code/controllers/subsystem/junkyard.dm
  code/controllers/subsystem/mapping.dm
  config/example/config.txt
Labels: Config Update

#8826 Ремап арены.
  maps/centcom/centcom.dmm
Labels: Map Edit

#8827 Насыщение поста прослушки контентом. Да, опять ремап.
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  icons/mob/animal.dmi
  maps/templates/space_structures/listening_post.dmm
Labels: Map Edit

#8830 Choose your default lang
  code/datums/qualities/negativeish.dm
  code/modules/admin/verbs/pray.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/say.dm
Labels: Feature, Revert / Removal

#8837 nyctophobia fear only when moving
  code/datums/traits/negative.dm
Labels: Tweak

#8850 Ритуал конверта по умолчанию для капеллана
  code/__DEFINES/religion.dm
  code/modules/religion/aspect.dm
  code/modules/religion/religion_sects.dm
  code/modules/religion/religion_types/chaplain.dm
  code/modules/religion/rites/instant/instant.dm
  code/modules/religion/rites/standing/consent.dm
Labels: Revert / Removal, Tweak

#8463 Snow environment
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/footsteps.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/maps.dm
  code/__DEFINES/subsystem.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/lists/sound.dm
  code/controllers/subsystem/environment.dm
  code/datums/cob_highlight.dm
  code/datums/dirt.dm
  code/datums/map_config.dm
  code/game/atoms_movable.dm
  code/game/machinery/computer/arrival_shuttle.dm
  code/game/machinery/embedded_controller/embedded_controller_base.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/mech_bay.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/tracks.dm
  code/game/objects/items/devices/furtree.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/crates_lockers/closets/secure/barber.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/game/objects/structures/flora.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/game/turfs/turf_snow.dm
  code/game/world.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/atmospheric/ZAS/Turf.dm
  code/modules/holiday/months/december.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/maps/space_management/space_level.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/procedural_mapping/mapGeneratorModules/flora.dm
  code/modules/procedural_mapping/mapGeneratorModules/helpers.dm
  code/modules/procedural_mapping/mapGeneratorModules/snow.dm
  code/modules/procedural_mapping/mapGenerators/snow.dm
  config/example/maps.txt
  icons/ss13_64_xmas.png
  icons/turf/overlays.dmi
  icons/turf/rocks.dmi
  icons/turf/snow2.dmi
  maps/boxstation_snow.json
  sound/effects/icestep.ogg
  sound/effects/snowstep.ogg
  taucetistation.dme
Labels: Sprites, Sound, Config Update

#8700 TG/Bay/Tau Emotes Framework
  code/__DEFINES/emote.dm
  code/__DEFINES/pronouns.dm
  code/__HELPERS/global_lists.dm
  code/datums/emotes/emote.dm
  code/datums/emotes/generic.dm
  code/datums/emotes/human/audible.dm
  code/datums/emotes/human/gesture.dm
  code/datums/emotes/human/visual.dm
  code/datums/emotes/state_checks.dm
  code/modules/genetics/side_effects.dm
  code/modules/mob/living/carbon/human/MedicalSideEffects.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/monkey/npc.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/hulk.dm
  code/modules/mob/say.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/organ_internal.dm
  taucetistation.dme
Labels: Refactor, Test Merge Candidate

#8810 The letters
  code/__DEFINES/language.dm
  code/__HELPERS/text.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/say.dm
Labels: Feature, Tweak, Test Merge Candidate

#8855 lectern can't be flipped while anchored
  code/game/objects/structures/chapel.dm
Labels: Fix

#8864 фикс багули
  code/game/objects/structures/ladders.dm
Labels: Map Edit

#8884 респрайт банок с краской
  icons/obj/items.dmi
Labels: Sprites

#8866 More lectern fixes
  code/game/objects/structures/chapel.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  icons/obj/lectern.dmi
Labels: Fix, Sprites

#8893 Респрайт воксов и так далее
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  icons/mob/human_face.dmi
  icons/mob/human_races/husk.dmi
  icons/mob/human_races/r_vox.dmi
  icons/mob/species/tail.dmi
  icons/mob/species/vox/back.dmi
  icons/mob/species/vox/eyes.dmi
  icons/mob/species/vox/gloves.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/masks.dmi
  icons/mob/species/vox/shoes.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/species/vox/uniform.dmi
Labels: Sprites, Test Merge Candidate

#8779 снижает замедление у всего в примерно два раза
  code/game/gamemodes/modes_gameplays/cult/cult_items.dm
  code/game/gamemodes/modes_gameplays/ninja/space_ninja.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/Skafandr_kosmicheskiy.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/spacesuits/globose.dm
  code/modules/clothing/spacesuits/rig/ert.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/spacesuits/void.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Experimental, Test Merge Candidate

#8919 Trash Was Never There
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Revert / Removal

#8768 Починил мусор.
  code/game/objects/random/random_scrap.dm
Labels: Fix

#8924 Банька-парилка, ~~ЕРП~~ и горилка
  code/datums/mood_events/generic_positive_events.dm
  code/defines/obj/weapon.dm
  code/game/objects/structures/watercloset.dm
  sound/weapons/sauna_broom.ogg
Labels: Feature, Sound

#8946 Воксы снова могут надеть геосканнер
  icons/mob/species/vox/eyes.dmi
Labels: Fix, Sprites

#8808 Wizard remap
  code/game/machinery/vending/clothing.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/torch_holder.dm
  code/game/turfs/unsimulated/walls.dm
  code/modules/clothing/head/wiz_tophat.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/holidays/new_year/clothing.dm
  code/modules/power/lighting.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/doors/mineral_doors.dmi
  icons/obj/lighting.dmi
  icons/turf/floors.dmi
  icons/turf/walls/log.dmi
  maps/centcom/centcom.dmm
  taucetistation.dme
Labels: Map Edit, Sprites

#8933 GPS для сервисного и уборочного модуля
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Fix

#8956 Воксы не могли носить спейс съюты
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/Skafandr_kosmicheskiy.dm
  code/modules/clothing/spacesuits/syndi.dm
Labels: Fix

#8841 Ремап библиотеки.
  code/game/objects/random/random_misc.dm
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#8940 Воксы смогут качаться и получить более накаченные бубисы
  code/modules/organs/external/flesh.dm
  icons/mob/human_races/r_vox.dmi
Labels: Feature, Sprites

#8917 ФИЧА ФРИЗ НА ВСЕ ПР-Ы ДОБАВЛЯЮЩИЕ УНИФОРМУ ВЫШЕ ЭТОГО
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/species/vox/uniform.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
Labels: Sprites, FEATURE FREEZE, Code Improvements

#8967 Fixes Missing Sprites
  code/modules/cargo/prices.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/pants.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/customitems/item_defines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
Labels: Sprites

#8579 telekinesis rework
  code/__DEFINES/mob.dm
  code/_onclick/click.dm
  code/_onclick/drag_drop.dm
  code/_onclick/telekinesis.dm
  code/datums/cob_highlight.dm
  code/datums/components/forcefield.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/modes_gameplays/families/induction_package.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/autoinjectors.dm
  code/game/objects/items/weapons/defibrillator.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/medical.dm
  code/game/objects/items/weapons/tanks/watertank.dm
  code/game/objects/structures/signs/_signs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/telekinesis.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
  code/modules/paperwork/carbonpaper.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paperbin.dm
  code/modules/projectiles/firing.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/projectile.dm
  code/modules/research/xenoarchaeology/tools/tools_wave_scanner.dm
  code/modules/scrap/scrap_light.dm
  code/modules/tgui/states/interactive_reach.dm
  taucetistation.dme
Labels: Balance, Feature, Test Merge Candidate

#8971 Теперь можно изменить спрайт алтаря священника
  code/modules/religion/atoms_religify.dm
Labels: Fix

#8930 removing mutantrace
  code/__DEFINES/varedit.dm
  code/datums/datumvars.dm
  code/datums/traits/negative.dm
  code/game/dna/dna2.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
  code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
  code/game/gamemodes/roles/heist.dm
  code/game/machinery/podmen.dm
  code/game/objects/structures/window.dm
  code/modules/awaymissions/corpse.dm
  code/modules/maps/maps_code/wildwest.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/external/flesh.dm
  code/modules/organs/organ_external.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
  icons/effects/genetics.dmi
  icons/mob/human_face.dmi
  icons/mob/human_races/r_zombie.dmi
  icons/mob/human_races/r_zombie_lizard.dmi
  icons/mob/human_races/r_zombie_skrell.dmi
  icons/mob/human_races/r_zombie_tajaran.dmi
Labels: Code Improvements, Test Merge Candidate

#8979 fixes vox, uniforms, rolling down
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
Labels: Fix, Sprites

#8949 Start landmark renaming
  code/controllers/subsystem/ticker.dm
  code/game/objects/effects/landmarks.dm
  code/modules/admin/create_mob.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
  code/modules/scrap/scrap_people.dm
  icons/mob/landmarks.dmi
  icons/mob/screen_gen.dmi
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit, Sprites

#9003 удаляет рандомные пушки и неиспользуемые спрайты пушек
  code/modules/cargo/exports/weapons.dm
  code/modules/projectiles/ammunition/energy.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/mob/back.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
  maps/templates/space_structures/secrete_lab.dmm
  maps/templates/space_structures/ships_squad.dmm
Labels: Map Edit, Sprites
