Repository TauCetiStation/TauCetiClassic, pull requests merged in 2022-02, with the labels that each got.

#8553 Золото из хранилища лежит в сейфе, а не в незащищенном ящике
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#8559 У дион нет порога скорости игры на пианино
  code/datums/music_player.dm
Labels: Revert / Removal

#8446 мыло респрайт+реворк
  code/datums/uplinks_items.dm
  code/game/machinery/kitchen/kitchen_machines.dm
  code/game/objects/items/devices/scanners/contraband_finder.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/gift_wrappaper.dm
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
  code/game/objects/items/weapons/mop.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/random/random_syndie.dm
  code/game/objects/structures/janicart.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/cargo/prices.dm
  code/modules/customitems/item_defines.dm
  code/modules/holidays/new_year/presents.dm
  code/modules/mining/equipment_locker.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  icons/effects/effects.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/items.dmi
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
  maps/templates/space_structures/abandoned_ship.dmm
  maps/templates/space_structures/broken_breacher.dmm
  maps/templates/space_structures/secrete_lab.dmm
  sound/voice/hiccup.ogg
Labels: Feature, Map Edit, Sprites, Sound

#8563 Фикс клонилки
  code/game/machinery/computer/cloning.dm
Labels: Fix

#8569 Респрайт пажилых аптечек
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/aibots.dmi
  icons/obj/storage.dmi
Labels: Sprites

#8540 Новый кораблик воксов
  code/game/area/shuttle_areas.dm
  code/game/gamemodes/factions/heist.dm
  code/game/gamemodes/objectives/heist/kidnap.dm
  code/game/gamemodes/objectives/heist/loot.dm
  code/game/gamemodes/objectives/heist/salvage.dm
  code/game/machinery/computer/vox_shuttle.dm
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/modules/locations/shuttles/floor.dm
  code/modules/locations/shuttles/object_wall.dm
  code/modules/locations/shuttles/shuttle_window.dm
  icons/locations/shuttles/vox_pc.dmi
  icons/locations/shuttles/vox_shuttle.dmi
  icons/locations/shuttles/vox_shuttle_inner.dmi
  icons/mob/back.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/tank.dmi
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit, Sprites, Test Merge Candidate

#8570 Laser cannon [slowed+reverb]
  icons/mob/belt.dmi
  icons/mob/belt_mirror.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
Labels: Sprites

#8527 Исправления спавна ЕРТшников через спавнер меню
  code/datums/spawners_menu/spawners.dm
  code/game/gamemodes/factions/strike_teams.dm
Labels: Fix, Stalled PR

#8547 Ребаланснул способы попадения на станцию у нюкеров.
  code/__DEFINES/_planes+layers.dm
  code/datums/announcements/gamemode.dm
  code/game/machinery/computer/intruder_station.dm
  code/game/machinery/computer/syndicate_shuttle.dm
  code/game/machinery/droppod.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/devices/gateway_locker.dm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
Labels: Balance, Map Edit

#8560 Скреллы не издают звук "М", "R" говоря на родном языке для тех кто его не знает
  code/modules/mob/language.dm
Labels: Tweak

#8578 правки доступа на посте прослушивания
  maps/templates/space_structures/listening_post.dmm
Labels: Map Edit

#8594 Ритуалы, где требуется согласие, автоматические ассептяца у мобов без маенда
  code/datums/components/rites/consent.dm
Labels: Tweak

#8551 Респрайт детективского пальто и шляпы
  code/game/machinery/vending/clothing.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/jobs.dm
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#8566 garbage collector update
  code/__DEFINES/qdel.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/garbage.dm
  code/modules/admin/verbs/getlogs.dm
  config/example/config.txt
Labels: Test Merge Candidate

#8561 Drunkenness, Confusion rework
  code/__DEFINES/mob.dm
  code/datums/diseases/advance/symptoms/confusion.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/status_effects/debuffs.dm
  code/game/gamemodes/modes_gameplays/abduction/gland.dm
  code/game/gamemodes/modes_gameplays/changeling/headcrab.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/shriek.dm
  code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/weapons/chaplain_weapons.dm
  code/game/objects/items/weapons/dice.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/modules/genetics/side_effects.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/reagents/reagent_types/Chemistry-Core.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
  code/modules/religion/rites/standing/misc.dm
  code/modules/virus2/effect.dm
Labels: Balance, Feature, Tweak

#8556 Нелюди тоже получили точки
  code/modules/mob/living/say.dm
Labels: Tweak

#8586 Beauty runtime
  code/__DEFINES/dcs/signals.dm
  code/datums/components/mood.dm
  code/game/area/areas.dm
Labels: Sprites

#8513 Из общедоступного мусора (теха) больше не падают робастные штуки
  code/game/objects/random/random_cloth.dm
  code/game/objects/random/random_science.dm
  code/game/objects/random/random_scrap.dm
  code/modules/scrap/scrap.dm
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit, Tweak

#8582 Аксессуары Можно Надевать На Верхнюю Одежду
  code/game/objects/items.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/armband.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Feature

#8572 Моё сееердце остановилось, моё сееердце замерло.
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/organs/organ_internal.dm
Labels: Tweak

#8587 Нерф и твик культа
  code/datums/spells/area_teleport.dm
  code/game/gamemodes/modes_gameplays/cult/rune_datum.dm
  code/modules/religion/religion.dm
  taucetistation.dme
Labels: Balance, Tweak

#8599 when the spawner is infinite, an infinity symbol is shown
  code/datums/spawners_menu/spawners_menu.dm
  tgui/packages/tgui/assets/bg-nanotrasen.svg
  tgui/packages/tgui/assets/bg-neutral.svg
  tgui/packages/tgui/assets/bg-syndicate.svg
  tgui/packages/tgui/assets/bg-wizard.svg
  tgui/packages/tgui/interfaces/SpawnersMenu.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: UI

#8615 добавляет аксессуары-броню
  code/modules/clothing/head/beret.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/under/accessories/armor.dm
  icons/obj/clothing/accessory.dmi
  icons/obj/clothing/hats.dmi
  taucetistation.dme
Labels: Feature, Sprites

#8603 Добавляет контрабандисту войс-чейнджер и взрывной имплант.
  code/game/gamemodes/modes_gameplays/families/outfit.dm
Labels: Tweak

#7929 Голый фреймворк особок
  code/__DEFINES/subsystem.dm
  code/controllers/subsystem/qualities.dm
  code/controllers/subsystem/ticker.dm
  code/datums/qualities/quality.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/lobby.dm
  code/modules/mob/dead/new_player/new_player.dm
  taucetistation.dme
Labels: Merge Conflict, Pinned, Preferences Update

#8472 Сила есть - ума не надо.
  code/__DEFINES/dcs/signals.dm
  code/game/objects/fitness.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/organs/external/flesh.dm
  code/modules/organs/organ_external.dm
  code/modules/scrap/scrap.dm
  code/modules/sports/PedalGen.dm
  icons/mob/human_races/r_human.dmi
  icons/mob/human_races/r_lizard.dmi
  icons/mob/human_races/r_skrell.dmi
  icons/mob/human_races/r_tajaran.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/fitness.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Feature, Sprites

#8625 pickup, putdown, drag, silently. while walking
  code/game/animation_helpers.dm
Labels: Feature

#8637 don't pump your prosthetics
  code/modules/organs/external/robotic.dm
  code/modules/organs/external/skeleton.dm
  code/modules/organs/external/stump.dm
Labels: Fix

#8644 vox, diona don't pump them dumbbells
  code/game/objects/fitness.dm
  code/modules/mining/mine_turfs.dm
  code/modules/organs/external/flesh.dm
  code/modules/organs/organ_external.dm
  code/modules/scrap/scrap.dm
Labels: Fix

#8635 suicide
  code/game/gamemodes/modes_gameplays/ninja/suit/SpiderOS/topic.dm
  code/game/machinery/computer/cloning.dm
  code/game/objects/items/devices/aicard.dm
  code/game/verbs/suicide.dm
  code/modules/mob/transform_procs.dm
Labels: Feature

#8652 fixes an issue with weight negation
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Fix

#8612 Luduk osobki content
  code/__DEFINES/traits.dm
  code/controllers/subsystem/jobs.dm
  code/controllers/subsystem/qualities.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/mood_events/quality_events.dm
  code/datums/qualities/negativeish.dm
  code/datums/qualities/positiveish.dm
  code/datums/qualities/quality.dm
  code/datums/qualities/quirkieish.dm
  code/game/gamemodes/factions/syndicate.dm
  code/modules/mob/dead/new_player/lobby.dm
  code/modules/mob/dead/new_player/logout.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/paperwork/paper.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/virus2/disease2.dm
  code/modules/virus2/helpers.dm
  taucetistation.dme
Labels: Feature

#8562 Лазер СБ борга перезаряжается
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/projectiles/ammunition/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
Labels: Fix

#8675 Pumped broken legs don't give speedup
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Tweak

#8647 нерф смазки
  code/game/turfs/simulated.dm
Labels: Balance

#8601 Тестовики и их подпрофы лишились зарплаты
  code/datums/outfits/jobs/assistant.dm
  code/game/area/station_areas.dm
  code/game/jobs/job/assistant.dm
  code/modules/client/preferences_savefile.dm
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Tweak, Test Merge Candidate

#8650 Кач кач кач кач
  code/__DEFINES/math.dm
  code/_onclick/item_attack.dm
  code/game/objects/fitness.dm
  code/modules/organs/external/flesh.dm
  code/modules/sports/PedalGen.dm
Labels: Fix, Tweak

#7091 Wedging crowbar
  code/__DEFINES/tools.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/events/cellular_biomass/biomass.dm
  code/modules/events/cellular_biomass/spacevines.dm
  code/modules/mining/mine_items.dm
  code/modules/paperwork/pen.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/effects/cut.dmi
Labels: Feature

#8636 Combos make you strong
  code/__DEFINES/mob.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/living.dm
  code/modules/unarmed_combat/combat_combo.dm
  code/modules/unarmed_combat/combo_handler.dm
  code/modules/unarmed_combat/combos/disarming.dm
  code/modules/unarmed_combat/combos/harmful.dm
Labels: Feature

#8609 World went melancholic from sadness
  code/__DEFINES/colors.dm
  code/datums/components/mood.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Feature, Test Merge Candidate

#8628 Подкидыши и Подмены. Забытая жажда крови
  code/__DEFINES/mob.dm
  code/datums/diseases/appendicitis.dm
  code/datums/spawners_menu/spawners.dm
  code/game/gamemodes/modes_gameplays/abduction/gland.dm
  code/game/machinery/hydroponics.dm
  code/game/machinery/podmen.dm
  code/game/machinery/seed_extractor.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/events/cellular_biomass/spacevines.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/mob.dm
  code/modules/organs/external/nymph.dm
  code/modules/organs/external/plant.dm
  code/modules/organs/organ_external.dm
  code/modules/surgery/gender_reassignment.dm
  icons/mob/head.dmi
  icons/mob/human_races/r_def_plant.dmi
  icons/mob/human_races/r_plant.dmi
  icons/mob/human_races/r_podman.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/monkey.dmi
  icons/mob/species/vox/helmet.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/hydroponics.dmi
  icons/obj/hydroponics/seeds.dmi
  icons/obj/objects.dmi
  taucetistation.dme
Labels: Feature, Merge Conflict, Sprites

#8687 Understanding Yet Not Speaking
  code/__DEFINES/language.dm
  code/datums/qualities/positiveish.dm
  code/game/gamemodes/modes_gameplays/changeling/evolution_menu.dm
  code/game/gamemodes/roles/traitor.dm
  code/game/objects/items/weapons/chaplain_weapons.dm
  code/modules/client/character menu/general.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/say.dm
Labels: Preferences Update

#8285 Реворк Контрабанд Сканнеров
  code/__HELPERS/global_lists.dm
  code/_onclick/drag_drop.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/scanners/contraband_finder.dm
  code/game/objects/items/devices/scanners/contraband_listing.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/admin/verbs/debug.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_forms.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/device.dmi
  taucetistation.dme
Labels: Sprites

#8404 Огрызок рунчата, который работает и на Тау
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/mc.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/subsystem.dm
  code/__HELPERS/game.dm
  code/__HELPERS/text.dm
  code/controllers/master.dm
  code/controllers/subsystem/runechat.dm
  code/controllers/subsystem/timer.dm
  code/datums/runechat.dm
  code/game/atoms.dm
  code/game/machinery/computer/camera.dm
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/say.dm
  icons/hud/chat_icons.dmi
  interface/skin.dmf
  taucetistation.dme
  tgui/packages/tgui/interfaces/CameraConsole.js
  tgui/public/tgui.bundle.js
Labels: Feature, DO NOT MERGE, Sprites, Test Merge Candidate, Preferences Update

#8671 Броня для бандитов
  code/datums/uplinks_items.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
Labels: Feature

#8672 Фиксы культа
  code/__HELPERS/_lists.dm
  code/datums/spells/religion.dm
  code/game/gamemodes/modes_gameplays/cult/structures/rune.dm
  code/game/objects/items/weapons/storage/bible/tome.dm
  code/modules/religion/religion.dm
Labels: Fix

#8720 Фикс нереанимации у генки и живых людей
  code/modules/mob/living/carbon/human/human.dm
  code/modules/organs/organ_internal.dm
Labels: Fix
