Repository TauCetiStation/TauCetiClassic, pull requests merged in 2023-07, with the labels that each got.

#11597 Lifted mood debuffs: screen overlay and slowdown
  code/datums/components/mood.dm
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Revert / Removal, Test Merge Candidate

#11604 Fix for bugged overlays?
  code/game/objects/structures/chapel.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Test Merge Candidate

#11533 переносит кучу говна из рюкзаков нюкеров в их шкафчики
  code/datums/outfits/nuclear.dm
  code/game/gamemodes/roles/syndicate.dm
  code/game/objects/structures/crates_lockers/closets/secure/syndicate.dm
  icons/obj/closet.dmi
  maps/centcom/centcom.dmm
  taucetistation.dme
Labels: Fix, Map Edit, Sprites, Tweak

#11626 Изменения починки протезов
  code/game/objects/items/weapons/tools.dm
  code/modules/power/cable.dm
Labels: Fix

#11555 Увеличил размер окна с бумажкой и пропорции сделал А4
  code/modules/paperwork/paper.dm
Labels: Tweak

#11637 Респрайт тазера
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
Labels: Sprites

#11631 респрайт бюджетного скафандра
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#11624 Фикс метаболизма карбонов (кроме людей)
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix, Test Merge Candidate

#11272 Crawling robusters
  code/__DEFINES/misc.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/unsorted.dm
  code/datums/spells/conjure.dm
  code/datums/spells/in_hand.dm
  code/datums/status_effects/debuffs.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/Whip.dm
  code/game/machinery/deployable.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/replicators/replicator_attacks.dm
  code/modules/surgery/surgery.dm
Labels: Feature, Test Merge Candidate

#11607 небольшая переделка нелегальной ветки
  code/modules/research/designs.dm
  code/modules/research/research.dm
  nano/css/shared.css
  nano/images/science.png
Labels: Feature

#11653 Boxstation Map Edit. Deleting some cameras
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#11654 Дополнение хирургической сумки Синдиката
  code/game/objects/items/weapons/storage/backpack.dm
Labels: Fix, Tweak

#11596 Бафф королевы ксеноморфов. Новая способность.
  code/modules/mob/living/carbon/xenomorph/effects/aliens.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/queen.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  icons/mob/xenomorph.dmi
Labels: Balance, Feature, Sprites

#11640 New default light mode
  code/modules/lighting/lamps/light_modes.dm
Labels: Tweak, Test Merge Candidate

#11647 New smartlight bulb icons
  code/modules/power/lighting/lamps.dm
  icons/obj/lighting.dmi
Labels: Sprites, Test Merge Candidate

#11580 Macro to help work with random types in code
  code/__DEFINES/misc.dm
  code/game/objects/random/pouches.dm
  code/game/objects/random/random.dm
  code/game/objects/random/random_all.dm
  code/game/objects/random/random_guns.dm
  code/game/objects/random/random_tools.dm
  code/game/turfs/turf_snow.dm
  code/modules/recycling/disposal.dm
  code/modules/religion/rites/standing/misc.dm
  code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm
  code/modules/roguelike/mob_modifiers/positive.dm
  code/modules/scrap/scrap.dm
  code/modules/scrap/scrap_people.dm
Labels: Refactor

#11661 нерф скелетов v 2
  code/modules/mob/living/carbon/species.dm
Labels: Balance

#11668 фикс быстрого снятия спес сьютов
  code/datums/components/clickplace.dm
Labels: Fix

#11681 Delta Station. Road to Playtest
  code/game/area/delta_areas.dm
  code/modules/holodeck/HolodeckControl.dm
  maps/delta/delta.dmm
  maps/delta/job_changes.dm
  taucetistation.dme
Labels: Map Edit

#11678 BRF&U
  code/game/objects/items/weapons/autoinjectors.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Labels: Fix

#11685 приводит пистолеты к единому родителю
  code/datums/outfits/nuclear.dm
  code/datums/qualities/positiveish.dm
  code/datums/uplinks_items.dm
  code/game/gamemodes/modes_gameplays/families/outfit.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/random/random_guns.dm
  code/game/objects/random/random_syndie.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/cargo/packs.dm
  code/modules/cargo/prices.dm
  code/modules/events/roundstart_events/area/replace/station_rearmament.dm
  code/modules/jungle/jungle_temple.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  maps/RandomZLevels/assistantChamber.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/templates/space_structures/cult_ship.dmm
  maps/templates/space_structures/secrete_lab.dmm
Labels: Map Edit, Translation/Localization

#11688 Default chair resprite
  icons/obj/objects.dmi
Labels: Sprites

#11671 смена режима гибдридного костюма больше не убирает замедление магбутсов
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Fix

#11710 [MDB IGNORE] Фикс кодировки дельты
  maps/delta/delta.dmm
Labels: Fix, Map Edit

#11690 Предметы можно ловить в полете
  code/game/atoms_movable.dm
  code/game/objects/fitness.dm
  code/game/objects/items/ashtray.dm
  code/game/objects/items/devices/biocan.dm
  code/game/objects/items/devices/scanners/contraband_finder.dm
  code/game/objects/items/devices/scanners/health_analyzer.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/light.dm
  code/game/objects/items/stacks/tiles/light.dm
  code/game/objects/items/stacks/tiles/plasteel.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/legcuffs.dm
  code/game/objects/items/weapons/makeshift.dm
  code/game/objects/items/weapons/mop.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/holidays/new_year/snow.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
  code/modules/mob/living/silicon/robot/analyzer.dm
  code/modules/mob/living/simple_animal/vox.dm
  code/modules/paperwork/pen.dm
  code/modules/paperwork/stamps.dm
  code/modules/power/lighting/bulbs.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/research/experiment.dm
  code/modules/research/xenoarchaeology/genetics/prehistoric_plants.dm
  code/modules/telesci/bscrystal.dm
Labels: Tweak, Test Merge Candidate

#11692 детективу теперь падают роли
  code/game/gamemodes/roles/changeling.dm
  code/game/gamemodes/roles/cultist.dm
  code/game/gamemodes/roles/families.dm
  code/game/gamemodes/roles/revolution.dm
  code/game/gamemodes/roles/shadowling.dm
  code/game/gamemodes/roles/traitor.dm
  code/game/objects/items/devices/traitor_caller.dm
  taucetistation.dme
Labels: Feature

#11700 Фикс шкафа БЩ
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Tweak

#11713 Фикс хранилища пробирок
  code/game/objects/items/weapons/storage/fancy.dm
Labels: Fix

#11715 [Fix]Фикс движения мыши
  icons/mob/animal.dmi
Labels: Fix, Sprites

#11721 [Fix] При разборе пожарных створок теперь спавнится плата
  code/game/machinery/doors/firedoor.dm
Labels: Fix

#11719 Gamma2 Areas and Lights
  code/game/area/gamma_areas.dm
  maps/gamma/gamma_revamp.dmm
Labels: Map Edit

#11706 Talismans rebalance
  code/modules/religion/altar_types/altar_of_gods.dm
  code/modules/religion/rites/instant/instant.dm
Labels: Experimental

#11697 Исправления переводов сообщений от ЦК во время революции
  code/game/gamemodes/factions/revolution.dm
Labels: Translation/Localization

#11727 Пластик из угля функционален.
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/scrap/scrap.dm
Labels: Fix

#11757 до работка гаммы
  maps/gamma/gamma_revamp.dmm
Labels: Map Edit

#11723 [MDB IGNORE] Delta Station Map Edit. Playtest Ready.
  code/controllers/subsystem/shuttles.dm
  code/game/area/shuttle_areas.dm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
Labels: Map Edit

#11761 Condiments Repsrite_shelf
  icons/obj/cond_shelf.dmi
Labels: Sprites

#11769 Борг апгрейд требует вытащить батарейку
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Balance

#11744 Дергаем спрайты ботинок у трапов
  icons/mob/feet.dmi
Labels: Sprites

#11775 Gamma_Revamp Road to Greatness #3
  code/game/area/gamma_areas.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  maps/gamma/gamma_revamp.dmm
Labels: Map Edit

#11778 515 верб панель
  interface/skin.dmf
Labels: Fix

#11786 Gamma4
  maps/gamma/gamma_revamp.dmm
Labels: Map Edit

#11785 больше нельзя лечить самого себя медганом
  code/modules/projectiles/guns/energy/special.dm
Labels: Fix

#11784 Controlles VV now requires R_DEBUG
  code/modules/admin/verbs/massmodvar.dm
  code/modules/admin/verbs/modifyvariables.dm
Labels: Admin

#11783 Station announcements
  code/datums/announcements.dm
  code/modules/economy/economy_misc.dm
Labels: Tweak

#11780 Lifted lightmode debuffs: screen overlay in bar is gone
  code/modules/smartlight/smartlight_presets.dm
Labels: Tweak

#11779 камеру блоба/ии/прочих не запихнуть в шкаф
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#11777 Autosolar 2: Electric Boogaloo
  code/modules/power/solar.dm
  maps/gamma/gamma_revamp.dmm
Labels: Map Edit

#11776 Уменьшает интервал между взятием некоторых гост-ролей.
  code/datums/spawners_menu/spawners.dm
Labels: Tweak

#11751 В мусоре теперь будут встечаться инъекторы и таблетки
  code/game/objects/random/random_meds.dm
Labels: Feature

#11773 Небольшие изменения плазма оружия
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/utility.dm
  code/modules/holidays/new_year/clothing.dm
  code/modules/projectiles/guns/plasma/plasma.dm
  icons/mob/belt_mirror.dmi
Labels: Balance, Sprites
