Repository TauCetiStation/TauCetiClassic, pull requests merged in 2023-03, with the labels that each got.

#10858 Грузторг твики и фичи
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/cargo/shop.dm
  code/modules/recycling/sortingmachinery.dm
Labels: Tweak

#10812 нерф кача ног
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Balance

#10893 добавляет молотов
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  icons/obj/drinks.dmi
  icons/obj/reagentfillings.dmi
Labels: Feature, Sprites

#9410 Сбор общественного мнения по завершении раунда
  code/__DEFINES/subsystem.dm
  code/controllers/subsystem/round_rating.dm
  code/controllers/subsystem/shuttles.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/voting/vote_choice.dm
  code/datums/browser.dm
  code/modules/statistic/stat_dto.dm
  code/modules/statistic/statistics.dm
  taucetistation.dme
  tgui/packages/tgui-panel/styles/goon/chat-base.scss
  tgui/public/tgui-panel.bundle.css
Labels: Feature, Test Merge Candidate, UI

#10661 Fix xeno eggs
  code/modules/mob/living/carbon/xenomorph/effects/aliens.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
Labels: Fix, Test Merge Candidate

#10917 Bonfire particles
  code/modules/scrap/scrap_light.dm
  icons/effects/bonfire.dmi
Labels: Sprites, Tweak

#10913 Сокращает ритуал Клоунконверсии до 40 секунд.
  code/modules/religion/rites/standing/consent.dm
Labels: Tweak

#10744 добавляет крутые шоковые перчатки
  code/datums/uplinks_items.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/clothing/gloves/power_gloves.dm
  icons/obj/clothing/gloves.dmi
  taucetistation.dme
Labels: Feature, Sprites

#10907 сhem master buff
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Tweak

#10681 Нанитовое дополнение кода исследований
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
  code/modules/research/server.dm
Labels: Stalled PR

#10937 Апдейт прометея
  maps/prometheus/prometheus.dmm
  nano/images/nanomap_prometheus_1.png
  nano/images/nanomap_prometheus_1_small.png
Labels: Map Edit

#10941 Удаление вечного рантайма мага
  maps/centcom/centcom.dmm
Labels: Map Edit

#10602 Перевод описания Емага, ИД карт и дисков.
  code/game/objects/items/weapons/cards_ids.dm
Labels: Stalled PR, Translation/Localization

#10720 Переименование деталей для более удобной установки
  code/_globalvars/lists/misc.dm
  code/defines/obj/weapon.dm
  code/game/gamemodes/modes_gameplays/abduction/abduction_gear.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/constructable_frame.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_wreckage.dm
  code/game/objects/random/random_science.dm
  code/modules/power/fusion/fusion_circuits.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/research/designs.dm
  code/modules/shieldgen/circuits_and_designs.dm
  maps/falcon/falcon.dmm
  maps/stroechka/stroechka.dmm
  maps/templates/space_structures/robostation.dmm
  maps/templates/space_structures/secrete_lab.dmm
Labels: Map Edit, Merge Conflict

#10806 Revert Labeler Del
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/vehicles/vehicle.dm
  code/modules/virus2/items_devices.dm
  icons/obj/bureaucracy.dmi
  icons/obj/device.dmi
Labels: Map Edit, Sprites

#10853 Sheets in-hands
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Sprites

#10874 Респрайт кошелька
  icons/obj/storage.dmi
Labels: Sprites

#10773 Закалённые Адомаем. Шерсть теперь влияет!
  code/modules/mob/living/carbon/species.dm
Labels: Feature

#10930 Хилган без харм интента вплотную теперь лечит, а не бьет.
  code/modules/projectiles/guns/energy/special.dm
Labels: Tweak

#10888 fix 10886/10826
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Tweak

#10923 non-admins can now vote for the custom vote
  code/controllers/subsystem/vote.dm
  tgui/packages/tgui/interfaces/Vote.tsx
  tgui/public/tgui.bundle.js
Labels: Fix, UI

#10827 еда повышает и понижает настроение
  code/datums/mood_events/needs_events.dm
  code/modules/reagents/_chemistry.dm
  code/modules/reagents/reagent_containers/food/glowsticks.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/reagents/reagent_types/Chemistry-Foods.dm
Labels: Tweak

#10935 buff chameleon skin / fix 10254
  code/game/gamemodes/modes_gameplays/changeling/powers/Chameleon_skin.dm
Labels: Balance

#10801 быстрый эквип карты теперь сует её в пда
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Feature

#10900 Обновление скилов на установку столов
  code/game/objects/items/weapons/table_rack_parts.dm
Labels: Tweak

#10926 КМ дебил пароль не поставил
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Tweak

#10838 Vote interface tweak
  tgui/packages/tgui/interfaces/Vote.tsx
  tgui/public/tgui.bundle.js
Labels: UI

#10871 голосование за шатл в красный код хотя бы
  code/controllers/subsystem/voting/poll_types.dm
Labels: Tweak

#10961 Revolution v.3.0. Reason Update
  code/_compile_options.dm
  code/game/gamemodes/factions/revolution.dm
  code/game/gamemodes/roles/revolution.dm
  code/game/objects/effects/decals/contraband.dm
Labels: Feature

#10986 рандомная сытость
  code/modules/mob/dead/new_player/new_player.dm
Labels: Tweak

#10880 Mags resprites + tweaks
  code/datums/outfits/misc/shitspawn.dm
  code/datums/outfits/nuclear.dm
  code/datums/qualities/positiveish.dm
  code/datums/uplinks_items.dm
  code/game/gamemodes/modes_gameplays/families/outfit.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/vending/other.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/random/random_guns.dm
  code/game/objects/random/random_syndie.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/cargo/packs.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/old_pirate_guns.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/reagents/dartgun.dm
  code/modules/research/designs.dm
  icons/obj/ammo.dmi
  icons/obj/ammo/boxes.dmi
  icons/obj/ammo/casings.dmi
  icons/obj/ammo/magazines.dmi
  icons/obj/gun.dmi
  icons/obj/tools.dmi
  maps/RandomZLevels/assistantChamber.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/wildwest.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/templates/space_structures/abandoned_lab.dmm
Labels: Map Edit, Sprites

#11011 быстрофикс экстендед магазина на глоук
  icons/obj/ammo/magazines.dmi
Labels: Sprites

#10983 добавляет задержку перед использованием нанопасты
  code/game/objects/items/stacks/nanopaste.dm
Labels: Fix

#10854 крупнокалиберные автоматы желательно держать в двух руках
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/plasma/plasma.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/launcher.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/rocket.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Balance

#11003 СПУ фиксы
  code/game/objects/items/stacks/nanopaste.dm
  code/modules/surgery/face.dm
  code/modules/surgery/other.dm
  code/modules/surgery/ribcage.dm
Labels: Fix

#10739 добавляет дереликт выживач
  code/_globalvars/mapping.dm
  code/datums/outfits/misc/survivalists.dm
  code/datums/space_structures.dm
  code/datums/spawners_menu/spawners.dm
  code/game/area/space_structures_areas.dm
  code/game/jobs/access.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/effects/spawners/mobspawner.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/power/smes.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/skills/skillsets/roles.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
  icons/turf/areas.dmi
  maps/templates/space_structures/old_station.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Sprites

#11027 CentComm Buying Underpriced CargoTrade Items
  code/controllers/subsystem/economy.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/cargo/exports.dm
  code/modules/cargo/shop.dm
  code/modules/cargo/shop_market_monitoring.dm
  code/modules/economy/economy_misc.dm
  code/modules/recycling/disposal.dm
  taucetistation.dme
Labels: Feature

#11028 when scanning something with shop tagger in your hand manually choose the price
  code/modules/recycling/sortingmachinery.dm
Labels: Tweak

#11032 CargoTrade: mark as delivered on click
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Tweak

#11031 bro tip for tagger usage
  code/modules/recycling/sortingmachinery.dm
Labels: Tweak

#10897 Скилы на стрельбу. Постоянство отдачи
  code/modules/projectiles/gun.dm
Labels: Tweak, Test Merge Candidate

#10971 vote hotfix
  code/controllers/subsystem/vote.dm
  tgui/packages/tgui/interfaces/Vote.tsx
  tgui/public/tgui.bundle.js
Labels: Test Merge Candidate

#11019 Temp Fix #11015
  code/__HELPERS/text.dm
Labels: Test Merge Candidate

#11039 vending machines don't charge twice
  code/game/machinery/vending.dm
Labels: Fix

#10980 Fix human hard delete
  code/_onclick/hud/alert.dm
  code/controllers/subsystem/garbage.dm
  code/datums/atom_huds/atom_hud.dm
  code/datums/atom_huds/atom_hud_antag.dm
  code/datums/components/mood.dm
  code/game/atoms_movable.dm
  code/game/machinery/iv_drip.dm
  code/game/machinery/kitchen/processor.dm
  code/game/objects/items/weapons/chaplain_weapons.dm
  code/modules/client/client_procs.dm
  code/modules/media/mediamanager.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/silicon/robot/syndi/drone/drone.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob.dm
  code/modules/organs/blood.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
  code/modules/virus2/isolator.dm
Labels: Performance, Test Merge Candidate

#11033 Where is my package? CargoTrade Fixes Abound
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/cargo/shop.dm
  code/modules/cargo/shop_market_monitoring.dm
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
  nano/templates/pda.tmpl
Labels: Tweak

#10927 бронебойность
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Feature

#11062 Human interfacing with revolution's poster
  code/game/objects/effects/decals/contraband.dm
Labels: Fix

#10870 Исправление рантайма при стрельбе по стенам
  code/game/turfs/simulated/walls.dm
Labels: Fix

#11010 Skrell toxin and blood tweaks
  code/game/sound.dm
  code/modules/mob/mob.dm
  code/modules/organs/blood.dm
  code/modules/reagents/reagent_types/Chemistry-Core.dm
  code/modules/reagents/reagent_types/Chemistry-Foods.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
Labels: Tweak

#10946 Immovable Rods + Meteors update port
  code/_globalvars/lists/objects.dm
  code/game/area/station_areas.dm
  code/modules/events/immovable_rod.dm
  code/modules/events/meteors.dm
Labels: Fix

#11080 fixes centcomm account money glitch
  code/modules/economy/Accounts.dm
  code/modules/economy/Accounts_DB.dm
  code/modules/economy/economy_misc.dm
Labels: Fix

#11030 Floor Tiles in-hands
  code/game/objects/items/stacks/tiles/plasteel.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/inhands/tiles_lefthand.dmi
  icons/mob/inhands/tiles_righthand.dmi
Labels: Sprites

#11072 пара фиксов дереликта old station
  code/game/objects/items/weapons/cards_ids.dm
  maps/templates/space_structures/old_station.dmm
Labels: Map Edit, MAP FREEZE

#10876 Abductor's assistant
  code/__DEFINES/gamemodes.dm
  code/game/gamemodes/modes_gameplays/abduction/gland.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/console.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/dispenser.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/experiment.dm
  code/game/gamemodes/roles/abductor.dm
  code/game/objects/items/weapons/implants/implanter.dm
Labels: Feature, Test Merge Candidate

#10922 Обновление голода
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/life.dm
Labels: Tweak, Test Merge Candidate

#11110 nerf pumped metabolism factor
  code/modules/organs/external/flesh.dm
Labels: Test Merge Candidate

#11093 Admin light modes
  code/controllers/subsystem/nightshift.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/secrets.dm
  code/modules/power/apc.dm
Labels: Test Merge Candidate

#11034 Акционерское Общество с Ограниченной Ответственностью "Каргония Стронк"
  code/__HELPERS/global_lists.dm
  code/controllers/subsystem/economy.dm
  code/controllers/subsystem/jobs.dm
  code/datums/qualities/positiveish.dm
  code/game/gamemodes/objectives/families/rob_nt.dm
  code/game/gamemodes/scoreboard.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/job.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/modules/cargo/exports/money.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/EFTPOS.dm
  code/modules/economy/cash.dm
  code/modules/economy/economy_misc.dm
Labels: Feature, Test Merge Candidate

#11081 solves all extinguisher abuses
  code/modules/reagents/reagent_containers/extinguisher.dm
Labels: Balance

#11025 Cyborg + Zurek = Kerfus! New borg sprite
  code/modules/mob/living/silicon/robot/robot.dm
  icons/mob/robots.dmi
Labels: Sprites

#11013 Ребаланс бол. Возвращение юзабельности.
  code/defines/obj/weapon.dm
  code/game/objects/items/weapons/legcuffs.dm
  code/modules/mob/living/living.dm
  taucetistation.dme
Labels: Balance, Feature

#11114 Defibrillator Resprite
  code/game/objects/items/weapons/defibrillator.dm
  icons/obj/defibrillator.dmi
Labels: Sprites

#11131 Анонсы к репликаторам
  code/datums/announcements.dm
  code/datums/announcements/gamemode.dm
  sound/AI/construction_began.ogg
  sound/AI/construction_doom.ogg
  sound/AI/construction_half.ogg
  sound/AI/construction_quarter.ogg
  sound/AI/construction_three_quarters.ogg
Labels: Sound

#11127 люди не будут терять сознание от сломанной ноги
  code/modules/organs/organ.dm
Labels: Feature

#10889 fixes hunter invis / fix 10850
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/hunter.dm
Labels: Fix

#10994 Нерф взрывного диализа
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Fix

#10903 добавляет парочку новых ядов
  code/defines/obj/hydro.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/cargo/packs.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
Labels: Feature

#11133 remove price tag on item purchase, instamagnetize
  code/game/objects/structures/tables_racks.dm
  code/modules/cargo/shop.dm
Labels: Tweak

#11139 Better tick usage according to byond 514 map_cpu
  code/__DEFINES/_tick.dm
  code/__DEFINES/tick.dm
  code/controllers/master.dm
  taucetistation.dme
Labels: Performance, Test Merge Candidate

#10959 бафф джефсквада
  code/datums/outfits/misc/shitspawn.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/rocket.dm
  icons/mob/belt_mirror.dmi
  icons/mob/head.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/gun.dmi
Labels: Feature, Sprites

#11150 возвращает ивент с вормхолами в список случайных ивентов
  code/modules/events/_event_container.dm
Labels: Feature

#11107 Перевод пары пар законов
  code/datums/ai_laws.dm
  code/game/gamemodes/factions/blob.dm
  code/game/gamemodes/factions/replicators.dm
  code/game/gamemodes/roles/traitor.dm
Labels: Translation/Localization

#11167 getting swole improves mood
  code/datums/mood_events/generic_positive_events.dm
  code/game/objects/fitness.dm
  code/modules/sports/PedalGen.dm
Labels: Feature

#11142 lag_switch subsystem from tg
  code/__DEFINES/chat.dm
  code/__DEFINES/dcs/helpers.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/lag_switch.dm
  code/__DEFINES/traits.dm
  code/_compile_options.dm
  code/_globalvars/configuration.dm
  code/_globalvars/lists/mob.dm
  code/_onclick/hud/parallax.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/demo.dm
  code/controllers/subsystem/input.dm
  code/controllers/subsystem/lag_switch.dm
  code/datums/components/footstep.dm
  code/datums/runechat.dm
  code/game/gamemodes/factions/malf_silicons.dm
  code/game/gamemodes/factions/replicators.dm
  code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
  code/game/verbs/ooc.dm
  code/game/world.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/say.dm
  config/example/config.txt
  taucetistation.dme
Labels: Admin, Performance, Test Merge Candidate, Config Update

#10659 Add queen screech stun to deaf humans and non human mobs
  code/modules/mob/living/carbon/xenomorph/powers.dm
Labels: Balance

#11016 станпрод апдейт
  code/game/objects/items/weapons/makeshift.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/recycling/sortingmachinery.dm
  icons/mob/back.dmi
Labels: Balance, Sprites

#11035 No speedrun
  code/game/gamemodes/factions.dm
  code/game/gamemodes/factions/infestation.dm
  code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
  code/game/gamemodes/objectives/shadowlings/shadowlings_objectives.dm
Labels: Balance

#11156 Fix stalls animation
  code/__DEFINES/animations.dm
  code/datums/components/clickplace.dm
  code/game/animation_helpers.dm
  code/game/objects/structures/tables_racks.dm
  taucetistation.dme
Labels: Fix

#11169 Usable toilets and urinals
  code/datums/mood_events/generic_positive_events.dm
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  sound/effects/toilet_flush.ogg
Labels: Feature, Test Merge Candidate, Sound
