Repository TauCetiStation/TauCetiClassic, pull requests merged in 2023-11, with the labels that each got.

#12379 Фикс камеры астеройда и переключателя света у криминалиста
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#12384 Imposters probabilites
  code/controllers/configuration.dm
Labels: Config Update

#12086 Небольшие перестановки ксено-запретов должностей
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/modules/client/preferences_savefile.dm
Labels: Balance, Preferences Update

#12374 Фикс библии священника
  code/modules/mob/inventory.dm
  code/modules/religion/religion_types/chaplain.dm
Labels: Fix

#12387 Твики микрофонов
  code/_globalvars/lists/objects.dm
  code/datums/announcements/station.dm
  code/game/gamemodes/modes_gameplays/nuclear/pinpointer.dm
  code/game/machinery/requests_console.dm
  code/game/objects/items/devices/microphone.dm
Labels: Revert / Removal, Tweak

#12391 In Mani works clear
  code/datums/spells/in_hand.dm
Labels: Fix

#12392 Chirrup! Нимфа дионы и отсутствие света
  code/modules/mob/living/carbon/monkey/life.dm
Labels: Feature

#12393 New dionea nymph health-hud
  code/_onclick/hud/monkey.dm
  code/_onclick/hud/ui_screens/basic.dm
  icons/hud/screen_diona.dmi
Labels: Sprites

#12394 Nymphs glowing eyes. Moving icon for podkid
  code/modules/mob/living/carbon/monkey/diona.dm
  icons/mob/monkey.dmi
Labels: Feature, Sprites

#12396 Korta Nut growing state repair
  icons/obj/hydroponics/growing_fruits.dmi
Labels: Fix, Sprites

#12389 cargotech and QM resprite
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/species/vox/uniform.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#12382 Stunbaton sound harm correct
  code/game/objects/items/weapons/stunbaton.dm
Labels: Fix

#12370 blob and canisters
  code/modules/atmospheric/machinery/portable/canister.dm
Labels: Balance

#12196 Фиксим перевод арбалета Fix #12193
  code/modules/projectiles/guns/projectile/bow.dm
Labels: Translation/Localization

#12407 Abomination`s notify fix
  code/game/gamemodes/roles/changeling.dm
Labels: Fix

#12401 Revert "Фикс библии священника (#12374)"
  code/modules/mob/inventory.dm
  code/modules/religion/religion_types/chaplain.dm
Labels: Fix

#12406 Transfer_actions fix
  code/datums/mind.dm
Labels: Fix

#12399 Pyro Anomaly runtime empty turfs
  code/modules/events/anomaly.dm
Labels: Fix

#12310 Машинка, печатающая формы в приёмной ГП.
  code/game/machinery/buttons.dm
  code/game/machinery/status_display.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/paperwork/ticket_machine.dm
  code/modules/recycling/sortingmachinery.dm
  icons/obj/bureaucracy.dmi
  icons/obj/card.dmi
  maps/boxstation/boxstation.dmm
  sound/items/label_printing.ogg
  sound/machines/ticket_printing.ogg
  taucetistation.dme
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#12383 Electronics tgui
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/machinery/doors/door.dm
  code/game/objects/structures/door_assembly.dm
  tgui/packages/tgui/interfaces/AirlockElectronics.tsx
  tgui/packages/tgui/interfaces/common/AccessList.js
  tgui/public/tgui.bundle.js
Labels: Fix, Feature, Tweak, Test Merge Candidate, UI

#12386 Крч огонь и взрывы с аномалиями переместились на плейн ламп.
  code/game/objects/effects/explosion_particles.dm
  code/modules/atmospheric/ZAS/Fire.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/ian/update_icons.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/update_icons.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/power/fusion/core/core_field.dm
Labels: Tweak, Test Merge Candidate

#12420 timer.dm:208 : undefined variable world/var/active_timers
  code/game/world.dm
Labels: Fix

#12398 fix resurrection after suicide
  code/game/objects/items/weapons/defibrillator.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#12409 Spawners update
  code/__HELPERS/cmp.dm
  code/_globalvars/lists/objects.dm
  code/_globalvars/mapping.dm
  code/controllers/subsystem/role_spawners.dm
  code/controllers/subsystem/ticker.dm
  code/datums/spawners_menu/spawners.dm
  code/datums/spawners_menu/spawners_living.dm
  code/datums/spawners_menu/spawners_menu.dm
  code/datums/spawners_menu/spawners_replicators.dm
  code/datums/spawners_menu/spawners_responder.dm
  code/game/gamemodes/factions/heist.dm
  code/game/gamemodes/factions/ninja.dm
  code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
  code/game/objects/effects/landmarks.dm
  code/modules/events/blob.dm
  code/modules/events/heist.dm
  code/modules/events/lone_op.dm
  code/modules/events/space_ninja.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/scrap/scrap_people.dm
  code/modules/tgui/states/spectator.dm
  taucetistation.dme
  tgui/packages/tgui/interfaces/SpawnersMenu.js
  tgui/public/tgui.bundle.js
Labels: Test Merge Candidate, UI

#12425 Monkey handle_environment()
  code/modules/mob/living/carbon/monkey/monkey.dm
Labels: Fix

#12416 Skeletons fixes
  icons/mob/human_races/r_skeleton.dmi
  icons/mob/human_races/r_skeleton_lizard.dmi
  icons/mob/human_races/r_skeleton_skrell.dmi
  icons/mob/human_races/r_skeleton_tajaran.dmi
  icons/mob/species/tail.dmi
Labels: Fix, Sprites

#12424 Last resort warning
  code/game/gamemodes/modes_gameplays/changeling/headcrab.dm
Labels: Tweak

#12426 Zombie spell
  code/_onclick/hud/_defines.dm
  code/modules/mob/living/carbon/human/zombie.dm
Labels: Tweak

#12340 Перевод ручного сканера здоровья
  code/__HELPERS/mobs.dm
  code/game/objects/items/devices/scanners/health_analyzer.dm
Labels: Translation/Localization

#12347 Изменение обозначений групп крови
  code/__HELPERS/mobs.dm
  code/game/dna/dna2.dm
  code/game/machinery/computer/medical.dm
  code/game/objects/effects/gibs.dm
  code/modules/client/character_menu/general.dm
  code/modules/client/preferences.dm
  code/modules/organs/organ_external.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
Labels: Tweak

#12328 Halloween Portal Creatures
  code/game/objects/effects/anomalies.dm
  code/game/objects/structures/traps.dm
  code/modules/mob/living/simple_animal/constructs.dm
  icons/mob/construct.dmi
Labels: Sprites, #halloween

#12363 Убрал мусор из Cryogenic3.dmi
  icons/obj/Cryogenic3.dmi
  icons/obj/cryogenics_split.dmi
Labels: Sprites

#12418 Мелко фикс перевода пневма пушки
  code/modules/projectiles/guns/projectile/pneumatic.dm
Labels: Translation/Localization

#12432 admin stuff
  code/game/world.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin.dm
  code/modules/client/guard.dm
  code/modules/tgui_panel/telemetry.dm
  config/example/guard_blacklist.txt
Labels: Config Update

#12438 Random cult portal fix
  code/datums/components/bound.dm
  code/datums/components/silence.dm
  code/datums/components/visible_radius.dm
  code/game/machinery/life_assist.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/structures/chapel.dm
  code/modules/events/cult_portals.dm
Labels: Tweak

#12430 Eye blur effect
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/living/living.dm
  code/modules/mob/login.dm
Labels: Feature, Preferences Update

#12446 удаляем выбор крови, чиним совместимость
  code/__DEFINES/DNA.dm
  code/__HELPERS/mobs.dm
  code/defines/obj/datacore.dm
  code/game/dna/dna2.dm
  code/game/machinery/computer/Operating.dm
  code/game/machinery/computer/medical.dm
  code/game/objects/effects/gibs.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/modules/admin/secrets.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/character_menu/general.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/organs/blood.dm
  code/modules/organs/external/flesh.dm
  code/modules/organs/organ_external.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
Labels: Fix, Revert / Removal, Preferences Update

#12428 Zombie virus effect
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/virus2/effect.dm
  icons/hud/screen_gen.dmi
Labels: Fix, Sprites, Tweak

#12277 telesci rework
  code/modules/telesci/telesci_computer.dm
Labels: Experimental, Test Merge Candidate

#12417 Changeling actions
  code/__DEFINES/dcs/signals.dm
  code/_onclick/hud/action.dm
  code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
  code/game/gamemodes/modes_gameplays/changeling/evolution_menu.dm
  code/game/gamemodes/modes_gameplays/changeling/headcrab.dm
  code/game/gamemodes/modes_gameplays/changeling/implant_menu.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/Chameleon_skin.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/Whip.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/augmented_eyesight.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/biodegrade.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/changespecies.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/digitalcamo.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/epinephrine.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/essences.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/fakedeath.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/fleshmend.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/hand_hammer.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/hivemind.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/lesserform.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/mimic_voice.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/mutations.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/panacea.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/revive.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/shriek.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/spiders.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/stings.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/strained_muscles.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/swallow.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/transform.dm
  code/modules/mob/transform_procs.dm
  icons/hud/actions_changeling.dmi
Labels: Feature, Sprites, Test Merge Candidate, UI

#12454 Spawner fixes
  code/datums/spawners_menu/spawners.dm
  code/datums/spawners_menu/spawners_menu.dm
  code/modules/client/client_defines.dm
Labels: Fix, Test Merge Candidate

#12452 Time to registration delete
  code/datums/spawners_menu/spawners_living.dm
Labels: Fix

#12457 fix
  code/datums/spawners_menu/spawners.dm
Labels: Fix

#12461 Микрофоны всем map/bugfix
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Fix, Map Edit

#12463 fix flashlight_emp
  code/game/objects/items/devices/flashlight.dm
Labels: Fix

#12470 fix #12468
  code/datums/spawners_menu/spawners.dm
Labels: Fix

#12437 Крупный перевод титров и немного до перевёл начало игры
  code/controllers/subsystem/jobs.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/modes_declares/blob.dm
  code/game/gamemodes/modes_declares/changeling.dm
  code/game/gamemodes/modes_declares/extended.dm
  code/game/gamemodes/modes_declares/imposters.dm
  code/game/gamemodes/modes_declares/infestation.dm
  code/game/gamemodes/modes_declares/malfunction.dm
  code/game/gamemodes/modes_declares/nuclear.dm
  code/game/gamemodes/modes_declares/replicators.dm
  code/game/gamemodes/modes_declares/revolution.dm
  code/game/gamemodes/modes_declares/shadowlings.dm
  code/game/gamemodes/modes_declares/traitorchan.dm
  code/game/gamemodes/modes_declares/traitors.dm
  code/game/gamemodes/modes_declares/wizard.dm
  code/game/gamemodes/scoreboard.dm
  code/game/jobs/job/captain.dm
Labels: Tweak, Translation/Localization

#12476 фикс педального спавна унатхов
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
Labels: Fix

#12381 Hallucination datum system
  code/__DEFINES/dcs/signals.dm
  code/__HELPERS/hallucinations.dm
  code/__HELPERS/mobs.dm
  code/datums/status_effects/debuffs.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/devices/scanners/health_analyzer.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/modules/mob/living/carbon/human/life.dm
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Test Merge Candidate

#12405 До переводим ОБР
  code/game/response_team/response_team.dm
Labels: Translation/Localization

#12415 Бафф фридома
  code/game/objects/items/weapons/implants/implantfreedom.dm
Labels: Tweak

#12429 аспект раунда пишется в титрах
  code/controllers/subsystem/ticker.dm
  code/datums/round_aspects/round_aspects.dm
Labels: Feature

#12441 ерп апдейт
  code/modules/client/character_menu/loadout/loadout_hats.dm
Labels: Tweak

#12385 Выпил дубликата кода откручивания смартхолодильников
  code/game/machinery/kitchen/smartfridge.dm
Labels: Fix

#12450 [#11977] Added check if admin ref was lost
  code/modules/admin/secrets.dm
  code/modules/admin/secrets/secrets_menu.dm
  code/modules/admin/secrets/tgui_secrets.dm
  code/modules/admin/secrets/tgui_secrets/custom_announcement.dm
  code/modules/admin/verbs/randomverbs.dm
  taucetistation.dme
Labels: Fix

#12431 Перевод сообщений от импланта лояльности
  code/game/objects/items/weapons/implants/mindshield.dm
Labels: Translation/Localization

#12465 респрайт костюмов для работ с аномалиями
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/research/xenoarchaeology/tools/particle_protection_suit.dm
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  maps/gamma/gamma.dmm
Labels: Fix, Map Edit, Sprites

#12473 Tables sprite fix
  icons/obj/smooth_structures/glass_table.dmi
  icons/obj/smooth_structures/poker_table.dmi
  icons/obj/smooth_structures/table.dmi
  icons/obj/smooth_structures/wooden_table.dmi
Labels: Sprites

#12478 Lesser form fix
  code/datums/components/cult_halo.dm
  code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
  code/game/gamemodes/modes_gameplays/changeling/headcrab.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/humanform.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/lesserform.dm
  code/modules/mob/transform_procs.dm
  taucetistation.dme
Labels: Fix

#12479 фикс машинки красящей карты у ГП
  code/game/machinery/IDpainter.dm
Labels: Fix

#12483 правим чуть-чуть реплеи
  code/__DEFINES/flags.dm
  code/controllers/subsystem/demo.dm
  code/modules/power/lighting/lamps.dm
Labels: Fix

#12495 экшен-кнопки работают у лежачих
  code/_onclick/hud/action.dm
  code/datums/components/zoom.dm
Labels: Fix

#12491 Stings fix
  code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/stings.dm
Labels: Fix

#12462 Процедурно генерируемые иконки штампов и оттиски
  code/datums/datumvars.dm
  code/game/gamemodes/objectives/families/steal_lowrisk.dm
  code/modules/cargo/prices.dm
  code/modules/paperwork/photocopier.dm
  code/modules/paperwork/stamps.dm
  code/modules/research/xenoarchaeology/misc.dm
  icons/obj/bureaucracy.dmi
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
  maps/stroechka/stroechka.dmm
Labels: Fix, Feature, Map Edit, Sprites

#12455 Closets and Crates resprite
  icons/obj/closet.dmi
  icons/obj/storage.dmi
Labels: Sprites, Test Merge Candidate

#12508 [Finished] Перевод описания гранат и других взрывчаток.
  code/game/objects/items/weapons/explosives.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/ghettobomb.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
  code/game/objects/items/weapons/syndie.dm
Labels: Translation/Localization

#12487 bartender resprite
  code/datums/outfits/misc/shitspawn.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/barber.dm
  code/modules/cargo/packs.dm
  code/modules/client/character_menu/loadout/loadout_accessories.dm
  code/modules/client/character_menu/loadout/loadout_clothing.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/accessory.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/clothing/accessory.dmi
  icons/obj/clothing/accessory_overlay.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/templates/holodeck/theatre.dmm
  maps/templates/space_structures/space_villa.dmm
Labels: Map Edit, Sprites, Awaiting Review [Sprite Dep]

#12510 qol pipes
  code/modules/atmospheric/machinery/atmospherics.dm
Labels: Tweak

#12553 фикс спавна ассистентов
  code/game/objects/effects/landmarks.dm
  icons/mob/landmarks.dmi
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Fix, Map Edit, Sprites
