Repository TauCetiStation/TauCetiClassic, pull requests merged in 2023-09, with the labels that each got.

#11987 BoxStation: apc fix for new light
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#12003 [MDB IGNORE] Delta Station Map Edit. New Turf Pallete and New Lighting
  icons/turf/turf_decals.dmi
  maps/delta/delta.dmm
Labels: Map Edit, Sprites

#12031 фикс спрайта ритэга
  code/modules/power/port_gen_riteg.dm
Labels: Fix

#12027 игрушечные мечи теперь разноцветные
  code/game/objects/items/toys.dm
Labels: Tweak

#12026 новый негативный квирк
  code/__DEFINES/quirks.dm
  code/__DEFINES/traits.dm
  code/datums/traits/negative.dm
  code/modules/organs/blood.dm
Labels: Feature

#12007 Gamma Fixes, New Nanoui, Floor Tweaks and Action Figure Collection!
  maps/gamma/gamma.dmm
  nano/images/nanomap_gamma_1.png
Labels: Map Edit

#12024 Delta Station Map Edit. Maintenance and Cameras, less view for security and AI
  maps/delta/delta.dmm
Labels: Map Edit

#12056 APC update: boxstation, asteroid, centcomm and z-levels
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/palette/palette.dmm
Labels: Map Edit

#11986 Fixes commited
  code/game/objects/items/weapons/implants/implanter.dm
  code/game/objects/items/weapons/storage/secure.dm
  code/modules/research/rdconsole.dm
  code/modules/research/server.dm
  code/modules/research/xenoarchaeology/artifact/effects/sleepy.dm
  maps/templates/space_structures/old_station.dmm
Labels: Fix, Map Edit

#12049 Нерф анестезии.
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  icons/obj/iv_drip.dmi
  icons/obj/tank.dmi
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Feature, Map Edit, Sprites, Tweak

#12044 теперь можно ставить стартовые лэндмарки для альт проф
  code/controllers/subsystem/jobs.dm
Labels: Fix

#11967 улучшение ролплея ии
  code/datums/datumvars.dm
  code/game/machinery/camera/tracking.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/mob_movement.dm
  icons/mob/AI.dmi
  sound/misc/ai_threads.ogg
Labels: Sprites, Test Merge Candidate, Sound

#11791 потассиум хлорофорид снова требует хлорки для крафта
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Balance, Feedback required

#11971 Unrestricted sides
  code/datums/wires/_wires.dm
  code/datums/wires/airlock.dm
  code/game/jobs/job/engineering.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/windoor_assembly.dm
  icons/obj/doors/airlocks/station/overlays.dmi
Labels: Feature, Sprites

#11995 баффы химического зольдата нюки
  code/__DEFINES/colors.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/items/weapons/tanks/watertank.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/items.dmi
Labels: Balance

#12005 Настраиваемая плата холодильника
  code/game/machinery/constructable_frame.dm
Labels: Feature

#12011 Часть 1.2 Вендоматы боргам
  code/game/machinery/vending.dm
Labels: Balance

#12012 Часть 1.3 Джетпаки для всех модулей
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
  code/modules/research/designs/mechfabricator_designs.dm
Labels: Balance

#12023 Уменьшает замедление специализированным костюмам
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/utility.dm
Labels: Balance

#12040 фикс бага спавнеров ерт воксов абдукторов
  code/datums/spawners_menu/spawners.dm
  code/datums/spawners_menu/spawners_responder.dm
Labels: Fix

#12042 repair wheelchairs
  code/modules/mob/mob_movement.dm
Labels: Fix

#12060 APC Update: Delta, Gamma, Falcon.
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/palette/palette.dmm
Labels: Map Edit

#11922 Перевод, дополнение и добавление помощи при получении антага
  code/datums/components/gamemodes/syndicate.dm
  code/game/gamemodes/roles/blob.dm
  code/game/gamemodes/roles/changeling.dm
  code/game/gamemodes/roles/cultist.dm
  code/game/gamemodes/roles/replicator.dm
  code/game/gamemodes/roles/revolution.dm
  code/game/gamemodes/roles/shadowling.dm
  code/game/gamemodes/roles/wizard.dm
  code/game/gamemodes/roles/zombie.dm
Labels: Translation/Localization

#12057 Удешевление боевой мини аптечки
  code/datums/uplinks_items.dm
Labels: Balance

#12062 Быстрофикс моей ошибки
  code/modules/atmospheric/machinery/portable/canister.dm
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit, Tweak

#12074 Fix #12073
  code/datums/qualities/quirkieish.dm
Labels: Fix

#12075 APC Update: Prometheus, Prometheus_asteroid and Stroechka
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
  maps/stroechka/stroechka.dmm
Labels: Map Edit

#12072 Респрайт усиленного пола и замена его на объединяемый пол.
  code/game/turfs/floor/carpets.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/walls_cult.dm
  icons/turf/floors/smooth/floortile.dmi
  icons/turf/floors/smooth/floortile_dark.dmi
  icons/turf/floors/smooth/floortile_neutral.dmi
  icons/turf/floors/smooth/floortile_white.dmi
  icons/turf/floors/smooth/hardfloor_1.dmi
  icons/turf/floors/smooth/hardfloor_2.dmi
  icons/turf/floors/smooth/hardfloor_3.dmi
  icons/turf/floors/smooth/hardfloor_4.dmi
Labels: Map Edit, Sprites

#12059 The Doors resprite and Plating fix
  code/game/machinery/doors/airlock_types.dm
  icons/obj/doors/DoorHazard.dmi
  icons/obj/doors/airlocks/centcom/centcom.dmi
  icons/obj/doors/airlocks/centcom/overlays.dmi
  icons/obj/doors/airlocks/external/external.dmi
  icons/obj/doors/airlocks/external/overlays.dmi
  icons/obj/doors/airlocks/hatch/centcom.dmi
  icons/obj/doors/airlocks/hatch/maintenance.dmi
  icons/obj/doors/airlocks/hatch/overlays.dmi
  icons/obj/doors/airlocks/highsec/highsec.dmi
  icons/obj/doors/airlocks/highsec/overlays.dmi
  icons/obj/doors/airlocks/station/atmos.dmi
  icons/obj/doors/airlocks/station/bananium.dmi
  icons/obj/doors/airlocks/station/command.dmi
  icons/obj/doors/airlocks/station/diamond.dmi
  icons/obj/doors/airlocks/station/engineering.dmi
  icons/obj/doors/airlocks/station/freezer.dmi
  icons/obj/doors/airlocks/station/gold.dmi
  icons/obj/doors/airlocks/station/maintenance.dmi
  icons/obj/doors/airlocks/station/medical.dmi
  icons/obj/doors/airlocks/station/mining.dmi
  icons/obj/doors/airlocks/station/neutral.dmi
  icons/obj/doors/airlocks/station/overlays.dmi
  icons/obj/doors/airlocks/station/phoron.dmi
  icons/obj/doors/airlocks/station/public.dmi
  icons/obj/doors/airlocks/station/research.dmi
  icons/obj/doors/airlocks/station/sandstone.dmi
  icons/obj/doors/airlocks/station/science.dmi
  icons/obj/doors/airlocks/station/security.dmi
  icons/obj/doors/airlocks/station/silver.dmi
  icons/obj/doors/airlocks/station/uranium.dmi
  icons/obj/doors/airlocks/station/virology.dmi
  icons/obj/doors/airlocks/station2/glass.dmi
  icons/obj/doors/airlocks/station2/overlays.dmi
  icons/obj/doors/airlocks/vault/overlays.dmi
  icons/obj/doors/airlocks/vault/vault.dmi
  icons/obj/doors/blast_door.dmi
  icons/obj/doors/mineral_doors.dmi
  icons/obj/doors/rapid_pdoor.dmi
Labels: Sprites

#12079 You Spin Me Right Round Baby Right Round
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/example.dmm
  maps/RandomZLevels/listeningpost.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/wildwest.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/mafia/mafia_ball.dmm
  maps/mafia/mafia_gothic.dmm
  maps/mafia/mafia_snow.dmm
  maps/mafia/mafia_syndie.dmm
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
  maps/stroechka/stroechka.dmm
  maps/templates/space_structures/abandoned_lab.dmm
  maps/templates/space_structures/abandoned_ship.dmm
  maps/templates/space_structures/agrosphere.dmm
  maps/templates/space_structures/broken_breacher.dmm
  maps/templates/space_structures/cloning_lab.dmm
  maps/templates/space_structures/cult_ship.dmm
  maps/templates/space_structures/derelict_station.dmm
  maps/templates/space_structures/dj_station.dmm
  maps/templates/space_structures/export_outpost.dmm
  maps/templates/space_structures/iss.dmm
  maps/templates/space_structures/listening_post.dmm
  maps/templates/space_structures/old_station.dmm
  maps/templates/space_structures/research_ship.dmm
  maps/templates/space_structures/robostation.dmm
  maps/templates/space_structures/robostation2.dmm
  maps/templates/space_structures/secrete_lab.dmm
  maps/templates/space_structures/space_villa.dmm
  maps/templates/space_structures/syndicate_fighter.dmm
Labels: Map Edit

#12080 Быстрофикс Дверных Кручений
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit

#12077 Del light preset hardcode
  code/modules/power/apc.dm
Labels: Test Merge Candidate

#12081 изификс пулла кухонной машинерии
  code/game/machinery/kitchen/kitchen_machines.dm
Labels: Fix

#12082 Mini_fix #12048
  code/modules/client/character_menu/loadout/loadout_general.dm
Labels: Fix

#12038 Добавление кастомных staffwho к праздникам (доп праздники и ( цензура) некст пром, киборг мерджи)
  code/modules/holiday/months/april.dm
  code/modules/holiday/months/august.dm
  code/modules/holiday/months/december.dm
  code/modules/holiday/months/february.dm
  code/modules/holiday/months/january.dm
  code/modules/holiday/months/may.dm
  code/modules/holiday/months/november.dm
  code/modules/holiday/months/october.dm
Labels: Feature

#12093 Исправил типы постеров и плитки лежащих в техах гаммы
  maps/gamma/gamma.dmm
Labels: Fix, Map Edit

#11745 Imposters without uplink
  code/__DEFINES/flags.dm
  code/__DEFINES/gamemodes.dm
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/traits.dm
  code/_globalvars/game_modes.dm
  code/_globalvars/lists/misc.dm
  code/datums/atom_huds/atom_hud_data.dm
  code/datums/components/gamemodes/syndicate.dm
  code/datums/qualities/quirkieish.dm
  code/game/gamemodes/factions.dm
  code/game/gamemodes/factions/autotraitors.dm
  code/game/gamemodes/factions/traitors.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/modes_declares/imposters.dm
  code/game/gamemodes/objectives/steal.dm
  code/game/gamemodes/roles/traitor.dm
  code/game/gamemodes/roles/traitorchan.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
  code/game/machinery/adv_med.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/modules/admin/DB_ban/functions.dm
  code/modules/admin/topic.dm
  code/modules/client/preferences_savefile.dm
  taucetistation.dme
Labels: Experimental, Config Update

#11923 [Часть 1]Перевод описания всего лазерного/огнестрельного оружия
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/energy/temperature.dm
  code/modules/projectiles/guns/plasma/plasma.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/bow.dm
  code/modules/projectiles/guns/projectile/launcher.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/pneumatic.dm
  code/modules/projectiles/guns/projectile/silencer.dm
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Translation/Localization

#11924 госты могут поменять себе дальность обзора
  code/__DEFINES/lag_switch.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/lag_switch.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/login.dm
  config/example/config.txt
Labels: Tweak, Pinned, Config Update

#11993 Changeling Biodegrade Tweak
  code/game/gamemodes/modes_gameplays/changeling/powers/biodegrade.dm
Labels: Balance, Tweak, Test Merge Candidate

#12061 ложки-вилки-палочки теперь кормят нормально
  code/game/objects/items/weapons/kitchen.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/kitchen.dmi
Labels: Fix, Sprites

#12070 Наследство древних шизов
  config/example/access levels.txt
  config/example/custom_sprites.txt
  config/example/rules.html
  config/example/svndir.txt
Labels: Config Update

#12071 добавляет экшн кнопки для переключения магбутсов и шлема в риге
  code/modules/clothing/spacesuits/rig/rig.dm
  icons/hud/actions.dmi
Labels: Feature, Sprites

#12084 Расширение ассортимента автолата
  code/game/machinery/autolathe.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/storage/firstaid.dm
Labels: Tweak

#12091 Карточки заимели инворлд иконки и были респрайтнуты.
  code/game/machinery/computer/guestpass.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/detectivework/evidence.dm
  code/modules/detectivework/scanner.dm
  icons/obj/card.dmi
Labels: Sprites

#12092 СПУ разучились в бессмертие
  code/modules/surgery/ribcage.dm
Labels: Fix

#12095 заменяет кнопку дыхания из баллонов на экшн кнопку у баллонов
  code/_onclick/hud/human.dm
  code/_onclick/hud/monkey.dm
  code/_onclick/hud/other_mobs.dm
  code/_onclick/hud/ui_screens/basic.dm
  code/datums/outfits/outfit.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/essences.dm
  code/game/gamemodes/modes_gameplays/heist/vox_equip.dm
  code/game/gamemodes/roles/ninja.dm
  code/game/machinery/life_assist.dm
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/admin/verbs/striketeam_syndicate.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/mob_defines.dm
Labels: Tweak

#12096 Музыка на арене стала дольше
  code/controllers/subsystem/ticker.dm
  sound/lobby/Thunderdome_cut.ogg
Labels: Sound

#12099 Windows and plate fix
  icons/obj/smooth_adapters/adapters.dmi
  icons/obj/smooth_structures/windows/window.dmi
  icons/obj/smooth_structures/windows/window_reinforced.dmi
  icons/turf/floors.dmi
Labels: Sprites

#12103 ТГУИ крио камеры
  code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
  nano/templates/cryo.tmpl
  tgui/packages/tgui/interfaces/Cryo.js
  tgui/public/tgui.bundle.js
Labels: Tweak, UI

#12104 Другой интерфейс кухонной машинерии
  code/game/machinery/kitchen/kitchen_machines.dm
Labels: Tweak

#12113 Адекватные спрайты внутренностей СПУ
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  icons/mob/species/ipc/surgery.dmi
Labels: Sprites

#12115 Пачка фиксов СПУ
  code/defines/obj/datacore.dm
  code/game/atoms_movable.dm
  code/game/dna/dna2.dm
  code/game/dna/dna_modifier.dm
  code/game/gamemodes/modes_gameplays/nuclear/pinpointer.dm
  code/game/gamemodes/modes_gameplays/wizard/soulstone.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/droppod.dm
  code/game/machinery/records_scanner.dm
  code/game/mecha/mecha_topic.dm
  code/game/objects/items/devices/paicard.dm
  code/game/objects/items/weapons/dna_injector.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
Labels: Fix

#12112 Окончательное устранение гендеров у некоторых рас
  code/__DEFINES/flags.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/sanitize_values.dm
  code/datums/emotes/human/audible.dm
  code/modules/client/character_menu/general.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_defines.dm
Labels: Fix, Preferences Update

#12119 Руки теперь можно помыть
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#12120 теперь можно сделать флафф-рюкзак
  code/modules/fluff/customitems.dm
Labels: Feature

#12129 Фикс крио камеры
  code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
  tgui/packages/tgui/interfaces/Cryo.js
  tgui/public/tgui.bundle.js
Labels: UI

#12090 Общее обновление пресетов света и фиксы Бокса
  code/modules/lighting/lamps/light_modes.dm
  code/modules/smartlight/smartlight_presets.dm
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#12134 SSSmoothing fixes
  code/__HELPERS/icon_smoothing.dm
  code/controllers/subsystem/icon_smooth.dm
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/machines.dm
  code/controllers/subsystem/overlays.dm
Labels: Test Merge Candidate

#12143 Fix #12131 Игрушечный арбалет теперь тоже на русском
  code/game/objects/items/toys.dm
Labels: Fix

#12018 Опустил на один пиксель кляп
  icons/mob/mask.dmi
Labels: Fix, Sprites, Stalled PR, Awaiting Review [Sprite Dep]

#12160 у нюкеров больше нет двух пар билетиков
  code/datums/spawners_menu/spawners.dm
  code/datums/spawners_menu/spawners_responder.dm
  code/game/gamemodes/role.dm
Labels: Fix

#12155 одиночные световые мечи светятся
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/paperwork/pen.dm
Labels: Fix

#12121 new space structure
  code/datums/space_structures.dm
  code/game/area/space_structures_areas.dm
  code/game/objects/effects/spawners/mobspawner.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
  icons/effects/landmarks_static.dmi
  icons/turf/turf_decals.dmi
  maps/templates/space_structures/flagship.dmm
Labels: Map Edit, Sprites

#12151 Дублирование обджективов убрано
  code/game/gamemodes/role.dm
Labels: DO NOT MERGE

#12127 Спрайты вскрытых воксов
  code/modules/mob/living/carbon/species.dm
  icons/mob/species/vox/surgery.dmi
Labels: Sprites

#12141 fix disposal overlay
  code/modules/recycling/disposal.dm
  icons/obj/pipes/disposal.dmi
Labels: Sprites

#12006 респрайт книг и книжной полки
  icons/obj/library.dmi
  icons/obj/objects.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#12028 [MDB IGNORE] Бесплатная Свалка на эксту
  code/game/area/awaymission_areas.dm
  code/game/gamemodes/modes_declares/junkyard.dm
  code/game/gamemodes/modesbundle.dm
  code/modules/scrap/scrap_people.dm
  code/modules/scrap/scrap_turfs.dm
  maps/junkyard/junkyard.dmm
  taucetistation.dme
Labels: Feature

#12153 Статусмониторы заимели свой нормальный тини шрифт
  code/game/machinery/status_display.dm
  code/modules/asset_cache/asset_list_items.dm
  html/custom-fonts/StatusDisplays.eot
  html/custom-fonts/StatusDisplays.ttf
  html/custom-fonts/StatusDisplays.woff
  html/custom-fonts/custom-fonts.css
Labels: Tweak, Test Merge Candidate

#12162 Guns tweaks
  code/modules/projectiles/firing.dm
  code/modules/projectiles/guns/plasma/plasma.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/automatic.dm
Labels: Balance, Tweak

#12163 New Tables
  icons/obj/smooth_structures/fancy_black_table.dmi
  icons/obj/smooth_structures/fancy_table.dmi
  icons/obj/smooth_structures/glass_table.dmi
  icons/obj/smooth_structures/poker_table.dmi
  icons/obj/smooth_structures/reinforced_table.dmi
  icons/obj/smooth_structures/stall_table.dmi
  icons/obj/smooth_structures/table.dmi
  icons/obj/smooth_structures/wooden_table.dmi
Labels: Sprites

#12161 HUD барбера и стилиста стал зелёным
  icons/hud/hud.dmi
Labels: Sprites

#12152 Добавил множество декоративных и не очень предметов.
  code/controllers/subsystem/ticker.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/items/decorations.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/simulated/walls_reinforced.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/cargo/packs.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/paperbin.dm
  html/custom-fonts/TINIESTONE.eot
  html/custom-fonts/TINIESTONE.ttf
  html/custom-fonts/TINIESTONE.woff
  html/custom-fonts/custom-fonts.css
  icons/obj/bureaucracy.dmi
  icons/obj/contraband.dmi
  icons/obj/items.dmi
  icons/obj/lamps.dmi
  icons/obj/lighting.dmi
  icons/obj/stationobjs.dmi
  maps/boxstation/boxstation.dmm
  maps/templates/space_structures/derelict_station.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Sprites

#12168 Быстренько пофиксил одну недоработку
  code/game/objects/items/decorations.dm
Labels: Fix

#12170 [MDB IGNORE] Delta Station Map Edit. Патч конца сентября.
  maps/delta/delta.dmm
Labels: Map Edit

#12164 disposal lightup
  code/modules/recycling/disposal.dm
  icons/obj/pipes/disposal.dmi
Labels: Sprites

#12176 Чистка...
  config/example/alienwhitelist.txt
  icons/VendingMachineBG.png
  icons/vending_icons/vendingslot_bg.png
Labels: Config Update

#12098 Бафф ловушек мага
  code/datums/spells/wizard.dm
  code/game/objects/structures/traps.dm
Labels: Balance, Feature

#12183 Мелкофиксы Гаммы: Окна, Мебель, Атмос
  maps/gamma/gamma.dmm
  maps/palette/palette.dmm
  nano/images/nanomap_gamma_1.png
Labels: Map Edit

#12184 бафф бол
  code/game/objects/items/weapons/legcuffs.dm
Labels: Balance

#12192 небольшой фикс самодельного арбалета
  code/modules/projectiles/guns/projectile/bow.dm
Labels: Fix
