Repository TauCetiStation/TauCetiClassic, pull requests merged in 2023-06, with the labels that each got.

#11430 теперь можно подглядеть пин-код во время пользования АТМ
  code/modules/economy/ATM.dm
Labels: Feature

#11484 Новые экраны для СПУ и стряхивание пыли со старых
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#11488 Closets nerf
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Tweak

#11493 2 positive qualities
  code/datums/qualities/positiveish.dm
  code/modules/paperwork/paper.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/ammo/magazines.dmi
  icons/obj/gun.dmi
Labels: Sprites

#11502 фикс ворлдикон шняги
  code/game/objects/items.dm
  code/modules/mining/coins.dm
Labels: Fix

#11505 Сообщения в чатике при изменении духа
  code/datums/components/mood.dm
Labels: Feature

#11382 Nuke fixes and TGUI
  code/datums/wires/nuclearbomb.dm
  code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
  tgui/packages/tgui/interfaces/NuclearBomb.js
  tgui/public/tgui.bundle.js
Labels: Fix, Tweak, UI

#11486 Replicator Mines Don't Give Out Nearby Replicators
  code/controllers/subsystem/mobs/chunks.dm
  code/game/gamemodes/factions/replicators.dm
Labels: Tweak

#11487 cargo starting money
  code/controllers/subsystem/jobs.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/job.dm
Labels: Tweak

#11504 Condiments Repsrite
  code/modules/reagents/reagent_containers/food/condiment.dm
  icons/obj/condiments.dmi
  icons/obj/food.dmi
Labels: Sprites

#11520 fixes #11519
  code/game/machinery/podmen.dm
Labels: Fix

#11516 форенсик техникал респрайт
  code/datums/outfits/jobs/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#10884 Удобный ефтпос.
  code/__DEFINES/memories.dm
  code/controllers/subsystem/jobs.dm
  code/game/machinery/autolathe.dm
  code/modules/cargo/packs.dm
  code/modules/economy/EFTPOS.dm
  code/modules/economy/cardpay.dm
  icons/obj/device.dmi
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/templates/space_structures/export_outpost.dmm
  taucetistation.dme
  tgui/packages/tgui/interfaces/CardPay.js
  tgui/public/tgui.bundle.js
Labels: Feature, Map Edit, Sprites, Test Merge Candidate, UI

#11498 Delta Station Map Edit. All shutters, buttons and some more fixes
  maps/delta/delta.dmm
Labels: Map Edit

#11517 Обновление наноуи карты бокса
  nano/images/nanomap_exodus_1.png
Labels: Fix

#11531 Фиксы Тыквяка
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/items/weapons/hydroponics.dm
Labels: Fix

#11540 Delta Map Edit. Access to almost all doors, windoors
  maps/delta/delta.dmm
Labels: Map Edit

#11301 Constructs balance
  code/datums/spells/conjure.dm
  code/game/gamemodes/modes_gameplays/cult/structures/cult_structures.dm
  code/modules/mob/living/simple_animal/constructs.dm
Labels: Balance

#11526 Slimes UI
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/carbon/metroid/powers.dm
  code/modules/mob/living/simple_animal/friendly/slime.dm
  icons/hud/actions.dmi
Labels: Feature, Sprites

#11546 Delta Station Map Edit. External Airlocks
  code/controllers/subsystem/shuttles.dm
  maps/delta/delta.dmm
Labels: Map Edit

#11440 Небольшой перевод animals
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/carbon/metroid/examine.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
  code/modules/mob/living/simple_animal/bees.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/friendly/crab.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/mushroom.dm
  code/modules/mob/living/simple_animal/friendly/pug.dm
  code/modules/mob/living/simple_animal/friendly/robot.dm
  code/modules/mob/living/simple_animal/friendly/shiba.dm
  code/modules/mob/living/simple_animal/friendly/slime.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/living/simple_animal/friendly/tomato.dm
  code/modules/mob/living/simple_animal/friendly/walle.dm
  code/modules/mob/living/simple_animal/head.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/bots.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  code/modules/mob/living/simple_animal/hostile/cyber_horror.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/living/simple_animal/hulk.dm
  code/modules/mob/living/simple_animal/hulk_powers.dm
  code/modules/mob/living/simple_animal/kobold.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/special/scp.dm
  code/modules/mob/living/simple_animal/vox.dm
  code/modules/mob/living/simple_animal/worm.dm
Labels: Translation/Localization

#11506 Удаляем синди джукбокс
  code/game/area/custom_areas.dm
  maps/centcom/centcom.dmm
  sound/ambience/loop_nuke_ops.ogg
Labels: Map Edit, Revert / Removal, Sound

#11557 реквизиты счетов отделов
  code/modules/paperwork/filingcabinet.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/stamps.dm
  maps/boxstation/boxstation.dmm
Labels: Feature, Map Edit, Tweak

#11556 Delta Station Map Edit. TauCeti remap Escape Hallway
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  maps/delta/delta.dmm
Labels: Map Edit

#11561 Smartfridge Resprite
  code/game/machinery/kitchen/smartfridge.dm
  icons/obj/vending.dmi
Labels: Sprites

#11543 User pincode input
  code/__DEFINES/accounts.dm
  code/game/machinery/vending.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/watercloset.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/cardpay.dm
  taucetistation.dme
Labels: Fix

#11541 добавляет новый эмоут на харчок
  code/datums/emotes/human/audible.dm
  sound/voice/spit_1.ogg
  sound/voice/spit_2.ogg
Labels: Sound

#11542 Fix mounted weapons
  code/modules/projectiles/firing.dm
Labels: Fix

#11544 Adaptation for animals
  code/__DEFINES/dcs/signals.dm
  code/game/gamemodes/modes_gameplays/blob/powers.dm
  code/modules/events/cellular_biomass/biome_nanite.dm
  code/modules/jungle/jungle_animals.dm
  code/modules/mining/equipment_locker.dm
  code/modules/mining/monsters.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/bots.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/cyber_horror.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/maintenance.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/replicators/replicator_ai_combat.dm
Labels: Feature, Admin

#11558 Простые субсидии. База.
  code/controllers/subsystem/economy.dm
Labels: Tweak

#11567 No access for paramedics to cargo
  code/game/jobs/job/medical.dm
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Revert / Removal

#11568 Cargo Delivery without HoP
  code/game/jobs/access.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/machinery/deployable.dm
  code/game/machinery/navbeacon.dm
  code/modules/cargo/console.dm
  config/example/access levels.txt
Labels: Revert / Removal, Config Update

#11525 Ксеноблюда в рецепты повару.
  code/defines/obj/hydro.dm
  code/game/machinery/vending/hydroponics.dm
  code/modules/food/recipes_grill.dm
  code/modules/food/recipes_microwave.dm
  code/modules/food/recipes_oven.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  icons/obj/food.dmi
  icons/obj/hydroponics/growing_fruits.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Sprites

#11483 Абдукторы удалены
  code/datums/spawners_menu/spawners.dm
  code/game/gamemodes/factions/abductors.dm
  code/game/gamemodes/modes_declares/abductors.dm
  code/game/gamemodes/modes_gameplays/abduction/abduction_gear.dm
  code/game/gamemodes/modes_gameplays/abduction/gland.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/console.dm
  code/game/gamemodes/modes_gameplays/abduction/machinery/experiment.dm
  code/game/gamemodes/objectives/abductors/abductor_objectives.dm
  code/game/gamemodes/roles/abductor.dm
  code/game/machinery/camera/abductors_console.dm
  code/modules/events/_event_container.dm
  code/modules/events/abduction.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/say.dm
  maps/centcom/centcom.dmm
  taucetistation.dme
Labels: Revert / Removal, Test Merge Candidate

#11532 Uplink discounts
  code/datums/components/gamemodes/syndicate.dm
  code/datums/uplinks_items.dm
  code/game/gamemodes/factions/syndicate.dm
  code/game/objects/items/devices/uplinks.dm
Labels: Feature, Test Merge Candidate

#11581 Замена рандом/саенса на рандом/саенс/саенс_саппли_сэйф
  maps/falcon/falcon.dmm
  maps/stroechka/stroechka.dmm
Labels: Fix, Map Edit

#11582 Замена рандом/саенса на рандом/саенс/саенс_саппли_сэйф 2
  maps/prometheus/prometheus.dmm
Labels: Map Edit

#11548 Zombie numbers
  code/modules/mob/living/carbon/species.dm
Labels: Balance

#11560 Crew help in blob mode
  code/__DEFINES/gamemodes.dm
  code/datums/announcements/gamemode.dm
  code/game/gamemodes/factions/blob.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/core.dm
  code/modules/cargo/packs.dm
Labels: Balance

#11515 Changeling Implant Managment
  code/__DEFINES/traits.dm
  code/datums/atom_huds/atom_hud_data.dm
  code/game/gamemodes/modes_gameplays/changeling/implant_menu.dm
  code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/mindshield.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/modules/mob/mob_helpers.dm
  code/modules/skills/skill_changer/cartridges.dm
  code/modules/skills/skill_changer/skills_console.dm
  code/modules/surgery/implant.dm
  taucetistation.dme
Labels: Feature

#11591 Delta Station Map Edit. Шаттл карго приземляется на станции
  code/controllers/subsystem/shuttles.dm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/stroechka/stroechka.dmm
Labels: Map Edit

#11588 Полная готовность к 515
  code/__DEFINES/callbacks.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/game.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/sorts/InsertSort.dm
  code/__HELPERS/sorts/MergeSort.dm
  code/__HELPERS/sorts/TimSort.dm
  code/__HELPERS/sorts/__main.dm
  code/controllers/master.dm
  code/controllers/subsystem/quirks.dm
  code/controllers/subsystem/timer.dm
  code/datums/components/mood.dm
  code/datums/datum.dm
  code/datums/mind.dm
  code/datums/runechat.dm
  code/defines/obj/datacore.dm
  code/defines/procs/AStar.dm
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/devices/scanners/contraband_finder.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/noticeboard.dm
  code/game/world.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/getlogs.dm
  code/modules/client/client_procs.dm
  code/modules/mafia/controller.dm
  code/modules/mob/living/carbon/metroid/powers.dm
Labels: Preferences Update

#11595 Delta Station Map Edit. Telescience Added
  maps/delta/delta.dmm
Labels: Map Edit

#11396 Shadowling and lights
  code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
  code/game/machinery/airlock_control.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/glowshroom.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/power/lighting/lamps.dm
  code/modules/reagents/reagent_containers/food/glowsticks.dm
  code/modules/scrap/scrap_light.dm
  code/modules/unarmed_combat/living_procs_defines.dm
Labels: Fix

#11569 No Hos in Cargo Office
  code/game/jobs/job/security.dm
Labels: Revert / Removal

#11577 Необходимый навык инженерного дела для использования SMES'а и консолей соляр понижен до нуля
  code/modules/power/smes.dm
  code/modules/power/solar.dm
Labels: Revert / Removal

#11603 Code quality rewrite
  code/modules/mob/living/living.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Code Improvements

#11601 Убраны бесполезные рольки в антаг панели игроков
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/misc.dm
  code/modules/client/preferences_savefile.dm
Labels: Preferences Update

#11592 Ящики охраны можно разрушать оружием 15+ урона
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Balance

#11503 Random storage refactoring
  code/__HELPERS/logging.dm
  code/__HELPERS/unsorted.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/mining/coins.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix, Test Merge Candidate

#11572 Удаляет Комбо Худ
  code/datums/progressbar.dm
  code/modules/clothing/gloves/boxing.dm
  code/modules/unarmed_combat/combo_handler.dm
  code/modules/unarmed_combat/living_procs_defines.dm
Labels: Balance, Sound

#11606 Delta Station Map Edit. Supermatter Destroying. Singularity and Tesla returns.
  code/game/area/delta_areas.dm
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  taucetistation.dme
Labels: Map Edit

#11602 tgui 515
  tgui/public/tgui.html
Labels: UI
