Repository TauCetiStation/TauCetiClassic, pull requests merged in 2023-01, with the labels that each got.

#10467 ГрузТорг новые фичи.
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/cargo/console.dm
  code/modules/cargo/shop.dm
  code/modules/economy/Accounts.dm
Labels: Feature, Map Edit, Sprites, Tweak

#10576 Gun dealer`s implants
  code/datums/uplinks_items.dm
Labels: Feature

#10432 ноу слип ботинки больше не защищают от порывов ветра
  code/__DEFINES/flags.dm
  code/modules/atmospheric/ZAS/Airflow.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Balance

#10537 Quirk friendly
  code/__DEFINES/quirks.dm
  code/__DEFINES/traits.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/traits/positive.dm
  code/game/objects/effects/temp_visual/miscellaneous.dm
  code/modules/mob/living/carbon/carbon.dm
  icons/mob/animal.dmi
Labels: Feature, Sprites, Stalled PR

#10542 DS equip small changes
  code/datums/outfits/misc/shitspawn.dm
  code/modules/clothing/suits/armor.dm
Labels: Stalled PR

#10569 Mecha Repair fix
  code/game/mecha/mecha.dm
Labels: Fix

#10552 Допил бафа нанокальция
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Labels: Balance

#10513 Turett upd
  code/datums/traits/negative.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/mob_helpers.dm
Labels: Tweak

#10573 Ghost teleportation interactions
  code/_onclick/observer.dm
  code/game/machinery/teleporter.dm
  code/game/objects/structures/ladders.dm
Labels: Tweak

#10594 Blob hud
  code/_onclick/hud/blob_overmind.dm
  code/_onclick/hud/other_mobs.dm
  code/_onclick/hud/ui_screens/other_mobs.dm
  code/game/gamemodes/modes_gameplays/blob/powers.dm
  icons/hud/blob.dmi
  taucetistation.dme
Labels: Feature, Sprites

#10598 medical telepor message
  code/game/objects/items/devices/radio/beacon.dm
Labels: Tweak

#10572 Фича для яиц ксеноморфов
  code/modules/mob/living/carbon/xenomorph/effects/aliens.dm
Labels: Tweak

#10328 Удаляет функцию поиска хайриск айтемов у поинтера капитана
  code/game/gamemodes/modes_gameplays/nuclear/pinpointer.dm
Labels: Map Edit, Contentious, Tweak

#10571 мыши теперь не могут показывать пальцем и спамить экзамином
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/parasite/meme.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hulk.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: Tweak

#10567 Ремап Гейта. Ребаланс нюки
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#10590 New coins icons, for inventory and for world
  code/__DEFINES/flags.dm
  code/game/atoms.dm
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/modules/mining/coins.dm
  code/modules/recycling/sortingmachinery.dm
  icons/obj/economy.dmi
Labels: Sprites

#10592 Shapeshift
  code/datums/spells/shapeshift.dm
  code/game/gamemodes/modes_gameplays/abduction/gland.dm
  code/game/gamemodes/modes_gameplays/wizard/spellbook.dm
  icons/hud/actions.dmi
  sound/effects/reee.ogg
  taucetistation.dme
Labels: Feature, Sprites, Sound

#10556 Nearsight no more in life()
  code/__DEFINES/traits.dm
  code/datums/traits/negative.dm
  code/game/dna/genes/disabilities.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/stings.dm
  code/game/machinery/adv_med.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/status_procs.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  code/modules/religion/rites/instant/instant.dm
  code/modules/surgery/eye.dm
Labels: Test Merge Candidate

#10607 сингулярити и тесла теперь убиваются одним выстрелом из ракетницы се
  code/modules/projectiles/projectile/special.dm
Labels: Tweak

#10591 cell and weapon rech upd
  code/game/machinery/cell_charger.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/recharger.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  icons/obj/power.dmi
Labels: Fix, Sprites, Tweak

#10588 Fixes #9816
  code/game/turfs/turf.dm
  code/modules/recycling/sortingmachinery.dm
Labels: Test Merge Candidate

#10643 Velocityarmor resprite+inhands
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#10610 сват шлем респрайт
  code/modules/clothing/head/helmet.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites
