Repository TauCetiStation/TauCetiClassic, pull requests merged in 2023-02, with the labels that each got.

#10708 Basketball Resprite (Hoop)
  code/modules/holodeck/HolodeckObjects.dm
  icons/obj/basketball.dmi
  icons/obj/basketball_hoop.dmi
Labels: Sprites

#10697 ПР который не могли сделать 6 лет. Это невероятно!
  icons/mob/inhands/items_righthand.dmi
Labels: Sprites

#10703 Voxes jump
  code/modules/mob/living/carbon/human/human.dm
Labels: Tweak

#10685 Анимация разливания реагентов на моба
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  icons/effects/effects.dmi
Labels: Sprites

#10663 Queen's kickstart
  code/datums/status_effects/debuffs.dm
  code/game/gamemodes/factions/infestation.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
  icons/hud/screen_alert.dmi
Labels: Balance

#10698 Респрайт тыквы
  icons/obj/clothing/hats.dmi
  icons/obj/hydroponics/harvest.dmi
Labels: Sprites

#10707 Cone Resprite
  icons/obj/janitor.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#10710 Beakers Resprite
  code/modules/reagents/reagent_containers/glass.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#10696 Не ставьте консоль исследований на дереликте без смены ей ID
  maps/RandomZLevels/zresearchlabs.dmm
  maps/templates/space_structures/abandoned_lab.dmm
Labels: Map Edit

#10693 Uncuff on convert
  code/modules/religion/rites/instant/instant.dm
Labels: Tweak

#10689 Ускорение Tajaran
  code/__DEFINES/traits.dm
  code/game/objects/structures.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/recycling/disposal.dm
Labels: Feature

#10718 Wood In-Hands
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Sprites

#10665 add ghost landmark to stroechka
  maps/stroechka/stroechka.dmm
Labels: Map Edit

#10724 Revert "add ghost landmark to stroechka (#10665)"
  maps/stroechka/stroechka.dmm
Labels: Map Edit

#10723 Скилы на столы
  code/game/objects/items/weapons/table_rack_parts.dm
Labels: Tweak

#10719 Bolas In-Hands
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Sprites

#10732 Waterbackpack and mister in-hands
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Sprites

#10738 Megaphone in-hands
  code/game/objects/items/devices/megaphone.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Sprites

#10582 synaptizine buff
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Labels: Balance

#10606 Добавляет комбоприёмы антагонистам
  code/__DEFINES/combat.dm
  code/__DEFINES/combos.dm
  code/datums/qualities/positiveish.dm
  code/game/gamemodes/role.dm
  code/game/gamemodes/roles/changeling.dm
  code/game/gamemodes/roles/cops.dm
  code/game/gamemodes/roles/cultist.dm
  code/game/gamemodes/roles/revolution.dm
  code/game/gamemodes/roles/syndicate.dm
  code/game/gamemodes/roles/traitor.dm
  code/game/gamemodes/roles/traitorchan.dm
  code/modules/unarmed_combat/combos/disarming.dm
  code/modules/unarmed_combat/combos/harmful.dm
  code/modules/unarmed_combat/movesets/type_movesets.dm
  icons/hud/unarmed_combat_combos.dmi
Labels: Feature, Sprites

#10687 Throwing message
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature

#10704 Телескопичка наносит голоурон на харме
  code/game/objects/items/weapons/swords_axes_etc.dm
Labels: Tweak

#10496 Supporters part 2: fluff ghosts
  code/modules/fluff/customitems.dm
  code/modules/fluff/fluffmenu.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Test Merge Candidate

#10752 Занерфлена страта блоба через атмос
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#10566 Abductors' vest and alien injector
  code/game/gamemodes/modes_gameplays/abduction/abduction_gear.dm
  code/modules/mining/equipment_locker.dm
  icons/obj/abductor.dmi
Labels: Fix, Balance, Sprites

#10730 Мейк портативный флешер грейт егеин
  code/game/machinery/flasher.dm
Labels: Tweak

#10768 Мегаремап офиса хопа
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#10700 Telebaton Resprite
  icons/obj/weapons.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#10712 Kitchen Repsrite!
  code/game/objects/items/weapons/kitchen.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/kitchen.dmi
  maps/boxstation/boxstation.dmm
Labels: Sprites, Awaiting Review [Sprite Dep]

#10692 Spacecash burning! Буржуи ликуют!
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/economy/cash.dm
  icons/obj/economy.dmi
Labels: Feature, Sprites

#10706 Рандом станы подскальзывания. Удаление
  code/modules/europa/fluids/fluid_mob.dm
Labels: Revert / Removal

#10769 Мегаремап офиса се
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#10761 Разделение зон общака
  code/datums/weather/weather_types.dm
  code/game/area/station_areas.dm
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#10749 Forge objectives for cult
  code/game/gamemodes/factions/cult.dm
  code/game/gamemodes/objectives/cult/cult_objectives.dm
Labels: Balance

#10764 Исключение карцера из зон поражений радиационным штормом
  code/datums/weather/weather_types.dm
  code/game/area/station_areas.dm
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#10666 Notification of a successful sacrifice
  code/modules/religion/rites/instant/instant.dm
Labels: Tweak

#10804 Изменение количества зарядов в наборах пополнения вендоматов.
  code/game/objects/items/weapons/vending_items.dm
Labels: Tweak

#10762 делает наркотики чуть более полезными, усложняет их рецепт и добавляет дженкем
  code/_globalvars/lists/maintenance_loot.dm
  code/_globalvars/lists/mob.dm
  code/datums/mood_events/generic_positive_events.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/mob_movement.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
Labels: Feature, Tweak

#10802 Mask in-hands review + update
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#10728 Fix #10727
  code/datums/helper_datums/construction_datum.dm
  code/game/mecha/mecha_construction_paths.dm
Labels: Fix

#10814 Blood drain fix
  code/modules/religion/rites/instant/instant.dm
Labels: Fix

#10664 Garanted anti-hugger protection
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
Labels: Balance

#10705 Воуты не крадут фокус
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  code/controllers/subsystem/voting/poll.dm
  code/controllers/subsystem/voting/poll_types.dm
  tgui/packages/tgui/interfaces/Vote.tsx
  tgui/public/tgui.bundle.js
Labels: Fix, Feature, UI

#10760 Тыквяк Апдейт
  code/datums/mood_events/beauty_events.dm
  code/defines/obj/hydro.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/items/weapons/hydroponics.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/reagents/reagent_types/Chemistry-Core.dm
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/drinks.dmi
  icons/obj/hydroponics/growing_fruits.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  sound/musical_instruments/maraca/maraca.ogg
Labels: Feature, Sprites, Sound

#10789 Revert "Для открытия склада в инженерном отсеке теперь нужен доступ"
  maps/boxstation/boxstation.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit

#10770 делает дробовики и гранатомёты двуручным оружием
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/plasma/plasma.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/launcher.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/rocket.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Balance

#10782 Abobination Heat damage
  code/modules/mob/living/carbon/species.dm
Labels: Balance

#10803 Изменение цены на наборы пополнения вендоматов в Карго
  code/modules/cargo/packs.dm
Labels: Tweak

#10715 Spawn larva in vents
  code/game/gamemodes/factions/blob.dm
  code/game/gamemodes/factions/infestation.dm
Labels: Feature

#10436 Снижение количества вендоматов, добавление возможности покупки сигарет, раменов и напитков в консоли карго в обычном виде.
  code/game/machinery/autolathe.dm
  code/game/objects/random/random_foods.dm
  code/game/objects/random/random_misc.dm
  code/modules/cargo/packs.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Sprites, Tweak, Test Merge Candidate

#10798 Minor fix AIsat
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#10813 Camera visuals
  code/datums/wires/camera.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/presets.dm
  icons/obj/monitors.dmi
Labels: Feature, Sprites

#10816 Фикс бага с заказом одного и того же предмета в грузторге.
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/cargo/shop.dm
Labels: Fix

#10662 Вендоматы в юрисдикции карго. Продукты падают набором пополнения.
  code/controllers/subsystem/economy.dm
  code/controllers/subsystem/shuttles.dm
  code/game/machinery/vending.dm
Labels: Feature, Map Edit, Sprites, Tweak, UI

#10805 Изменение процента загрузки вендоматов на старте раунда.
  code/game/machinery/vending.dm
Labels: Tweak

#9104 Key Memories
  code/__DEFINES/memories.dm
  code/controllers/subsystem/jobs.dm
  code/datums/mind.dm
  code/defines/obj/datacore.dm
  code/game/gamemodes/factions/revolution.dm
  code/game/gamemodes/scoreboard.dm
  code/game/jobs/jobs.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/economy_misc.dm
  code/modules/memories/memories.dm
  taucetistation.dme
Labels: Feature, Test Merge Candidate

#10568 большие вещи в руках снова замедляют
  code/__DEFINES/flags.dm
  code/game/objects/items/weapons/makeshift.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/living.dm
Labels: Feature, Merge Conflict, Test Merge Candidate

#10653 Blueshield RETURNS!!!!!
  code/datums/mood_events/needs_events.dm
  code/datums/outfits/jobs/security.dm
  code/datums/outfits/outfit.dm
  code/game/area/station_areas.dm
  code/game/gamemodes/factions/revolution.dm
  code/game/gamemodes/modes_gameplays/nuclear/pinpointer.dm
  code/game/gamemodes/roles/changeling.dm
  code/game/gamemodes/roles/cops.dm
  code/game/gamemodes/roles/cultist.dm
  code/game/gamemodes/roles/families.dm
  code/game/gamemodes/roles/revolution.dm
  code/game/gamemodes/roles/shadowling.dm
  code/game/gamemodes/roles/traitor.dm
  code/game/jobs/access.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/security.dm
  code/game/jobs/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/head/beret.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/mob_helpers.dm
  code/modules/skills/skillsets/security.dm
  icons/hud/hud.dmi
  icons/mob/ears.dmi
  icons/mob/head.dmi
  icons/mob/landmarks.dmi
  icons/mob/suit.dmi
  icons/mob/suit_fat.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/card.dmi
  icons/obj/closet.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/pda.dmi
  icons/obj/radio.dmi
  maps/boxstation/boxstation.dmm
  maps/falcon/job_changes.dm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/stroechka/job_changes.dm
Labels: Feature, Map Edit, Sprites, Test Merge Candidate, Preferences Update

#10564 Стена щитов. Нереальный баф командной работы
  code/game/gamemodes/modes_gameplays/changeling/powers/mutations.dm
  code/game/gamemodes/modes_gameplays/cult/cult_items.dm
  code/game/objects/items/weapons/shields.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
Labels: Feature

#10839 ламп очка
  maps/centcom/centcom.dmm
Labels: Map Edit

#10837 Фиксы багов, связанных с последним изменением вендоматов, которые я не заметил когда делал ПРы.
  code/game/machinery/vending.dm
  code/game/machinery/vending/clothing.dm
  code/game/machinery/vending/eat.dm
  code/game/machinery/vending/engineering.dm
  code/game/machinery/vending/hydroponics.dm
  code/game/machinery/vending/medical.dm
  code/game/machinery/vending/modkit.dm
  code/game/machinery/vending/other.dm
Labels: Fix

#10699 небольшой рефактор пушек
  code/game/gamemodes/modes_gameplays/families/outfit.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/portable_turret.dm
  code/game/objects/random/random_guns.dm
  code/game/objects/structures/crates_lockers/closets/fitness.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/awaymissions/planetarium_spawner.dm
  code/modules/cargo/packs.dm
  code/modules/cargo/prices.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/chameleon.dm
  code/modules/events/roundstart_events/area/replace/deathly_sec.dm
  code/modules/jungle/jungle_temple.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/plasma/plasma.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/launcher.dm
  code/modules/projectiles/guns/projectile/old_pirate_guns.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/rocket.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile/silencer.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/religion/aspect.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  maps/centcom/centcom.dmm
  maps/falcon/falcon.dmm
  maps/templates/space_structures/cult_ship.dmm
  maps/templates/space_structures/secrete_lab.dmm
  maps/testmap/testmap.dmm
Labels: Map Edit, Sprites

#10840 нерф сахара
  code/modules/reagents/reagent_types/Chemistry-Core.dm
Labels: Balance

#10862 возвращает хаотический пончик
  code/_globalvars/lists/misc.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
  icons/obj/storage.dmi
Labels: Feature, Sprites

#10863 pizza box parcel
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
  icons/obj/storage.dmi
Labels: Sprites
