Repository TauCetiStation/TauCetiClassic, pull requests merged in 2023-08, with the labels that each got.

#11792 Explosions flame wave imitation
  code/controllers/subsystem/explosions.dm
  code/game/atoms.dm
  code/game/machinery/alarm.dm
  code/game/objects/items/latexballoon.dm
  code/game/turfs/simulated/floor.dm
  code/modules/atmospheric/ZAS/Fire.dm
  code/modules/europa/fluids/fluid_update.dm
  code/modules/events/cellular_biomass/biomass.dm
  code/modules/events/cellular_biomass/spacevines.dm
  code/modules/holidays/new_year/snow.dm
  code/modules/mob/living/living_defense.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/scrap/scrap_light.dm
  code/modules/statistic/stat_dto.dm
  code/modules/statistic/statistics_helpers.dm
Labels: Test Merge Candidate

#11657 твики корзины бумаги
  code/modules/paperwork/carbonpaper.dm
  code/modules/paperwork/paperbin.dm
  icons/obj/bureaucracy.dmi
Labels: Sprites, Tweak

#11739 Evil Shades. Objectives
  code/__DEFINES/role_preferences.dm
  code/datums/spawners_menu/spawners.dm
  code/game/gamemodes/roles/evil_shade.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/projectiles/projectile/magic.dm
  taucetistation.dme
Labels: Feature

#11763 Починка багов крыс и ящерок годовой давности
  code/datums/components/gnawing.dm
  code/modules/power/cable.dm
Labels: Fix

#11717 [Fix] Дрель и клешни работают с ускорителем частиц
  code/__HELPERS/unsorted.dm
  code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
Labels: Fix

#11772 Чиним плазму
  code/modules/projectiles/guns/plasma/plasma.dm
Labels: Fix

#11789 добавляет в лодаут охранный худ
  code/modules/client/character_menu/loadout/loadout_glasses.dm
Labels: Feature

#11801 Добавляет исправленную форму почтальона
  icons/mob/uniform.dmi
Labels: Fix, Sprites

#11806 Респрайт знаков и карты станции
  icons/obj/decals.dmi
Labels: Sprites

#11809 Last bumped
  code/game/atoms_movable.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/objects/structures/inflatable.dm
Labels: Tweak

#11815 Новый заказ в карго
  code/modules/cargo/packs.dm
Labels: Feature

#11818 Все yellow/fyellow теперь insulated/budget_insulated
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/outfits/misc/survivalists.dm
  code/datums/qualities/positiveish.dm
  code/game/gamemodes/modes_gameplays/heist/vox_equip.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/vending/engineering.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/random/random_cloth.dm
  code/game/objects/random/random_tools.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/awaymissions/corpse.dm
  code/modules/cargo/packs.dm
  code/modules/cargo/prices.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/events/roundstart_events/area/cargo_storage.dm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/challenge.dmm
  maps/RandomZLevels/wildwest.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/gamma/gamma_revamp.dmm
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
  maps/stroechka/stroechka.dmm
  maps/templates/space_structures/agrosphere.dmm
  maps/templates/space_structures/old_station.dmm
  maps/templates/space_structures/teleporter.dmm
Labels: Map Edit

#11802 Добавление инструкции и списка песен к джукбоксу + джук на Дельту.
  code/game/objects/items/weapons/manuals.dm
  icons/obj/library.dmi
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit, Sprites

#11529 Добавляет предателям новую цель
  code/datums/components/gamemodes/syndicate.dm
  code/datums/uplinks_items.dm
  code/game/gamemodes/objectives/objectives.dm
  code/game/gamemodes/objectives/sabotage_research.dm
  code/game/gamemodes/objectives/target/dehead.dm
  code/game/gamemodes/roles/traitor.dm
  code/game/machinery/constructable_frame.dm
  code/modules/research/server.dm
  taucetistation.dme
Labels: Feature, Map Edit

#11823 фикс абуза клонирования через голову
  code/modules/mob/living/carbon/human/death.dm
Labels: Fix

#11790 скорость ходьбы теперь быстрая
  code/controllers/configuration.dm
  code/modules/mob/mob.dm
  config/example/game_options.txt
Labels: Tweak, Config Update

#11836 votable delta
  config/example/maps.txt
Labels: Map Edit, Config Update

#11810 Try_access
  code/game/jobs/access.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/windowdoor.dm
Labels: Feature

#11840 фиксил исправлял на гамме что видел
  maps/gamma/gamma.dmm
Labels: Map Edit

#11845 фиксы дельты
  maps/delta/delta.dmm
Labels: Map Edit

#11854 Мелкофиксы гаммы
  maps/gamma/gamma.dmm
Labels: Map Edit

#11859 Delta Station Map Edit. Закрываем первые ишуи
  code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
  maps/delta/delta.dmm
Labels: Map Edit

#11866 Карта гаммы на гамме
  code/game/objects/structures/signs/signs_maps.dm
  maps/gamma/gamma.dmm
Labels: Map Edit

#11867 апдейт прометея.
  maps/prometheus/prometheus.dmm
Labels: Map Edit

#11839 More explosions nerfs
  code/datums/spells/in_hand.dm
  code/datums/spells/wizard.dm
  code/game/machinery/syndicatebeacon.dm
  code/modules/mining/mine_items.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/research/server.dm
Labels: Test Merge Candidate

#11838 Turfs explosion act
  code/game/turfs/simulated/floor.dm
Labels: Tweak, Test Merge Candidate

#11782 респрайт реактивной телеброни + небольшие твики и её возвращение научному руководителю
  code/_globalvars/lists/maintenance_loot.dm
  code/game/gamemodes/objectives/steal.dm
  code/game/objects/structures/rd_armor_stand.dm
  code/modules/cargo/prices.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/stationobjs.dmi
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/prometheus/prometheus.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#11816 теперь куклы могут сдаваться
  code/datums/emotes/emote.dm
  code/datums/emotes/human/gesture.dm
  icons/mob/emote.dmi
Labels: Sprites, Tweak, Test Merge Candidate

#11858 Silicon PDA disable
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Fix

#11750 прогрессбар при использовании шприца на себе
  code/modules/mob/living/carbon/human/human.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Balance

#11868 Мелкофиксы гаммы + НаноЮай
  maps/gamma/gamma.dmm
  nano/images/nanomap_gamma_1.png
Labels: Map Edit

#11871 Мелкофиксы гаммы: Мусорка, Экраны, Атмосферное АПЦ и прочие мелочи
  maps/gamma/gamma.dmm
Labels: Map Edit

#11870 Delta Station Map Edit. НаноУИ карта и второй заход фиксов
  maps/delta.json
  maps/delta/delta.dmm
  nano/images/nanomap_delta_1.png
Labels: Map Edit

#11707 Changeling Transformation Sting. Rework
  code/game/dna/dna2.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/stings.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/transform.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Experimental

#11869 Увеличение количества выпадаемого из вендоматов лута.
  code/game/machinery/vending.dm
Labels: Tweak

#11875 Мелкофиксы гаммы №9: Ещё экраны, ещё диспоузал, камеры, лампы, мусорка в рнд, затемнение окон и прочие мелочи
  maps/gamma/gamma.dmm
Labels: Map Edit

#11863 теперь можно узнать свою особенность если вдруг пропустил
  code/modules/mob/dead/new_player/new_player.dm
Labels: Feature

#11834 skrell-specific uniform + species loadout
  code/modules/client/character_menu/loadout.dm
  code/modules/client/character_menu/loadout/loadout_accessories.dm
  code/modules/client/character_menu/loadout/loadout_clothing.dm
  code/modules/clothing/under/jobs/security.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#11795 Небольшое обновление способности абсорба генокрада
  code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
Labels: Feature

#11857 nukies pinpointer update
  code/game/gamemodes/modes_gameplays/nuclear/pinpointer.dm
Labels: Tweak

#11860 [MDB IGNORE] Turfs cleanup, part 1 of ?: Turf Decals
  code/__DEFINES/misc.dm
  code/game/objects/effects/decals/floor_stripes.dm
  code/game/objects/effects/decals/turf_decal.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated/floor.dm
  code/modules/locations/centcomm/velocity.dm
  code/modules/locations/shuttles/warning_stripes.dm
  icons/effects/turf_decals.dmi
  icons/locations/centcomm/floor.dmi
  icons/turf/floors.dmi
  icons/turf/turf_decals.dmi
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/arcticwaste.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/challenge.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/junkyard/junkyard.dmm
  maps/mafia/mafia_ball.dmm
  maps/mafia/mafia_syndie.dmm
  maps/palette/palette.dmm
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
  maps/stroechka/stroechka.dmm
  maps/templates/holodeck/meetinghall.dmm
  maps/templates/holodeck/theatre.dmm
  maps/templates/space_structures/abandoned_lab.dmm
  maps/templates/space_structures/agrosphere.dmm
  maps/templates/space_structures/broken_breacher.dmm
  maps/templates/space_structures/cloning_lab.dmm
  maps/templates/space_structures/derelict_station.dmm
  maps/templates/space_structures/export_outpost.dmm
  maps/templates/space_structures/iss.dmm
  maps/templates/space_structures/listening_post.dmm
  maps/templates/space_structures/old_station.dmm
  maps/templates/space_structures/robostation.dmm
  maps/templates/space_structures/robostation2.dmm
  maps/templates/space_structures/secrete_lab.dmm
  maps/templates/space_structures/ships_squad.dmm
  maps/templates/space_structures/space_villa.dmm
  maps/testmap/testmap.dmm
  taucetistation.dme
Labels: Sprites, Test Merge Candidate

#11830 ресурсы в автолате и протолате теперь нормально отображаются
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/research/rdconsole.dm
Labels: Fix

#11856 добавляет особку на подопытного
  code/__DEFINES/gamemodes.dm
  code/_globalvars/mapping.dm
  code/datums/atom_huds/atom_hud_data.dm
  code/datums/qualities/quirkieish.dm
  code/game/gamemodes/roles/prisoner.dm
  code/game/objects/effects/landmarks.dm
  icons/hud/hud.dmi
  icons/misc/logos.dmi
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  taucetistation.dme
Labels: Map Edit, Sprites

#11849 Map weight
  code/controllers/subsystem/voting/poll_types.dm
Labels: Experimental, Test Merge Candidate

#11883 [MDB IGNORE] Turfs cleanup, part 1 of ?: Turf Decals II
  code/game/objects/effects/decals/turf_decal.dm
  icons/turf/floors.dmi
  icons/turf/turf_decals.dmi
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/mafia/mafia_gothic.dmm
  maps/palette/palette.dmm
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
  maps/stroechka/stroechka.dmm
  maps/templates/space_structures/derelict_station.dmm
  maps/templates/space_structures/old_station.dmm
  maps/testmap/testmap.dmm
Labels: Map Edit, Sprites

#11885 Мелкофиксы Гаммы 11
  maps/gamma/gamma.dmm
Labels: Map Edit

#11889 [MDB IGNORE] Delta Station Map Edit. Decals and Feedback changes
  code/game/objects/effects/decals/turf_decal.dm
  maps/delta/delta.dmm
Labels: Map Edit

#11878 fix-borg-intent
  code/datums/keybinding/living.dm
Labels: Fix

#11888 [MDB IGNORE] Turfs cleanup, part 2 of ?: Carpets
  code/game/objects/effects/decals/turf_decal.dm
  code/game/objects/items/weapons/storage/bible/bible.dm
  code/game/turfs/floor/carpets.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/turf.dm
  code/modules/religion/atoms_religify.dm
  code/modules/religion/religion.dm
  code/modules/religion/religion_types/chaplain.dm
  code/modules/religion/religion_types/cult.dm
  icons/turf/carpets.dmi
  icons/turf/floors.dmi
  icons/turf/floors/carpets/carpet_classic_cyan.dmi
  icons/turf/floors/carpets/carpet_classic_green.dmi
  icons/turf/floors/carpets/carpet_classic_red.dmi
  icons/turf/floors/carpets/carpet_lattice_black.dmi
  icons/turf/floors/carpets/carpet_lattice_blue.dmi
  icons/turf/floors/carpets/carpet_lattice_lightblue.dmi
  icons/turf/floors/carpets/carpet_lattice_orange.dmi
  icons/turf/floors/carpets/carpet_lattice_purple.dmi
  icons/turf/floors/carpets/carpet_lattice_red.dmi
  icons/turf/turf_decals.dmi
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/challenge.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/templates/holodeck/courtroom.dmm
  maps/templates/holodeck/meetinghall.dmm
  maps/templates/holodeck/theatre.dmm
  maps/templates/space_structures/broken_breacher.dmm
  taucetistation.dme
Labels: Map Edit, Sprites, Test Merge Candidate

#11879 Skrell-M-J
  code/__DEFINES/is_helpers.dm
  code/defines/obj/weapon.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated/beach.dm
  code/modules/europa/fluids/fluid_controller.dm
  code/modules/europa/fluids/fluid_turf.dm
  code/modules/jungle/jungle_turfs.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/mob_movement.dm
  code/modules/scrap/scrap.dm
Labels: Tweak, Test Merge Candidate

#11894 Фикс турфоф с ERROR, фикс джука на Дельте.
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/wildwest.dmm
  maps/asteroid/asteroid.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/templates/holodeck/basketball.dmm
  maps/templates/holodeck/emptycourt.dmm
  maps/templates/holodeck/thunderdomecourt.dmm
Labels: Map Edit

#11862 Руссификация медибота
  code/game/machinery/bots/medbot.dm
Labels: Feature, Sound, Translation/Localization

#11895 jukebox default config
  code/controllers/configuration.dm
  code/game/machinery/machinery.dm
  code/modules/media/jukebox.dm
Labels: Config Update

#11893 [MDB IGNORE] Turfs cleanup, part 3 of 3: Damage overlays
  code/game/mecha/mech_bay.dm
  code/game/objects/effects/decals/turf_decal.dm
  code/game/objects/items/stacks/tiles/plasteel.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/walls.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/mining/mine_turfs.dm
  icons/turf/floors.dmi
  icons/turf/floors/damaged_overlays.dmi
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/mafia/mafia_ayylmao.dmm
  maps/mafia/mafia_ball.dmm
  maps/mafia/mafia_gothic.dmm
  maps/mafia/mafia_syndie.dmm
  maps/palette/palette.dmm
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
  maps/stroechka/stroechka.dmm
  maps/templates/space_structures/abandoned_lab.dmm
  maps/templates/space_structures/abandoned_ship.dmm
  maps/templates/space_structures/broken_breacher.dmm
  maps/templates/space_structures/derelict_station.dmm
  maps/templates/space_structures/derelict_teleporter.dmm
  maps/templates/space_structures/export_outpost.dmm
  maps/templates/space_structures/ghost_ship_1.dmm
  maps/templates/space_structures/iss.dmm
  maps/templates/space_structures/listening_post.dmm
  maps/templates/space_structures/old_station.dmm
  maps/templates/space_structures/resource_shuttle.dmm
  maps/templates/space_structures/robostation2.dmm
  maps/templates/space_structures/secrete_lab.dmm
  maps/templates/space_structures/ships_squad.dmm
  maps/templates/space_structures/space_villa.dmm
Labels: Sprites, Test Merge Candidate

#11900 [MDB IGNORE] Delta Station Map Edit. Playtest End
  config/example/maps.txt
  maps/delta/delta.dmm
Labels: Map Edit, Config Update

#11896 Supermatter Distortion
  code/modules/supermatter/supermatter.dm
  icons/effects/160x160.dmi
  icons/effects/224x224.dmi
  icons/effects/288x288.dmi
  icons/effects/32x32.dmi
  icons/effects/512x512.dmi
  icons/effects/96x96.dmi
Labels: Sprites, Test Merge Candidate

#11887 Респрайт одежды повара
  code/game/machinery/vending/other.dm
  code/game/objects/random/random_cloth.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/civilian.dm
  icons/mob/belt_mirror.dmi
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/templates/space_structures/ships_squad.dmm
Labels: Map Edit, Sprites

#11884 New Wall-Lockers from Space-IKEA
  icons/obj/walllocker.dmi
Labels: Sprites, Awaiting Review [Sprite Dep]

#11890 ГП борг в работе
  code/game/machinery/fax.dm
  code/modules/skills/skillsets/roles.dm
Labels: Fix

#11916 cooks uniform inhand sprites
  code/modules/clothing/under/jobs/civilian.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Fix, Sprites

#11920 Delta HoP office update
  maps/delta/delta.dmm
Labels: Map Edit

#11906 [MDB IGNORE] Delta Station Map Edit. Camera Review
  maps/delta/delta.dmm
Labels: Map Edit

#11919 Мелкофиксы гаммы 13
  maps/gamma/gamma.dmm
Labels: Map Edit

#11882 Расширение функционала газового анализатора
  code/__HELPERS/atmospherics.dm
Labels: Feature

#11897 больше случайных обр
  code/datums/outfits/misc/responders.dm
  code/datums/spawners_menu/spawners_responder.dm
  code/game/gamemodes/factions/responders.dm
  code/game/gamemodes/objectives/target/assassinate.dm
  code/game/gamemodes/roles/responders.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/response_team/teams.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/spacesuits/rig/ert.dm
  code/modules/mining/mine_items.dm
  code/modules/skills/skillsets/misc.dm
  icons/misc/logos.dmi
  icons/mob/belt_mirror.dmi
  icons/mob/head.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/tools.dmi
Labels: Feature, Sprites, Test Merge Candidate, Awaiting Review [Sprite Dep]

#11901 алиены теперь говорят в алиенский чатик через ;
  code/modules/mob/living/carbon/xenomorph/say.dm
Labels: Tweak

#11907 Борг апгрейд, возвращение старого порядка вставления платы в борга
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Balance

#11917 Блоб наносит больше урона халкам
  code/modules/mob/living/simple_animal/hulk.dm
Labels: Balance

#11936 Фикс старых декалек и добавление новых на цк слое.
  maps/centcom/centcom.dmm
Labels: Map Edit

#11938 Гамма фиксы
  maps/gamma/gamma.dmm
Labels: Map Edit

#11905 Контролклик по кухонной машинерии активирует её.
  code/game/machinery/kitchen/kitchen_machines.dm
Labels: Tweak

#11953 Фикс переводов акций по АТМ.
  code/modules/economy/ATM.dm
Labels: Fix

#11831 Вальтер Эмоут Панель
  code/__HELPERS/global_lists.dm
  code/_onclick/hud/radial.dm
  code/datums/emotes/emote.dm
  code/datums/keybinding/human.dm
  code/modules/client/character_menu/emote_panel_editor.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/living/carbon/human/emote.dm
  icons/misc/emotes.dmi
  taucetistation.dme
  tgui/packages/tgui/interfaces/EmotePanelEditor.js
  tgui/public/tgui.bundle.js
Labels: Feature, Sprites, Test Merge Candidate

#11942 Jul'Mah Tul'Krash теперь можно скрафтить.
  code/modules/food/recipes_microwave.dm
Labels: Fix

#11929 Небольшой перевод интерфейса
  interface/interface.dm
Labels: Translation/Localization

#11927 Шанс на полезную спам-рассылку.
  code/modules/events/pda_spam.dm
Labels: Tweak

#11925 Апдейт Гефеста
  code/game/machinery/igniter.dm
  maps/stroechka/stroechka.dmm
Labels: Map Edit

#11891 Часть 1.1 Раздаем боргам средства для улучшения РП
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature

#11972 [MDB IGNORE] Delta Station Map Edit. Medbay Tweaks + Maintenance Improves
  maps/delta/delta.dmm
Labels: Map Edit

#11551 Action buttons
  code/_onclick/hud/action.dm
  code/controllers/subsystem/action_buttons.dm
  code/datums/datum.dm
  code/game/gamemodes/modes_gameplays/abduction/abduction_gear.dm
  code/game/gamemodes/modes_gameplays/cult/eminence_actions.dm
  code/game/gamemodes/modes_gameplays/shadowling/shadowling_items.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/devices/scanners/gas.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/devices/whistle.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/defibrillator.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/scrolls.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/game/objects/items/weapons/tanks/watertank.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/clothing/gloves/power_gloves.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/mining/scanners.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/syndi/drone/rc.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/reagents/reagent_containers/food/glowsticks.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/research/xenoarchaeology/finds/finds_pipboy.dm
  code/modules/research/xenoarchaeology/tools/tools_wave_scanner.dm
  code/modules/scrap/scrap_light.dm
  code/modules/surgery/implant.dm
  taucetistation.dme
Labels: Refactor, Test Merge Candidate

#11877 Автор и название тест мержей
  .gitignore
  code/__DEFINES/cache.dm
  code/__DEFINES/misc.dm
  code/_globalvars/configuration.dm
  code/controllers/configuration.dm
  code/game/verbs/ooc.dm
  code/game/world.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/persistent_cache/persistent_cache.dm
  code/modules/statistic/statistics.dm
  config/example/config.txt
  interface/interface.dm
  scripts/fetch_test_merges.py
Labels: Feature, Test Merge Candidate, Config Update

#11928 Тотал респрайт пола, стен и решетки.
  icons/obj/smooth_adapters/adapters.dmi
  icons/obj/smooth_structures/grille.dmi
  icons/obj/smooth_structures/windows/window_sill.dmi
  icons/obj/smoothlattice.dmi
  icons/turf/catwalks.dmi
  icons/turf/floors.dmi
  icons/turf/floors/damaged_overlays.dmi
  icons/turf/turf_decals.dmi
  icons/turf/walls/has_false_walls/reinforced_wall.dmi
  icons/turf/walls/has_false_walls/wall.dmi
Labels: Sprites, Test Merge Candidate

#11943 Агентство Блумный свет.
  code/__DEFINES/_planes_layers.dm
  code/__DEFINES/preferences.dm
  code/_onclick/hud/rendering/plane_master.dm
  code/_onclick/hud/rendering/plane_master_controller.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/lightswitch.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder2.dm
  code/modules/admin/verbs/BloomEdit.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/lighting/lighting_source.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/organs/organ_external.dm
  code/modules/power/lighting/lamps.dm
  code/modules/power/tesla/energy_ball.dm
  code/modules/projectiles/effects.dm
  icons/effects/exposures.dmi
  icons/obj/doors/DoorHazard.dmi
  icons/obj/doors/airlocks/centcom/overlays.dmi
  icons/obj/doors/airlocks/external/overlays.dmi
  icons/obj/doors/airlocks/hatch/overlays.dmi
  icons/obj/doors/airlocks/highsec/overlays.dmi
  icons/obj/doors/airlocks/multi_tile/overlays.dmi
  icons/obj/doors/airlocks/shuttle/overlays.dmi
  icons/obj/doors/airlocks/station/overlays.dmi
  icons/obj/doors/airlocks/station2/overlays.dmi
  icons/obj/doors/airlocks/vault/overlays.dmi
  icons/obj/doors/doorint.dmi
  icons/obj/lamps.dmi
  icons/obj/lighting.dmi
  taucetistation.dme
  tgui/packages/tgui/interfaces/BloomEdit.js
  tgui/public/tgui.bundle.js
Labels: Feature, Sprites, Test Merge Candidate

#11956 Departaments lighting
  code/__HELPERS/hex_colors.dm
  code/controllers/subsystem/smartlight.dm
  code/modules/lighting/lamps/light_modes.dm
  code/modules/power/apc.dm
  code/modules/smartlight/smartlight_presets.dm
Labels: Test Merge Candidate

#11946 Добавление спрайтов для пустых кружек Dutch Hot Coco и Robust Coffee
  code/modules/reagents/reagent_containers/food/drinks.dm
  icons/obj/drinks.dmi
Labels: Sprites

#11954 Фикс дюпа деняк darkrp банкомат
  code/modules/economy/ATM.dm
  code/modules/economy/cash.dm
Labels: Fix

#11969 Access related fixes
  code/game/jobs/access.dm
  code/game/machinery/doors/door.dm
Labels: Fix

#11979 BoxStation: быстрофиксы под новые лампы.
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#11978 Обновление маперской палеты, добавление новых полов
  icons/turf/floors.dmi
  icons/turf/turf_decals.dmi
  maps/palette/palette.dmm
Labels: Map Edit, Sprites

#11980 Космо-бомжи больше не голые
  code/modules/scrap/scrap_people.dm
Labels: Fix

#11983 Исправлено неправильное отображение УЧ при 2
  icons/obj/machines/particle_accelerator2.dmi
Labels: Sprites

#11989 Фиксы тотал респрайта после теста.
  icons/obj/smooth_adapters/adapters.dmi
  icons/obj/smooth_structures/windows/window_sill.dmi
  icons/turf/floors.dmi
  icons/turf/walls/has_false_walls/reinforced_wall.dmi
  icons/turf/walls/has_false_walls/wall.dmi
Labels: Sprites

#11988 [MDB IGNORE] Delta Station Map Edit. Smartlights and Floor tweaks
  code/game/objects/effects/decals/turf_decal.dm
  maps/delta/delta.dmm
Labels: Map Edit

#11933 Перевод молитв
  code/modules/religion/rites/instant/death_alarm.dm
  code/modules/religion/rites/standing/consent.dm
  code/modules/religion/rites/standing/legacy.dm
  code/modules/religion/rites/standing/misc.dm
  code/modules/religion/rites/standing/spawn_item.dm
  code/modules/religion/rites/standing/swap.dm
Labels: Translation/Localization

#11932 Небольшой перевод церкви
  code/modules/religion/altar_types/altar_of_gods.dm
  code/modules/religion/altar_types/cult/altar_of_gods.dm
  code/modules/religion/religion_sects.dm
Labels: Translation/Localization

#11998 Фикс стражей улья
  code/modules/mob/living/carbon/xenomorph/humanoid/caste/sentinel.dm
Labels: Fix

#11999 Fixes camera console filters
  code/_onclick/hud/rendering/plane_master.dm
  code/_onclick/hud/rendering/render_plate.dm
  code/game/machinery/computer/camera.dm
Labels: Fix

#11997 Фикс мута дедчата. Мут стал работать на всех мертвых, не только на обсерверов
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/say.dm
Labels: Fix

#11949 soviet resprited
  code/datums/outfits/misc/responders.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#12002 Lighting prefs
  code/__DEFINES/preferences.dm
  code/_onclick/hud/rendering/plane_master.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
Labels: Tweak, Preferences Update
