Repository TauCetiStation/TauCetiClassic, pull requests merged in 2023-10, with the labels that each got.

#12204 Lib query fix
  code/modules/library/lib_machines.dm
Labels: Fix

#12206 Runtime in code/game/objects/items/decorations.dm:195 : Cannot execute null.add filter()
  code/game/objects/items/decorations.dm
Labels: Fix

#12205 Admin notes/bans now include player minutes at the moment of creation
  SQL/ss13.sql
  code/modules/admin/DB_ban/functions.dm
  code/modules/admin/admin.dm
  code/modules/admin/player_notes.dm
  code/modules/bridge/commands/bans.dm
  code/modules/bridge/commands/notes.dm
Labels: Admin, Database

#11939 Обновление UI здоровья ксеноморфов и небольшие перестановки.
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ui_screens/alien.dm
  icons/hud/screen1_xeno.dmi
  icons/hud/screen2_xeno.dmi
Labels: Sprites

#12185 More erts
  code/datums/outfits/misc/responders.dm
  code/datums/spawners_menu/spawners.dm
  code/datums/spawners_menu/spawners_responder.dm
  code/game/gamemodes/factions/responders.dm
  code/game/gamemodes/objectives/custom.dm
  code/game/gamemodes/roles/responders.dm
  code/game/jobs/access.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/response_team/teams.dm
  code/modules/admin/verbs/debug.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/launcher.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/hud/hud.dmi
  icons/mob/head.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/ammo/casings.dmi
  icons/obj/ammo/magazines.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/gun.dmi
  sound/weapons/guns/gunshot_m41.ogg
Labels: Feature, Sprites, Sound

#12174 Перевод Body Scanner(a)
  code/game/machinery/adv_med.dm
Labels: Translation/Localization

#11992 exosuit targeting
  code/game/machinery/portable_turret.dm
Labels: Fix

#12116 Уменьшение количества игроков необходимое для режимов
  code/game/gamemodes/factions/syndicate.dm
  code/game/gamemodes/modes_declares/blob.dm
  code/game/gamemodes/modes_declares/families.dm
  code/game/gamemodes/modes_declares/nuclear.dm
  code/game/gamemodes/modes_declares/shadowlings.dm
Labels: Tweak, Test Merge Candidate

#12186 ФПС по умолчанию поднят с 40 до 100
  code/__DEFINES/preferences.dm
Labels: Performance, Test Merge Candidate

#12225 Delta Station Map Edit. Новые декорации на карту
  code/game/objects/effects/decals/contraband.dm
  maps/delta/delta.dmm
Labels: Map Edit

#12182 нерф разгерм
  code/modules/mob/living/carbon/human/life.dm
Labels: Test Merge Candidate

#11994 Changeling New Ability. Swallow Victim Body.
  code/__DEFINES/traits.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/swallow.dm
  code/game/gamemodes/roles/changeling.dm
  code/modules/detectivework/detective_work.dm
  code/modules/mob/living/carbon/human/examine.dm
  taucetistation.dme
Labels: Feature, Test Merge Candidate

#12065 добавление падежей сумкам
  code/game/objects/items/weapons/storage/backpack.dm
Labels: Translation/Localization

#12202 Обновил консольку power
  code/game/machinery/computer/power.dm
Labels: Tweak

#12211 делает бинты и мази менее требовательными к скиллам
  code/game/objects/items/stacks/medical.dm
Labels: Balance

#12215 Imposters gamemode probabilities
  code/game/gamemodes/modes_declares/imposters.dm
Labels: Tweak

#12217 удаляет риг с астероида прометея
  maps/prometheus_asteroid/prometheus_asteroid.dmm
Labels: Map Edit

#12221 Chain of Command for Changelings
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/weapons/melee/misc.dm
Labels: Fix

#12229 Shuttle hallway window mapfix
  maps/gamma/gamma.dmm
Labels: Map Edit

#12234 New sprites for prosthetics
  code/game/objects/items/robot/robot_parts.dm
  icons/mob/human_races/robotic.dmi
  icons/obj/robot_parts.dmi
Labels: Sprites

#12238 Продолжение отлова Error-турфов. asteroid.dmm and centcom.dmm
  maps/asteroid/asteroid.dmm
  maps/centcom/centcom.dmm
Labels: Map Edit

#12250 Revert "New sprites for prosthetics"
  code/game/objects/items/robot/robot_parts.dm
  icons/mob/human_races/robotic.dmi
  icons/obj/robot_parts.dmi
Labels: Sprites

#11326 Комоды заимели диры, Комоды стали прозрачны для вытсрелов и на них можно залезть.
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/paperwork/filingcabinet.dm
  icons/obj/bureaucracy.dmi
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Sprites, Tweak

#11872 Stunbaton Rewrite
  code/__DEFINES/dcs/signals.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/mob_helpers.dm
Labels: Tweak, Test Merge Candidate

#12169 fix turret abuse
  code/game/machinery/portable_turret.dm
Labels: Fix

#12190 Вес голосов гостов, глав, антагов немного изменен
  code/controllers/subsystem/voting/poll.dm
Labels: Tweak, Test Merge Candidate

#12216 добавляет магбутсы в рнд
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit

#12227 Фикс камер (безглавых) СПУ
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/living.dm
  code/modules/organs/external/skeleton.dm
  code/modules/organs/organ_external.dm
  code/modules/surgery/limbs.dm
Labels: Fix

#12239 Toggle Ghost Icon verb without fluff
  code/modules/mob/dead/observer/observer.dm
Labels: Feature

#12262 Мелкобыстрофикся анастезических канистр в меде.
  code/modules/atmospheric/machinery/portable/canister.dm
Labels: Fix

#12261 hos shades colormatrix fix
  code/modules/clothing/glasses/glasses.dm
Labels: Fix

#12266 Новая бумага в анимации факса
  icons/obj/bureaucracy.dmi
Labels: Sprites

#12208 Исправляю описание квирков
  code/datums/traits/negative.dm
  code/datums/traits/neutral.dm
Labels: Translation/Localization, Awaiting Review [Trans Dep]

#12265 515.1618 компилятор больше не отбрасывает варнинг
  code/modules/mafia/roles.dm
Labels: Fix

#12274 Фикс отрыва головы
  code/modules/organs/organ_external.dm
Labels: Fix

#12231 Welcome to Omsk!
  code/game/machinery/vending/medical.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Feature

#12257 Цветные цифры урона в медсканере
  code/game/machinery/adv_med.dm
Labels: Tweak

#12259 удаляет нацистов
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
  maps/prometheus/prometheus.dmm
Labels: Sprites, Revert / Removal

#12260 electrified arm nerf
  code/game/objects/items/robot/robot_items.dm
Labels: Balance

#12241 Time and date fix
  code/modules/economy/economy_misc.dm
Labels: Fix, Map Edit

#12126 Часть 1.5 Открываем канистры боргам
  code/modules/atmospheric/machinery/portable/canister.dm
Labels: Balance

#12320 На боксе в допросной комнате существовал особый стол...
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#12318 быстрофикс фимейл униформы повара
  icons/mob/uniform.dmi
Labels: Fix, Sprites

#12298 Secure closets cleanup
  code/game/machinery/doors/brigdoors.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/crates_lockers/closets/secure/barber.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/syndicate.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/locations/centcomm/velocity.dm
  code/modules/mining/mine_items.dm
  code/modules/research/xenoarchaeology/misc.dm
  icons/locations/centcomm/closet.dmi
  icons/obj/closet.dmi
  icons/obj/guncabinet.dmi
Labels: Sprites

#12307 security smg resprite
  code/modules/projectiles/ammunition/magazines.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/ammo/magazines.dmi
  icons/obj/gun.dmi
  icons/obj/gun_40x32.dmi
Labels: Sprites

#12281 [Часть 1.2]Перевод патронов, пуль и т.п.
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/energy.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/special.dm
Labels: Translation/Localization

#11245 Жрём энергию от улучшений техники
  code/__DEFINES/machinery.dm
  code/game/dna/dna_modifier.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/barber.dm
  code/game/machinery/biogenerator.dm
  code/game/machinery/cell_charger.dm
  code/game/machinery/cloning.dm
  code/game/machinery/hologram.dm
  code/game/machinery/hydroponics.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/machinery/kitchen/kitchen_machines.dm
  code/game/machinery/kitchen/monkeyrecycler.dm
  code/game/machinery/kitchen/processor.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/machinery.dm
  code/game/machinery/recharger.dm
  code/game/machinery/rechargestation.dm
  code/game/machinery/recycler.dm
  code/game/machinery/seed_extractor.dm
  code/game/machinery/spaceheater.dm
  code/game/machinery/teleporter.dm
  code/game/mecha/mech_bay.dm
  code/game/mecha/mech_fabricator.dm
  code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
  code/modules/atmospheric/machinery/components/unary_devices/thermomachine.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/equipment_locker.dm
  code/modules/power/port_gen.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/smes.dm
  code/modules/power/tesla/coil.dm
  code/modules/power/turbine.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/research/circuitprinter.dm
  code/modules/research/destructive_analyzer.dm
  code/modules/research/protolathe.dm
  code/modules/research/server.dm
  code/modules/scrap/scrap_pileripper.dm
  code/modules/scrap/scrap_refinery.dm
  code/modules/telesci/telepad.dm
Labels: Tweak

#12283 Фикс ошибки в переводе
  code/game/objects/effects/decals/turf_decal.dm
Labels: Translation/Localization

#12330 музыка
  code/controllers/subsystem/ticker.dm
  sound/music/halloween/ghosts.ogg
  sound/music/halloween/halloween.ogg
  sound/music/halloween/skeletons.ogg
Labels: Tweak

#12335 Обновление затворок: астеройд и палетта
  maps/asteroid/asteroid.dmm
  maps/palette/palette.dmm
Labels: Map Edit

#10067 asteroid_update (part 2: "Ящик для руды") (splitting #9557)
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mining/satchel_ore_boxdm.dm
  sound/items/mining_satchel_unload.ogg
  sound/items/orebox_unload.ogg
Labels: Tweak, Sound

#11926 грузторг консоли в отделы
  code/game/machinery/computer/shop.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/cargo/shop.dm
  code/modules/economy/Accounts.dm
  icons/obj/computer.dmi
  maps/boxstation/boxstation.dmm
  nano/templates/shop.tmpl
  taucetistation.dme
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#12200 Imposters code refactor + features
  code/game/gamemodes/factions.dm
  code/game/gamemodes/factions/autotraitors.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/modes_declares/imposters.dm
  code/game/gamemodes/role.dm
  code/game/gamemodes/roles/traitor.dm
  code/game/objects/items/weapons/implants/mindshield.dm
Labels: Fix, Tweak, Code Improvements, Test Merge Candidate

#12209 Часть 1.6.2 Учимся держать пласталь + Покрасчик шлюзов
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Balance, Feature

#12253 Nuke RIg modules update
  code/datums/outfits/nuclear.dm
  code/datums/outfits/outfit.dm
  code/modules/clothing/spacesuits/rig/modules/ai.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Balance

#12299 Уменьшение размера картриджа рцд
  code/game/objects/items/weapons/RCD.dm
Labels: Tweak

#12302 Навыки космо-бомжам
  code/modules/scrap/scrap_people.dm
Labels: Tweak

#12337 Reverting revert of negative quality
  code/datums/qualities/negativeish.dm
Labels: Revert / Removal

#12339 OOC fix
  code/controllers/configuration.dm
  code/controllers/subsystem/ticker.dm
  code/game/verbs/ooc.dm
Labels: Fix, Tweak, Config Update

#12228 rounds aspects
  code/__DEFINES/round_aspects.dm
  code/__DEFINES/subsystem.dm
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/jobs.dm
  code/controllers/subsystem/round_aspects.dm
  code/datums/outfits/jobs/civilian.dm
  code/datums/outfits/jobs/command.dm
  code/datums/outfits/jobs/engineering.dm
  code/datums/outfits/jobs/medical.dm
  code/datums/outfits/jobs/science.dm
  code/datums/outfits/jobs/security.dm
  code/datums/round_aspects/round_aspects.dm
  code/game/machinery/telecomms/presets.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/cargo/packs.dm
  code/modules/events/_event_container.dm
  code/modules/events/roundstart_events/area/replace/del_tcomms.dm
  code/modules/events/roundstart_events/area/replace/station_rearmament.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/paperwork/paper.dm
  code/modules/research/designs.dm
  taucetistation.dme
Labels: Experimental, Test Merge Candidate

#12304 Микрофоны
  code/datums/components/wrench_to_table.dm
  code/game/objects/items/devices/microphone.dm
  code/modules/economy/cardpay.dm
  icons/obj/radio.dmi
  maps/boxstation/boxstation.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#12344 Spooky Scary skeletones resprite
  icons/mob/human_races/r_skeleton.dmi
  icons/mob/human_races/r_skeleton_lizard.dmi
  icons/mob/human_races/r_skeleton_skrell.dmi
  icons/mob/human_races/r_skeleton_tajaran.dmi
  icons/mob/human_races/r_skeleton_vox.dmi
  icons/mob/species/tail.dmi
Labels: Sprites

#12342 Однозначный фикс удаления счетов отделов
  code/modules/events/money_lotto.dm
Labels: Fix

#12349 фикс спрайта гильз .45
  code/modules/projectiles/ammunition/bullets.dm
Labels: Fix

#12350 Мелкофикс кпк спама грузторгом
  code/modules/events/pda_spam.dm
Labels: Fix

#12346 Обновление фаердоров: часть вторая
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
  maps/stroechka/stroechka.dmm
Labels: Map Edit

#12291 Firedoors update, doors fixes
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/windowdoor.dm
  icons/obj/doors/DoorHazard.dmi
Labels: Sprites

#12248 Удаление старой каски
  code/modules/clothing/head/hardhat.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit, Sprites, Awaiting Review [Sprite Dep]

#12353 Fix missing windows
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#12359 Garden window-wall fix
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#12360 хеллоуинский декор
  code/modules/holidays/halloween/decorations.dm
  code/modules/holidays/new_year/decorations.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  icons/holidays/halloween/decorations.dmi
  icons/holidays/halloween/tinsel.dmi
  icons/holidays/new_year/decorations.dmi
  icons/holidays/new_year/tinsel.dmi
  taucetistation.dme
Labels: Feature, Sprites

#12361 хеллоуинский декор супербыстрофикс иконки одной
  icons/holidays/halloween/tinsel.dmi
Labels: Sprites
