Repository TauCetiStation/TauCetiClassic, pull requests merged in 2024-03, with the labels that each got.

#12843 Перевод целек антагов, допереводим статистику и обьяснения, связанные с ними
  code/_onclick/hud/blob_overmind.dm
  code/datums/mind.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/core.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/factory.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/node.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/resource.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/shield.dm
  code/game/gamemodes/modes_gameplays/blob/overmind.dm
  code/game/gamemodes/modes_gameplays/blob/powers.dm
  code/game/gamemodes/modes_gameplays/blob/theblob.dm
  code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
  code/game/gamemodes/objectives/abductors/abductor_objectives.dm
  code/game/gamemodes/objectives/absorb.dm
  code/game/gamemodes/objectives/blob_takeover.dm
  code/game/gamemodes/objectives/block.dm
  code/game/gamemodes/objectives/borer/borer_objectives.dm
  code/game/gamemodes/objectives/capture.dm
  code/game/gamemodes/objectives/custom.dm
  code/game/gamemodes/objectives/download.dm
  code/game/gamemodes/objectives/download_tcoms_data.dm
  code/game/gamemodes/objectives/escape.dm
  code/game/gamemodes/objectives/families/rob_nt.dm
  code/game/gamemodes/objectives/families/steal_lowrisk.dm
  code/game/gamemodes/objectives/heist/inviolate_crew.dm
  code/game/gamemodes/objectives/heist/inviolate_death.dm
  code/game/gamemodes/objectives/heist/kidnap.dm
  code/game/gamemodes/objectives/heist/loot.dm
  code/game/gamemodes/objectives/heist/salvage.dm
  code/game/gamemodes/objectives/heist/stealnuke.dm
  code/game/gamemodes/objectives/hijack.dm
  code/game/gamemodes/objectives/nuclear.dm
  code/game/gamemodes/objectives/objectives.dm
  code/game/gamemodes/objectives/plunder.dm
  code/game/gamemodes/objectives/replicators/replicators_objectives.dm
  code/game/gamemodes/objectives/sabotage_research.dm
  code/game/gamemodes/objectives/shadowlings/shadowlings_objectives.dm
  code/game/gamemodes/objectives/silence.dm
  code/game/gamemodes/objectives/steal.dm
  code/game/gamemodes/objectives/survive.dm
  code/game/gamemodes/objectives/target/assassinate.dm
  code/game/gamemodes/objectives/target/debrain.dm
  code/game/gamemodes/objectives/target/dehead.dm
  code/game/gamemodes/objectives/target/harm.dm
  code/game/gamemodes/objectives/target/protect.dm
  code/game/gamemodes/objectives/target/rp_rev.dm
  code/game/gamemodes/objectives/target/target.dm
  code/game/gamemodes/role.dm
  code/game/gamemodes/roles/traitor.dm
  code/game/objects/items/devices/remote_device.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/displaycase.dm
  code/modules/paperwork/stamps.dm
  code/modules/statistic/gamemode_stat.dm
Labels: Translation/Localization

#12855 Перевод armor.dm
  code/modules/clothing/suits/armor.dm
Labels: Translation/Localization

#12896 NVG resprite
  code/modules/clothing/glasses/glasses.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Sprites

#12920 complinator sounds a bit louder
  code/modules/clothing/masks/gasmask.dm
  sound/voice/complionator/davai_poprobui_pobejat.ogg
  sound/voice/complionator/lawful_ne_dvigatsya.ogg
  sound/voice/complionator/lawful_ni_s_mesta.ogg
  sound/voice/complionator/lawful_stoyat.ogg
  sound/voice/complionator/lawful_stoyat_na_meste.ogg
  sound/voice/complionator/neudachnik_vybral.ogg
  sound/voice/complionator/seychas_uznaesh.ogg
  sound/voice/complionator/stoy_prestupnoe.ogg
  sound/voice/complionator/tolko_dvineshsya.ogg
  sound/voice/complionator/u_vas_est_tolko.ogg
  sound/voice/complionator/ukrytsya_ot_pravosudia.ogg
  sound/voice/complionator/upal_mordoy_v.ogg
  sound/voice/complionator/vinoven_ili_nevinoven.ogg
  sound/voice/complionator/ya_zakon_ty.ogg
  sound/voice/complionator/zhivym_ili_mertvym.ogg
Labels: Sound

#12924 Disables client.color for plane masters
  code/_onclick/hud/rendering/plane_master.dm
Labels: Fix

#12908 Реорганизация дискет
  code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
  code/game/gamemodes/objectives/download_tcoms_data.dm
  code/game/gamemodes/objectives/sabotage_research.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/smartlight_console.dm
  code/game/objects/items/weapons/disks.dm
  code/modules/research/designs.dm
  code/modules/research/experiment.dm
  code/modules/research/research.dm
  icons/obj/cloning.dmi
  icons/obj/disks.dmi
  icons/obj/items.dmi
  taucetistation.dme
Labels: Feature, Sprites, Merge Ready

#12932 Update absorb.dm
  code/game/gamemodes/objectives/absorb.dm
Labels: Fix

#12935 Revert translation
  code/_onclick/hud/blob_overmind.dm
  code/datums/mind.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/core.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/factory.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/node.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/resource.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/shield.dm
  code/game/gamemodes/modes_gameplays/blob/overmind.dm
  code/game/gamemodes/modes_gameplays/blob/powers.dm
  code/game/gamemodes/modes_gameplays/blob/theblob.dm
  code/game/gamemodes/objectives/abductors/abductor_objectives.dm
  code/game/gamemodes/objectives/absorb.dm
  code/game/gamemodes/objectives/blob_takeover.dm
  code/game/gamemodes/objectives/block.dm
  code/game/gamemodes/objectives/borer/borer_objectives.dm
  code/game/gamemodes/objectives/capture.dm
  code/game/gamemodes/objectives/custom.dm
  code/game/gamemodes/objectives/download.dm
  code/game/gamemodes/objectives/download_tcoms_data.dm
  code/game/gamemodes/objectives/escape.dm
  code/game/gamemodes/objectives/families/rob_nt.dm
  code/game/gamemodes/objectives/families/steal_lowrisk.dm
  code/game/gamemodes/objectives/heist/inviolate_crew.dm
  code/game/gamemodes/objectives/heist/inviolate_death.dm
  code/game/gamemodes/objectives/heist/kidnap.dm
  code/game/gamemodes/objectives/heist/loot.dm
  code/game/gamemodes/objectives/heist/salvage.dm
  code/game/gamemodes/objectives/heist/stealnuke.dm
  code/game/gamemodes/objectives/hijack.dm
  code/game/gamemodes/objectives/nuclear.dm
  code/game/gamemodes/objectives/objectives.dm
  code/game/gamemodes/objectives/plunder.dm
  code/game/gamemodes/objectives/replicators/replicators_objectives.dm
  code/game/gamemodes/objectives/sabotage_research.dm
  code/game/gamemodes/objectives/shadowlings/shadowlings_objectives.dm
  code/game/gamemodes/objectives/silence.dm
  code/game/gamemodes/objectives/steal.dm
  code/game/gamemodes/objectives/survive.dm
  code/game/gamemodes/objectives/target/assassinate.dm
  code/game/gamemodes/objectives/target/debrain.dm
  code/game/gamemodes/objectives/target/dehead.dm
  code/game/gamemodes/objectives/target/harm.dm
  code/game/gamemodes/objectives/target/protect.dm
  code/game/gamemodes/objectives/target/rp_rev.dm
  code/game/gamemodes/objectives/target/target.dm
  code/game/gamemodes/role.dm
  code/game/gamemodes/roles/traitor.dm
  code/game/objects/items/devices/remote_device.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/displaycase.dm
  code/modules/paperwork/stamps.dm
  code/modules/statistic/gamemode_stat.dm
Labels: Translation/Localization

#12926 dirty hands fix
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/clown_items.dm
  code/modules/detectivework/detective_work.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix

#12939 insurance href exploit fix
  code/modules/economy/ATM.dm
Labels: Fix

#12951 fixes cave generation runtimes
  code/modules/mining/mine_turfs.dm
Labels: Fix

#12947 x2 перед ионосферной аномалией
  code/modules/events/communications_blackout.dm
Labels: Fix

#12941 Profiler
  code/__DEFINES/messages.dm
  code/__DEFINES/subsystem.dm
  code/_compile_options.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/profiler.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  config/example/config.txt
  taucetistation.dme
Labels: Maintainability Improvements, Config Update

#12960 telesci fix
  code/modules/telesci/telesci_computer.dm
Labels: Fix

#12945 Фикс обычных спрайтов дисков при спавне
  code/game/objects/items/weapons/disks.dm
Labels: Fix

#12977 Fix Donut_Chaos
  code/modules/food/recipes_microwave.dm
Labels: Fix

#12983 Lighting again
  code/__DEFINES/sight.dm
  code/__HELPERS/matrices.dm
  code/_onclick/hud/fullscreen.dm
  code/_onclick/hud/rendering/plane_master.dm
  code/datums/lighting/level_light.dm
  code/modules/admin/verbs/lighting.dm
  code/modules/lighting/lighting_object.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/replicators/replicators_forcefields.dm
  icons/effects/lighting_object.dmi
Labels: Sprites

#12984 Fixes #12166
  code/game/turfs/simulated/floor.dm
Labels: Fix

#12981 Windowsill environment smash hostile
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Fix

#12974 New candy's and cornflakes
  code/modules/food/recipes_candymaker.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
Labels: Fix, Feature, Sprites

#12971 Chef CQC (light)
  code/__DEFINES/traits.dm
  code/game/area/station_areas.dm
  code/game/jobs/job/civilian.dm
  code/game/machinery/adv_med.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/modules/mob/mob_grab.dm
Labels: Balance, Contentious

#12903 Перевод имплантов
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implantcase.dm
  code/game/objects/items/weapons/implants/implantchair.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/game/objects/items/weapons/implants/implantfreedom.dm
  code/game/objects/items/weapons/implants/implantpad.dm
  code/game/objects/items/weapons/implants/implantuplink.dm
  code/game/objects/items/weapons/implants/mindshield.dm
  code/modules/surgery/implant.dm
Labels: Translation/Localization

#12914 Silicon takes EMP.ogg
  code/_globalvars/lists/sound.dm
  code/modules/mob/living/silicon/silicon.dm
  sound/voice/silicon/damage/borg_damage-1.ogg
  sound/voice/silicon/damage/borg_damage-2.ogg
  sound/voice/silicon/damage/borg_damage-3.ogg
Labels: Test Merge Candidate, Sound

#12956 nettle fix
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Fix

#12902 Перенос БЩ и АВД в отдельную группу профессий.
  code/__DEFINES/flags.dm
  code/datums/outfits/jobs/centcom.dm
  code/datums/outfits/jobs/civilian.dm
  code/datums/outfits/jobs/security.dm
  code/defines/obj/datacore.dm
  code/game/jobs/access.dm
  code/game/jobs/departments.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/centcom.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/jobs.dm
  code/game/machinery/computer/card.dm
  code/modules/client/preferences_savefile.dm
  code/modules/economy/Job_Departments.dm
  code/modules/mob/dead/new_player/new_player.dm
  nano/css/shared.css
  nano/templates/pda.tmpl
  taucetistation.dme
Labels: Tweak, Preferences Update

#12887 добавляет аспект на мехи
  code/__DEFINES/round_aspects.dm
  code/datums/round_aspects/round_aspects.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/honker.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/medical/odysseus.dm
  code/game/mecha/working/ripley.dm
  code/game/objects/effects/spawners/aicorespawner.dm
  code/game/objects/effects/spawners/aspects_spawners.dm
  code/modules/events/roundstart_events/area/replace/station_rearmament.dm
  icons/effects/landmarks_static.dmi
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  taucetistation.dme
Labels: Map Edit, Sprites, Test Merge Candidate

#12991 rcd radial menu
  code/game/objects/items/weapons/RCD.dm
  icons/obj/doors/airlocks/station/public.dmi
Labels: Sprites, Tweak

#13000 Vox NVG fix
  icons/mob/species/vox/eyes.dmi
Labels: Sprites
