Repository TauCetiStation/TauCetiClassic, pull requests merged in 2024-10, with the labels that each got.

#13562 ears sprites fix
  code/__DEFINES/human_layers.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/update_icons.dm
  icons/mob/ears.dmi
  icons/mob/l_ear.dmi
  icons/mob/r_ear.dmi
Labels: Fix, Sprites

#13560 Fix mentalist hair
  icons/mob/human_face.dmi
Labels: Sprites

#13287 Новое дерево технологий
  code/__DEFINES/research.dm
  code/_onclick/hud/action.dm
  code/game/objects/items/weapons/disks.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/item_upgrades/item_upgrade.dm
  code/modules/research/designs.dm
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/goggles.dmi
  icons/obj/item_upgrades.dmi
  maps/templates/space_structures/cloning_lab.dmm
  maps/templates/space_structures/delivery_shuttle.dmm
  maps/templates/space_structures/secrete_lab.dmm
  maps/templates/space_structures/ships_squad.dmm
  nano/css/shared.css
  nano/images/science.png
  sound/machines/disk-upload.ogg
  taucetistation.dme
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#13566 фикс взрывной цели
  code/game/gamemodes/objectives/bomb.dm
Labels: Fix

#13541 Resprite pda.dmi
  code/game/machinery/computer/ai_core.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/aicard.dm
  code/game/objects/items/devices/paicard.dm
  code/modules/mob/living/silicon/ai/death.dm
  icons/obj/pda.dmi
Labels: Feature, Sprites, Test Merge Candidate

#13580 Слот шеи
  code/__DEFINES/clothing.dm
  code/__DEFINES/human_layers.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/ui_screens/complex.dm
  code/_onclick/hud/ui_screens/ian.dm
  code/_onclick/hud/ui_screens/inventory.dm
  code/datums/outfits/outfit.dm
  code/game/machinery/vending/other.dm
  code/game/objects/items.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/character_menu/loadout/loadout_accessories.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/neck/ties.dm
  code/modules/clothing/suits/alien.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/fluff/customitems.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/ian/inventory.dm
  code/modules/mob/living/carbon/ian/update_icons.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/update_icons.dm
  icons/hud/screen1_Midnight.dmi
  icons/hud/screen1_Orange.dmi
  icons/hud/screen1_White.dmi
  icons/hud/screen1_old.dmi
  icons/mob/collar.dmi
  icons/mob/mask.dmi
  icons/mob/neck.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/clothing/suits.dmi
  maps/templates/space_structures/old_station.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#13576 Обновление спрайтов мусора
  code/game/objects/random/random_structures.dm
  code/modules/scrap/oldificator.dm
  code/modules/scrap/scrap_refine.dm
  icons/obj/decals.dmi
  icons/obj/janitor.dmi
  icons/obj/structures/scrap/all_mixed.dmi
  icons/obj/structures/scrap/cloth.dmi
  icons/obj/structures/scrap/engine.dmi
  icons/obj/structures/scrap/food_trash.dmi
  icons/obj/structures/scrap/guns_trash.dmi
  icons/obj/structures/scrap/medical_trash.dmi
  icons/obj/structures/scrap/science.dmi
  icons/obj/structures/scrap/syndie.dmi
  icons/obj/structures/scrap/vehicle.dmi
Labels: Sprites

#13574 Добавление звуков для ATM
  code/modules/economy/ATM.dm
Labels: Sound

#13557 Горохострел 2.5
  code/defines/obj/hydro.dm
  code/modules/cargo/exports/grown.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Fix, Balance, Feature, Sprites

#13593 Спрайты горохострела
  icons/obj/gun.dmi
Labels: Fix, Sprites

#13113 Перевод консоли коммуникаций и связанных с ней вещей
  code/__DEFINES/misc.dm
  code/datums/wires/nuclearbomb.dm
  code/game/machinery/alarm.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/shop.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/response_team/response_team.dm
  code/modules/admin/secrets.dm
  code/modules/security_levels/security_levels.dm
Labels: Translation/Localization

#13600 Последний фикс спрайтов горохострела!
  icons/obj/gun.dmi
Labels: Fix, Sprites

#13601 Знай своего Админа или же Handle Ticket
  code/modules/admin/verbs/adminhelp.dm
Labels: Admin, Tweak

#13598 Добавлен звук включение фонарика в пда
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Sound, Config Update

#13532 Перевод гидропоники
  code/defines/obj/hydro.dm
  code/game/objects/items/weapons/hydroponics.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
Labels: Test Merge Candidate, Translation/Localization

#13615 replace floor fix
  code/game/turfs/simulated/floor.dm
Labels: Fix

#13609 Фикс и мини рефактор культа
  code/game/gamemodes/modes_gameplays/cult/structures/tech_table.dm
  code/modules/religion/altar_types/altar_of_gods.dm
  code/modules/religion/religion.dm
  code/modules/religion/religion_types/cult.dm
  code/modules/religion/tech.dm
Labels: Fix
