Repository TauCetiStation/TauCetiClassic, pull requests merged in 2024-06, with the labels that each got.

#13138 Update station_areas.dm
  code/game/area/station_areas.dm
Labels: Fix, Translation/Localization

#13125 Fix tables
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/weapons/table_rack_parts.dm
Labels: Fix

#13144 light fix
  code/_onclick/hud/rendering/planes/lighting_planes.dm
Labels: Fix

#13140 Новые звуки для синтетиков
  code/datums/emotes/robot/audible.dm
  sound/machines/dwoop.ogg
  sound/machines/longwhistle_robot.ogg
  sound/machines/roboboop.ogg
  sound/machines/robochirp.ogg
  sound/machines/synth_alert.ogg
  sound/machines/synth_no.ogg
  sound/machines/synth_yes.ogg
Labels: Fix, Test Merge Candidate, Sound

#13145 ipc operations skill fix
  code/modules/skills/skillbooks/skillbooks.dm
  code/modules/surgery/surgery.dm
Labels: Fix, Tweak

#13092 More Screen Alerts
  code/_onclick/hud/alert.dm
  code/datums/components/aura_healing.dm
  code/datums/status_effects/buffs.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/neutral.dm
  code/datums/status_effects/status_effect.dm
  code/game/objects/items/weapons/legcuffs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/life.dm
  icons/hud/screen_alert.dmi
  sound/weapons/legtrap.ogg
Labels: Feature, Sprites, Test Merge Candidate, Sound, Translation/Localization, Awaiting Review [Translation Dep]

#13143 Monkeys resprite
  code/modules/mob/living/carbon/monkey/update_icons.dm
  icons/mob/head.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/monkey.dmi
Labels: Sprites, Test Merge Candidate

#13169 внешниго перемитра
  code/game/area/station_areas.dm
Labels: Translation/Localization

#13176 фикс объявления о призыве Нар-Си
  code/datums/announcements/centcomm.dm
Labels: Fix

#13173 Fix спрайтов вещей уборщика
  code/game/objects/structures/janicart.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Fix

#13161 Фикс синдишлема
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Fix

#13171 Switch siren from master to misc
  code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
Labels: Tweak, Sound

#13168 Glass floor to Palette and Delta
  maps/delta/delta.dmm
  maps/palette/palette.dmm
Labels: Map Edit

#13111 обезболивающие препараты уменьшают шок стейдж
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/shock.dm
Labels: Fix

#13155 Nabbers resprite. Body Colorization
  code/modules/mob/living/carbon/species.dm
  icons/mob/human_races/r_serpentid.dmi
  icons/mob/human_races/r_serpentid_grey.dmi
  icons/mob/serpentid_face.dmi
  taucetistation.dme
Labels: Sprites

#13170 убирает возможность спайдерботу переносить nuclear authentication disk
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
Labels: Balance

#13212 Prefs cleanup (cid history), admin stuff
  code/__DEFINES/varedit.dm
  code/__HELPERS/_lists.dm
  code/game/area/shuttle_areas.dm
  code/game/machinery/computer/arrival_shuttle.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/bridge/commands/player_panel.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/guard.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/login.dm
  code/modules/tgui_panel/telemetry.dm
Labels: Admin, Preferences Update

#13188 Dropdown fix
  tgui/packages/tgui/components/Dropdown.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Fix, UI

#13211 virology runtime monkey heal
  code/modules/virus2/effect.dm
Labels: Fix

#13198 Фикс ужасной мапперской ошибки на спутнике бокса
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#13178 leap switch on hotkey
  code/__DEFINES/human.dm
  code/__DEFINES/traits.dm
  code/_onclick/hud/human.dm
  code/datums/keybinding/human.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
  icons/hud/actions.dmi
Labels: Feature, Revert / Removal

#13189 Spiderling resprite
  icons/effects/effects.dmi
Labels: Sprites

#13186 White underwear fix
  icons/mob/human_socks.dmi
  icons/mob/human_socks_fat.dmi
  icons/mob/human_undershirt.dmi
  icons/mob/human_undershirt_fat.dmi
  icons/mob/human_underwear.dmi
  icons/mob/human_underwear_fat.dmi
Labels: Sprites

#13220 connection_log
  SQL/ss13.sql
Labels: Database

#13192 Phoron contagion fix 2
  code/modules/atmospheric/ZAS/Phoron.dm
Labels: Fix

#13204 Новые фразы от туретта у таяр
  code/modules/mob/living/carbon/human/life.dm
Labels: Tweak

#13205 Новые фразы от туретта у унатхов
  code/modules/mob/living/carbon/human/life.dm
Labels: Tweak

#13224 Removes legacy ban system, small cleanup of bans code
  code/__DEFINES/admin.dm
  code/controllers/configuration.dm
  code/game/world.dm
  code/modules/admin/DB_ban/functions.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/NewBan.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/library.dm
  code/modules/client/guard.dm
  code/modules/client/preferences.dm
  config/example/config.txt
  taucetistation.dme
Labels: Admin, Config Update

#13225 New notes panel
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/notes_panel.dm
  code/modules/admin/player_notes.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/bridge/commands/notes.dm
  taucetistation.dme
Labels: Admin, Test Merge Candidate, Config Update
