Repository TauCetiStation/TauCetiClassic, pull requests merged in 2024-11, with the labels that each got.

#13595 Revert #13204
  code/modules/mob/living/carbon/human/life.dm
Labels: Stalled PR, Revert / Removal

#13625 Добавление звуков курице
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  sound/voice/chiken_cluck.ogg
  sound/voice/chiken_egg.ogg
Labels: Sound

#13624 Добавлены звуки при ремонте боргов
  code/modules/mob/living/silicon/robot/robot.dm
  sound/items/remove.ogg
Labels: Sound

#13628 cyborg suit добавлены спрайты на мобе
  code/modules/clothing/under/chameleon.dm
  icons/mob/suit.dmi
Labels: Sprites

#13651 1 Полка
  code/modules/library/lib_items.dm
  icons/obj/objects.dmi
Labels: Feature, Sprites

#13648 3 Бюста
  code/game/objects/items/decorations.dm
  code/modules/library/lib_items.dm
  icons/obj/items.dmi
Labels: Feature, Sprites

#13646 3 Глобуса
  code/game/objects/items/decorations.dm
  code/modules/library/lib_items.dm
  icons/obj/items.dmi
Labels: Feature, Sprites

#13657 Переделка полки
  code/modules/library/lib_items.dm
Labels: Tweak

#13656 Ещё 4 глобуса.
  code/game/objects/items/decorations.dm
  code/modules/library/lib_items.dm
  icons/obj/items.dmi
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/gamma/gamma.dmm
Labels: Feature, Sprites

#13655 Толстая надпись в хабе.
  code/game/world.dm
Labels: Tweak
