Repository TauCetiStation/TauCetiClassic, pull requests merged in 2024-07, with the labels that each got.

#13217 prototypes reliability update
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implantfreedom.dm
  code/game/objects/items/weapons/implants/mindshield.dm
  code/game/objects/random/random_guns.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/research/prototipify.dm
  icons/obj/ammo/magazines.dmi
  icons/obj/gun.dmi
Labels: Sprites, Tweak

#13190 Exosuit DNA lock device
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_parts.dm
  code/game/mecha/mecha_topic.dm
  code/game/mecha/medical/odysseus.dm
  code/game/mecha/working/ripley.dm
  code/game/mecha/working/working.dm
  code/modules/research/designs/mechfabricator_designs.dm
  maps/centcom/centcom.dmm
Labels: Map Edit, Tweak

#13202 OneHuman law -> OneNTEmploye law
  code/game/objects/items/weapons/AI_modules.dm
  code/game/objects/random/random_science.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit, Tweak

#13191 Добавлен доступ к консоли карго в компутер редактирования доступов
  code/game/jobs/access.dm
  code/game/machinery/computer/buildandrepair.dm
  code/modules/cargo/console.dm
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Fix

#13233 фикс модуля РЦД
  code/game/objects/items/weapons/RCD.dm
Labels: Fix

#13234 фикс защиты от пуль
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix

#13238 Добавление недостающих декалей в парке на Boxstation
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#13240 Продолжение отлова Error-турфов
  maps/RandomZLevels/wildwest.dmm
  maps/templates/space_structures/derelict_station.dmm
Labels: Map Edit

#13239 Добавление декалей для астероида
  maps/asteroid/asteroid.dmm
Labels: Map Edit

#13245 Фикс дорм на коробкастанция
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#13246 Фикс АПЦ Прометея
  maps/prometheus/prometheus.dmm
Labels: Map Edit

#13247 Фикс Research Ship
  maps/templates/space_structures/research_ship.dmm
Labels: Map Edit

#13244 Фикс оверлея дверей
  icons/obj/doors/airlocks/external/overlays.dmi
  icons/obj/doors/airlocks/hatch/overlays.dmi
  icons/obj/doors/airlocks/highsec/overlays.dmi
  icons/obj/doors/airlocks/shuttle/overlays.dmi
  icons/obj/doors/airlocks/station/overlays.dmi
  icons/obj/doors/airlocks/station2/overlays.dmi
  icons/obj/doors/airlocks/vault/overlays.dmi
Labels: Sprites

#13146 new impaired sight overlay & nearsight blur
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/status_procs.dm
  icons/hud/screen1_full.dmi
Labels: Sprites, Test Merge Candidate

#13174 Голод больше не увеличивается настолько сильно после качалки
  code/modules/organs/external/flesh.dm
Labels: Tweak, Test Merge Candidate

#13249 Mech tracking disassembly hotfix
  code/game/mecha/mecha.dm
Labels: Map Edit

#13252 Фикс the mecha equipment у рипли/файрфайтеров из аспекта
  code/game/mecha/working/ripley.dm
Labels: Fix

#13248 Chat bans & admin cooldowns
  code/__DEFINES/admin.dm
  code/game/gamemodes/modes_gameplays/blob/blobmouse.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/factory.dm
  code/game/gamemodes/modes_gameplays/blob/overmind.dm
  code/game/gamemodes/modes_gameplays/cult/eminence.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/verbs/ooc.dm
  code/modules/admin/DB_ban/functions.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_cooldowns.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/admin/verbs/pray.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mentor/mentorhelp.dm
  code/modules/mentor/mentorpm.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/robot/drone/maintenance.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/mob/say.dm
  taucetistation.dme
Labels: Admin, Test Merge Candidate, Preferences Update

#13255 Починил термалы боргам
  code/modules/mob/living/silicon/robot/life.dm
Labels: Fix

#13243 Правка шаттеров относительно общей проекции дверей, стен, окон
  maps/asteroid/asteroid.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
  maps/stroechka/stroechka.dmm
Labels: Map Edit

#13268 Добавление большего количества безвоздушных турфов, обновление палетты
  code/game/turfs/simulated/floor_types.dm
  maps/palette/palette.dmm
Labels: Map Edit

#13260 Фикс проводки в дормах
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#13194 Выдан доступ АВД на мостик
  code/game/jobs/job/centcom.dm
Labels: Stalled PR, Tweak

#13228 Стан-перчатки и помощь
  code/modules/clothing/gloves/power_gloves.dm
Labels: Tweak

#13264 Небольшое улучшение кабинета психолога
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#13272 Добавление айрлесс турфов
  maps/asteroid/asteroid.dmm
  maps/delta/delta.dmm
  maps/stroechka/stroechka.dmm
  maps/templates/space_structures/abandoned_lab.dmm
  maps/templates/space_structures/broken_breacher.dmm
  maps/templates/space_structures/cloning_lab.dmm
  maps/templates/space_structures/flagship.dmm
  maps/templates/space_structures/ghost_ship_1.dmm
  maps/templates/space_structures/iss.dmm
  maps/templates/space_structures/resource_shuttle.dmm
  maps/templates/space_structures/robostation.dmm
  maps/templates/space_structures/secrete_lab.dmm
  maps/templates/space_structures/ships_squad.dmm
  maps/templates/space_structures/syndicate_fighter.dmm
  maps/templates/space_structures/toilet.dmm
Labels: Map Edit, Performance

#13196 superior welding goggles стали полезнее
  code/modules/mob/living/carbon/human/life.dm
Labels: Feature, Stalled PR

#13207 Добавляем в шкаф АВД дополнительный наушник, 2 пары очков и 2 флэша
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Tweak

#13279 Фикс финдбреин-а зомби
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/virus2/effect.dm
Labels: Fix

#13288 Фикс названия камеры на Гамме
  maps/gamma/gamma.dmm
Labels: Map Edit

#13209 спу и дионы больше не считаются экипажовцами для ксеноморфов
  code/datums/atom_huds/alternate_apperance.dm
  code/game/gamemodes/factions.dm
  code/game/gamemodes/factions/infestation.dm
  code/game/gamemodes/objectives/reproduct.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/carbon/species.dm
  tools/midi2piano/midi2piano/obj/x86/Debug/midi2piano.csproj.AssemblyReference.cache
Labels: Tweak

#13214 Добавление потерянных или забытых форм из вики
  code/modules/paperwork/predefined_forms.dm
Labels: Tweak

#13274 Гамма фиксы
  maps/gamma/gamma.dmm
Labels: Map Edit

#13282 меняет цветофильтр у шахтёрских мезонок и очков для диагностики
  code/__HELPERS/matrices.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/mining/scanners.dm
Labels: Tweak

#13293 Ethanol SetSleeping fix
  code/modules/reagents/reagent_types/Chemistry-Drinks.dm
Labels: Fix

#13316 Фикс нестов
  code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
Labels: Fix

#13307 flare light_color fix
  code/game/objects/items/devices/flashlight.dm
Labels: Fix

#13254 old station update
  code/datums/outfits/misc/survivalists.dm
  code/datums/spawners_menu/spawners.dm
  code/game/jobs/access.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/paperwork/paper.dm
  code/modules/skills/skillsets/roles.dm
  icons/hud/hud.dmi
  maps/templates/space_structures/old_station.dmm
Labels: Balance, Feature, Map Edit, Sprites, Tweak

#13313 СПУ и дионы больше не видят выдаваевамых им альт_аппирансов
  code/modules/mob/living/carbon/species.dm
Labels: Fix

#13322 Добавление айрлесс турфов, замена их на Сизифе, апдейт паллеты
  code/game/turfs/floor/glass.dm
  maps/palette/palette.dmm
  maps/templates/space_structures/old_station.dmm
Labels: Map Edit

#13324 Инженерам выдан доступ к генератору щита
  code/game/machinery/shieldgen.dm
Labels: Tweak

#13326 facehuggers vomit fix
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
Labels: Fix

#13334 Cap cap fix
  code/modules/clothing/head/jobs.dm
Labels: Fix

#13344 Положил перчатки и сканер на стенд в хранилище
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#13253 Мелко фиксы текстов
  code/datums/announcements/events.dm
  code/datums/announcements/gamemode.dm
  code/game/area/station_areas.dm
  code/modules/paperwork/predefined_forms.dm
  code/modules/power/apc.dm
Labels: Fix, Translation/Localization

#13303 Fix ammo box
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/magazines.dm
Labels: Fix, Translation/Localization

#13305 Перевод Freeform и возвращение потеряного перевода Антимова
  code/game/objects/items/weapons/AI_modules.dm
Labels: Translation/Localization

#13317 Фикс инхенда шлема ГСБ, фикс скаттергана
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
Labels: Sprites

#13319 Фикс застревания во время полёта.
  maps/centcom/centcom.dmm
Labels: Fix, Map Edit

#13329 Новые премиум предметы для автомата с горячими напитками
  code/game/machinery/vending/eat.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Feature

#13331 Урон по вендомату может выбить из него какой-то предмет.
  code/game/machinery/vending.dm
Labels: Tweak

#13335 Эктоплазму теперь можно дробить на научные очки
  code/_globalvars/lists/maintenance_loot.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Tweak

#13336 Fixed requirement check for "Create Antagonist" button
  code/datums/mind.dm
Labels: Fix

#13328 Цель на мясо Яна теперь нельзя выполнить с мясом обычного корги
  code/game/gamemodes/objectives/steal.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
Labels: Tweak

#13281 glasses lighting alpha changes
  code/modules/clothing/glasses/glasses.dm
  code/modules/mining/scanners.dm
Labels: Fix, Tweak

#13356 Продолжение новых спрайтов для карго.
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
Labels: Sprites

#13280 Machinery power usage fix
  code/game/machinery/machinery.dm
Labels: Fix, Test Merge Candidate

#13357 замена всех упоминаний ЛСД в билде
  code/game/gamemodes/modes_gameplays/changeling/powers/stings.dm
  code/game/machinery/vending/medical.dm
  code/modules/reagents/reagent_containers/pill.dm
  icons/hud/actions_changeling.dmi
  maps/templates/space_structures/agrosphere.dmm
Labels: Sprites

#13361 Обновление ЦК слоя
  code/__DEFINES/misc.dm
  code/controllers/subsystem/station_coloring.dm
  code/game/turfs/unsimulated/walls.dm
  maps/centcom/centcom.dmm
Labels: Map Edit

#13342 Фиолетовый паук теперь может плеваться кислотой
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/projectiles/projectile/special.dm
Labels: Map Edit

#13321 Убирает отстегивание от стула при наручах
  code/modules/mob/living/living.dm
Labels: Tweak, Test Merge Candidate

#13235 Кислотная турель для королевы ксеноморфов
  code/datums/spells/in_hand.dm
  code/game/gamemodes/modes_gameplays/cult/structures/cult_structures.dm
  code/game/objects/effects/anomalies.dm
  code/modules/mob/living/carbon/xenomorph/humanoid/queen.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/pylon.dm
  code/modules/projectiles/projectile/beams.dm
  icons/hud/actions.dmi
  icons/mob/alien.dmi
  taucetistation.dme
Labels: Feature, Sprites

#13373 хотфикс бага дюпа с вендоматом!
  code/game/machinery/vending.dm
Labels: Fix

#13395 Улучшение кода спавнеров
  code/datums/spawners_menu/spawners.dm
Labels: Fix, Code Improvements

#13393 Fix reinforced walls
  code/game/turfs/simulated/walls_reinforced.dm
Labels: Fix

#13377 Добавление новых моб спавнеров, добавление их на карты.
  code/game/area/centcom_areas.dm
  code/game/area/custom_areas.dm
  code/game/area/space_structures_areas.dm
  code/game/objects/effects/spawners/mobspawner.dm
  code/modules/mining/mine_areas.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/pug.dm
  code/modules/mob/living/simple_animal/friendly/tomato.dm
  icons/effects/landmarks_static.dmi
  maps/asteroid/asteroid.dmm
  maps/centcom/centcom.dmm
  maps/templates/space_structures/agrosphere.dmm
  maps/templates/space_structures/broken_breacher.dmm
  maps/templates/space_structures/cult_ship.dmm
  maps/templates/space_structures/ghost_ship_1.dmm
  maps/templates/space_structures/ghost_ship_2.dmm
  maps/templates/space_structures/listening_post.dmm
  maps/templates/space_structures/old_station.dmm
  maps/templates/space_structures/research_ship.dmm
  maps/templates/space_structures/robostation.dmm
  maps/templates/space_structures/robostation2.dmm
  maps/templates/space_structures/secrete_lab.dmm
  maps/templates/space_structures/space_villa.dmm
Labels: Map Edit, Sprites

#13388 Фиксы научного аванпоста
  maps/asteroid/asteroid.dmm
Labels: Map Edit

#13368 Теперь точно все щиты могут настривать ученые и инженеры
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit, Tweak

#13311 Возврат многозарядного гранатомета на станции.
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit

#13380 Фикс невозможности сделать укрепленные плитки из форонного стекла
  code/game/objects/items/stacks/sheets/glass.dm
Labels: Fix

#13366 Исправление бага с плевком мага
  code/datums/spells/in_hand.dm
Labels: Fix

#13362 Добавил анимацию супу
  icons/obj/food.dmi
Labels: Sprites

#13327 Поменял старые спрайты картонок, на новые
  icons/obj/cardboard_cutout.dmi
Labels: Sprites

#13299 Новые фигурки профессий
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/toys.dm
  icons/obj/toy.dmi
Labels: Sprites

#13354 Bluespace satchel могут использовать не только шахтеры
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/research/designs.dm
  code/modules/research/prototipify.dm
Labels: Map Edit, Tweak

#13399 позволяем фейсхаггерам садиться на лица прикреплённых к чему либо
  code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
Labels: Fix

#13402 Быстрофикс спавнеров
  maps/centcom/centcom.dmm
Labels: Map Edit

#13401 исправление отображения ненатурального желе
  code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Labels: Fix

#13398 выправляем порядок лайфтика обезьян
  code/modules/mob/living/carbon/monkey/life.dm
Labels: Fix

#13383 Новые кепки by WROTL
  code/game/machinery/washing_machine.dm
  code/modules/clothing/head/soft_caps.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites

#13358 Clickplace: Fixes shoving and slamming.
  code/datums/components/clickplace.dm
Labels: Fix

#13301 Добавляем возможность станить ксеноморфов болами
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/buffs.dm
  code/game/objects/items/weapons/legcuffs.dm
  icons/hud/screen_alert.dmi
Labels: Balance, Test Merge Candidate
