Repository TauCetiStation/TauCetiClassic, pull requests merged in 2025-08, with the labels that each got.

#14280 Фиксит блющилд имплант
  code/game/objects/items/weapons/implants/misc.dm
Labels: Fix, Tweak

#14254 Фиксит баг с настройкой внешности на ОБР и Фортах
  code/game/response_team/response_team.dm
Labels: Fix

#14278 jobs occupation in lobby
  code/modules/mob/dead/new_player/new_player.dm
Labels: Experimental

#14272 ИИ теперь может менять статус ареста в консоли СБ
  code/defines/procs/records.dm
Labels: Fix

#14274 Симплмобы больше не спамят в чатик при взаимодействии с объектами.
  code/game/objects/obj_defense.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Fix, Tweak

#14263 Фикс бага со спауном мыла и клинера в шкафу уборщика
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Fix

#14282 Real fix преференсов
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/roles_preferences.dm
  code/modules/client/preferences_savefile.dm
  taucetistation.dme
Labels: Test Merge Candidate, Preferences Update

#14291 Фиксит малюсенький баг
  code/controllers/subsystem/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Test Merge Candidate

#14334 Manifest fix
  code/__HELPERS/cmp.dm
Labels: Fix

#14325 space bike simple fix
  code/modules/vehicles/vehicle.dm
Labels: Fix

#14329 Чиним цели сбойных дронов.
  code/game/gamemodes/objectives/malf_drones.dm
Labels: Fix

#14277 Багфиксы для кандалов
  code/modules/clothing/shoes/colour.dm
Labels: Fix

#14265 Твики для фортов
  code/datums/spawners_menu/maps/forts.dm
  code/game/area/misc.dm
  code/game/machinery/computer/fort_console.dm
  code/modules/rockets/rockets.dm
Labels: Fix, Balance, Tweak

#14328 Фиксит черный экран при взаимодействии с интерфейсами tgui
  code/__DEFINES/tgui.dm
  code/modules/tgui/tgui.dm
  tgui/packages/tgui/components/ByondUi.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Fix, UI
