Repository TauCetiStation/TauCetiClassic, pull requests merged in 2025-01, with the labels that each got.

#13707 Update traders_objectives.dm
  code/game/gamemodes/objectives/traders_objectives.dm
Labels: I ded, Translation/Localization

#13720 Ex_act @ turf/environment
  code/game/turfs/space/holospace.dm
  code/game/turfs/turf.dm
Labels: Fix

#13706 Online milestones
  code/__DEFINES/bridge.dm
  code/controllers/subsystem/samosbor.dm
  taucetistation.dme
Labels: Test Merge Candidate, Config Update

#13721 holopad no-power fix
  code/game/machinery/hologram.dm
Labels: Fix

#13710 Total plantz resprite
  code/game/objects/structures/flora.dm
  icons/obj/flora/plants.dmi
  maps/RandomZLevels/spacebattle.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/templates/space_structures/old_station.dmm
  maps/templates/space_structures/robostation.dmm
  maps/templates/space_structures/robostation2.dmm
Labels: Sprites, Test Merge Candidate

#13731 эмиттеры перестали убивать вплотную лежачих людей
  code/__HELPERS/vector.dm
  code/game/turfs/turf.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/projectile.dm
Labels: Fix, Test Merge Candidate

#13740 font awesome bump to 6.7.2
  code/modules/asset_cache/asset_list_items.dm
  html/font-awesome/README.MD
  html/font-awesome/css/all.min.css
  html/font-awesome/css/v4-shims.min.css
  html/font-awesome/webfonts/fa-regular-400.eot
  html/font-awesome/webfonts/fa-regular-400.ttf
  html/font-awesome/webfonts/fa-regular-400.woff
  html/font-awesome/webfonts/fa-solid-900.eot
  html/font-awesome/webfonts/fa-solid-900.ttf
  html/font-awesome/webfonts/fa-solid-900.woff
  html/font-awesome/webfonts/fa-v4compatibility.ttf
Labels: Code Improvements, UI

#13736 vox hardsuit modification kit fix
  code/game/objects/items/devices/modkit.dm
Labels: Fix

#13679 фикс перевода дроби
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
Labels: Merge Ready, Translation/Localization
