Repository TauCetiStation/TauCetiClassic, pull requests merged in 2025-06, with the labels that each got.

#14117 Use default client redirects
  code/game/world.dm
Labels: Tweak, Code Improvements

#14098 fastmicroroflofix RCD
  code/game/objects/items/weapons/RCD.dm
Labels: Fix

#14100 Фиксит пару багов на научке.
  code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm
  maps/asteroid/asteroid_classic.dmm
  maps/asteroid/asteroid_rich.dmm
Labels: Fix, Map Edit

#14108 Vox mind impant resistance
  code/game/objects/items/weapons/implants/mindshield.dm
Labels: Map Edit, Sprites, Tweak

#14125 Hub independed authorisation: server password
  .gitignore
  SQL/ss13.sql
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/varedit.dm
  code/__HELPERS/logging.dm
  code/_compile_options.dm
  code/_onclick/hud/tooltip.dm
  code/game/gamemodes/modes_gameplays/blob/blobs/factory.dm
  code/game/gamemodes/modes_gameplays/blob/overmind.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/essences.dm
  code/game/gamemodes/modes_gameplays/cult/eminence.dm
  code/game/sound.dm
  code/game/world.dm
  code/modules/admin/holder2.dm
  code/modules/admin/permissionverbs/permissionedit.dm
  code/modules/client/client_auth.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/client_profile_menu.dm
  code/modules/demo/hooks.dm
  code/modules/mob/dead/new_player/lobby.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/living/carbon/human/login.dm
  code/modules/mob/living/carbon/ian/login_out.dm
  code/modules/mob/living/carbon/login.dm
  code/modules/mob/living/carbon/metroid/login.dm
  code/modules/mob/living/carbon/monkey/login.dm
  code/modules/mob/living/carbon/xenomorph/login.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/parasite/meme.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/login.dm
  code/modules/mob/living/silicon/robot/login.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/hulk.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/species_larvaes.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/replicators/replicators.dm
  code/modules/ventcrawl/ventcrawl.dm
  taucetistation.dme
  tgui/packages/tgui/interfaces/ProfileSettings.js
  tgui/public/tgui.bundle.js
Labels: Feature, Test Merge Candidate, UI

#14099 Reverts spike hair
  icons/mob/human_face.dmi
Labels: Sprites

#13963 machine's exosuit
  code/game/objects/items.dm
Labels: Tweak

#14146 Scale non-tgui browsers based on devicePixelRatio
  code/datums/browser.dm
  code/modules/client/character_menu/global.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/tgui_panel/telemetry.dm
  code/modules/tooltip/tooltip.dm
  tgui/packages/tgui-panel/telemetry.js
  tgui/public/tgui-panel.bundle.js
Labels: UI

#14148 516 chat
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/chat/middleware.js
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/reducer.js
  tgui/public/tgui-panel.bundle.js
Labels: UI

#14158 Guests more
  code/__DEFINES/config.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/configuration.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/database.dm
  code/controllers/subsystem/vote.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin.dm
  code/modules/client/client_profile_menu.dm
  code/modules/mob/dead/new_player/lobby.dm
  code/modules/mob/dead/new_player/new_player.dm
  config/example/config.txt
  taucetistation.dme
  tgui/packages/tgui/interfaces/ProfileSettings.js
  tgui/public/tgui.bundle.js
Labels: UI, Config Update

#14154 инвалиды могут нормально ползать
  code/modules/mob/living/living.dm
  code/modules/organs/organ.dm
Labels: Fix

#14143 [TM-only] 516
  .github/workflows/ci_suite.yml
  code/_compile_options.dm
  code/_onclick/hud/rendering/map_view.dm
  code/_onclick/hud/rendering/plane_master.dm
  code/_onclick/hud/rendering/render_plane_relay.dm
  code/datums/browser.dm
  code/datums/datumvars.dm
  code/game/machinery/computer/shop.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/client/character_menu/global.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/economy/Accounts_DB.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/tgui_panel/telemetry.dm
  code/modules/tooltip/tooltip.dm
  code/modules/tooltip/tooltip.html
  html/browser/playeroptions.css
  nano/css/shared.css
  nano/templates/accounts_terminal.tmpl
  nano/templates/identification_computer.tmpl
  nano/templates/pda.tmpl
  nano/templates/shop.tmpl
  nano/templates/smartfridge.tmpl
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/chat/middleware.js
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/reducer.js
  tgui/packages/tgui-panel/telemetry.js
  tgui/public/tgui-panel.bundle.js
Labels: Test Merge Candidate

#14145 Whale Hair V5
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#14075 Spaceheater update
  code/game/machinery/spaceheater.dm
  nano/templates/space_heater.tmpl
  tgui/packages/tgui/interfaces/SpaceHeater.js
  tgui/public/tgui.bundle.js
Labels: Fix, Tweak, UI

#13459 Сбойные дроны на станции
  code/__DEFINES/gamemodes.dm
  code/_globalvars/lists/objects.dm
  code/_globalvars/misc.dm
  code/datums/ai_laws.dm
  code/datums/spawners_menu/spawners.dm
  code/game/area/station_areas.dm
  code/game/gamemodes/factions/malf_drones.dm
  code/game/gamemodes/objectives/malf_drones.dm
  code/game/gamemodes/roles/malf_drone.dm
  code/game/jobs/access.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/turfs/simulated/floor.dm
  code/modules/events/ion_storm.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/silicon/robot/drone/drone_console.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/living/silicon/robot/drone/maintenance.dm
  code/modules/recycling/disposal.dm
  icons/mob/head.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/robots.dmi
  icons/obj/objects.dmi
  taucetistation.dme
Labels: Sprites

#14078 Амброзиевые пончики в торговый автомат
  code/game/machinery/vending/eat.dm
Labels: Tweak

#14105 Это протек
  code/modules/mob/living/carbon/human/life.dm
Labels: Tweak

#14176 Update glass.dm
  code/modules/reagents/reagent_containers/glass.dm
Labels: Fix

#14192 Maks Fish gaming
  code/controllers/subsystem/mapping.dm
  code/game/machinery/computer/camera.dm
  nano/images/nanomap_asteroid_classic_1.png
  nano/images/nanomap_asteroid_rich_1.png
  nano/images/nanomap_prometheus_asteroid_1.png
  tgui/packages/tgui/components/ByondUi.js
  tgui/packages/tgui/components/NanoMap.tsx
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/CameraConsole.js
  tgui/packages/tgui/interfaces/CameraConsole.tsx
  tgui/packages/tgui/styles/interfaces/CameraConsole.scss
  tgui/packages/tgui/styles/main.scss
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Feature, UI

#14033 Adds an Easter Egg Hunt Game
  code/controllers/subsystem/jobs.dm
  code/datums/announcements/events.dm
  code/game/gamemodes/modes_gameplays/changeling/powers/mutations.dm
  code/game/objects/random/random_foods.dm
  code/modules/events/_event_container.dm
  code/modules/events/egg_hunt.dm
  code/modules/food/recipes_oven.dm
  code/modules/holiday/special_holidays.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/hud/actions_changeling.dmi
  icons/mob/head.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/food.dmi
  taucetistation.dme
Labels: Feature, Sprites

#14121 Теперь в шкафу у уборщика есть мыло и клинер
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/prometheus/prometheus.dmm
Labels: Tweak

#14162 Добавляет печать ЦК на раунд старт сообщение от ЦК
  code/game/gamemodes/misc_gamemode_procs.dm
Labels: Tweak

#14182 Вешаем камеру в операционную прометея.
  maps/prometheus/prometheus.dmm
Labels: Map Edit

#14194 fat uniforms visibility fix
  icons/mob/uniform_fat.dmi
Labels: Sprites

#14165 фикс сбойных дронов
  code/datums/spawners_menu/spawners.dm
  code/game/gamemodes/objectives/malf_drones.dm
  code/modules/mob/living/silicon/robot/drone/drone_console.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
Labels: Fix, Test Merge Candidate

#14195 Airlock Controller TGUI
  code/game/machinery/embedded_controller/airlock_controllers.dm
  nano/templates/advanced_airlock_console.tmpl
  nano/templates/door_access_console.tmpl
  nano/templates/simple_airlock_console.tmpl
  tgui/packages/tgui/interfaces/AccessAirlockController.tsx
  tgui/packages/tgui/interfaces/AdvancedAirlockController.tsx
  tgui/packages/tgui/interfaces/AirlockController.tsx
  tgui/packages/tgui/interfaces/common/AirlockControllerBase.tsx
  tgui/public/tgui.bundle.js
Labels: Tweak, UI
