Repository TauCetiStation/TauCetiClassic, pull requests merged in 2025-07, with the labels that each got.

#14184 TGUI для вирусологии
  code/modules/virus2/centrifuge.dm
  code/modules/virus2/diseasesplicer.dm
  code/modules/virus2/dishincubator.dm
  nano/templates/disease_splicer.tmpl
  nano/templates/dish_incubator.tmpl
  nano/templates/isolation_centrifuge.tmpl
  tgui/packages/tgui/interfaces/DiseaseSplicer.js
  tgui/packages/tgui/interfaces/DishIncubator.js
  tgui/packages/tgui/interfaces/IsolationCentrifuge.js
  tgui/public/tgui.bundle.js
Labels: Tweak, UI

#14202 deagle new sprite
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
Labels: Sprites

#14142 Обновил спрайты тыквы на мобе
  icons/mob/head.dmi
Labels: Fix, Sprites

#14215 New facial hair
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Feature, Sprites

#14204 Теперь печати ЦК отоброжаются на приказах от ЦК во время ревы
  code/game/gamemodes/factions/revolution.dm
Labels: Tweak

#14239 Debug stuff
  code/__HELPERS/icons.dm
  code/__HELPERS/logging.dm
  code/_globalvars/logging.dm
  code/controllers/configuration.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder2.dm
  code/modules/admin/verbs/debug.dm
  code/modules/mob/mob.dm
  config/example/config.txt
Labels: Config Update

#13157 Увеличение скорости колясочникам и жирничам
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Tweak, Test Merge Candidate

#14255 Плувийцы могут качаться
  code/__DEFINES/flags.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/external/flesh.dm
Labels: Fix

#14234 Добавлены строки для корректного отображения иконки диска нуклеиновых кислот (GNA disk) в мире
  code/modules/virus2/items_devices.dm
Labels: Fix

#14262 Фиксит баг с токсинами у скреллов
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Fix, Test Merge Candidate
