Repository TauCetiStation/TauCetiClassic, pull requests merged in 2025-09, with the labels that each got.

#14370 небольшие изменения в аспекте на крутую охрану
  code/datums/outfits/jobs/security.dm
  code/game/objects/items/devices/radio/headset.dm
Labels: Tweak

#14366 фикс багов со стейтами молока и рамена
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Fix

#14369 исправление абуза таймера смерти после дефибрилляции
  code/game/objects/items/weapons/defibrillator.dm
Labels: Fix

#14359 Обновление спрайта сейфа
  icons/obj/structures.dmi
Labels: Sprites

#14376 Обновление спрайта напольного сейфа
  icons/obj/structures.dmi
Labels: Sprites

#14318 Medkits resprite
  code/game/objects/items/weapons/medical.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/storage.dmi
Labels: Sprites

#14353 Фикс сломанной головый у толстых скреллов
  icons/mob/human/skrell.dmi
Labels: Sprites

#14317 Ребаланс еды поздним летом
  code/modules/food/recipes_grill.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_types/Chemistry-Foods.dm
  icons/obj/food.dmi
Labels: Balance, Sprites

#14332 new quirks
  code/__DEFINES/quirks.dm
  code/__DEFINES/traits.dm
  code/controllers/subsystem/quirks.dm
  code/datums/quirks/negative.dm
  code/datums/quirks/positive.dm
  code/modules/mining/mine_areas.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/living.dm
Labels: Feature

#14410 Исправление лишней точки и названия SMES в соответствии с Wikipedia
  code/datums/announcements/events.dm
Labels: Translation/Localization

#14419 Фиксит спрайт маленьких аптечек
  code/game/objects/items/weapons/medical.dm
Labels: Sprites

#14420 Fixes smoked door electronics
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/machinery/doors/windowdoor.dm
Labels: Sprites

#14399 Добавлены раундстартовые предметы в грузторг.
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/cargo/shop.dm
  code/modules/economy/economy_misc.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
  icons/obj/package_wrap.dmi
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Feature, Map Edit, Sprites

#14320 Language Collar
  code/game/objects/items/weapons/disks.dm
  code/modules/clothing/neck/language_collar.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/neck.dmi
  icons/obj/clothing/neck.dmi
  maps/boxstation/boxstation.dmm
  taucetistation.dme
Labels: Map Edit, Sprites, Tweak

#14432 Быстронерф раундстарт товаров
  code/game/objects/random/random_trader_product.dm
  code/modules/cargo/shop.dm
Labels: Tweak

#14434 Позорная ненаблюдательность. Фикс неспавна посылок раундстартом.
  code/game/objects/random/random_trader_product.dm
  code/modules/cargo/shop.dm
Labels: Fix

#14421 Фикс работы шлюзов в доках карго и шахтеров
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/stroechka/stroechka.dmm
Labels: Fix, Map Edit

#14414 Surgery tools, bloodpack resprite and medkits resprite
  code/game/objects/items/weapons/surgery_tools.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/bloodpack.dmi
  icons/obj/storage.dmi
  icons/obj/surgery.dmi
Labels: Sprites
