Repository TauCetiStation/TauCetiClassic, pull requests merged in 2025-04, with the labels that each got.

#13988 Circuit boards resprite
  code/defines/obj/weapon.dm
  code/game/machinery/alarm.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/mecha/mecha_parts.dm
  code/game/objects/items/devices/PDA/radio.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/weapons/AI_modules.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
  code/modules/power/tracker.dm
  icons/obj/doors/door_electronics.dmi
  icons/obj/module.dmi
Labels: Sprites

#13989 импланты не колятся сквозь броню и колятся с задержкой
  code/game/objects/items/weapons/implants/implanter.dm
Labels: Tweak

#13984 Replicator random event
  code/datums/spawners_menu/spawners.dm
  code/modules/events/_event_container.dm
  code/modules/events/replicator.dm
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  taucetistation.dme
Labels: Feature, Map Edit

#13980 fix explanation_text shade
  code/game/gamemodes/roles/evil_shade.dm
Labels: Translation/Localization

#13932 Depressurize buff
  code/modules/mob/living/carbon/human/life.dm
Labels: Revert / Removal

#13929 Update tools translations
  code/__DEFINES/_translation.dm
  code/game/gamemodes/scoreboard.dm
Labels: Tools, Code Improvements, Translation/Localization

#13848 qol chem
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Feature

#13868 Бинарный дешифратор
  code/game/gamemodes/objectives/steal.dm
  code/game/objects/items/weapons/AI_modules.dm
  code/modules/mob/living/silicon/ai/laws.dm
  code/modules/mob/living/silicon/robot/decoder.dm
  icons/obj/device.dmi
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Sprites

#13994 Добавил перчатки БЩ
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Mapmerge/Mapedit Fail, Tweak

#14005 anoncefix
  code/game/machinery/telecomms/telecomunications.dm
Labels: Fix

#13810 Система частиц
  code/__DEFINES/particles.dm
  code/datums/particles/fire.dm
  code/datums/particool.dm
  code/game/objects/effects/particle_holder.dm
  code/game/objects/effects/shared_particle_holder.dm
  icons/effects/particles/fire.dmi
  taucetistation.dme
  tgui/packages/tgui/interfaces/Particool.js
  tgui/public/tgui.bundle.js
Labels: Feature, Sprites, Stalled PR

#13931 немного переписал док андок у шаттлов
  code/controllers/subsystem/shuttles.dm
  code/game/machinery/computer/arrival_shuttle.dm
  code/game/machinery/computer/specops_shuttle.dm
  code/game/machinery/computer/trader_shuttle.dm
  code/modules/admin/admin.dm
  code/modules/locations/shuttles/mine_sci_shuttle.dm
  code/modules/locations/shuttles/officer_shuttle.dm
  maps/asteroid/asteroid_classic.dmm
  maps/asteroid/asteroid_rich.dmm
  maps/boxstation/boxstation.dmm
  maps/centcom/centcom.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
  maps/prometheus_asteroid/prometheus_asteroid.dmm
Labels: Map Edit, Test Merge Candidate

#13952 power_fist_arena
  code/game/objects/items/weapons/melee/powerfist.dm
  code/game/objects/random/random_melee.dm
Labels: Fix, Stalled PR

#13992 dispenser fix
  code/game/objects/structures/tank_dispenser.dm
Labels: Fix, Sprites, Awaiting Author

#14016 Stale bot bump
  .github/workflows/stale.yml
Labels: Maintainability Improvements

#14031 PDA painter fix
  code/game/machinery/PDApainter.dm
Labels: Fix

#14023 capduck
  code/game/objects/structures/watercloset.dm
  icons/obj/watercloset.dmi
  maps/boxstation/boxstation.dmm
  maps/delta/delta.dmm
  maps/falcon/falcon.dmm
  maps/gamma/gamma.dmm
  maps/prometheus/prometheus.dmm
Labels: Map Edit, Sprites, Tweak

#14017 toy_sword
  code/game/machinery/vending/other.dm
Labels: Tweak

#13927 surplus crate sprite
  code/datums/uplinks_items.dm
  code/game/objects/structures/crates_lockers/crates.dm
  icons/obj/storage.dmi
Labels: Sprites

#13923 new_med_sign
  maps/boxstation/boxstation.dmm
  maps/gamma/gamma.dmm
Labels: Map Edit

#14032 Window structures reduce laser damage by half
  code/__DEFINES/misc.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures/windows/shuttle.dm
  code/game/objects/structures/windows/window_fulltile.dm
  code/game/objects/structures/windows/window_thin.dm
  code/modules/projectiles/projectile.dm
Labels: Balance, Tweak

#14021 scrap_robot_components_sprite
  icons/obj/structures/scrap/all_mixed.dmi
  icons/obj/structures/scrap/science.dmi
Labels: Sprites

#13940 Добавить немного приватности Vol. 2.0
  maps/boxstation/boxstation.dmm
Labels: Map Edit, Stalled PR

#13965 Mining charge update
  code/modules/mining/mine_items.dm
Labels: Balance, Tweak, Translation/Localization

#13999 Магбутсы защищают от репульса
  code/datums/spells/repulse.dm
  code/modules/clothing/shoes/magboots.dm
Labels: Balance

#14003 При отключении света во время клонирования клон погибает
  code/game/machinery/cloning.dm
Labels: Tweak

#14027 UI fixes, blood overlay fix
  code/__DEFINES/sight.dm
  code/_onclick/hud/rendering/planes/UI.dm
  code/game/objects/items.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/ian/inventory.dm
  code/modules/mob/living/carbon/monkey/inventory.dm
  code/modules/scrap/oldificator.dm
  taucetistation.dme
Labels: Fix, Test Merge Candidate

#14037 Mood update vol. 1: Удаление лишних муд ивентов + отображения настроения в экземайне
  code/datums/components/mood.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/needs_events.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
Labels: Revert / Removal, Test Merge Candidate

#14002 ксеносы могут плеваться и через альтклик
  code/modules/mob/living/carbon/xenomorph/humanoid/alien_powers.dm
Labels: Tweak

#14006 Crew transfer recall fix
  code/game/machinery/computer/communications.dm
Labels: Revert / Removal
