Repository TauCetiStation/TauCetiClassic, pull requests merged in 2025-02, with the labels that each got.

#13754 IPC resprite
  code/modules/client/character_menu/general.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/external/ipc.dm
  code/modules/organs/organ_external.dm
  icons/mob/human_face.dmi
  icons/mob/human_races/r_machine.dmi
Labels: Sprites, Resprite

#13762 fix ipc hair update
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/races_abilities.dm
  code/modules/mob/living/carbon/species.dm
Labels: Preferences Update

#13763 fix
  code/modules/client/preferences_savefile.dm
Labels: Preferences Update

#13744 Фикс исследования НОВЫХ аспектов на культе (и еще кое-что)
  code/game/gamemodes/modes_gameplays/cult/structures/tech_table.dm
  code/modules/religion/building_agent.dm
  code/modules/religion/religion_types/cult.dm
  code/modules/religion/tech.dm
Labels: Fix

#13760 Особка на дефекты речи
  code/__DEFINES/traits.dm
  code/datums/qualities/negativeish.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/say.dm
Labels: Feature

#13768 очень грубый фикс спрайтов спу
  icons/mob/human_races/r_machine.dmi
Labels: Sprites

#13769 вправляем глаза спу
  icons/mob/human_face.dmi
Labels: Sprites

#13765 Удалил не нужные стекла в сбросе мусора в техах
  maps/boxstation/boxstation.dmm
Labels: Fix, Map Edit

#13787 Новые спрайты spacevines
  icons/effects/spacevines.dmi
Labels: Sprites

#13788 Новые спрайты Book binder и анимация к нему
  code/modules/library/lib_machines.dm
  icons/obj/library.dmi
Labels: Sprites

#13737 возвращает хопу доступ к консоли заказов
  code/game/jobs/job/captain.dm
Labels: Merge Ready, Revert / Removal

#13766 Фикс карты ЦК слоя
  maps/centcom/centcom.dmm
Labels: Fix, Map Edit

#13770 Теперь из гранатомета можно доставать заряженые гранаты
  code/modules/reagents/grenade_launcher.dm
Labels: Tweak

#13775 Добавлены коробки с взрывающимеся гранатми для гранатомета в заказы карго (дубликат фикс дмай конфликта)
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/cargo/packs.dm
  icons/obj/storage.dmi
Labels: Feature, Sprites

#13781 cardiopulmonary resuscitation (CPR) update
  code/modules/mob/living/carbon/human/human.dm
Labels: Tweak

#13789 brepsi
  code/_globalvars/lists/maintenance_loot.dm
  code/game/machinery/vending/eat.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#13790 supermatter new sprite
  code/modules/supermatter/supermatter.dm
  icons/obj/engine.dmi
  icons/obj/supermatter.dmi
Labels: Sprites, Resprite

#13782 убирает упоминания пола Дасти
  code/game/gamemodes/objectives/traders_objectives.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Translation/Localization

#13778 Новые спрайт майнинг дрона с паридзов
  icons/obj/aibots.dmi
Labels: Sprites

#13771 Теперь при заражении паразитами, появлиась возможность играть за ящериц
  code/datums/spawners_menu/spawners_living.dm
  code/modules/events/infestation.dm
Labels: Tweak

#13793 Добавлен бейджик новичка.
  code/controllers/subsystem/jobs.dm
  code/modules/clothing/under/accessories/accessory.dm
  icons/mob/neck.dmi
  icons/obj/clothing/accessory.dmi
  icons/obj/clothing/accessory_overlay.dmi
Labels: Feature, Sprites

#13815 фикс пикселя прически
  icons/mob/human_face.dmi
Labels: Fix, Sprites

#13814 другой изначальный дир при постройке структур
  code/datums/cob_highlight.dm
Labels: Tweak

#13818 Замена стола с аптечками на вендомат на боксе.
  maps/boxstation/boxstation.dmm
Labels: Map Edit

#13826 два новых смайлика с факсом
  tgui/packages/tgui-panel/assets/emoji/faxbride.gif
  tgui/packages/tgui-panel/assets/emoji/faxsent.gif
  tgui/packages/tgui-panel/emotes/constants.js
  tgui/packages/tgui-panel/styles/components/Emoji.scss
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
Labels: Sprites, UI

#13823 Небольшие фиксы декораций.
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/items/decorations.dm
  code/modules/paperwork/folders.dm
  icons/obj/contraband.dmi
Labels: Fix, Sprites, Tweak

#13836 fixes null list pintointer runtime
  code/__DEFINES/misc.dm
  code/_globalvars/lists/objects.dm
  code/game/objects/items/devices/scanners/occult_pinpointer.dm
  code/modules/religion/pluvia_heaven.dm
Labels: Fix
