Repository TauCetiStation/TauCetiClassic, pull requests merged in 2025-05, with the labels that each got.

#14055 строечка хотфикс
  maps/stroechka/stroechka.dmm
Labels: Fix, Map Edit

#14039 Mood update vol. 2: Баффы и дебаффы
  code/__DEFINES/colors.dm
  code/__DEFINES/mob.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/item_attack.dm
  code/_onclick/telekinesis.dm
  code/datums/components/mood.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/nanopaste.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/surgery_limbattachment.dm
  code/game/verbs/suicide.dm
  code/modules/detectivework/autopsy.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/surgery/surgery.dm
Labels: Experimental, Revert / Removal, Tweak

#14038 Wizard buff.
  code/datums/spells/in_hand.dm
Labels: Tweak

#14054 Новые спрайты бургеров
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/food.dmi
Labels: Sprites

#14057 getFlatIcon bandaid
  code/__HELPERS/icons.dm
Labels: Fix, Test Merge Candidate

#14050 закрываем пачку абузов
  code/game/atoms_movable.dm
  code/game/gamemodes/modes_gameplays/abduction/abduction_gear.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/machinery.dm
  code/game/machinery/rechargestation.dm
  code/modules/lighting/lighting_object.dm
  code/modules/mob/mob_grab.dm
Labels: Fix

#14052 респрайт автомата А28 и добавление его ОБРу
  code/datums/outfits/misc/responders.dm
  code/game/gamemodes/modes_gameplays/families/outfit.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/silencer.dm
  icons/mob/belt_mirror.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/ammo/magazines.dmi
  icons/obj/gun.dmi
  icons/obj/gun_40x32.dmi
Labels: Sprites, Tweak

#13956 fix_muligan
  code/modules/reagents/reagent_types/Chemistry-Toxic.dm
Labels: Tweak, Test Merge Candidate

#14046 Удешевление емп гранат
  code/datums/uplinks_items.dm
Labels: Balance

#14045 Waffles
  code/game/machinery/vending/eat.dm
  code/game/objects/items/weapons/storage/food_package.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_types/Chemistry-Foods.dm
  icons/obj/food.dmi
  icons/obj/storage.dmi
Labels: Feature, Sprites

#13874 Возможность выбора нескольких ролей в спавнер меню
  code/datums/spawners_menu/spawners.dm
  code/modules/map_module/forts.dm
  code/modules/mob/dead/dead.dm
Labels: Tweak

#14063 fix secure
  code/game/objects/items/weapons/storage/secure.dm
Labels: Fix

#13921 Добавлена новая газовая аномалия reborn
  code/datums/announcements/events.dm
  code/game/objects/effects/anomalies.dm
  code/modules/events/_event_container.dm
  code/modules/events/anomaly_gas.dm
  icons/effects/anomalies.dmi
  taucetistation.dme
Labels: Feature

#14081 cross
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/pit.dm
  icons/obj/gravestone.dmi
Labels: Feature, Sprites

#14082 Rack resprite
  icons/obj/items.dmi
  icons/obj/objects.dmi
Labels: Sprites

#14051 516 Window scaling & tgui fixes
  code/__HELPERS/mobs.dm
  code/datums/browser.dm
  code/datums/datumvars.dm
  code/game/gamemodes/modes_gameplays/ninja/suit/SpiderOS/display_spideros.dm
  code/game/gamemodes/modes_gameplays/wizard/spellbook.dm
  code/game/machinery/droppod.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_topic.dm
  code/game/objects/items/devices/paicard.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/modules/admin/create_mob.dm
  code/modules/admin/create_object.dm
  code/modules/admin/create_turf.dm
  code/modules/admin/permissionverbs/permissionedit.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/whitelist.dm
  code/modules/client/character_menu/global.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/fluff/fluffmenu.dm
  code/modules/fluff/premoderation.dm
  code/modules/library/lib_items.dm
  code/modules/metahelp/metahelp.dm
  code/modules/mining/mining_fabricator/mining_fabricator.dm
  code/modules/mob/dead/new_player/lobby.dm
  code/modules/mob/living/silicon/pai/recruit.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/nano/nanoui.dm
  code/modules/research/xenoarchaeology/finds/finds_pipboy.dm
  code/modules/tgui/tgui.dm
  code/modules/tooltip/tooltip.dm
  code/modules/tooltip/tooltip.html
  html/admin/color_matrix.html
  html/create_object.html
  nano/css/shared.css
  nano/templates/rdconsole.tmpl
  tgui/packages/tgui-dev-server/dreamseeker.js
  tgui/packages/tgui-dev-server/reloader.js
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/components/ByondUi.js
  tgui/packages/tgui/drag.js
  tgui/packages/tgui/layouts/Window.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Fix, Test Merge Candidate, UI

#14086 Убирает хак с сохранением позиции ТГУИ окон
  tgui/packages/tgui/drag.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Pinned, UI

#14085 fix_blindfold v2
  code/modules/clothing/glasses/glasses.dm
Labels: Fix

#14062 fix issues 13983
  code/modules/clothing/glasses/glasses.dm
Labels: Fix

#14040 Deprecating emote state check
  code/__DEFINES/emote.dm
  code/datums/emotes/emote.dm
  code/datums/emotes/generic/audible.dm
  code/datums/emotes/generic/gesture.dm
  code/datums/emotes/generic/visual.dm
  code/datums/emotes/human/audible.dm
  code/datums/emotes/human/clickable.dm
  code/datums/emotes/human/gesture.dm
  code/datums/emotes/human/visual.dm
  code/datums/emotes/monkey/audible.dm
  code/datums/emotes/robot/audible.dm
  code/datums/emotes/robot/gesture.dm
  code/datums/emotes/robot/visual.dm
  code/datums/emotes/slime/visual.dm
  code/datums/emotes/state_checks.dm
  code/datums/emotes/xenomorph/audible.dm
  code/datums/emotes/xenomorph/larva/audible.dm
  code/datums/emotes/xenomorph/visual.dm
  code/modules/replicators/replicator_emotes.dm
  taucetistation.dme
Labels: Sprites, Test Merge Candidate, Preferences Update

#14009 maaagboots
  code/_globalvars/lists/sound.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  icons/hud/actions.dmi
  icons/mob/feet.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/structures/scrap/cloth.dmi
  sound/effects/magb1.ogg
  sound/effects/magb2.ogg
  sound/effects/magb3.ogg
  sound/effects/magb4.ogg
Labels: Sprites

#14092 fix_warden/blue
  icons/obj/clothing/hats.dmi
Labels: Fix, Sprites
